### ISSUE TITLE
[Feature Request] Add "Update emulators" to EmuDeck plugin

### ISSUE THREAD

**Issue by mdeguzis** [dragoonDorise/EmuDeck#1000]
### Prerequisite Steps

- [x] I have searched existing issues
- [x] This issue is not a duplicate of an existing one
- [x] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

EmuDeck Feedback

### Elaborate on the feature you would like to see added to EmuDeck.

Can we add something like my hack https://github.com/mdeguzis/SteamOS-Tools/blob/master/utilities/update-emudeck.sh to allow updating emulators from SteamOS/GameMode?  I basically add this script using the DeckyLoader "Bash Shortcuts" plugin so I don't have to go to desktop mode to update the emulators. I understand that Stem Rom Manager is different in this regard. I don't think we need to load full EmuDeck (and that's overkill too). I think something like this is done in https://github.com/EmuDeck/EmuDecky/blob/ca548d2f38fcf941da6e135d90683dc0d750a1c7/src/components/Content.tsx?

I don't think EmuDeck even loads for me from Game Mode on the Steam Deck. 

### Include any websites or links that may support your feature request.

None

### Does this feature work on the Steam Deck?

Yes

**Comment by dragoonDorise** [comment]
will do

**Comment by mdeguzis** [comment]
There a way I can test this out? Installing from ZIP or URL in DeckyLoader doesn't seem to install the release.

**Comment by julianrios** [comment]
Is this available yet? Would love to give this a try

**Comment by dragoonDorise** [comment]
Its available right now for patrons, this will be available in the next summer public release ;)

**Comment by julianrios** [comment]
Nice thanks!

**Comment by dragoonDorise** [comment]
Published to public
