### ISSUE TITLE
[Bug Report]  EmulationStation DE does not launch if going back/forth between patreon/free EmuDeck

### ISSUE THREAD

**Issue by mdeguzis** [dragoonDorise/EmuDeck#1023]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

ChimeraOS

### Which SteamOS Branch are you using?

Stable

### What happened?

A bug happened!

### Relevant log output

```shell
Log: http://sprunge.us/p4Qs9e


[gamer@chimeraos esde]$ ./emulationstationde.sh 
./emulationstationde.sh: line 3: cloud_sync_downloadEmuAll: command not found
ESDE location: /EmulationStation-DE.AppImage
./emulationstationde.sh: line 5: /EmulationStation-DE.AppImage: No such file or directory
[gamer@chimeraos esde]$ 

```

IMHO, a 'quick reset' from EmuDeck needs to redownload/apply these core configs.
```

**Comment by dragoonDorise** [comment]
this was fixed
