### ISSUE TITLE
[Bug Report] pcsx2.ps1 fails to launch titles that include single quotes

### ISSUE THREAD

**Issue by linnw** [dragoonDorise/EmuDeck#1024]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

Windows

### Which SteamOS Branch are you using?

Not Using a Steam Deck

### What happened?

pcsx2.ps1 fails to launch titles that include single quotes marks.

Repro steps:
1. Add Tony Hawk's Pro Skater 3 for Playstation 2 to Steam via EmuDeck's Steam ROM Manager implementation
2. Attempt to launch Tony Hawk's Pro Skater 3 from Steam

**Comment by aabdellah** [comment]
Same issue here, workaround is to add a single quote in the target argument in Steam game properties.
