### ISSUE TITLE
Can´t start installation because buttons don´t appear after update check

### ISSUE THREAD

**Issue by adriansegade** [dragoonDorise/EmuDeck#1029]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

"Easy Mode" and "Custom Mode" buttons don´t appear after checking updates and hence can´t initiate the installation

[Welcome screen screenshot](https://imgur.com/a/qBRQG6z)

Steps to reproduce:
1. Reset BIOS
2. Reset SteamOS
3. Login and update SteamOS
4. Log into Desktop mode, download Emudeck from website, move to `~/Desktop` and let files download
5. Download finishes, Emudeck launches, check updates and gets stuck in `Welcome to Emudeck` while not rendering the options to install

Logs:
[Emudeck.desktop console output](https://pastebin.com/jZ5H42RV)
[Emudeck.AppImage console output](https://pastebin.com/0e5GNNip)
[main.log](https://pastebin.com/LkZQBrBW)

Extra:
I noticed that if you open `Emudeck.AppImage` without internet access and then join the internet after the UI has loaded, the options render properly and you can navigate the menus as normal (except you can only choose `Internal Storage` on install). But after some seconds the update check kicks in again and you get stuck on the same screen as before. 
[Log when join internet after start](https://pastebin.com/rrTXLTxx)
[Error when choosing install on `SD card`](https://imgur.com/a/Ki8yy1N) (it doesn't download/restart)

PS: I had Emudeck previously installed on the same Steam Deck but when I wanted to install RPCS3 it didn´t work and it all went downhill when I tried troubleshooting by myself. I had undervolted my Steam Deck and hence why I reseted the BIOS. I also had many other things installed on my Deck so I reset everything for good.

Previous similar issue (insufficient reporting): #953 

### Relevant log output

```shell
[02/25/2024] stdout: Error: Command failed: mkdir -p $HOME/emudeck/ && cd ~/.config/EmuDeck/backend/ && git rev-parse --is-inside-work-tree
/bin/bash: line 1: cd: /home/deck/.config/EmuDeck/backend/: No such file or directory

[02/25/2024] mkdir -p $HOME/emudeck/ && cd ~/.config/EmuDeck/backend/ && git rev-parse --is-inside-work-tree
[02/25/2024] rm -rf ~/.config/EmuDeck/backend && mkdir -p ~/.config/EmuDeck/backend && git clone --no-single-branch --depth=1 https://github.com/dragoonDorise/EmuDeck.git ~/.config/EmuDeck/backend/ && cd ~/.config/EmuDeck/backend && git checkout main && touch ~/.config/EmuDeck/.cloned && printf "ec" && echo true
[02/25/2024] stdout: Error: Command failed: rm -rf ~/.config/EmuDeck/backend && mkdir -p ~/.config/EmuDeck/backend && git clone --no-single-branch --depth=1 https://github.com/dragoonDorise/EmuDeck.git ~/.config/EmuDeck/backend/ && cd ~/.config/EmuDeck/backend && git checkout main && touch ~/.config/EmuDeck/.cloned && printf "ec" && echo true
Cloning into '/home/deck/.config/EmuDeck/backend'...
error: 6617 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
```

**Comment by dragoonDorise** [comment]
@adriansegade were you able to install it? seems like a network issue

**Comment by adriansegade** [comment]
(Apparently) Yes, if I fresh install, the installer downloads (apparently) everything and then launches EmuDeck. Then when it checks for updates is when this issue happens. 

Although now that you mention it, I have to say that I do have a pretty slow connection, <400KB/s max.

I already gave up on this issue since I can´t get any meaningful logs and I just install emulators manually.
