### ISSUE TITLE
[Feature Request] bring back support for systemwide Flatpaks

### ISSUE THREAD

**Issue by cobalt2727** [dragoonDorise/EmuDeck#1042]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

Emulator Configuration Feedback

### Elaborate on the feature you would like to see added to EmuDeck.

By default out of the box, installing stuff on SteamOS from the software store installs it system-wide. Seems like EmuDeck installs it at the user level, though - so I have a bunch of duplicate dependencies like Mesa and application themes installed when I check `flatpak list`.
Furthering the problem, if I was to share the device with someone else I'd have to reinstall all the extra programs on each user.

Having the option to make EmuDeck install stuff system-wide would be a huge benefit.

### Include any websites or links that may support your feature request.

https://github.com/dragoonDorise/EmuDeck/commit/c1c6de2efd529d3dd47bf3d82bbd0653a40c76cd#diff-69f97613e14cd2a3ddc807f2fa340bef67c2f1f2d5350d3600a18b51eeddeb09

**Comment by cobalt2727** [comment]
Worth noting it seems like I can force this myself by installing each individual emulator systemwide, then resetting that emulator's configuration in EmuDeck. Haven't tested to see if the same applies for, say, Google Chrome yet.

**Comment by dragoonDorise** [comment]
we will broke all the current installations if we did, we are slowly moving away from flatpack so this will become a non issue
