### ISSUE TITLE
[Feature Request]  Add M3U file creation

### ISSUE THREAD

**Issue by WingofaGriffin** [dragoonDorise/EmuDeck#1047]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

EmuDeck Application Feedback

### Elaborate on the feature you would like to see added to EmuDeck.

Add m3u file gen as shown by OnionOS

### Include any websites or links that may support your feature request.

https://github.com/OnionUI/Onion/blob/b5b77c2958dbad6a62e71e33082e9414d9993cad/static/build/.tmp_update/script/m3u_gen.sh#L4

### Does this feature work on the Steam Deck?

I see no reason why it shouldn't.

**Comment by dragoonDorise** [comment]
@rawdatafeel @Godsbane what do you guys think about this?

**Comment by dragoonDorise** [comment]
duplicated: https://github.com/dragoonDorise/EmuDeck/issues/1208
