### ISSUE TITLE
[Feature Request] Support for Suzu and Lime-3DS

### ISSUE THREAD

**Issue by monyarm** [dragoonDorise/EmuDeck#1055]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

New Emulator

### Elaborate on the feature you would like to see added to EmuDeck.

Suyu and Lime-3DS are forks of now-discontinued emulators that used be part of EmuDeck

### Include any websites or links that may support your feature request.

https://github.com/RyzenDew/Lime-3DS-Emulator 
https://gitlab.com/suyu-emu/suyu

### Does this feature work on the Steam Deck?

I haven't, but they are forks of two now-discontinue emulators which used to run on the deck.

**Comment by dragoonDorise** [comment]
we are closely checking all the possible options, these two are so my favorites so far but we'll see, it's still too soon

**Comment by saildot4k** [comment]
I agree, too soon. Looking into Suyu, I am not impressed with the team and what they have done previously....nor how they are already making missteps.

**Comment by Dimensional** [comment]
On the subject of 3DS emulators, there's also Panda3DS.

**Comment by Dimensional** [comment]
Suyu has been DMCA'd, so looks like that is out of any running now.

**Comment by dragoonDorise** [comment]
We are staying away of any Yuzu / Citra forks for the time being.

**Comment by DraconicNEO** [comment]
> We are staying away of any Yuzu / Citra forks for the time being.

Hopefully you will consider supporting these forks in the future as they mature and become more refined.

**Comment by dragoonDorise** [comment]
@DraconicNEO we will add them eventually don't worry
