### ISSUE TITLE
chd conversion script seems to convert files in psp romsfolder anyway

### ISSUE THREAD

**Issue by joyrider3774** [dragoonDorise/EmuDeck#106]
The chd conversion script seems to convert files in psp romsfolder anyway even though the find command tries to exclude it

![image](https://user-images.githubusercontent.com/10714776/166551410-211be0ca-970a-480c-b0e3-555401a891fe.png)

**Comment by joyrider3774** [comment]
![image](https://user-images.githubusercontent.com/10714776/166562953-35920598-f9c0-4ebd-99e1-b34cec6c8e39.png)

**Comment by joyrider3774** [comment]
also requires "/*" to be added to the -path var so for example `"$romsPath/psp/*"` if no trailing path delimiter is included

```
#!/bin/bash
romsPath="/run/media/mmcblk0p1/Emulation/roms"
find "$romsPath" -not -path "$romsPath/psp/*" -type f -name "*.iso" | while read f; do echo "$f"; done;
```
works for me in skipping psp

**Comment by AngelofWoe** [comment]
https://github.com/AngelofWoe/EmuDeck/commit/966dd44f306d0fe9f03851f1962b4d6f51d3e6ec
