### ISSUE TITLE
[Feature Request] add Yuzu mirror

### ISSUE THREAD

**Issue by free-storage** [dragoonDorise/EmuDeck#1065]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

New Emulator

### Elaborate on the feature you would like to see added to EmuDeck.

Yuzu mirror - second life

### Include any websites or links that may support your feature request.

https://github.com/yuzu-mirror

### Does this feature work on the Steam Deck?

Yes

**Comment by dragoonDorise** [comment]
Yuzu and Citra now belongs to Nintendo so we are not going to add them back, we are waiting for alternatives
