### ISSUE TITLE
[Bug Report] After update, CloudSync error notification keeps popping up

### ISSUE THREAD

**Issue by joaociocca** [dragoonDorise/EmuDeck#1082]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

On a previous installation of EmuDeck I was able to set up the CloudSync. After updating, that config is unreachable for Patreon gatekeeping (no judgement here, I understand), but the functionality keeps generating a "EmuDeck CloudSync error" notification on Gaming mode.

There was no relevant information on `emudeckApp.log` or anywhere else I could dig, except for two lines on `settings.sh` exported along with the previousl mentioned log:
```
rclone_provider=Emudeck-OneDrive
cloud_sync_provider=Emudeck-OneDrive
```

The only way to make it stop is restarting Steamdeck. On startup, this won't happen, but after closing the first game you play, hell is let loose.

**Comment by joaociocca** [comment]
Latest update seem to have fixed this.

**Comment by cammelspit** [comment]
I have the same issue, is in not fixed and is still happening incessantly. This one is real insidious because it is so constant it makes the deck unplayable with the repeated notification. For me starts after about 10ish minutes of play and will not stop until reboot of deck or switch to desktop. Uninstalling via emudeck does not fix the issue.

**Comment by Juexis** [comment]
I'm getting this same issue as well

**Comment by LuckyRabbitFeet** [comment]
I also have this problem. When I use the ToMoon plugin to open the proxy, this error is sometimes triggered.

[ToMoon](https://github.com/YukiCoco/ToMoon) - a decky loader plugin for the clash proxy client

**Comment by DD1TTY** [comment]
I am now experiencing this issue as well. It just started after a recent update to EmuDeck within the last few days. I'm on SteamOS Stable.

**Comment by lemon5ky** [comment]
Still have the same problem. Please help to fix it.

**Comment by fullpwemium** [comment]
still have this issue
