### ISSUE TITLE
[Bug Report] -EmuDeck will not import games loaded onto the Steam Deck, and Steam ROM Manager will not detect games already present but only emulators

### ISSUE THREAD

**Issue by PS2ClassicsVault** [dragoonDorise/EmuDeck#1085]
### Prerequisite Steps

- [x] I have searched existing issues
- [x] This issue is not a duplicate of an existing one
- [x] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [x] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

so not sure if this played a part in it, but when i reset and re installed the emulators, then proceeded to wanting to add a new game to steam game mode and my internal storage, and it goes through the process but does nothing but create existing folders and check to see if bios are present to copy then does nothing. no importing of games from usb etc

this issue also persists even after doing a full fresh install it will only imports the emulators but not the games to my steam library 

also upon relaunching emu deck requires me to reinstall emudeck again even though it already is

i have made a fresh clean install of steamos and did a clean install of emudeck and the problem still persists!

**Comment by dragoonDorise** [comment]
@PS2ClassicsVault was your issue resolved by some of our latest updates?
