### ISSUE TITLE
[Bug Report] - EmuDeck will transfer bios but will not create/syslink required folders for emulators like ryujinx/yuzu and fails to locate bios required

### ISSUE THREAD

**Issue by PS2ClassicsVault** [dragoonDorise/EmuDeck#1086]
### Prerequisite Steps

- [ ] I have searched existing issues
- [ ] This issue is not a duplicate of an existing one
- [ ] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [ ] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

old emudeck version created folders and syslinked folder for bios to be inserted into the emulators without fuss, but new update broke this and switch emulators etc cannot find or locate the missing bios/firmware. i have made a fresh clean install of steamos and did a clean install of emudeck

**Comment by dragoonDorise** [comment]
You need to have the AppImages in the proper place. Open EmuDeck, manage emulators and then read the instructions on where the AppImages should be, after that restart emudeck, go back again to manage emulators, a new button should be there to apply the configuration for those emulators

**Comment by PS2ClassicsVault** [comment]
> You need to have the AppImages in the proper place. Open EmuDeck, manage emulators and then read the instructions on where the AppImages should be, after that restart emudeck, go back again to manage emulators, a new button should be there to apply the configuration for those emulators

But doesn't it already install the Appimages on setup?

**Comment by dragoonDorise** [comment]
@PS2ClassicsVault no, yuzu is now property of Nintendo, we can't install them
