### ISSUE TITLE
If not installing RetroArch, don't ask about RetroArch Customizations

### ISSUE THREAD

**Issue by IBNobody** [dragoonDorise/EmuDeck#109]
It looks like the script is set up to always ask about RetroArch Customizations, even if RA was not set to be installed (doInstallRA).

I would recommend wrapping the entire section starting with this line.

https://github.com/dragoonDorise/EmuDeck/blob/0636b0eea249177eb863489e38b10e880f55c87c/install.sh#L377

**Comment by Godsbane** [comment]
i think there is a use case where this is ok.

On the second run of the app, the user already has Retroarch, but wants only adjust one of the retroarch options.

maybe we need to detect the install of retroarch before asking about customizing it?

**Comment by IBNobody** [comment]
So... If installing RA or if RA exists, do the customization.

**Comment by IBNobody** [comment]
This issue is still present in the mainline 17.3, and in general, EmuDeck does not work well with a la carte emulation installations. I noticed another case where it did not respect me not wanting to install EmuStation or Xemu

**Comment by Godsbane** [comment]
I am remaking the whole expert mode experience.
