### ISSUE TITLE
[Feature Request] Triforce Emulator support

### ISSUE THREAD

**Issue by mdeguzis** [dragoonDorise/EmuDeck#1096]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

New Emulator

### Elaborate on the feature you would like to see added to EmuDeck.

Could Trifoce/libretro triforce core be added to EmuDeck? The build is hard to get working, old code
See also: https://gitlab.com/es-de/emulationstation-de/-/blob/stable-3.0/resources/systems/linux/es_find_rules.xml?ref_type=heads#L918

I tried this app image, but it needs some libraries (tested on latest PopOS!):

https://www.reddit.com/r/linux_gaming/comments/iazg18/dolphin_triforce_appimage_support_for_version/
```
$ ./dolphin-emu-triforce-4.0-315.glibc2.15-x86_64.AppImage 
dolphin-emu: /tmp/.mount_H9YPVd/usr/lib/x86_64-linux-gnu/libselinux.so.1: no version information available (required by /lib/x86_64-linux-gnu/libgio-2.0.so.0)
dolphin-emu: /tmp/.mount_H9YPVd/usr/lib/x86_64-linux-gnu/libselinux.so.1: no version information available (required by /lib/x86_64-linux-gnu/libmount.so.1)
dolphin-emu: symbol lookup error: /lib/x86_64-linux-gnu/libgio-2.0.so.0: undefined symbol: g_module_open_full

$ ls /lib/x86_64-linux-gnu/libgio-2.0.so.0
/lib/x86_64-linux-gnu/libgio-2.0.so.0

```

### Include any websites or links that may support your feature request.

Possible appimage: https://github.com/qurious-pixel/dolphin/releases/tag/triforce

* Old libretro code: https://github.com/dolphin-emu/dolphin/tree/b957980d9f27279d2507a50e115bf275141a4ea7\
* https://www.reddit.com/r/emulation/comments/13nmamc/dolphin_progress_report_february_march_and_april/
* https://www.reddit.com/r/emulation/comments/13zsahm/complete_guide_how_to_play_mario_kart_gp_one_and/
* https://www.reddit.com/r/Gamecube/comments/1b7kxic/triforce_arcade_running_on_the_steamdeckfzero_ax/
* https://www.reddit.com/r/emulation/comments/9hu5ib/what_happened_to_triforce_support_in_dolphin/

### Does this feature work on the Steam Deck?

Not sure.

**Comment by WingofaGriffin** [comment]
Dolphin wiki itself says zero games are playable so this is likely not possible: https://wiki.dolphin-emu.org/index.php?title=Triforce

**Comment by mdeguzis** [comment]
Interesting. I wonder how/why Botacera Linux still has it and uses it. Will have to test their version.

**Comment by Godsbane** [comment]
There is a fork of dolphin which was made for triforce and still works. It
was never merged into the main emulator for whatever reason.

That emulator does work on the deck. Someone posted about it on the discord
a long while back. They had to modify the app image to get it to function
though.

**Comment by mdeguzis** [comment]
This might help actually: https://github.com/batocera-linux/batocera.linux/blob/96a9a97f523fce6917aee9809eb283406ae79f16/package/batocera/emulators/dolphin-triforce/dolphin-triforce.mk#L3

**Comment by aderumier** [comment]
Hi,

a new fork based on 5.X as been released last year, supporting almost all games

sources are available here

https://crediar.dev/crediar/dolphin
