### ISSUE TITLE
[Feature Request] Switch to Flatpak Version of Cemu

### ISSUE THREAD

**Issue by Spurlos** [dragoonDorise/EmuDeck#1140]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

Emulator Configuration Feedback

### Elaborate on the feature you would like to see added to EmuDeck.

I propose the integration of the Flatpak version of Cemu into EmuDeck. Currently, EmuDeck utilizes the AppImage version of Cemu, which requires manual updates. However, with the recent availability of a Flatpak release for Cemu, transitioning to this distribution method would bring several benefits. Flatpak offers automatic updates, ensures users have the latest version, and provides a reliable, official distribution channel through Flathub. This switch aligns with modern packaging standards and enhances the user experience.

### Include any websites or links that may support your feature request.

[Cemu Flatpak on Flathub](https://flathub.org/apps/info.cemu.Cemu)
[Cemu GitHub Issue on Linux Experimental State](https://github.com/cemu-project/Cemu/issues/107#issuecomment-2001397125)

### Does this feature work on the Steam Deck?

I haven't tested the Flatpak version of Cemu specifically on the Steam Deck. However, as EmuDeck aims to provide compatibility with various emulators on Linux, integrating the Flatpak version of Cemu should not pose compatibility issues. Since Flatpak ensures consistency across different Linux distributions, it should run smoothly on the Steam Deck. Additionally, if it's configured properly, Cemu should perform well natively on the Steam Deck, as it does on other Linux systems.

**Comment by dragoonDorise** [comment]
Hi @Spurlos , thanks for the suggestion but most of the emulator's devs we've talked with always tell us to use the AppImage before the Flatpak, we've migrated several emulators from Flatpak to AppImage. Flatpacks also needs manual updates, we have an Update Emulators inside EmuDeck that makes updating AppImages as easy as updating a Flatpak
