### ISSUE TITLE
[Bug Report] Emudeck won't remember install and reports a javascript error at startup

### ISSUE THREAD

**Issue by brandflake11** [dragoonDorise/EmuDeck#1142]
### Prerequisite Steps

- [x] I have searched existing issues
- [x] This issue is not a duplicate of an existing one
- [x] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [x] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

Fedora Linux 39.20240305.0 (Bazzite GNOME)

### Which SteamOS Branch are you using?

Stable

### What happened?

After emudeck updated to include animations (which are very nice), emudeck always launches as if it is the first time to install. It also has a javascript error with this information (it looks like a gnome pop up for the program):

`A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Cannot read properties of undefined (reading 'distributorID')
  at /tmp/.mount_EmuDecp2DdNd/resources/app.asar/dist/main/main.js:2:544637
  at /tmp/.mount_EmuDecp2DdNd/resources/app.asar/dist/main/main.js:2:369418
  at ChildProcess.exithandler (node:child_process:417:5)
  at ChildProcess.emit (node:events:513:28)
  at maybeClose (node:internal/child_process:1093:16)
  at Socket.<anonymous> (node:internal/child_process:451:11)
  at Socket.emit (node:events:513:28)
  at Pipe.<anonymous> (node:net:757:14)`

### Relevant log output

```shell
https://pastebin.com/d8s3PUSY
```

**Comment by dragoonDorise** [comment]
@brandflake11 can you check if you have lsb_release installed?

https://refspecs.linuxfoundation.org/LSB_3.0.0/LSB-PDA/LSB-PDA/lsbrelease.html

**Comment by AceAsket** [comment]
same problem on bazzite, lsb release installed - lsb_release-3.2-2.fc39.noarch

**Comment by brandflake11** [comment]
Sorry, I just saw this message. I'll make sure to check today

**Comment by brandflake11** [comment]
Hello, I do have lsb_release installed: lsb_release-3.2-2.fc39.noarch.

**Comment by dragoonDorise** [comment]
last bazzite release added usb_release by default, can you guys check if it works fine now? @AceAsket @brandflake11

**Comment by brandflake11** [comment]
Yes, I can confirm that emudeck is now working great on Bazzite.
