### ISSUE TITLE
[Bug Report]VDF entries on Steam Deck will not merge.

### ISSUE THREAD

**Issue by laconicspacecat** [dragoonDorise/EmuDeck#1143]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

After the EmuDeck update, my installation is ruined. My Steam Deck completely freezes when merging VDF entries after hitting Save to Steam. It hangs on the first one and my Deck seizes up completely, forcing me to hard reboot. I have no access to any of my ROMs now. I wish I hadn't updated, this new one is broken.

**Comment by dragoonDorise** [comment]
Hi @laconicspacecat this happens sometimes with SRM, the vdf can get corrupted. 

Try deleting this file ( make a backup before )
**/home/deck/.steam/steam/userdata/YOURID/config/shortcuts.vdf**

**Comment by laconicspacecat** [comment]
Hello there, thank you for your assistance. I've looked and looked, and cannot seem to locate that file. Options?

**Comment by dragoonDorise** [comment]
@laconicspacecat this should be fixed with the latest SRM update, can you try again?

**Comment by laconicspacecat** [comment]
> @laconicspacecat this should be fixed with the latest SRM update, can you try again?

Hello. Sorry for the late reply. I didn't get the notification until now. I instead decided to formal the microSD card my ROMs were on reload them and try again. It worked.

**Comment by laconicspacecat** [comment]
Thanks for the help!
