### ISSUE TITLE
[Feature Request] Compression tool as standalone app?

### ISSUE THREAD

**Issue by menaceinfrills** [dragoonDorise/EmuDeck#1149]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

EmuDeck Application Feedback

### Elaborate on the feature you would like to see added to EmuDeck.

Hi! I really like the compression tool yall made for Emudeck, and wanted to ask if this could maybe be made available as a standalone application? I don't really want to install all of Emudeck onto my main machine, but having the compressor on there would be very useful, instead of having to do all the compression through my Steam Deck. Thanks!

### Include any websites or links that may support your feature request.

None.

### Does this feature work on the Steam Deck?

Yes, works inside Emudeck.

**Comment by dragoonDorise** [comment]
Hi @menaceinfrills Compression tool is a part of EmuDeck, and needs other parts of it to work, we don't have plans to release it as a standalone app.

You can always do a custom install and just don't pick up any emulator so only the EmuDeck App will be on your system.
