### ISSUE TITLE
[Feature Request] - WiiU in ES DE

### ISSUE THREAD

**Issue by AngelofWoe** [dragoonDorise/EmuDeck#116]
ES DE doesn't display Wii U due to assuming it won't work outside of Windows. 

Are we able to add WiiU as a custom system to ES DE, and then have ES DE call Cemu through the Proton scripts in Steam?

There are some threads about calling the Proton scripts with custom prefix files to do something like this.

**Comment by AngelofWoe** [comment]
What Steam does when you run Cemu:
```bash
/home/deck/.local/sh
are/Steam/steamapps/common/Proton - Experimental/proton waitforexitandrun /run/media/mmcblk0p1/Emulation/roms/w
iiu/Cemu.exe
```

**Comment by AngelofWoe** [comment]
https://github.com/dragoonDorise/EmuDeck/pull/117

**Comment by dragoonDorise** [comment]
@AngelofWoe , merged your latest PR but it does not work on ESDE :/

**Comment by dragoonDorise** [comment]
Added on 0.17.3!
