### ISSUE TITLE
[Bug Report] After installation no desktop icon is created if the desktop folder name is set in a locale other than English.

### ISSUE THREAD

**Issue by Labaman** [dragoonDorise/EmuDeck#1183]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

Arch

### Which SteamOS Branch are you using?

Not Using a Steam Deck

### What happened?

This bug is related to the incident: https://github.com/dragoonDorise/EmuDeck/issues/954#issue-2092644146
Now CloudBackup works differently and is no longer a problem. But there is still a problem with Emudeck itself - after installation no desktop icon is created if the desktop folder name is set in a locale other than English.

**Comment by dragoonDorise** [comment]
@Godsbane an we use `xdg-user-dir DESKTOP` to fix this?

**Comment by Godsbane** [comment]
@dragoonDorise I am unfortunately not familiar with non-English locales. It does appear to work properly across a few distros for me. Perhaps do some testing with a fresh install in Spanish and let me know how it does there?

**Comment by Labaman** [comment]
Tested on the latest version - the shortcut was successfully created on the desktop with Russian locale and user folder names. Thanks for fixing this error.  
![image](https://github.com/user-attachments/assets/b0a1fc28-639d-4ff9-9140-ea4a59d6466d)
