### ISSUE TITLE
[Bug Report] Steam Rom Manager does not install on Legion Go

### ISSUE THREAD

**Issue by SpongeDaddy** [dragoonDorise/EmuDeck#1185]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

Windows 11 Legion Go

### Which SteamOS Branch are you using?

Not Using a Steam Deck

### What happened?

Installed and uninstalled Emudeck multiple times, but SRM is not installing with setup. Doesn't open. When I tried to install manually in Emudeck, it says "SRM installation failed." Person on Reddit has the same issue with the ROG Ally.

**Comment by dragoonDorise** [comment]
This was fixed some weeks ago.
