### ISSUE TITLE
[Bug Report] Steam Rom Manager fails to install due to `dragoonDorise/steam-rom-manager` not having any releases

### ISSUE THREAD

**Issue by veech** [dragoonDorise/EmuDeck#1186]
### Prerequisite Steps

- [ ] I have searched existing issues
- [ ] This issue is not a duplicate of an existing one
- [ ] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [ ] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

Windows 10

### Which SteamOS Branch are you using?

Stable

### What happened?

On a new install on Windows 10, Steam Rom Manager was not getting installed. Attempted full reinstall of Emudeck and attempted install via 'Manage Emulators' but no luck. I replaced the `dragoonDorise/steam-rom-manager` repo with `SteamGridDB/steam-rom-manager` and it installed successfully. Looks like the `dragoonDorise` repo has no releases listed right now. I could create a PR with the fix but I'm assuming it's supposed to be using that fork instead of the official release.

### Relevant log output

```shell
[04/08/2024] stderr: Invoke-RestMethod : {"message":"Not 
Found","documentation_url":"https://docs.github.com/rest/releases/releases#get-the-latest-release"}
At C:\Users\USER\AppData\Roaming\EmuDeck\backend\functions\helperFunctions.ps1:239 char:9
+     $url = Invoke-RestMethod -Uri $url | Select-Object -ExpandPropert ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc 
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
Exception calling "DownloadFile" with "2" argument(s): "The remote server returned an error: (403) Forbidden."
At C:\Users\USER\AppData\Roaming\EmuDeck\backend\functions\download.ps1:12 char:2
+     $wc.Downloadfile($url, $destination)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
 
Move-item : Cannot find path 'C:\Users\USER\EmuDeck\temp\srm.exe' because it does not exist.
At C:\Users\USER\AppData\Roaming\EmuDeck\backend\functions\ToolScripts\emuDeckSRM.ps1:5 char:2
+     Move-item -Path "$temp/srm.exe" -destination "$toolsPath/srm.exe" ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\USER\EmuDeck\temp\srm.exe:String) [Move-Item], ItemNotFoundExce 
   ption
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.MoveItemCommand
```
```

**Comment by Scarsz239** [comment]
I had the same problem and did some research.
Seems the problem here is that powershell does not support TLS1.2. but only TLS1.1.

So one could add `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12` to the files.

When i tried it tho on startup EmuDeck always reset the files back so i can't really test it.

[Source](https://stackoverflow.com/questions/32355556/powershell-invoke-restmethod-over-https)

**Comment by richlira** [comment]
> I had the same problem and did some research. Seems the problem here is that powershell does not support TLS1.2. but only TLS1.1.
> 
> So one could add `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12` to the files.
> 
> When i tried it tho on startup EmuDeck always reset the files back so i can't really test it.
> 
> [Source](https://stackoverflow.com/questions/32355556/powershell-invoke-restmethod-over-https)

Maybe this issue is related with https://github.com/dragoonDorise/EmuDeck/issues/1116 , @dragoonDorise 

I just installed Emudeck on a new Windows 11 PC, and Steam Rom Manager is not working.

**Comment by dragoonDorise** [comment]
this was fixed some days ago. thanks for the report!
