### ISSUE TITLE
[Bug Report] install directory unquoted

### ISSUE THREAD

**Issue by papaj-na-wrotkach** [dragoonDorise/EmuDeck#1191]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

Manjaro

### Which SteamOS Branch are you using?

Stable

### What happened?

I am trying to use EmuDeck with RetroArch on my Manjaro PC. After running EmuDeck setup, I started RetroArch to see how EmuDeck had configured it. I opened `Settings -> Directory`. The paths using my "rom directory" (the one I picked during EmuDeck setup) are invalid.

My "rom directory" path contains spaces, so they have been truncated by RetroArch to the first space. The RetroArch config file contains full, untrimmed paths, but they are not quoted.

I think EmuDeck should quote the path when necessary - we usually need this path quoted, but there may be situations where quoting is unnecessary or invalid.

**Comment by dragoonDorise** [comment]
@papaj-na-wrotkach can you get these lines in your Terminal, see if they fix your issue?

`source $HOME/.config/EmuDeck/backend/functions/all.sh

RetroArch_setConfigOverride 'rgui_browser_directory' "\"${romsPath}\"" "$RetroArch_configFile"`

**Comment by papaj-na-wrotkach** [comment]
> @papaj-na-wrotkach can you get these lines in your Terminal, see if they fix your issue?
> 
> `source $HOME/.config/EmuDeck/backend/functions/all.sh`
> 
> `RetroArch_setConfigOverride 'rgui_browser_directory' "\"${romsPath}\"" "$RetroArch_configFile"`

Your solution does change the `rgui_browser_directory` in RetroArch config file correctly, I believe.

_Old config_
```toml
rgui_browser_directory = /run/media/<redacted>/NTFS Data/Games/Emulation/roms
```
_New config_
```toml
rgui_browser_directory = "/run/media/<redacted>/NTFS Data/Games/Emulation/roms"
```

In RetroArch not everything seems to be fine.
![image](https://github.com/dragoonDorise/EmuDeck/assets/29522138/8bd03f57-bb47-407a-be3a-347b1e49cea2)
As you can see the `System/BIOS` directory is not correct. There's also the `Cheat Files` directory which has the same problem (not included on the screenshot).

Sorry for not specifying which variables are not correct earlier.
