### ISSUE TITLE
[Bug Report] Steam ROM Manager not detecting ROMs and Emulators, then Emudeck does not detect the SRM installation

### ISSUE THREAD

**Issue by smanc5** [dragoonDorise/EmuDeck#1195]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

It only detects PCSX2 and Pegasus. I have a lot more than that installed via EMudeck.

In the parse selection list, I have everything selected.

I am using a fresh install of Emudeck. I already reinstalled SRM via Emudeck.

I installed the emulators via Emudeck and my ROMs are on my SD card: /run/media/deck/3c32e0ab-7a5c-4ec6-83b0-b4bba61dc745/Emulation/roms/

I then closed Emudeck and reopened. When I click on Steam ROM Manager from EMU Deck, is saying it isn't installed. I get this error when trying to install it: "There was an issue trying to install SRM"

I didn't uninstall SRM manually.

**Comment by dragoonDorise** [comment]
@smanc5 seems like a network issue, please try to install SRM again. Change your DNS to 1.1.1.1 if the issue still continues

**Comment by smanc5** [comment]
Hi,

Thanks for the reply. I tried that, too. I reinstalled Emudeck all together
about 4-5 times in the past week.

The latest time (today), I set my DNS to 1.1.1.1. SRM installed. I closed
and reopened emudeck and SRM is no longer installed. I tried to reinstall
from emudeck and it says "SRM installation failed. There was an issue
trying to install SRM."

**Comment by smanc5** [comment]
I reinstalled it again and I got it working for now.
