### ISSUE TITLE
scripts improvements

### ISSUE THREAD

**Issue by dragoonDorise** [dragoonDorise/EmuDeck#12]
* Switch shebang to bash, it seems to be a bash script and you are even executing it in bash DONE
* remove the 999999 sleeps and swap them for a simple read, it'll hang until enter is pressed instead of "unexitable" sleep DONE
* since you seem to be using versioning - why not add the version to the script itself? DONE
* make your editor to kill trailing newlines, there's a bunch of tabs strewn around the files at ends of lines DONE
* make your editor show you spaces/tabs in the first place, sometimes there's a mix of 'tab-space-tab' DONE
* make your editor run shellcheck on the file - it'll show you problems like unused variables (for example raCorePath) DONE
* use a different delimiter for sed other than / when dealing with file paths, it'll allow you not to have to escape a bazillion slashes DONE
* why make the user download and extract cemu instead of doing it in the script itself? DONE
* probably should say 'BIOSs'

**Comment by fiordiconio** [comment]
Hi, I followed what you said
https://github.com/dragoonDorise/EmuDeck/pull/16

**Comment by dragoonDorise** [comment]
All done
