### ISSUE TITLE
[Feature Request] LRPS2 Retroarch core parser support

### ISSUE THREAD

**Issue by Candyhands** [dragoonDorise/EmuDeck#1200]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

Steam ROM Manager Parser

### Elaborate on the feature you would like to see added to EmuDeck.

I would love if there was an option to have PS2 isos recognized w/ the Retroarch core rather than solely the standalone PCSX2. I understand that for most people, standalone PCSX2 is the preferred version (for obvious reason). But for me, shader support is a much more important feature. And on Steam Deck, using Retroarch is the best way to accomplish that due to the Linux version of PCSX2 not having shader support. I can obviously manually create entries or launch Retroarch directly, but neither of those are ideal with a large PS2 library.

### Include any websites or links that may support your feature request.

https://docs.libretro.com/library/pcsx2/

**Comment by dragoonDorise** [comment]
Hi @Candyhands, we won't do this since the core performs way worse in the Deck. Thanks for the suggestion though
