### ISSUE TITLE
[Feature Request] Add lime3ds emulator

### ISSUE THREAD

**Issue by nahoss** [dragoonDorise/EmuDeck#1204]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

New Emulator

### Elaborate on the feature you would like to see added to EmuDeck.

Could lime3ds be added to EmuDeck? It's one of the best 3DS emulators. It has a Flatpak in Discover and runs great on Steam Deck and windows. For the website, see https://lime3ds.github.io

### Include any websites or links that may support your feature request.

https://lime3ds.github.io and https://flathub.org/pt-BR/apps/io.github.lime3ds.Lime3DS

### Does this feature work on the Steam Deck?

Yes, I downloaded lime3ds from Discover and tested it on my Steam Deck. It works great!

**Comment by nahoss** [comment]
I just saw that the developer has no plans at the moment to add even a fork of citra

**Comment by benoror** [comment]
What's the latest status update for this?

**Comment by benoror** [comment]
Looks like this was introduced 2 weeks ago. So we wait.

> Yuzu fork discussion is not allowed at this time. There is no way of knowing if these forks are safe and none are close to usable at this time. Once a fork has matured and shown that it is a viable alternative to Yuzu, it will be considered for inclusion in EmuDeck. 
> 
> Citra forks will likely be added to EmuDeck in the near-future.

https://github.com/EmuDeck/emudeck.github.io/commit/fce727ade41d09c06a266f62761584ec8a99ea78#diff-a1e68e248a246920de01ad52536961e3b6db4705a0ed20357601b427d0f39b14R995-R997

**Comment by benoror** [comment]
https://x.com/emudeck/status/1838231857831317590?s=46&t=ssP6EM3-WGWpWUN96NHzSA
