### ISSUE TITLE
Suggestion - Replace all MAME cores with the standalone release

### ISSUE THREAD

**Issue by Sterophonick** [dragoonDorise/EmuDeck#121]
Using really old versions of MAME such as MAME2003 and MAME2010 like being used here is never a good idea outside of the realm of devices with weak CPUs like the Raspberry Pi. The usage of such versions ensures outdated ROM sets and old emulation glitches remain present in the modern era. Steam Deck is plenty capable of running a modern version of MAME at full speed in just about any Arcade game. To top that off, the current release of MAME as a libretro core is just a really bad port. Screwy joystick support, unusable UI scaling, and unpredictable machine support for more oddball machines.

**Comment by Sterophonick** [comment]
I get that this project uses Flatpaks for all the emulators, and MAME doesn't have its own Flatpak or AppImage, but there's a way around that.

So, I have my MAME folder, extracted from the Arch Linux package: [https://archlinux.org/packages/community/x86_64/mame/](url)

![image](https://user-images.githubusercontent.com/34801996/167044910-e7caf3e9-daf4-4a73-b420-ed99164cccb5.png)

Notice that `mame.sh` script.
```sh
#!/bin/bash
export SDL_JOYSTICK_HIDAPI=0
export LD_LIBRARY_PATH=./lib:$LD_LIBRARY_PATH
./mame "$@"
```

`LD_LIBRARY_PATH` exposes another directory for `mame` to look for dependencies.

And then, we can add all the libraries as needed to a folder named `lib`:
![image](https://user-images.githubusercontent.com/34801996/167045077-fa96cefa-8b4d-45dd-a299-da8582fda8cb.png)

This has worked with live environments of Manjaro and EndeavourOS.

**Comment by Sterophonick** [comment]
UI controls are remappable. The important ones are `Config Menu` and `UI Cancel`. Pressing the `UI Cancel` mapping within a game will close the emulator.
![image](https://user-images.githubusercontent.com/34801996/167049882-6e54b3a5-5581-4839-85ed-a80829b2a12d.png)
![image](https://user-images.githubusercontent.com/34801996/167049890-69640147-f463-4669-90f6-c9811f9226d8.png)
![image](https://user-images.githubusercontent.com/34801996/167049894-b4cca12f-dd05-4cde-a354-30aab537ed92.png)

**Comment by dragoonDorise** [comment]
Added standalone Mame as an option in 0.17.6

**Comment by drewbaumann** [comment]
> Added standalone Mame as an option in 0.17.6

Is it possible to launch a game directly from steam into the standalone MAME? I haven't had success.

**Comment by Godsbane** [comment]
yes, it works fine. Did you use the Mame parser, and put your games in the
arcade folder? are your games from the right romset, and do you have the
bios files with the roms?

**Comment by drewbaumann** [comment]
@Godsbane Thanks for your response. This is what I did, and please correct me if I incorrectly used the software:

1. Uninstalled Emudeck
2. Install MAME flatpak via discover
3. Reinstalled Emudeck with easy installer
4. Transferred rom to mame directory in the roms directory
5. Opened up Steam Rom Manager
6. Ensured that the parsers for Arcade - MAME were all checked
7. Clicked Preview, Generate App List, it found the rom, and I saved the list
8. Open Steam
9. Find game in collection (or non-steam games)
10. Attempt to open - fails
11. Look at properties, see it points to retroarch
![CleanShot 2022-08-12 at 10 50 23](https://user-images.githubusercontent.com/337808/184415296-04d7e19e-071a-453b-a329-b4db29cc6e3a.png)

12. Go into Emulation Station, change emulator to MAME standalone, and successfully launch from there

So given that information, did I make a mistake somewhere along the way?

**Comment by Godsbane** [comment]
Which specific folder is your game in? It appears you are trying to use the mame2003 folder and parser. (This is for mame2003 core in retroarch)

The correct location is Emulation/roms/arcade for mame standalone.

If you wish to use MAME standalone, I recommend you turn off the other parsers for the RetroArch versions unless you need them for some reason.

**Comment by drewbaumann** [comment]
I just fixed the rom directory, uninstalled and reinstalled emudeck, and we are in business! Thank you for the support!
