### ISSUE TITLE
Steam Rom Manager Freezing When Saving To Steam[Bug Report] 

### ISSUE THREAD

**Issue by SuessesHasi** [dragoonDorise/EmuDeck#1215]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

A bug happened!

I updated to new EmuDeck Version and all was Messer up. I have EmuDeck and my Roms on SD. 
I installed Hotfix, reset installation, updated SRM and all emulators, however always the same issue:
I can parse my Switch games, but when I Hit „Save to Steam“ SRM freezes. Waited for up to 1 Hour.

Dont want to uninstall und reinstall as I would lose Yuzu.

No log is visible as SRM freezes and needs hard reset.

Any help or is EmuDeck dead?

**Comment by cbartondock** [comment]
This is fixed or should be on current SRM versions. What is your version?

**Comment by SuessesHasi** [comment]
I am on the road 2.4.27

**Comment by cbartondock** [comment]
Do you per chance have a lot of controller templates?

**Comment by SuessesHasi** [comment]
Maybe I have used a few templates in Steam, yes.

**Comment by cbartondock** [comment]
Could you go to one of the parsers and hit fetch controller templates and see if that also crashes SRM?

**Comment by cbartondock** [comment]
Adding images should no longer be blocking renderer process in recent SRM versions, the only thing I haven't made totally asynchronous is the controller template fetching. But if you want to test if it's the images, you could also disable sgdb as an image provider in the parser and see if it freezes just trying to add shortcuts without artwork.

**Comment by SuessesHasi** [comment]
Can you Tell me exctly what to do and where? Thanks

**Comment by SuessesHasi** [comment]
In SRM, I went to Settings, disabled SGDB, still freezes when hitting „Save to Steam“.
