### ISSUE TITLE
PCSX2 Save/Load Hotkeys Not Working

### ISSUE THREAD

**Issue by LBRapid** [dragoonDorise/EmuDeck#122]
While using the PCSX2 steam input mapping I tried to use the save/load state hotkeys Select-R1 and Select-L1, which are mapped to SHIFT-L and SHIFT-K. I noticed I couldn't get them working.

After hooking up a keyboard and taking a look at the PCSX2_keys.ini file I noticed that they are mapped to options that require "Input Recording" to be on and not the default savestate management keys (default of F1/F3). I enabled input recording in PCSX2 and they still didn't work.

I noticed for them to work with my keyboard I had to have Caps Lock on and then press Shift+L or Shift+K. Which is weird. So I remapped them to Shift+F1 and Shift+F3 and were able to get them working with steam input.

Just wondering if maybe the PCSX2_keys.ini should use the save state hotkeys that don't require "Input Recording" to be on, which Emudeck has disabled by default.

And then wondering if the caps lock issue is a bug in PCSX2 in general or maybe just something with the nightly build I am on.

Sorry I would try to be more clear with the relevant parts of the config files linked, but I'm not at my computer right now. I can share more details if desired.

**Comment by Godsbane** [comment]
hi LBRapid, thanks for the info and digging in. I took a look and i agree this looks to be a bug.

Did you attempt to change the PCSX2_keys.ini to match the binds in the bundled steam input profile?

So swap out f1 with L and f3 with K?

I'm just curious if that ended up fixing it or not. If it does, we can just update the config file and get away from the f keys.

**Comment by LBRapid** [comment]
@Godsbane So I first tried enabling input recording and using the hotkeys defined here: https://github.com/dragoonDorise/EmuDeck/blob/main/configs/net.pcsx2.PCSX2/config/PCSX2/inis/PCSX2_keys.ini#L90-L102

They worked, but only if I had caps lock on.

So then I replaced the defaults (F1/F3) here:  https://github.com/dragoonDorise/EmuDeck/blob/main/configs/net.pcsx2.PCSX2/config/PCSX2/inis/PCSX2_keys.ini#L35-L36
with Shift-L and Shift-K and turned off input recording. Again, I could only get them to work with caps lock on.

So that's what led me to trying F keys instead, which did work.

I did not try just using "L" and "K" without Shift. That might work and I can give it a try, Though I think it would be good to keep these are two button combos so you don't accidentally press them.

Does that answer the question? I'm willing to take a stab at a PR if we agree on there being an issue and what keys should be used instead. I assume just the following two files need to be updated:
https://github.com/dragoonDorise/EmuDeck/blob/main/configs/net.pcsx2.PCSX2/config/PCSX2/inis/PCSX2_keys.ini
https://github.com/dragoonDorise/EmuDeck/blob/main/configs/steam-input/pcsx2_controller_config.vdf

Does that seem right?  Thanks for the reply.

**Comment by Godsbane** [comment]
I believe it is just those two files, yes. As for the specific keys? I don't know.

I messed around with this a alittle bit by changing the steaminput binding to F1 / F3 last night, and I was able to get load to trigger but not save. I did not try caps lock on a physical keyboard, but I also mapped that to a button on steam input and tested that too, with no change. May need some more investigation to figure out what's going on there.

**Comment by LBRapid** [comment]
Okay. I was able to get both Save and Load to work with my changes and have been using it while playing a game today with no issues. Let me put together a PR with the changes I made so we have something to look at.

**Comment by LBRapid** [comment]
@Godsbane I opened a PR here https://github.com/dragoonDorise/EmuDeck/pull/127

**Comment by Godsbane** [comment]
I tested last night and it worked great.

**Comment by LBRapid** [comment]
Awesome. Thanks for reviewing.
