### ISSUE TITLE
Switch to BigPEmu flatpak

### ISSUE THREAD

**Issue by pizzadude** [dragoonDorise/EmuDeck#1223]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

New Emulator

### Elaborate on the feature you would like to see added to EmuDeck.

BigPEmu has a flatpak now. It is native Linux, it could be better than using Proton for BigPEmu. https://flathub.org/apps/com.richwhitehouse.BigPEmu

### Include any websites or links that may support your feature request.

https://flathub.org/apps/com.richwhitehouse.BigPEmu

### Does this feature work on the Steam Deck?

Yes, it works on Steam Deck.

**Comment by dragoonDorise** [comment]
@rawdatafeel
