### ISSUE TITLE
[Feature Request] Add gamepad navigation to the EmuDeck application so it could be used exclusively in gaming mode at the convenience of the user

### ISSUE THREAD

**Issue by ttang4299** [dragoonDorise/EmuDeck#1228]
### Prerequisite Steps

- [X] I have searched existing issues
- [x] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

EmuDeck Application Feedback

### Elaborate on the feature you would like to see added to EmuDeck.

Add gamepad navigation to the EmuDeck application, as well as allow a way to add a Gaming Mode shortcut to the EmuDeck application, so that homebrew game management (among other things) can be easily handled in Gaming Mode. This could work in tandem with an improved version of the EmuDeck plugin, which could send notifications every time anything has a new update available.

This is a repost of #1165 which I will close since I want to separate that into two separate issues that may be easier to address.

### Include any websites or links that may support your feature request.

It is an improvement to the EmuDeck application that do not require any outside reference to implement, so unfortunately, I have nothing to provide here.

### Does this feature work on the Steam Deck?

Its goal is to improve the experience on Steam Deck (among other handhelds) anyways. It's very oriented towards the idea of Gaming Mode use.

**Comment by dragoonDorise** [comment]
@ttang4299 we are working on improving the Decky plugin to give it more features so the reliance in desktop mode is less than it is today. We tried to add controller navigation to the app and the user experience was not that great, we are also working on a new UX design so maybe in the future we take a look back at this, closing it for now
