### ISSUE TITLE
[Bug Report] Incorrect parsing of launch arguments in PCSX2 shell script

### ISSUE THREAD

**Issue by mykbit** [dragoonDorise/EmuDeck#1232]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

The issue is that PCSX2 shell script within `~/Emulation/tools/launchers/` does not parse launch arguments correctly. Normally, I boot PCSX2 from Steam, so I inserted `-bigpicture` flag in Steam Launch Options after it was removed from the default configuration of the shell file. However, no matter which flag I insert, the app doesn't boot at all. Directly starting the shell file with `./pcsx2-qt.sh -bigpicture` did not help either.

Then I inserted `echo "$param"` right after `param=$(echo "$param" | sed 's/.$/"/')`. You can see the output below.

![Faulty_out](https://github.com/dragoonDorise/EmuDeck/assets/96201443/19a2c26f-3daa-451b-a899-7115f14d6913)

As you can see, current parsing algorithm substitutes the last character with `"` even though it's supposed to substitute only single quotes. 

I have already written a fix for it, which I will upload as a pull request and tie it to this issue shortly.

### Relevant log output

```shell
https://pastebin.com/LnQemPFf
```

**Comment by mykbit** [comment]
I messed up the connection of the pull request and the issue, so here's the link:
https://github.com/dragoonDorise/EmuDeck/pull/1233

Or you can find the pull request by number 1233

**Comment by mjcampagna** [comment]
Is this why PCSX2 crashes when trying to run from ES-DE? I'm only able to run it as a standalone app.

**Comment by mykbit** [comment]
Closing as the fix is already in dev branch.
