### ISSUE TITLE
[Bug Report] EmuDecky and Power Tools cannot be installed if a password is not already set 

### ISSUE THREAD

**Issue by ghost** [dragoonDorise/EmuDeck#1245]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

If a password is not previously set, the install buttons on the power tools and emudecky page do not appear. 

It looks like the script is attempting to set a temporary password for the user, but this doesn't seem to happen.

**Comment by dragoonDorise** [comment]
Published to public
