### ISSUE TITLE
[Feature Request] Correct inconsistencies between Cemu on Windows and Steam OS.

### ISSUE THREAD

**Issue by NatParable** [dragoonDorise/EmuDeck#1253]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

Emulator Configuration Feedback

### Elaborate on the feature you would like to see added to EmuDeck.

I am an EmuDeck user on both Steam Deck and Windows who only just recently got into CEMU emulation. I typically use SyncthingGTK to sync both my roms and save files between my Steam Deck and Windows PC, which has served me well for every other platform i've emulated.

However, i've discovered that there are some strange (and apparently intentional) inconsistencies between the way CEMU is set up between Windows and Steam OS that make syncing my files unnecessarily complicated.

The first is the roms folder. On Windows, CEMU games go into the roms/wiiu folder, which makes sense. However, on Steam OS, the CEMU games instead have to go into roms/wiiu/roms. According to the wiki this seems to be intentional, but it's not explained why this is. This difference in game filepath seems to also be reflected in both Steam Rom Manager and ES-DE, so fixing this isn't as simple as just changing the rom folder in CEMU.

There is a similar inconsistency with CEMU's save data. On Windows, the mlc01 folder is in the same place the Cemu.exe is, but on Steam OS the mlc01 folder is located in the roms/wiiu folder. Again, according to the wiki this seems to be intentional, but it's not explained why this is.

I haven't come across these kinds of inconsistencies in any other emulator included with EmuDeck, as far as I can tell it's just CEMU. And since CEMU allows you to choose the rom and mlc01 filepaths, I can't understand why these inconsistencies exist. Fixing these inconsistencies would make it much easier for those who, like me, want to be able to sync their games/saves between systems using something like SyncthingGTK.

(Also, tangentially related, but when I recently reinstalled and reset CEMU on my Steam Deck to see if the different filepaths was just a mistake, it ended up installed the controllerProfiles into the roms/wiiu folder instead of the .config/cemu folder like the wiki said it should, which should also probably be looked into)

### Include any websites or links that may support your feature request.

https://emudeck.github.io/emulators/steamos/cemu/cemu-native/#cemu-native-folder-locations
https://emudeck.github.io/emulators/windows/cemu/#cemu-configuration

**Comment by dragoonDorise** [comment]
@NatParable this is because the old Proton version of Cemu needed that special folder architecture. We haven't removed it yet to avoid broking current EmuDeck installations, we might "fix" it in the future, but it's a really risky task. Won't do at the moment
