### ISSUE TITLE
Automatic Emulator Updates via Emudeck Decky Plugin (Flatpak and Appimage)

### ISSUE THREAD

**Issue by CreeperofDoom** [dragoonDorise/EmuDeck#1255]
### Prerequisite Steps

- [ ] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

EmuDeck Application Feedback

### Elaborate on the feature you would like to see added to EmuDeck.

A EmuDeck Plugin is available via the Decky Store. The Emudeck App on Desktop Mode has an option to update your Emulators. The Ability to Automatically Update those Emulators on Startup if Available via the Emudeck plugin would be very great (I have OCD and always need to update those emulators manually so it would help)

### Include any websites or links that may support your feature request.

None Here

### Does this feature work on the Steam Deck?

No. Not yet, At least through that Plugin.

**Comment by dragoonDorise** [comment]
@CreeperofDoom automatic updates its something we won't do, sometimes updates break the emulators until a new version is launched so this will always be the user decision.

But, we are adding buttons to update emulators from gaming mode, so no need to go to desktop mode to do that.

**Comment by dragoonDorise** [comment]
Published to public
