### ISSUE TITLE
Investigate new Gyro control DSU addon

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#126]
We should try to incorporate it if possible.

https://github.com/kmicki/SteamDeckGyroDSU

**Comment by kmicki** [comment]
From now the zip file with binaries and install script is provided. It takes care of group management, USB permissions and installation of service. Without necessity to compile anything.

**Comment by Godsbane** [comment]
Very nice. 
@IBNobody  - Is there a reason we can't use the built in DSU handler in CEMU? I genuinely do not know, and have not tried it.
@kmicki - This is very cool. It does require sudo, correct? And since i have you here, permission to pull the zip during EmuDeck installation?

**Comment by kmicki** [comment]
@Godsbane - According to [Cemu wiki](https://wiki.cemu.info/wiki/Motion_Controls) built in DSU client shouldn't be used.

Installation script requires sudo in order to grant permissions for reading USB device to the deck user. Once that's done, the server runs as a user service and sudo is no longer needed.

**Comment by Godsbane** [comment]
When you do releases as a zip, if it always has the same name, we can get a permalink url for it.

**Comment by IBNobody** [comment]
It's a zip now with install/uninstall scripts.

**Comment by Godsbane** [comment]
@kmicki  here's the URL i managed to pull that should always be the latest:

https://github.com/kmicki/SteamDeckGyroDSU/releases/download/latest/SteamDeckGyroDSUSetup.zip

So long as the filename doesn't change when you do another release, we should be good to go with this.

**Comment by kmicki** [comment]
All right, I will keep the same filename every release then.

**Comment by kmicki** [comment]
@Godsbane I think it's https://github.com/kmicki/SteamDeckGyroDSU/releases/latest/download/SteamDeckGyroDSUSetup.zip

**Comment by Godsbane** [comment]
right you are. thanks for the correction.
