### ISSUE TITLE
[Bug Report] Alphabetize emulators on manage emulators page

### ISSUE THREAD

**Issue by ghost** [dragoonDorise/EmuDeck#1268]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

The arrangement is crazy!

**Comment by Godsbane** [comment]
Something I'd like to see here is a breakup of the tools. and emulators for better organization

Multi Emulators (ares, retroarch, mgba) under a header separate from the single system emulators.

Frontends / tools (SRM / ES-DE / Pegasus) should also get their own header (or even page!)

**Comment by dragoonDorise** [comment]
@rawdatafeel  I already did this in the last release in dev :)

@Godsbane I've moved all the non emulators to the bottom of the page, but sure, we can add a visual separation

**Comment by dragoonDorise** [comment]
Published to public
