### ISSUE TITLE
Suggestion - Add Yuzu Early Access Support

### ISSUE THREAD

**Issue by RamazanKara** [dragoonDorise/EmuDeck#128]
Yuzu EA Builds run better then the flatpak Version. https://github.com/pineappleEA/pineapple-src/releases/tag/continuous. EA Versions are available here. Could that be integrated? And if not, is there a way to integrate it to Emudeck myself?

**Comment by Godsbane** [comment]
Hi @RamazanKara
Thanks for bringing this to our attention. We can certainly investigate this.

What kind of performance gains do you see from using it? Any standout games that are better?

If you want to integrate it yourself:

Download the appimage, put it someplace safe. Make it executable.

Go in to steam rom manager, and change the Yuzu executable from the flatpak to the app image and adjust the commands accordingly. The app image may use different paths than the flatpak does, so be aware of that. Your config may not carry over because of it.

**Comment by RamazanKara** [comment]
Generally EA is regarded as the much better Yuzu Build, with auto updater integrated and many bug fixes aswell as performance improvements built in. I did not do a comparison between the 2 Builds but Performance Improvements should be there across nearly all Games. Could be a nice option for the expert settings. Starting the EA Build is as simple as starting the discovery one.

**Comment by Godsbane** [comment]
I looked into this a little bit. Is this piracy? Yuzu seems to charge for Early Access builds.

**Comment by RamazanKara** [comment]
Early Access Yuzu Builds are Open-Source GPLv2 licensed. pineappleEA just creates AppImage releases for it. You can support Yuzu and access their own releases, or just create your own release out of the Source Code. So no, this is not Piracy.

**Comment by dragoonDorise** [comment]
Im not sure about this:

https://yuzu-emu.org/help/early-access/

They do the early access for patreons, it might be legal but don't know about the morality of it...

**Comment by RamazanKara** [comment]
yuzu is a GPLv2 program, which allows fully free redistribution of its source code. Patreon does not give you additional permissions to the Code, but to compiled Builds. Morally and legally Pineapple EAs releases are therefore totally fine, but a notice to support the Developers could be implemented for further support.

**Comment by Godsbane** [comment]
Hi @RamazanKara. 

I reached out and had a discussion with one of the members of the Yuzu team to get their take on this, and they strongly disapproved of this release.

Unfortunately, after careful consideration, I do not think it's appropriate for our project to bundle this version of Yuzu.

Regardless as to whether or not the GPLv2 allows for it, this being a third party build of another project's work when they don't want it done doesn't sit well with me. (Especially considering we already have a version of this project available from a supported and trusted repository - flathub)

While you are yourself are welcome to do whatever you like, it's just not the right fit for this project. We would like to have a good relationship with the projects which build the emulators we rely upon, and bundling builds they don't want released to public would surely sour that relationship.
