### ISSUE TITLE
[Feature Request] Per Emulator QAM Profile (TDP/FPS)

### ISSUE THREAD

**Issue by RhanCandia** [dragoonDorise/EmuDeck#1281]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

Emulator Configuration Feedback

### Elaborate on the feature you would like to see added to EmuDeck.

As a user, I would like to be able to set specific TDP limits for individual emulators. Because I would like to be able to set lower TDP limits for older emulated systems and higher TDP limits for newer systems.

### Include any websites or links that may support your feature request.

N/A

### Does this feature work on the Steam Deck?

I thought it would be possible. But I noticed that all the profiles are just being saved for EmulationStation-DE. They can't be set for individual emulators.

I tried looking at the existing issues in GitHub with "per emulator tdp profile" but I didn't find any. I also checked the Wiki but I didn't see it.

If this feature already exist, I apologize, and please point me to the right resource. Thanks.

**Comment by dragoonDorise** [comment]
@RhanCandia to do this you have to use SRM, so every game has its own entry and in that way you can set a custom TDP just any other Steam game
