### ISSUE TITLE
[Bug Report] emudeck fails to install, backend error

### ISSUE THREAD

**Issue by Crunchwrap01** [dragoonDorise/EmuDeck#1283]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

I downloaded the installer from emudeck website and put the file on my desktop. When opening the file it will install emudeck, but after selecting the hard drive option it says there was an error when installing. Konsole says no file found in /home/deck/.config/EmuDeck/backend/versions.json. I tried changing dns setting in Wi-Fi and using a mobile hotspot but I still got the same error
![IMG_7195](https://github.com/dragoonDorise/EmuDeck/assets/174745403/2d7e91a1-6662-496f-9602-77ccc8f00f95)

**Comment by Crunchwrap01** [comment]
I ended up buying an sd card an and trying to install it again and it worked this time. It must be something about using the internal hard drive that was messing it up. I have plenty of space on my hard drive so it couldn't be that. Also I after getting the install to work I noticed that I have to reinstall EmuDeck each time I want to access it. Is this intended or am I doing something wrong?

**Comment by JohnGuan** [comment]
Me too. But I don’t have a TF card

**Comment by EnixCoda** [comment]
My workaround

1. Save content of the https://github.com/dragoonDorise/EmuDeck/blob/main/install.sh file to your local
2. Edit the saved install.sh file, delete the line `trap report_error ERR`
3. In terminal, run `sh ./path/to/install.sh`

Although the error is still prompted in the console, the installation would finish successfully.
