### ISSUE TITLE
[Bug Report] Emudeck on HoloISO shows no parsers 

### ISSUE THREAD

**Issue by jamescastells** [dragoonDorise/EmuDeck#1286]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

holoISO

### Which SteamOS Branch are you using?

Stable

### What happened?

I've installed Emudeck on SteamOS, Windows and ChimeraOS, and it works fine in all of those. However, when installing it on HoloISO, I come to a point where the Steam ROM Manager has no parsers saved and thus I can't include emulationStation (or others) to my Steam library.

When arriving to the Steam rom manager page I should get this:

![image](https://github.com/user-attachments/assets/f25462c7-edcd-4ec2-aa89-781979ca76de)
(where the parser for emulationstation and others have been created)

But instead I arrive at this:

![image](https://github.com/user-attachments/assets/ba3d7e32-a20c-448b-9d7a-cd9348306e5d)

No parsers exist.

Note: my configuration **does** have "Steam rom manager" selected, as pointed by the [wiki](https://github.com/dragoonDorise/EmuDeck/wiki/steam-rom-manager#why-does-steam-rom-manager-have-no-parsers).

This only happens with holoISO. How can I fix this?

**Comment by Godsbane** [comment]
Please upload the emudeck.log file. You can find it in ~/emudeck.

Most likely your system is missing a required package, but hard to say
without the log.

**Comment by jamescastells** [comment]
This were the logs I found:

[emudeckApp.log](https://github.com/user-attachments/files/16367417/emudeckApp.log)
[emudeckSetup.last.log](https://github.com/user-attachments/files/16367418/emudeckSetup.last.log)
[emudeckSetup.log](https://github.com/user-attachments/files/16367419/emudeckSetup.log)

**Comment by Godsbane** [comment]
Thanks. @dragoondorise any idea, it looks ok to me at first glance but the
section for srm_init has nothing going on.

**Comment by jamescastells** [comment]
One thing I noticed is that when installing Emudeck, one of the last steps is that Steam Rom manager asks me to select my steam user so it can add the parsers. ChimeraOS and the Steam deck give me the option to select the user immediately, but in HoloISO, it tells me first to point to my steam folder, and only then I can select the user.

Also, some emulators fail to install in HoloISO, while in the other distros, they install fine.

There's something not working properly on HoloISO.

**Comment by Godsbane** [comment]
Yeah it's like it got zero srm config files at all.

I'm not familiar enough with Holo unfortunately

**Comment by jamescastells** [comment]
For anyone interested, I gave up with holoISO. It's got too many problems and this is just one of them.

I tried a new distro called [SteamFork](https://github.com/SteamFork). It's still based on SteamOS but replicates 1:1 its experience. And guess what? Emudeck works perfectly there.
