### ISSUE TITLE
token has been used too many times

### ISSUE THREAD

**Issue by Jsian1** [dragoonDorise/EmuDeck#1287]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

Windows

### Which SteamOS Branch are you using?

Not Using a Steam Deck

### What happened?

trying to install the emudeck ony my ROG ally X but its been showing token had used too many times. even when i try log in using my computer

**Comment by BennyJ95** [comment]
Having the same issue, could log in on my laptop fine, but on my ASUS ROG Ally X it keeps saying Error... This token has been used too many times... been trying for days now... someone please help ffs

**Comment by dragoonDorise** [comment]
@Jsian1 @BennyJ95 the GitHub issues is not for Patreon, we have Discord channels for that, please post over there your issues!
