### ISSUE TITLE
[Bug Report] config resets fail but output as successful 

### ISSUE THREAD

**Issue by frostymm** [dragoonDorise/EmuDeck#1289]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

After recently updating emudeck as well as emulators after several months, I also clicked to reset all the configs at once as well. Less than a second later it would popup as successful but all the configs were all messed up still when I went to actually play. I had to go through and reset each emulator config individually (and sometimes multiple tries) to get it to actually reset properly. 

Besides dealing with the false positives, it would be nice if there was some kind of progress bar or output so I could tell generally where it's failing. If a progress bar disappears only a third of the way through at least, it'd be easy to see something was up! 

### Relevant log output

```shell
Sorry I don't have any logs, this actually happened to me like a month ago and I'm only putting it in now after it came up while talking with emotion 😔
```

**Comment by dragoonDorise** [comment]
The way emulator settings are updated changed a while back, this should be fixed now
