### ISSUE TITLE
[Bug Report] PCSX2 config reset doesn't apply to flatpak

### ISSUE THREAD

**Issue by frostymm** [dragoonDorise/EmuDeck#1290]
### Prerequisite Steps

- [x] I have searched existing issues
- [x] This issue is not a duplicate of an existing one
- [x] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [x] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

PCSX2 config reset affects AppImage version but does not affect Flatpak version. 
Flatpak configs:
[PCSX2.zip](https://github.com/user-attachments/files/16446093/PCSX2.zip)
AppImage configs:

[PCSX2 (1).zip](https://github.com/user-attachments/files/16446100/PCSX2.1.zip)

**Comment by dragoonDorise** [comment]
@frostymm that's normal behaviour, we don't support the flatpak version
