### ISSUE TITLE
[Bug Report] Dolphin doesn't recognise Steam Input

### ISSUE THREAD

**Issue by seby42** [dragoonDorise/EmuDeck#1310]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

I was surprised to find that one day I was unable to input any controls into my GameCube games. Neither the Game Pad nor the external controller (DualShock 4) was recognized, although other emulators worked fine.

I had to manually configure Dolphin to use either `SDL/0/Steam Deck Controller` or `SDL/0/PS4 Controller`. However, doing so removed the ability to switch between my Game Pad and controller on the fly. Setting Dolphin to use `SteamDeck/0/Steam Deck` device doesn't seem to work.

I'm fairly certain that EmuDeck was working out of the box the first time I used it. I'm confused as to why I now have to manually configure Dolphin's input settings instead of relying on the EmuDeck script to handle this automatically.

I’ve tried multiple clean installs, including a Steam Deck factory reset, but the issue persists.

**Comment by dragoonDorise** [comment]
@seby42 this was broken by the latest dolphin update, but it's been fixed today. Do a reset on Dolphin settings from Manage Emulators and you are good to go!
