### ISSUE TITLE
EmulationStation manual update not possible due to symlinked folders not transferring

### ISSUE THREAD

**Issue by av1155** [dragoonDorise/EmuDeck#1315]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

Windows 11

### Which SteamOS Branch are you using?

Not Using a Steam Deck

### What happened?

How do I update ES-DE on Windows via EmuDeck? Do I need to wait for the update via manage emulators section on windows emudeck? 

I tried the manual update but the symlinks for all the folders did not transfer over to the updated EmulationStation folder, so I “lost” my saves. Hopefully an update is released via EmuDeck which will handle that.

I just reverted back to my original ES-DE folder that has the symlinks.

**Comment by dragoonDorise** [comment]
@av1155 always update ESDE from EmuDeck in manage emulators
