### ISSUE TITLE
[Bug Report] Multiple instances of EmuDeck can be opened on the desktop

### ISSUE THREAD

**Issue by Filip-Anicic** [dragoonDorise/EmuDeck#1318]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

TLDR: If you open the EmuDeck shortcut twice, two EmuDeck instances will open. The first window will notice the local installation and skip the install wizard, while the second window act as nothing is installed and will prompt you to go through the installation wizard. 

Unknowingly, I opened the EmuDeck desktop shortcut multiple times, causing multiple instances of EmuDeck to be opened. Confused, I closed the window and clicked on the desktop shortcut again, not noticing that on the task bar there was one window of it open.

I thought that it was just a update bug and that it would not need to reinstall the emulators, but it started a long process of downloading, uninstalling and installing the emulators.

Expected result: Opening EmuDeck through the shortcut or app launcher would focus on the already opened instance of EmuDeck.

**Comment by dragoonDorise** [comment]
Closed for inactivity
