### ISSUE TITLE
[Bug Report] Clearing Steam rom manager cache, deletes save data for non-steam games

### ISSUE THREAD

**Issue by thebear-tech** [dragoonDorise/EmuDeck#1322]
### Prerequisite Steps

- [x] I have searched existing issues
- [x] This issue is not a duplicate of an existing one
- [x] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [x] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

A bug happened!

**Comment by dragoonDorise** [comment]
Yeah, that's expected behaviour since all non steam games share the same file that SRM uses.

**Comment by eeveeh69** [comment]
> Yeah, that's expected behaviour since all non steam games share the same file that SRM uses.

is there a way to recover those files? what to do if you need to clear the cache to fix SRM crashing but you don't want to clear all the save files and the shortcuts and the art?
