### ISSUE TITLE
[Feature Request] Manually add Riujinx to emulators from flatpack install

### ISSUE THREAD

**Issue by Jhyrachy** [dragoonDorise/EmuDeck#1327]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

Emulator Configuration Feedback

### Elaborate on the feature you would like to see added to EmuDeck.

Since now Riujinx is no more, there is a need to streamline installation from different sources.

### Include any websites or links that may support your feature request.

https://flathub.org/apps/org.ryujinx.Ryujinx

### Does this feature work on the Steam Deck?

Yes, I downloaded Riujinx from Discover and tested it on my Steam Deck. It works great!

**Comment by dragoonDorise** [comment]
We are already using a fork, the flatpak will probably go down sooner tan later
