### ISSUE TITLE
[Feature Request] Sudachi emulator inclusion

### ISSUE THREAD

**Issue by dstrnad** [dragoonDorise/EmuDeck#1329]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

New Emulator

### Elaborate on the feature you would like to see added to EmuDeck.

Could Sudachi be added to EmuDeck? It's the only updated switch emulator right now (besides the ryujinx hard fork). The developer is skilled and reliable. 

### Include any websites or links that may support your feature request.

https://sudachi.emuplace.app/
https://www.reddit.com/r/sudachiemulator/s/rHPinG0gZk

### Does this feature work on the Steam Deck?

Works great on linux, there is a new build.

**Comment by TheRazerMD** [comment]
> [@dstrnad](https://github.com/dstrnad) the developer has announced today he is stopping development in Sudachi so we won't add support :(

Funnily enough, Sudachi developer seems to be back as there's a new version released

**Comment by dstrnad** [comment]
@TheRazerMD Yeah, I just saw that yesterday. The latest version has broken audio on Linux, but the developer promised to address it in another future update. He also mentioned working on another Android version, so it seems like Sudachi isn’t completely dead after all…maybe this feature request could be reopened.

**Comment by TheRazerMD** [comment]
Indeed, Sudachi might have a future. Albeit, in the meantime, I would like to see the Greemdev fork of Ryujinx (or, Ryubing now) be added to Emudeck, as they seem to be going full steam ahead.

**Comment by dragoonDorise** [comment]
> Indeed, Sudachi might have a future. Albeit, in the meantime, I would like to see the Greemdev fork of Ryujinx (or, Ryubing now) be added to Emudeck, as they seem to be going full steam ahead.

That's the fork we currently use for Ryujinx :)

**Comment by TheRazerMD** [comment]
> That's the fork we currently use for Ryujinx :)

Excellent, great to hear! That solves my request. Btw is there a list to check which sources EmuDeck uses for each emulator?

**Comment by BlackJackAU** [comment]
It would be great to have Sudachi added as it had an update a few days ago so it still looks to be in active development.

**Comment by WildFyr16** [comment]
On this note, with switching between different emulators and what not. Would EmuDeck ever have the ability to copy save files/mods/cheats/what ever else from between emulators? I made the "Switch" from Yuzu to Ryujinx about 3 months ago and I know it was a pain, but I have been noticing some issues with Ryujinx and the idea of having to find all the files and copy them to a new emulator is probably the only thing keeping me from manually installing Sudachi to play around with it.

**Comment by Audiowylde23** [comment]
Can we get citron and sudachi support they are both being actively worked on ?
