### ISSUE TITLE
Blank Patreon Login Screen

### ISSUE THREAD

**Issue by brianysf** [dragoonDorise/EmuDeck#1330]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

I have been running EA version for a while on Steamdeck. I had not updated EmuDeck for months so decided to check for updates. Upon launching EmuDeck I am prompted to login to Patreon to access. Clicking on login brings up a blank window. Underneath I can see the EmuDeck window has a blank token field.

Exited EmuDeck. Launched again, and this time clicked on Change Account. Window opens showing Patreon page and shows that I am logged in.

Tried resbooting SteamDeck with the same result.

Downloaded latest EA Stable and installed. Same result.

**Comment by weeLzy** [comment]
Same issue here.

**Comment by dragoonDorise** [comment]
This was fixed

**Comment by git4maz** [comment]
I have the same issue, today!
