### ISSUE TITLE
[Feature Request] Binary checker for sync

### ISSUE THREAD

**Issue by ZombieBear** [dragoonDorise/EmuDeck#1340]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

EmuDeck Application Feedback

### Elaborate on the feature you would like to see added to EmuDeck.

I recently configured cloud sync on my steam deck, joined the patron and updated emudeck , but was running into issues getting the sync to work. After a lot of troubleshooting and digging in the logs, it turned out that the rclone binaries we're missing from my install. I was able to address it by downloading the latest binaries manually from the project's site and placing them in the correct folder.
My suggestions would be to add a repair button in the client which would ensure all the binaries needed by the software are available, and if possible try to download them, or at least provide a user facing message so it doesn't involve exporting logs and digging through them for less experienced users

### Include any websites or links that may support your feature request.

N/A

**Comment by jabuxas** [comment]
I'm having an issue where every time I try to install cloudsave, it errors with executable failure, reinstall. That might be the reason, e.g I don't have tools/rclone. Wonder why there wasn't a check..

What tools were you missing?

**Comment by ZombieBear** [comment]
Yeah I was missing rclone but I solved it myself, this is a feature request for a binary checker, but I was recently informed in the discord this is already implemented

**Comment by ZombieBear** [comment]
This seems to be implemented already I just didn't know where to find it

**Comment by jabuxas** [comment]
what menu is it in? can't find it :v

**Comment by ZombieBear** [comment]
It's in the cloudync section, the Test Cloud Synch Health button

**Comment by jabuxas** [comment]
oh yeah, I have that, but it doesn't install rclone for me at all. it only says "executable failure, reinstall."

**Comment by ZombieBear** [comment]
You can download the binaries from the rclone site at
https://rclone.org/downloads/, choose the Intel/AMD 64bit package for Linux
and place the files in the folder to solve the issue. You can get the
specific folder for your system by exporting logs in the emudeck app and
it'll place a file on your desktop

**Comment by jabuxas** [comment]
thanks! that worked.

**Comment by ZombieBear** [comment]
Happy to help!
