### ISSUE TITLE
Add Warning about RPCS3 requiring firmware installation

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#137]
Tell the user where to get the update from Sony and how to install it.

**Comment by dordododo** [comment]
wait you need a firmware installation?

**Comment by Godsbane** [comment]
For RPCS3? yes. https://rpcs3.net/quickstart

**Comment by dordododo** [comment]
> For RPCS3? yes. https://rpcs3.net/quickstart

Thank you, had no idea why it wasn't working

**Comment by Godsbane** [comment]
Documentation added to appimage for this.
