### ISSUE TITLE
Dev_HDD0 copy doesn't always work.

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#139]
START:
![image](https://user-images.githubusercontent.com/1683513/167286457-ea644496-7166-4512-9100-96e247c9f097.png)
after script - empty saves folder, all files still remain in original location:
![image](https://user-images.githubusercontent.com/1683513/167286507-401baf9b-ff05-4ded-a99e-0fd3d233e0fc.png)
Command from script on it's own - Everything functions(i have also reset the folders to be like start and it still works):
![image](https://user-images.githubusercontent.com/1683513/167286560-790258a3-4cf5-4796-9ba3-83c28f74fe72.png)

@dragoonDorise i do not understand.

Can we change to rsync perhaps?

offending block starts here: https://github.com/dragoonDorise/EmuDeck/blob/32aafaaca01336755826242cb94ba2c53a1757c0/install.sh#L1437

**Comment by dragoonDorise** [comment]
@Godsbane changed it to rsync on every branch, as this shouldn't broke anything

**Comment by Godsbane** [comment]
Thanks, I'll test and validate Ina bit

**Comment by Godsbane** [comment]
i figured it out. will patch and pr.

**Comment by Godsbane** [comment]
https://github.com/dragoonDorise/EmuDeck/commit/02bf4aec739b08245be7eae225eb94d7f5c5dae8

**Comment by Godsbane** [comment]
pushed to main, closing.
