### ISSUE TITLE
select all” on the expert installer

### ISSUE THREAD

**Issue by dragoonDorise** [dragoonDorise/EmuDeck#141]
Can we have a “select all” on the expert installer when selecting which emulators we want to install?

**Comment by Godsbane** [comment]
how about just a "Do you want to install all emulators?" dialog before. if the user says yes, we skip the checkboxes. if they say no, we show them. 

Also maybe All / None / Custom ? would hit a lot more use cases.

**Comment by Godsbane** [comment]
@dragoonDorise do you want me to make it so all the lists are all checked by default?
