### ISSUE TITLE
Do more basic configuration for systems for optimal settings.

### ISSUE THREAD

**Issue by dragoonDorise** [dragoonDorise/EmuDeck#143]
any chances we can do some basic configurations in the future? like choosing the language of the emulated consoles, or using the parallel plugin instead of GLideN64 for N64 games

**Comment by Godsbane** [comment]
definitely, should be part of a quality pass, i think?
there's so much we can optimize.

**Comment by Godsbane** [comment]
Retroarch - melonDS: Firmware controls language. We can't adjust this for the user because we don't provide firmware.

**Comment by dragoonDorise** [comment]
OLD
