### ISSUE TITLE
Suggestion - Add Ryujinx Support

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#156]
Had a request. can install and setup as a disabled parser.

**Comment by Godsbane** [comment]
wih the bug in the flatpak about calling roms, need to pursue the binary.

**Comment by KylerNyhagen** [comment]
+1 to this.

Ryujinx and Yuzu both focus on different features of the switch. It makes sense to have the option. I regularly find myself having to bounce between them.

**Comment by chowder3907** [comment]
+1, I would love to have ryujinx LDN for multiplayer built into emudeck

**Comment by Kuusetsu** [comment]
+1 for sure, at the time of writing Ryujinx (and the Early Access build of Yuzu) is the only emulator capable of playing Xenoblade Chronicles 3.

**Comment by dragoonDorise** [comment]
Fixed in 0.17.6
