### ISSUE TITLE
PS3 not working at all

### ISSUE THREAD

**Issue by Enerccio** [dragoonDorise/EmuDeck#17]
Invalid file or folder. I think it's related to flatpak or something like that. If I install disc from same folder as would steam rom manager and create shortcut from that it will have completely different path: Exec="/app/bin/rpcs3" --no-gui "/run/user/1000/doc/e74b382/Persona 5/PS3_GAME"

**Comment by Enerccio** [comment]
I "fixed" it by changing the path on steam rom manager to scan for /{title} only and then I used `/run/user/1000/doc/e74b382/{title}/PS3_GAME` as path. 

But also controls do not work out of box, have to set them up in rpcs3 desktop mode

**Comment by dragoonDorise** [comment]
Hi @Enerccio , can you share your config with me? Did you install the game on RPCS3?

**Comment by Enerccio** [comment]
I think I figured it out. It was flatpak issue with disk permissions. Btw would it be possible for steam rom manager to detect games installed in rpcs3 as packages?

**Comment by dragoonDorise** [comment]
Hi, I added flatseal instructions to fix PS3 problems a while back. There is no current plans to support that kind of games right now, we’ll see in the future!
