### ISSUE TITLE
[Feature Request] Mupen64Plus standalone

### ISSUE THREAD

**Issue by Spidy123222** [dragoonDorise/EmuDeck#170]
I find having standalone emulators to perform better in general when not under retroarch and wonder if mupen64plus could be supported as standalone. This could also just give people options if they rather have standalone or a retroarch core. 

The controls could be the same layout as what’s on the retroarch core but for standalone version.

**Comment by Godsbane** [comment]
As we have added Rosalie's Mupen Gui, i'll mark this as fixed.
