### ISSUE TITLE
[Bug] Installer incorrectly gives a statement about PowerTools when installing Gyro

### ISSUE THREAD

**Issue by AngelofWoe** [dragoonDorise/EmuDeck#186]
install.sh Line 1766 - text="$(printf "To finish the installation of PowerTools you must reboot your system. Ypu can continue the rest of the EmuDeck installation and rom configuration, but remember to reboot if you want to enable PowerTools")"

**Comment by Godsbane** [comment]
fixed: https://github.com/dragoonDorise/EmuDeck/commit/70aa12e05c1ed311411baa00305793ac2101ecc2
