### ISSUE TITLE
PPSSPP standalone - No config to get back to emu menu

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#187]
needs binds work

**Comment by Godsbane** [comment]
i don't think this will work without a steam input profile.

none of the hot keys seem to be bindable as combos.

**Comment by Zandengoff** [comment]
I am in the same situation. If using the individual game links for psp games in steam, there is no way to get to the ppsspp menus. Setting the config in the main app does not carry over to the individual games. So all games have to run with default settings.

**Comment by Zandengoff** [comment]
That was it, I swear I had tried L3+R3 before, but it worked as expected. Went ahead and took your suggestion and turned on the parser for PPSSPP standalone in the rom manager. I know it shouldn't really matter, but it seems I am getting better performance through the stand alone app, so going to stick to that from now on. Mapped Esc to L4 and have everything I need now. Thanks!

**Comment by Godsbane** [comment]
I do agree it's better. The one in RA is for people who like the RA system of converged settings etc.

**Comment by Zandengoff** [comment]
I don't really understand the default of pushing it to RA, but also installing PPSSPP standalone. I figured it would be one or the other. The defaults in this case seem to be a bit mixed. Wanted to also ask, will the parser settings stay now that I have them set or will I need to change them on every update now?

**Comment by Godsbane** [comment]
The reason that PPSSPP RA is the default, is that it was first. We didn't add PPSSPP until later, and it's easy enough to toggle if you want it.
parser settings are reset on update, like other configs.

**Comment by Godsbane** [comment]
Added steam input profile.
