### ISSUE TITLE
RPCS3 Controller not working after profile update

### ISSUE THREAD

**Issue by IBNobody** [dragoonDorise/EmuDeck#189]
The SD controller inputs for RPCS3 don't work for me out of the box or after rerunning the EmuDeck installer (at least for P5). Just tested it today again and still had the issue.

Even though evdev is already set up, I have to do the following to fix it: 

open RPCS3, open pads, select keyboard under handlers, click ok, open pads, select evdev under handlers, click ok.

So something else is being set in the config files. 

Once I do this, I'm golden until I run the EmuDeck installer.

**Comment by Godsbane** [comment]
Hey - I just want to validate your experience. same thing happens to me, and others in the discord as well.

Thanks for opening the ticket, i'd been meaning to for a while, but keep forgetting. I will try to get this figured out.

**Comment by Godsbane** [comment]
fixed: https://github.com/dragoonDorise/EmuDeck/commit/9a552d5d95854b65af6dab787d7f950c549c26a1
