### ISSUE TITLE
Custom file extention limit

### ISSUE THREAD

**Issue by ChobitsCrazy** [dragoonDorise/EmuDeck#199]
So this is kind of my last ditch effort here, I've come up empty everywhere else thus far. Is there a way to limit ES to only look at a single file extension for certain systems? I would like to limit PSX to only m3u but not sure if it is possible based on what I've found so far.

**Comment by Godsbane** [comment]
https://gitlab.com/es-de/emulationstation-de/-/blob/master/FAQ.md#i-have-many-games-with-multiple-files-is-there-a-way-to-show-these-as-single-entries
