### ISSUE TITLE
[Suggestion] Thinking of ideas to add specific controller mappings

### ISSUE THREAD

**Issue by IrealiTY** [dragoonDorise/EmuDeck#2]
First of all thanks for this script and setup!

I was wondering if it's possible to use your script to add controller mappings on the deck to specific emulators maybe?

For example, Yuzu doesn't quit properly if a game is launched via Steam command line in full screen and the most common fix is mapping `CTRL+Q` on a button to force close it. But since mappings on steam are individual by the game in the library, I was wondering if those kinds of extras could be done as part of the script? 
something like, `IF YUZU THEN ADD CTRL+Q TO R5 BUTTON`

**Comment by dragoonDorise** [comment]
Hey, I did something similar to Citra, so you can change the screen layout on the fly. Issue is you have to made a Steam input and apply it for every single game. You can see my Citra guide and do the same for yuzu: https://www.emudeck.com/
