### ISSUE TITLE
Controls not recognized on GameCube games

### ISSUE THREAD

**Issue by Vysp3r** [dragoonDorise/EmuDeck#20]
When I launch GameCube games from EmulationStation, the controls works just fine on my GameCube games, but when I launch them directly from the shortcut in Steam, they doesn't work. When I load the games in EmulationStation I can see a little box appearing telling me that the virtual controller has been set or something like that, but not on the shortcut version. Is there a way to fix this, or maybe I'm doing something wrong? 

P.S. I really like EmuDeck, I think it's amazing what you've done!

**Comment by dragoonDorise** [comment]
What version of EmuDeck are you using? This was fixed some days ago, please update EmuDeck and let me know if it worked!

**Comment by Vysp3r** [comment]
> What version of EmuDeck are you using? This was fixed some days ago, please update EmuDeck and let me know if it worked!

Oh yeah, I was way behind the latest version. My bad ahah. Now everything works fine!
