### ISSUE TITLE
[Feature Request] Add EasyRPG core to RetroArch via EmuDeck script

### ISSUE THREAD

**Issue by DFelten** [dragoonDorise/EmuDeck#208]
Please add the EasyRPG core to RetroArch when running the EmuDeck script. 

For this purpose I've created here a Steam Rom Manager preset for the RPG Maker with EasyRPG and RetroArch: https://github.com/SteamGridDB/steam-rom-manager/issues/98#issuecomment-1131316084 

So RPG Maker games can also be added and played directly via the Steam Rom Manager via preset after the EmuDeck script has run through.

**Comment by DFelten** [comment]
As far as I see there are no special configs for EasyRPG. You can't really set anything specific for this console. I do not use core overrides.

The only important thing for some older RPG Maker games is that we have to add the [RTP files](https://www.google.com/search?client=safari&rls=en&q=rpg+maker+rtp&ie=UTF-8&oe=UTF-8) for 2000 and 2003 into the bios folder:

- `bios/rtp/2000`
- `bios/rtp/2003`

**Comment by Godsbane** [comment]
been a while. I added easyRPG core to the list.

Looks like automatically downloading and extracting those two files will be easy. Any thoughts on the legality?

**Comment by DFelten** [comment]
These files are legit and this is the [official source](https://www.rpgmakerweb.com/run-time-package) for these files. As far as I know it's only not allowed to upload them on an other site. It would be easier if they were downloaded automatically. Alternatively, a hint should appear that leads to the page.

However, they are needed in some RPG Maker games, especially the older ones.

**Comment by Godsbane** [comment]
I've added the core to the install list. I attempted to download the two files and rename to zip and extact, but it didn't work. i'll look into it further.

**Comment by Godsbane** [comment]
looks like 7zr will work, but unzip will not.

**Comment by Godsbane** [comment]
7zr l easyrpg.zip 

7-Zip (a) [64] 17.04 : Copyright (c) 1999-2021 Igor Pavlov : 2017-08-28
p7zip Version 17.04 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,8 CPUs x64)

Scanning the drive for archives:
1 file, 13374927 bytes (13 MiB)

Listing archive: easyrpg.zip


ERROR: easyrpg.zip : Can not open the file as archive



Errors: 1

**Comment by Godsbane** [comment]
7zr not working either

**Comment by Godsbane** [comment]
aha it's just plain 7z. i'm stupid. all set.

**Comment by dragoonDorise** [comment]
Fixed in 0.17.6
