### ISSUE TITLE
[Question] Use DolphinTool CLI to compresss roms to RVZ?

### ISSUE THREAD

**Issue by DylanTackoor** [dragoonDorise/EmuDeck#216]
It looks like new Dolphin releases include a `DolphinTool.exe` CLI that can be used to convert and verify roms https://github.com/dolphin-emu/dolphin/pull/10252. Would it be worthwhile to try using it for a RVZ conversion prompt, similar to the CHD one?

I couldn't find a precompiled linux binary after searching for admittedly only a couple of minutes, so that would need to be figured out.

**Comment by Godsbane** [comment]
Good idea.

also we could handle cso for psp.

**Comment by Godsbane** [comment]
i couldn't find a linux binary on this, but maybe i can take apart something from a repository. I did try the windows binary via proton and that worked.

**Comment by DylanTackoor** [comment]
I also couldn’t find a source for a dolphin-tool binary, only compile instructions 🙃 I could try putting together a branch/draft PR this weekend to run it via proton, and I can mess with the cso tool if no one else is already working on it.

Also thinking I’ll test the dolphin-tool verify command via proton, and load up some proton compressed games to see if they’re fine

**Comment by Godsbane** [comment]
I actually already did the dolphin tool one locally on my machine. I will push my changes to got for you to look at. Certainly the whole script needs love.

**Comment by Godsbane** [comment]
@DylanTackoor here's the commit with the tool and the beginnings of what i was doing. I jotted down notes in comments for what my plan was. Feel free to run with it though.
https://github.com/dragoonDorise/EmuDeck/commit/935479a3d778663d62609a6e176911b673bca1ef

**Comment by Godsbane** [comment]
@DylanTackoor i found the linux binary:

/var/lib/flatpak/app/org.DolphinEmu.dolphin-emu/current/active/files/bin/dolphin-tool

**Comment by dragoonDorise** [comment]
Fixed in 0.17.6
