### ISSUE TITLE
PSX (PS1) roms not showing up 

### ISSUE THREAD

**Issue by DaBrondo** [dragoonDorise/EmuDeck#217]
I've installed the SCHP1001.bin bios.  I have both cue/bin and chd roms in the proper directory.  However, when I run steam rom manager they never show up in the list.  Any ideas?  My PS2 roms work fine.

**Comment by Godsbane** [comment]
Bios files must be in Emulation/bios with the proper case sensitive names. I would use the 550x named files as they are known good.

That does not have anything to do with srm not seeing your things though. That's going to be path and file extension.

For better support please come to the discord.
