### ISSUE TITLE
RetroAchievements crashes games if the user has not verified the account

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#224]
![image](https://user-images.githubusercontent.com/1683513/169952253-d50ea32e-1f27-4ca5-ad7e-03035f2d04b1.png)

**Comment by dragoonDorise** [comment]
Added this message

Make sure your RetroAchievments is validated on the website or RetroArch will crash

**Comment by dragoonDorise** [comment]
Added this message

Make sure your RetroAchievments is validated on the website or RetroArch will crash

**Comment by dragoonDorise** [comment]
Added on 0.17.5
