### ISSUE TITLE
Check if the user !has CEMU instead of overwriting the custom_systems xml on ESDE

### ISSUE THREAD

**Issue by dragoonDorise** [dragoonDorise/EmuDeck#228]
on easy mode, also check if some other auto configs on ESDE can be done without overwriting the users configs

**Comment by Godsbane** [comment]
I think we should just simple extend this to "Don't wipe out configs on update". in the case of XML, w e can easily insert properties using sed.

We should do this with the cemu settings.xml as well.

**Comment by Godsbane** [comment]
i've downloaded the binary for xmlstarlet from the arch repo, to begin experimenting with updating these xml files instead of wiping them out.

**Comment by dragoonDorise** [comment]
Added on 0.17.5
