### ISSUE TITLE
SRM Flatpak version has been released

### ISSUE THREAD

**Issue by goooooodman** [dragoonDorise/EmuDeck#229]
https://flathub.org/apps/details/com.steamgriddb.steam-rom-manager

**Comment by Godsbane** [comment]
Thanks for the heads up :)

As of now we'll probably stick with the AppImage as it's what's already out there on devices, and i'm not sure it's worth the effort to switch.

Maybe one day though!

**Comment by geekosaurusR3x** [comment]
Maybe a option in expert for switching to the flathub version ?
Or using it only if it's a fresh install (and who whant to swap must reinstall from scratch)?
It will be more choerent with all of the emulator app and take less place on the desktop folder

**Comment by Witherking25** [comment]
Funny enough, I made that flatpak. All you would really have to do is copy the configs and stuff from ~/.config to ~/.var/app/com.steamgriddb.steam-rom-manager/config
