### ISSUE TITLE
Multiple Controller Configuration

### ISSUE THREAD

**Issue by Rahabib** [dragoonDorise/EmuDeck#230]
I can rearrange my controllers to get my xbox controller recognized in game, but any additional controllers added are not.  I know I can manually configure the additional controllers, but its not an easy process, and users may end up screwing up their configs.

It would be convenient to have controllers 2-4 configured automatically.

**Comment by Godsbane** [comment]
is there a specific emulator you are having this problem with? At one point Dragoon added 3 more controllers for most of them, so if something got missed let us know which.

**Comment by dragoonDorise** [comment]
Hi, we have PS4 and PS5 controller support for some games, can you send me the configuration for dolphin for your Xbox controller so we can add it?

**Comment by dragoonDorise** [comment]
Hi, we have PS4 and PS5 controller support for some games, can you send me the configuration for dolphin for your Xbox controller so we can add it?

**Comment by Godsbane** [comment]
it should not matter what type of controller it is, because steam input will abstract the controllers as "evdev/0/Xbox pad #" and it's just up to the user to pair the controllers and change the controller order in the front end. The program in the background has no idea the controllers are changing (as long as steam input is being used!)

**Comment by Rahabib** [comment]
I am not sure where the configuration is located. I installed it to my SD card, and with hidden files there isn't a location for the configs. In my local .emulationstation folder I don't see the any configuration files.

**Comment by Godsbane** [comment]
So, for dolphin specifically, this has an unfortunate side effect of making it so that extra wii pointers show up in games regardless of how many controllers are actually on. (see SMGalaxy for example)

**Comment by Godsbane** [comment]
every emu is setup for multiplayer at this point in time. I will close this :)
