### ISSUE TITLE
Yuzu : Wrong save folder

### ISSUE THREAD

**Issue by geekosaurusR3x** [dragoonDorise/EmuDeck#231]
Hi

i have intall yuzu from emudeck and setup for usind the sdcard.
Having a non patched switch i have backup my saves and ported them to my SD.

actualy: 
/primary/Emulation/saves/yuzy/saves is linked to ~/.var/app/org.yuzu_emu.yuzu/data/yuzu/sdmc
But when i open the save directory from yuzu it point to :

/.var/app/org.yuzu_emu.yuzu/data/yuzu/nand/user/save/

Did i have setup something wrong ?
Or the link path need to be updated ?

Thank

**Comment by Godsbane** [comment]
@dragoonDorise i am not sure on this one. I don't know the yuzu structure well enough.

**Comment by dragoonDorise** [comment]
Hi @geekosaurusR3x , you are right, I've pushed a quickifix so if you update emudekc the symlinks should be fixed
