### ISSUE TITLE
Can we add recursive rom parsing tips somewhere?

### ISSUE THREAD

**Issue by emehrkay** [dragoonDorise/EmuDeck#232]
I have some roms (switch, psx) in folders that have multiple parts (.bin .que etc). Can there be something added to the guide that tells users how to recursively search for those files?

I discovered that you need to:
1.  Open Steam Rom Manager
2. Go to the emulator of choice
3. Find the parser section
4. Prefixing `**/` to ${title} so it looks like `**/${title}`

> apparently `*/${title}` searches one dir deep `**/${title}` does recursive searching

And everything works as expected

**Comment by Godsbane** [comment]
Part of this being the way it is, is because of ignorance when we started. We have used recursive searching in at least once parser, so it's a known factor. But also now people have been doing things like putting dlc in sub folders so they don't get picked up, etc.  An argument could be made that this is wrong, and just remove the unneeded files, but it's just another thing to think about.

Overall I am for it, and have thought about doing this quite a bit, because would be nice to not have to tell people to put the files in the base of the rom directory.

**Comment by emehrkay** [comment]
Yeah definitely dont change the default behavior of things. Just mention how to do recursive searching in the documentation somewhere. Just to give people access to some info that `I` had to search for

**Comment by Godsbane** [comment]
In the end it might be worth changing the behavior in any case. It would be a one time thing, and people might be caught unaware, so if we do it will provide people with plenty of warning.

**Comment by dragoonDorise** [comment]
I've added a explanation at the end to not use subdirectories for roms or bios except for PS3, Wii U and Switch games

**Comment by dragoonDorise** [comment]
I've added a explanation at the end to not use subdirectories for roms or bios except for PS3, Wii U and Switch games

**Comment by Godsbane** [comment]
Lets think about just enabling recursion on all of the dirs. What would it hurt? A few people with extra stuff might be like wtf? But then we just have them move it. The more i think on this the more i think it's the right way to do it.

**Comment by dragoonDorise** [comment]
Fixed in 0.17.6

**Comment by realJustinLee** [comment]
Broken again

**Comment by dragoonDorise** [comment]
@realJustinLee which system?

**Comment by realJustinLee** [comment]
@dragoonDorise for me, it’s nes. But actually it seemed to affect multiple other systems.

**Comment by realJustinLee** [comment]
@dragoonDorise I simply unzipped the download rom with the wrapping folder, I thought it might be every dedicated folder for a single game.

**Comment by Godsbane** [comment]
As a heads up:

RetroArch content directory overrides are NOT recursive, no matter what.

This means the settings applied by all the things we do are not applied unless you use the actual folder, and subfolders break it all.

**Comment by realJustinLee** [comment]
@Godsbane Oh I see, thanks.
