### ISSUE TITLE
Suggestion - DuckStation quick menu binding

### ISSUE THREAD

**Issue by CleyFaye** [dragoonDorise/EmuDeck#234]
When using DuckStation (which seems to be the default for PSX games launched from the Steam library) no "extra" command works; in particular there's no "exit" command with start+select (which is fine by me) and no access to menu/options/disc changes (which is problematic).

I'm not too sure *how* this could be integrated into EmuDeck, but binding the quickmenu from DuckStation to any key and providing a controller configuration that bind this key to something like L5 would greatly improve the experience.

I already did that "manually" (by launching duckstation by hand and binding the M key to the quick menu, then mapping that in Steam controller config) and confirm it works fine, but I wouldn't know how to put that in a PR for now.

**Comment by Godsbane** [comment]
i dug in, and it doesn't work to do combo keys on controller.

I did build a touch menu interface just for this with a brand new steaminput profile.

**Comment by Godsbane** [comment]
fixed: https://github.com/dragoonDorise/EmuDeck/commit/78ec14356ddb2556348e9295de7b272cbdbd67dd

**Comment by Godsbane** [comment]
certainly. i did the quick menu one, i can add change disc.

**Comment by CleyFaye** [comment]
Great, thanks again! Looking forward to it.

**Comment by dragoonDorise** [comment]
Added on 0.17.5
