### ISSUE TITLE
ES-DE - EpicNoir Theme - Missing backgrounds for DOOM / DOS and possibly a few other supported systems

### ISSUE THREAD

**Issue by AngelofWoe** [dragoonDorise/EmuDeck#235]

**Comment by dragoonDorise** [comment]
List of missing systems:

64dd
ags
amiga600
android
apple2gs
astrocde
atarijaguarcd
atarixe
bbcmicro
cavestory
cdimono1
cdtv
chailove
channelf
coleco
cps
desktop
doom
dos
dragon32
epic
fbneo
gx4000
j2me
lutris
lutro
macintosh
mame-advmame
mame-mame4all
megacdjp
mess
model2
model3
moonlight
moto
msx1
msxturbor
multivision
naomigd
neogeocdjp
odyssey2
openbor
oric
palm
pc88
pcfx
pico8
pokemini
ps4
psvita
samcoupe
satellaview
saturnjp
sega32xjp
sega32xna
snesna
solarus
spectravideo
stratagus
sufami
symbian
tanodragon
ti99
tic80
to8
trs-80
uzebox
videopac
x1
zmachine

**Comment by dragoonDorise** [comment]
Added backgrounds + Names for all the systems, still remains to add descriptions but at least people will see the name of the system

**Comment by Godsbane** [comment]
Fix the 3ds text overlap

**Comment by dragoonDorise** [comment]
Closing the issue since I've added a ton of this. Will open separate issues if new systems are added on ESDE
