### ISSUE TITLE
Suggestion: Add texture load folders for emulators

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#242]
Certain emulators let you do texture replacments.

Abstracting to a folder in Emulation would make this easier for people.

Started this with the migration to Yuzu appimage for it's directories.

(requested on Discord)

Mesen - DONE
Citra
Yuzu https://github.com/amakvana/YuzuModDownloader?
N64

**Comment by dragoonDorise** [comment]
Crated "$emulationPath"/hdpacks
and "$emulationPath"/hdpacks/Mesen as a symlink for bios/HdPacks

**Comment by dragoonDorise** [comment]
Closing this issue, better to open new ones. One per Emu so its easier to track. We also have some PR with changes related to this issue so it's even easier to follow over there :)
