### ISSUE TITLE
RA Bug: Retroachievements Verbose mode doesn't play well with Mame-Current

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#245]
turn on Advanced settings
go to achievements
turn off Verbose mode.

the above only partially fixes it.

Achievements must be all the way off for mame-current controls to work for some games

Build Core override disabling RetroAchievements for this core.
`$HOME\.var\app\org.libretro.RetroArch\config\retroarch\config\MAME\MAME.cfg`
`cheevos_enable = "false"`

**Comment by Godsbane** [comment]
the above only partially fixes it.

Achievements must be all the way off for mame-current

**Comment by JediRhymeTrix** [comment]
I can confirm that enabling achievements seems to be breaking the controls.
