### ISSUE TITLE
Suggestion: Add standalone mGBA

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#249]
![image](https://user-images.githubusercontent.com/1683513/173246872-e340cf94-0246-4832-bd3b-a15d08200bb4.png)
apparently upscaling in the standalone is better

**Comment by Richi08** [comment]
I definitely wouldn't complain about this getting configured automatically as standalone 👍

**Comment by mgtpt** [comment]
It was very good that you went ahead with this request, how can I help?
