### ISSUE TITLE
[feature request] Xenia support

### ISSUE THREAD

**Issue by Spidy123222** [dragoonDorise/EmuDeck#25]
Xenia is a Xbox 360 emulator on windows at the moment and is being ported to Linux. Xenia is able to do a range amount of games. Currently only way that the developers on the discord suggested to run Xenia at the moment is to use wine/proton and seems like some people get good results on Linux. There haven't really been much testing that I saw on steam deck on Linux side but some have been testing on windows 10 dual booted which seemed to run alright. What would be ideal is to have Linux port used on emudeck but other option is using wine/proton as a compatibility layer.

**Comment by dragoonDorise** [comment]
Hi @Spidy123222 we have beta support of Xenia, wanna help us testing it?

**Comment by Spidy123222** [comment]
> Hi @Spidy123222 we have beta support of Xenia, wanna help us testing it?

Unfortunately I don't have a steam deck yet. I think I'll try it on a virtual machine when I get the time.

**Comment by Spidy123222** [comment]
> > Hi @Spidy123222 we have beta support of Xenia, wanna help us testing it?
> 
> 
> 
> I recently got my Steam Deck and wouldn't mind testing it.

From what I saw on emudeck Discord Xenia channel it doesn't work fully compared to the other versions. Also Xenia's Vulkan is quite old so it's like one of the factors. I've been tracking their progress on Vulkan to tell about their progress sense I don't think any Xenia devs are likely in emudeck discord. You can try out the emulator, it might work out for you maybe.

**Comment by mdeguzis** [comment]
How do I test this? I tried to run `./installCLI.sh` with expert mode with the `dev` branch, but I didn't see `xenia` on the emulator list

**Comment by mdeguzis** [comment]
ok I see...
```
case $devMode in
	"BETA") 	branch="beta" 		;;
	"beta") 	branch="beta" 		;;
	"DEV") 		branch="dev" 		;;  
	"dev") 		branch="dev" 		;;
	*) 			branch="main" 		;;
esac	
```

**Comment by mdeguzis** [comment]
I tried to get this to work, updated xpp image for xenia within EmuDeck, and then I copied the launcher files from this repo into the Emulation folder for ROM manager so it showed up easily under that collect in the deck ui.  Hower it wouldn't even start.  Are there any dev notes on a quick setup?

**Comment by bugs181** [comment]
Off-topic but;

@mdeguzis For politeness, it may be better to edit your original comment instead of having 3 different comments. It really clogs up the issue for others tracking it's progress and wreaks havoc with the Github notifier.

**Comment by whise** [comment]
Any progress on this?

**Comment by whise** [comment]
I wouldn't mind testing also

**Comment by Godsbane** [comment]
So overall, it's not really working at all in proton yet, with an exception. Some XBLA games are apparently working (though i am not certain how well)

Will look at putting together a proper installer script as soon as we do the next release.

**Comment by emmett-os** [comment]
any updates?

**Comment by Spidy123222** [comment]
Relying on Xenia on their Linux port so nothings different rn.

**Comment by mdeguzis** [comment]
Xenia Canary experimental works ok: https://github.com/mdeguzis/SteamOS-Tools/wiki/Xenia-on-SteamOS. Playing Goldeneye 007 XBLA fine on it. If the steps could somehow be automated into EmuDeck, it could be offered in a limited beta capacity.

**Comment by Godsbane** [comment]
Custom system for Es-de is done, parsers for srm are done.

Going to tag as fixed in dev.
