### ISSUE TITLE
Steam Rom Manager - Yuzu games with an é in the path break it

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#255]
"/run/media/mmcblk0p1/Emulation/tools/launchers/yuzu.sh" -f -g "'/run/media/mmcblk0p1/Emulation/roms/switch/Pokémon Let's Go, Pikachu!.nsp'"
for example

**Comment by Godsbane** [comment]
and also stylized apostrophe

**Comment by Godsbane** [comment]
This appears to be a steam bug. I ran the same command from commandline without issue. only happens when the string is pasted into a steam shortcut.

**Comment by yenhanshih** [comment]
Can confirm with the title "The Legend of Zelda - Link's Awakening"

Launching from Gaming Mode crashes immediately whereas launching from Desktop mode works.

"run/media/mmcblk0p1/Emulation/tools/launchers/yuzu.sh" -f -g "'run/media/mmcblk0p1/Emulation/roms/switch/The Legend of Zelda Link's Awakening [01006BB00C6F0000][v0].nsp'"

**Comment by m0nk210** [comment]
> Can confirm with the title "The Legend of Zelda - Link's Awakening"
> 
> Launching from Gaming Mode crashes immediately whereas launching from Desktop mode works.
> 
> "run/media/mmcblk0p1/Emulation/tools/launchers/yuzu.sh" -f -g "'run/media/mmcblk0p1/Emulation/roms/switch/The Legend of Zelda Link's Awakening [01006BB00C6F0000][v0].nsp'"

took me ages to figure out - workaround for just rename the .nsp and run the Rom Manager again.
