### ISSUE TITLE
How to save shaders per core?

### ISSUE THREAD

**Issue by Temporalin** [dragoonDorise/EmuDeck#257]
Hi, I'm emulating some N64 games and, while I can set up a shader preset, I have to do it manually every time I launch a game. I try to save the settings for the core and it shows a message like it did, but when I close and open a game again it is again without shaders.

This works in my standard RA installation in my main rig, so I guess the cause is either the Flatpak stuff or the EmuDeck stuff.

**Comment by Godsbane** [comment]
Try saving the content directory override.

**Comment by Temporalin** [comment]
It said that the settings where saved as `n64.slangp` (or something similar) but loading a different game shows that it didn't work. The file does not even exist under `/home/deck/Emulation/roms/n64`.

**Comment by svera** [comment]
@Godsbane there seems to be a problem with shaders presets in RetroArch, as I have the same issue as @Temporalin but with Gameboy. Every time I change to use the `lcd3x.slangp` it works OK, I save core overrides and close RetroArch. When I load the same game again, shader preset is not the applied though.

**Comment by Godsbane** [comment]
Load content that has a shader applied automatically. Go to the quick menu via both sticks in retroarch. from there, navigate to shaders.
![image](https://user-images.githubusercontent.com/1683513/174447565-be119f1e-38a3-4297-9248-ae3fcc48ee0f.png)
in shaders find remove, and select it.
![image](https://user-images.githubusercontent.com/1683513/174447588-6390f58b-2606-4f10-9935-3f82acbf3ad1.png)
hit the button that says remove content directory preset
![image](https://user-images.githubusercontent.com/1683513/174447596-38bc3c39-d667-4c5a-8b06-8cc8c3b9505b.png)
close retroarch, reload content. no shaders applied (yes it's hard to see, but no more lcd squares)
![image](https://user-images.githubusercontent.com/1683513/174447652-b4ca78d1-7b5a-4ae9-b3f9-120a5b16f3cc.png)

**Comment by svera** [comment]
Thank you @Godsbane , that was it! Sometimes it is hard to know which config is applied, nice to know Emudeck is using configs at content directory level.

**Comment by Godsbane** [comment]
Awesome. glad that worked. I'll leave this open a couple of days and then close.

I made a wiki entry with the same instructions in case anyone else needs the info.

**Comment by svera** [comment]
Just a comment @Godsbane , because it seems that by default the lcd3x shader is not applied to Game Boy core on a fresh Emudeck install, although it appears as enabled. It would be great if you could take a look.

**Comment by Godsbane** [comment]
I do see the appropriate slangp for the gb folder, but i'll test and see what's up there, thank you.

**Comment by Temporalin** [comment]
It doesn't work for N64 games. Weirdly enough, there were 2 saved options under Quick Menu > Shaders > Remove (the 2 I tried: core preset and content directory preset). I removed them, loaded a preset, changed some parameters, applied, saved as preset for content directory, but it doesn't work.

If there is some way for me to help debug this let me know

**Comment by Godsbane** [comment]
so far i've figured out how to make it apply manually, but i can't seem to get the UI options to save the setting that's required.
You need a file called n64.cfg in `/home/deck/.var/app/org.libretro.RetroArch/config/retroarch/config/Mupen64Plus-Next/`
with these contents: (video_shader_enable = "true" being the key line)
```
aspect_ratio_index = "0"
video_crop_overscan = "false"
video_driver = "glcore"
video_shader_remember_last_dir = "true"
video_smooth = "true"
video_shader_enable = "true"
```
I've tried changing the Menu Item to save enable the shader, and then saved a content directory override, but it never contains the above line. Adding it manually and setting a shader override for content directory makes it work just fine.

**Comment by Godsbane** [comment]
with the wiki entry made, i'm going to close this. Will work on fleshing it out over time. Feel free to add more stuff too!
