### ISSUE TITLE
Clarity: give more data during migration so users aren't surprised

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#258]
Should give more data to the user / pop up about how much data and where before starting

**Comment by dragoonDorise** [comment]
@Godsbane can we close this issue? Since last migration was a looot of time ago, most of the users must have migrated already when we launched EmuDeck 2, right?

**Comment by Godsbane** [comment]
Yes, I will close it. I took this migration out anyways. No longer triggers
