### ISSUE TITLE
Bug report: cemu - after wake right analog stick stops working

### ISSUE THREAD

**Issue by sjdodge123** [dragoonDorise/EmuDeck#259]
Steps to reproduce:
1) Using deck ui 
2) launch a Wii u game: I used twilight princess hd
3) right analog stick works to control camera in game 
4) put the deck to sleep
5) wake the deck
6) right analog stick is now ignored

**Comment by Godsbane** [comment]
Sorry there's nothing we can do with this. it's unlelated to emudeck or configuration of the emu.
You'd want to repor this to the Cemu devs, but likely they won't support running cemu through proton, and will have to wait for native linux support.
