### ISSUE TITLE
Documentation Updates

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#261]
Documentation says the xemu hdd should be in Emulation/saves/xemu when it should be in Emulation/storage/xemu sinc 0.17.5

**Comment by Godsbane** [comment]
Documentation says RPCSX2 instead of PCSX2 in emulator table

**Comment by Godsbane** [comment]
Documentation for PPSSPP indicates 7z is supported. The RA Core does, but the standalone does not.

**Comment by dragoonDorise** [comment]
Fixed in 0.17.6
