### ISSUE TITLE
Unselected emulators (emulator settings) are updated

### ISSUE THREAD

**Issue by SiriusVI87** [dragoonDorise/EmuDeck#263]
Quick bug report, (I think). If I run Emudeck again and unselect emulators and emulator updates, the unselected emulators will still be set to their default configs. Example: I wanted to reset only the Yuzu settings to emudeck default, so I deselected everthung besides Yuzu, but e.g. retroarch configs were also reset to their defaults.

Both the retroarch.cfg as well as configs for individual cores were reset.

**Comment by Godsbane** [comment]
this should be fixed in Beta.

**Comment by dragoonDorise** [comment]
Fixed in 0.17.6
