### ISSUE TITLE
Wii U games from cd

### ISSUE THREAD

**Issue by dndeus** [dragoonDorise/EmuDeck#264]
Hello everyone! Thank you for your hard work!!

My question is: I have some wii u games directly from the cd. How should I compress them into wud or .wux or whatever file is appropriate for emudeck?

Thanks

**Comment by Godsbane** [comment]
Emudeck simply uses the windows emulator cemu. Take a look at the wiki article https://github.com/dragoonDorise/EmuDeck/wiki/CEMU and let me know if you still have questions.

**Comment by dndeus** [comment]
Cool, I figured it out! It looks amazing! Steam deck play them all like a champ

Thanks
