### ISSUE TITLE
Enhancement: Move Retroarch Shader location to a writable location

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#274]
The default config for the flatpak ships with the shader location configured for:
`video_shader_dir = "/app/share/libretro/shaders"`

Should change to:

`video_shader_dir = "~/.var/app/org.libretro.RetroArch/config/retroarch/shaders"`

and then copy the files from:
`/var/lib/flatpak/app/org.libretro.RetroArch/x86_64/stable/active/files/share/libretro/shaders/shaders_slang` to `~/.var/app/org.libretro.RetroArch/config/retroarch/shaders`

**Comment by dragoonDorise** [comment]
@Godsbane did we did this already?

**Comment by Godsbane** [comment]
Yes, but we don't download the shaders during install. We probably should.

**Comment by zrooda** [comment]
Would be great to have some choice in the installer between the main categories of a) CRT and b) Upscaling shaders/filters like xbrz or similar. Unless I'm missing something it seems kind of inconvenient to use shaders in RA atm since EmuDeck sets up video filters that have to be turned off first.

**Comment by Godsbane** [comment]
The toggle turns the filters off.

**Comment by zrooda** [comment]
I'm aware though my point is a bit different - still out of scope for this here issue, I'll make a separate one.

**Comment by Godsbane** [comment]
It's specifically made to be easy. Turn on the shaders, and then adjust the preset if you don't like the chosen one.
