### ISSUE TITLE
Suggestion: add .wua file support for Cemu 

### ISSUE THREAD

**Issue by MuskettDev** [dragoonDorise/EmuDeck#279]
The latest version of Cemu uses .wua file format which allows for base game, update and DLC to be in one file, whilst compressing the file without any performance loss.

**Comment by dragoonDorise** [comment]
Hi @MuskettDev , we do support wua for Cemu. We are using Cemu 1.6.2 as 1.7.x is still experimental and not stable, but after you install EmuDeck, there an icon on the Desktop where you can update Cemu to 1.7.1 if you want, its called "EmuDeck Tool Updater"

**Comment by Godsbane** [comment]
this is meant to say we support 1.26 by default, and the experimental is 1.27 :)

**Comment by MuskettDev** [comment]
Thanks
