### ISSUE TITLE
Add Model 3 and 2 Emulator

### ISSUE THREAD

**Issue by dragoonDorise** [dragoonDorise/EmuDeck#282]
[SupermodelAssistant](https://github.com/nikescar1/SupermodelAssistant)

**Comment by WingofaGriffin** [comment]
Supermodel continuous builds in progress here https://github.com/trzy/Supermodel/pull/55

**Comment by mdeguzis** [comment]
@WingofaGriffin Have you had any time this year yet to look at that build? Looking forward to this!

**Comment by WingofaGriffin** [comment]
@mdeguzis Model 2 will hopefully get into next beta build thanks to https://github.com/dragoonDorise/EmuDeck/pull/959

Model 3 is in progress but currently blocked by a bad flatpak https://github.com/dragoonDorise/EmuDeck/pull/937

**Comment by mdeguzis** [comment]
Yea I had to build supermodel 3 from source.
