### ISSUE TITLE
Request: Add ZX Spectrum support to EmuDeck/Steam Rom Manager setups

### ISSUE THREAD

**Issue by gazchap** [dragoonDorise/EmuDeck#289]
It looks like EmuDeck's installer already adds a Spectrum emulator (Fuse) but it doesn't detect Spectrum ROMs in Steam Rom Manager so you have to launch EmulationStation.

**Comment by dragoonDorise** [comment]
Hi @gazchap , added on DEV, will go live on the next release

**Comment by gazchap** [comment]
Great, thanks!

**Comment by dragoonDorise** [comment]
Fixed in 0.17.6
