### ISSUE TITLE
SD Card support is broken for sd cards not called mmcblk0p1

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#29]
https://github.com/dragoonDorise/EmuDeck/blob/bf9ba69421a1260201227e194f504bf6fd95c5ab/install.sh#L93-L112

This block of code pulls the name of the SD Card for use in the script, and then it checks the sdcard name. If the sd card name isn't "mmcblk0p1" as referenced by line 103 above, it is treated as a failure. 
I don't believe that's the correct behavior, and i believe the check block should be removed or you should look for /dev/mmcblk0p1 instead.
You can format an SD card with whatever name you like and it mounts and operates correctly.

for example mine is called "external" and here is the current mount parameter: "/dev/mmcblk0p1 on /run/media/external type ext4 (rw,noatime)"

**Comment by MagonDead** [comment]
Hi Godsbane,

it would resolve the install script, sure, but not the rest of the package - the mmcblk0p1 as a name is kind of carpetbombed in the config files that is copied by the install script for various emulators, etc

**Comment by Witherking25** [comment]
Btrfs totally works however this explicitly checks for ext4 so it no longer lets you use btrfs.

**Comment by Godsbane** [comment]
I am open to adding btrfs. I was just going with what the deck formats by default.

is there a certain format that does NOT work? ntfs / fat32 come to mind. I could explicitly check that it's NOT one of these instead.

**Comment by Witherking25** [comment]
Exfat and fat32 do not support symlinks.

**Comment by Godsbane** [comment]
based on a comment chain in the discord, it seems BTRFS may not work by default. Seems to be mounted without permissions for the Deck user. also see: https://github.com/Trevo525/btrfdeck

**Comment by Witherking25** [comment]
Don’t use that use this
https://gitlab.com/popsulfr/steamos-btrfs

**Comment by Witherking25** [comment]
It’s persistent across updates and it doesn’t mount it is root

**Comment by Witherking25** [comment]
It is also simpler set up

**Comment by Witherking25** [comment]
> I am open to adding btrfs. I was just going with what the deck formats by default.
> 
> is there a certain format that does NOT work? ntfs / fat32 come to mind. I could explicitly check that it's NOT one of these instead.

The thing is, a whitelist is better than a blacklist in case a new filesystem type comes around that is incompatible. And it’s not guaranteed that every filesystem type other than fat32, exfat, and ntfs is compatible. Ext4 and btrfs are good for now. If a new filesystem comes around that is compatible that people would use for their sd card, then we can add support then.

**Comment by Godsbane** [comment]
Sounds good. I'll do a whitelist into a variable at the start of the script so we can modify it later.

**Comment by dragoonDorise** [comment]
See issues when using non ext4 cards:

https://github.com/dragoonDorise/EmuDeck/issues/8#issuecomment-1106943784

**Comment by Godsbane** [comment]
Fixed.
