### ISSUE TITLE
Yuzu flatpak permission issues

### ISSUE THREAD

**Issue by james2432** [dragoonDorise/EmuDeck#290]
Yuzu installed on SD card with ROMS on SD card freezes up because it doesn't have permissions to access the SD card's rom location.

Your script launches from ~/Applications/yuzu.AppImage  instead of the discover store one and you do not pass the permissions on to the flatpak arguments in yuzu.sh

https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access

you would have to give the rom folder or /run/media/mmcblk0p1 access via the launch parameters

**Comment by james2432** [comment]
I fixed my shell script by introducing:
    eval "/usr/bin/flatpak run --filesystem=/run/media/mmcblk0p1/Emulation/roms/switch/  org.yuzu_emu.yuzu ${param}"

on line 24:
https://github.com/dragoonDorise/EmuDeck/blob/main/tools/launchers/yuzu.sh#L24

**Comment by Godsbane** [comment]
It downloads the latest. If you ran it yesterday, that's why you got that one.
