### ISSUE TITLE
Cemu Path logic error

### ISSUE THREAD

**Issue by james2432** [dragoonDorise/EmuDeck#291]
https://github.com/dragoonDorise/EmuDeck/blob/main/install.sh#L900

They need to be back slashes or else CEMU doesn't load the roms, you are adding forward slashes

Example output should look like this:
```
<GamePaths>
        <Entry>Z:\run\media\mmcblk0p1\Emulation\roms\wiiu\roms</Entry>
</GamePaths>
```

not 

```
<GamePaths>
        <Entry>Z:/run/media/mmcblk0p1/Emulation/roms/wiiu/roms</Entry>
</GamePaths>
```

**Comment by Godsbane** [comment]
While correct, it doesn't affect anything.

**Comment by james2432** [comment]
I just came from a fresh install, it does not load the game cache if the directory contains forward slashes. I had to remove it and re-add it manually in the configuration screen, then it loaded the list of games

**Comment by james2432** [comment]
![image](https://user-images.githubusercontent.com/498547/181126130-383597a0-29cf-4503-a3b9-ae1bc67ad8ae.png)

vs

![image](https://user-images.githubusercontent.com/498547/181126448-2dd381eb-3959-4a3a-9c9f-a649cb3fef94.png)


and if I update it manually in the configuration like you did:


![image](https://user-images.githubusercontent.com/498547/181126693-242067c9-433e-4e76-a3ce-d1aca9f63c89.png)

**Comment by Godsbane** [comment]
![image](https://user-images.githubusercontent.com/1683513/181129807-ccc6f5a1-e6f8-445c-92ab-641b2ec73502.png)
works fine

**Comment by james2432** [comment]
https://cemu.info/changelog.html

Might be a cemu bug, in latest experimental:

- Fixed several bugs where Cemu sometimes wouldn't be able to locate a title stored in a game path

**Comment by Godsbane** [comment]
Run the Emudeck Tool Updater on your desktop, and update to cemu 1.27.1 and try again.  (Though i did use the same version you used)

As for actually entering the paths? haven't tried it. I've only edited the config via xmlstarlet.

**Comment by Godsbane** [comment]
i'm marking this as a bug, because you are correct that the opposite slashes are correct. I couldn't find a problem with it functionally, so it's not high priority. The only way to trigger that error seems to be to actually type the slashes as we have edited them into the xml. (which we don't do, and you do not need to do)

**Comment by james2432** [comment]
merged, closing
