### ISSUE TITLE
Use pcsx2 QT version

### ISSUE THREAD

**Issue by rlach** [dragoonDorise/EmuDeck#292]
Instead of using the PCSX2 emu from Discorer on Steam Deck use the QT version. QT UI adds per-game configuration, and other improvements over the old UI. This could be an option in Expert setup, but I feel like it would benefit all users. The QT menus are much better organized and much cleaner, so any user that has to launch PCSX2 directly, ever, would benefit from this.

**Comment by Godsbane** [comment]
literally done in dev

**Comment by iamPanka** [comment]
Hi, can someone give me instructions to set pcsx2 qt with Emudeck and Steam rom manager? Thanks a lot

**Comment by Godsbane** [comment]
Wait until release. Soon.
