### ISSUE TITLE
RetroArch Steam support

### ISSUE THREAD

**Issue by StefanTischler** [dragoonDorise/EmuDeck#31]
It would be great to support the Steam version of RetroArch (cloud save, ...)

Should be doable with just changing paths to the steam version (maybe user-selectable?).

Installing cores might be tricky, IDK if that's possible outside of steam.
Still would be great to support it, even if cores have to be installed manually.

**Comment by Witherking25** [comment]
es-de not support steam retroarch

**Comment by dragoonDorise** [comment]
Hi, I'm closing this as we don't plan to offer support for Steam's RA

**Comment by Crono141** [comment]
I'd like to point out [this thread](https://www.reddit.com/r/SteamDeck/comments/v2j0j0/guide_on_how_to_use_emulationstation_de_with_the/), that this is technically possible. Would you consider reopening this issue?

**Comment by Godsbane** [comment]
yeah why not. Actually did some testing with Leon (author of EmulationStation-DE).
We can look, but no promises. There's some logistical stuff here that makes it less feasible for automation, but perhaps we can add it as an extra option at some point.
`steam steam://rungameid/1118310 -L "nestopia_libretro.so" <pathtorom>` seems to be working, provided all paths are escaped properly.

**Comment by Crono141** [comment]
In the meantime, I have discovered a simple workaround to get your steam retroarch saves synced to non-steam retroarch.  Simply, have both installed, and point non-steam retroarch saves and states directory to the steam retroarch saves and states directory.  Steam handles keeping these folders synced up, and allows common saves.

We still lose other steam enhancements, such as remote play together, but if all one is looking for is cloud save support, this does the trick.

**Comment by Godsbane** [comment]
That is true, but if that's what you want we're working on implementing saves to cloud in general.

**Comment by Crono141** [comment]
I mean, cloud saves is the most obvious bonus for the steam version of retroarch, but certainly not the only one. I'm having a weird issue with my steam retroarch right now so this workaround gets me what I need right now, but I'm not the only one interested, I don't think.

**Comment by Godsbane** [comment]
Yeah, but unfortunately, I don't think we can ever fully support steam RetroArch. Many games fail to launch if called externally, there's issues installing it and cores automatically. I just don't think it will work out for emudeck. I will leave this open in case it all changes...

**Comment by hpfr** [comment]
You can close an issue as not planned if you use the [dropdown by the close button](https://docs.github.com/en/issues/tracking-your-work-with-issues/closing-an-issue); that would be a little clearer to searchers coming across this issue in the future.
