### ISSUE TITLE
Support for auto fetching latest Yuzu EA build

### ISSUE THREAD

**Issue by Titaniumtown** [dragoonDorise/EmuDeck#310]
It would be nice if EmuDeck incorporated fetching the latest Yuzu EA build automatically. This is a perk of being a Patreon Subscriber to the project and would seem simple to add to EmuDeck as well (only requiring a token to be used that's supplied via becoming a patreon subscriber).

Here's a script made on someone on Yuzu's discord server that could be adapted for this purpose: https://paste.gg/p/anonymous/179e3d37b3c748348d046f1b3f016c01

This may be out of scope however due to this being a Patreon benefit for another project however, so I don't know what other people's thoughts on this would be. lmk if this is out of scope or not.

**Comment by Godsbane** [comment]
Once we switched from the Flatpak to the AppImage it became rather trivial to swap your Patreon version in place of the current one.

It seems you already have a working script for this? What's the benefit to having Emudeck do it? You could just change the output of the python you have there to be yuzu.AppImage and it should work fairly seamlessly.

Let me know if i am missing something there, and there's more benefit to having it come from Emudeck.

**Comment by Titaniumtown** [comment]
> Let me know if i am missing something there, and there's more benefit to having it come from Emudeck.

Like I was thinking during setup or during the "EmuDeck Tool Update" one could select the Early Access branch and enter their token, it is just a way for the process to be streamlined for newbies.

**Comment by Godsbane** [comment]
Ok I'll put an enhancement tag on this for now.

**Comment by Godsbane** [comment]
Implemented in Beta.

put patreon key in "~/emudeck/yuzu-ea-token.txt"
