### ISSUE TITLE
This is causing SOME not all users to have games crash at start.

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#328]
https://github.com/dragoonDorise/EmuDeck/blob/37cd117bf071bade3a196de10387a7a14dda655e/configs/pcsx2qt/.config/PCSX2/inis/PCSX2.ini#L199

**Comment by peterlewis** [comment]
Fixed in https://github.com/dragoonDorise/EmuDeck/commit/218b5190e76bbf893866449a48e534b9e78891e1

**Comment by Godsbane** [comment]
Really want to understand why... Lol

**Comment by Godsbane** [comment]
closing for now
