### ISSUE TITLE
Why format sd card

### ISSUE THREAD

**Issue by christiaan** [dragoonDorise/EmuDeck#33]
The instructions say in the first step to format your sd card but fails to explain why a sd card is needed.

**Comment by Witherking25** [comment]
Roms can take up a lot of space so sd card is useful

**Comment by Witherking25** [comment]
And if you are against sd cards you can just install it on internal

**Comment by Witherking25** [comment]
And if your sd card is already in ext4 or btrfs file system you don’t need format

**Comment by filmcriticbeta** [comment]
My apologies for butting in, but I believe the OP is referring to step 1. of the 5 steps as listed on emudeck.com. It states in bold text “Format your SD Card in Steam UI” as the first sentence.  It can be therefore be inferred by less technically aware users that:

1. An SD card is required for this script to function correctly.
2. The end user is required to reformat their sd card, regardless of whether it has previously been formatted for steam deck or not.

To avoid end user confusion, it would be best to update the instructions to mention that the SD card is optional, and formatting is only required for new SD cards: eg//

( Optional - not required if you intend to install emudeck onto internal storage ): An SD card that has been previously been formatted for use on the steam deck.

**Comment by christiaan** [comment]
> My apologies for butting in, but I believe the OP is referring to step 1. of the 5 steps as listed on emudeck.com. It states in bold text “Format your SD Card in Steam UI” as the first sentence. It can be therefore be inferred by less technically aware users that:
> 
>   1. An SD card is required for this script to function correctly.
> 
>   2. The end user is required to reformat their sd card, regardless of whether it has previously been formatted for steam deck or not.

Sorry for replying late, I did not get any notifications about this somehow.
What @filmcriticbeta says is exactly what my problem is/was.

I just finished up installing Windows on my SD card and wanted to install emudeck on SteamOS and did not want to wipe my SD card. I still have enough room on the internal SSD so I did not understand why a SD card was needed.

**Comment by dragoonDorise** [comment]
Hi @christiaan , you don't need an SD Card, EmuDeck gives you the option to use your Internal Storage too. I'll clarify that on the website. Thanks!
