### ISSUE TITLE
Include multiple control profiles for Dolphin - i.e. Wiimote w/ Nunchuck, Wiimote Only, etc.?

### ISSUE THREAD

**Issue by coolspot18** [dragoonDorise/EmuDeck#331]
Hi all,

Some Wii games require a Wiimote only, others use a Nunchuck attacked, etc. It would be good if EmuDeck shipped with several pre-configured profiles so that games can be assigned one of the profiles using GameIni.

I could always create my own controller profile; but I believe these would be overwritten with an upgrade or reinstallation of EmuDeck?

In short, need several controller variations to account for the way a controller can be used with a Wii?

**Comment by Godsbane** [comment]
No creating your own would not be overwritten.

**Comment by Godsbane** [comment]
This is something i would like to include more of, but it needs to be a bit of a community effort (there's so many unique wii games!). So if you do create any send them to me and i will include them.

**Comment by coolspot18** [comment]
Hi @Godsbane,

The wiitdb at [Game](https://www.gametdb.com/) contains controller settings on a per game basis, I wonder if this file can be used in conjunction with Dolphin to auto-configure the control scheme during startup?
