### ISSUE TITLE
possible for widescreen and bezels to be turned on for PSX

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#333]
causes overlap

**Comment by failzers** [comment]
with the implementation of https://github.com/dragoonDorise/EmuDeck/pull/332/commits/1d1bbcffc12a181bb59560931af200b822aa9439 and https://github.com/dragoonDorise/EmuDeck/commit/6b80f38dc4e18991fcbc42120712ab5b33cb73b7 this should now make them turn each other off, but I wonder which will take preference if both are enabled upon setup 🤔

**Comment by Godsbane** [comment]
hrm. I think, turning off widescreen should NOT turn on bezels. however, turning on wideescreen should absolutely turn OFF bezels.

**Comment by Godsbane** [comment]
and to add on to this, turning on bezels should be be blocked if widescreen is on. Basically Widescreen should take priority as it's a more specific setting.

**Comment by Godsbane** [comment]
needs testing in dev
