### ISSUE TITLE
Hide Bin Files in Emulation Station and Steam Rom Manager for PSX

### ISSUE THREAD

**Issue by lifeiscontent** [dragoonDorise/EmuDeck#337]
Hi do you know how I could make this change using EmuDeck?

**Comment by Godsbane** [comment]
We don't look at bin files in Steam Rom Manager already, and require the cue.

Emulationstation has it's own method. https://gitlab.com/es-de/emulationstation-de/-/blob/master/USERGUIDE.md#directories-interpreted-as-files

The other (better alternative) is use the Compression tool on your desktop to conver to CHD for one file per game (which is also compressed)
