### ISSUE TITLE
Rumble does not work with Dolphin

### ISSUE THREAD

**Issue by miketweaver** [dragoonDorise/EmuDeck#34]
The controller rumble for GameCube does not work with the dolphin emulator config, while it does work with the retroarch config.

**Comment by Godsbane** [comment]
This is configurable in Dolphin. Just needs to be added to the profile.

**Comment by dragoonDorise** [comment]
Hi, already done, will be available on the next release!

PS: The Decks rumble motor is really shitty, you can't feel almost anything :(

**Comment by Godsbane** [comment]
I believe it just uses the touchpad haptics to simulate a motor, and that's why it's barely there
