### ISSUE TITLE
Check primehacks when running EmuDeck Compression

### ISSUE THREAD

**Issue by Stevoisiak** [dragoonDorise/EmuDeck#340]
### Issue
EmuDeck Compression script does not check PrimeHacks folder when searching for games to compress, even though the script supports compressing Wii and GameCube games.

### Steps to reproduce
1. Place ISO for Metroid Prime Trilogy (Wii) in roms/primehacks
2. Run EmuDeck Compression Script

### Expected result
Compression script asks if you want to compress primehacks folder, then compresses files as it would other Wii/GameCube games.

### Actual result
Compression script does not offer to compress primehacks folder

### System
- EmuDeck 0.17.6

**Comment by Godsbane** [comment]
Good point. Will add it.

**Comment by Godsbane** [comment]
fixed: f458550c94faf60d07240699d4d79c21792c2320
