### ISSUE TITLE
[Feature Request] BoilR integration/configuration

### ISSUE THREAD

**Issue by redoxeon** [dragoonDorise/EmuDeck#343]
[BoilR](https://github.com/PhilipK/BoilR) is another option for getting images from SteamGridDb, and can be run without sudo, and in cli with `flatpak run io.github.philipk.boilr --no-ui`

As far as I can tell, it's about the same as steam rom manager, but another option. it looks like it can possibly import from even more non-steam platforms based on the readme compared to SRM's readme.

**Comment by Godsbane** [comment]
At some point there was a bad interaction with SRM and Boilr. I do not know if it has been fixed. Would need to make sure of that first.
