### ISSUE TITLE
Add MSX/MSX2, Wonderswan/Wonderswan Color, and PC88/PC98 Steam Parsers

### ISSUE THREAD

**Issue by jet082** [dragoonDorise/EmuDeck#345]
As the title suggests. These are supported via RetroArch easily enough via the fMSX, Beetle Cygne, quasi88, and Neko Project II Kai cores.

**Comment by Godsbane** [comment]
are you certain these don't work? did you test in EmulationStation-DE?

For some of the more niche emulators there's not a steam rom manager parser provided, but they work in EmulationStation-DE.

**Comment by jet082** [comment]
Ah, so they do. The Deck just got released in Japan (I got a preview release) and I’m newer to it, so I didn’t know about DE. I tested it with the Wonderswan Color game I wanted to play and it worked just fine.

It would be nice to have parsers, however.

**Comment by Godsbane** [comment]
EmulationStation-DE supports launching something like 150 different platforms.

I don't know if we will add them all to SteamRomManager by default, but if there's some more popular choices, it's definitely something we can / should consider.

There's also community parsers available in the meantime (or you can make your own by copying an existing one).

**Comment by jet082** [comment]
Ah, I did not notice the community parsers at all. That worked really quite well. There were ones for the Wonderswan and MSX.
