### ISSUE TITLE
When launching a Wii U game from Steam on a 1080p monitor, the game starts with a black border (windowbox) around it

### ISSUE THREAD

**Issue by lionsnob** [dragoonDorise/EmuDeck#346]
The black border disappears when "ESC" is pressed on a keyboard but cannot be removed with an XBOX One controller.

This is HoloISO on a desktop PC. Is there a way to configure cemu or Steam to start in full screen? Default commands have not been edited.

Thank you!

**Comment by lionsnob** [comment]
Pressing STEAM+Left D pad will act as "ESC" and remove the border. I'd still prefer the game launching without the border but at least I don't need a keyboard with me now!

**Comment by Godsbane** [comment]
Haven't seen this, but unfortunately we have no bearing on what gamescope does.

**Comment by Godsbane** [comment]
i'm going to close this, because it's a steam or gamescope or cemu issue. If you disagree or find a way to change the behavior to  what you want, let me know.
