### ISSUE TITLE
Cemu - wine: RLIMIT_NICE is <= 20, unable to use setpriority safely.

### ISSUE THREAD

**Issue by TylerJaacks** [dragoonDorise/EmuDeck#347]
`../Emulation/tools/launchers/cemu.sh`

Results in

`fsync: up and running`
`wine: RLIMIT_NICE is <= 20, unable to use setpriority safely.`

**Comment by Godsbane** [comment]
Sometimes the prefix is messed up. I don't know why it happens, but you can change your prefix. 

in cemu.sh, look at the last line and change this bit from   `"${PROTONLAUNCH}" -p '7.0'`  to  `"${PROTONLAUNCH}" -p '7.0' -i 1`

**Comment by TylerJaacks** [comment]
So like this

`"${PROTONLAUNCH}" -p '7.0' -i -- "${CEMU}" "{$@}"`

**Comment by TylerJaacks** [comment]
Cause this results in return from the terminal with error code `1`

**Comment by Godsbane** [comment]
You missed the parameter for -i

`"${PROTONLAUNCH}" -p '7.0' -i 1 -- "${CEMU}" "{$@}"`

**Comment by TylerJaacks** [comment]
![Screenshot_20220814_205457](https://user-images.githubusercontent.com/1505374/184565026-1bb04056-c453-4482-86fa-e7699462541d.png)

So I am unable to select a rom.

**Comment by HonkinWaffles** [comment]
@TylerJaacks  - Try updating Cemu and then rebooting. I changed from Experiemental to Stable then back and it started working for me.

@Godsbane - +1 to this issue though, seems like something broke since last night. Though I was fucking around with the OS user permissions when it broke.

**Comment by Godsbane** [comment]
no has nothing to do with last night. it happens occasionally to users on the discord too. We don't know why. Everything is fine until it isn't, and there's no good reason why (that i can see).

just try another prefix if that one doesn't work. Experimental is also an option.

**Comment by TylerJaacks** [comment]
How to change the prefix and change from experimental to stable?

**Comment by Godsbane** [comment]
prefix is changed with the -i <number> parameter.
proton version is changed with the -p <version> parameter.

`-p '- Experimental'` will set it to use Proton Experimental. capitalization and such matters.

**Comment by Godsbane** [comment]
closing this, as, it's not really an Emudeck problem, but a proton problem. The tools to change prefix and proton version work.

let me know if you have more trouble and we can take a look.
