### ISSUE TITLE
Dolphin - change default graphics backend from Vulkan to OpenGL

### ISSUE THREAD

**Issue by scowalt** [dragoonDorise/EmuDeck#348]
### Bug
I was trying to play Paper Mario: The Thousand-Year Door on Dolphin on my Steam Deck. The game kept crashing on startup (or during the middleware screens). I was able to track down [this reddit post](https://www.reddit.com/r/DolphinEmulator/comments/vupf89/settings_to_get_paper_mario_the_thousandyear_door/). There are a few suggestions there, but the only non-default option was switching the graphics backend from Vulkan to OpenGL. Making this change (with no other changes) caused the game to work.

### Root cause
It looks like that option is set here:
https://github.com/dragoonDorise/EmuDeck/blob/a718692cba4e5dde97d2b899aa23a201452415e1/configs/io.github.shiiion.primehack/config/dolphin-emu/Dolphin.ini#L19

Or here:
https://github.com/dragoonDorise/EmuDeck/blob/00c843121cad50b32533419a2db6f511b59dbbdd/configs/org.DolphinEmu.dolphin-emu/config/dolphin-emu/Dolphin.ini#L9

### Fix
Could we change that setting to be "OpenGL" instead of "Vulkan"?

**Comment by scowalt** [comment]
Potentially related comment here: https://github.com/dragoonDorise/EmuDeck/issues/97#issuecomment-1116277192

**Comment by Godsbane** [comment]
No, just roll back Dolphin

**Comment by scowalt** [comment]
Got it, thanks for adding more context!
