### ISSUE TITLE
PCSX2 always crash when trying to boot a game 

### ISSUE THREAD

**Issue by Niksokupa** [dragoonDorise/EmuDeck#35]
Hi!

I've been trying to boot any ps2 game and I always get the same result; pcsx2 just closes.

I've tried with games in US and EU region, with .iso and .chd and it's always the same.

The only strange thing I noticed was that I installed it using the internal storage but when it tried to search for bios it was trying to search on run/media/mmcblkppq/Emulation/bios, I just switched it to home/deck/Emulation/bios.

For now it's the only emulator I've been having trouble with. I've tried SNES/N64/PS3/3DS/Switch and everything ran perfectly.

The log doesn't really says anything helpful but here it is in case that you need it:

PCSX2 Nightly - v1.7.2622 Compiled on Apr 17 2022
Savestate version: 0x9a2c0000

Host Machine Init:
	Operating System =  
	Physical RAM     =  14838 MB
	CPU name         =  AMD Custom APU 0405
	Vendor/Model     =  AuthenticAMD (stepping 02)
	CPU speed        =  2.799 ghz (8 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  178bfbff 7ed8320b
	x86EFlags        =  2fd3fbff

x86 Features Detected:
	SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX.. AVX2.. FMA
	SSE4a 

Installing POSIX SIGSEGV handler...
Reserving memory for recompilers...
WARNING: radv is not a conformant Vulkan implementation, testing use only.
Patches: No CRC found, using 00000000 instead.
Bios Found: Japan   v01.00(17/01/2000)  Console
Bios Found: Europe  v02.00(14/06/2004)  Console
Bios Found: USA     v01.60(07/02/2002)  Console
Bios Found: Europe  v01.60(04/10/2001)  Console
HLE Host: Set 'host:' root path to: /

Patches: No CRC found, using 00000000 instead.
isoFile open ok: /home/deck/Emulation/roms/ps2/Dot Hack Part 1 - Infection (US).chd
	Image type  = DVD
 * CDVD Disk Open: DVD, Single layer or unknown:
 * * Track 1: Data (Mode 1) (1268832 sectors)
Overriding 'Framelimiter_TurboToggle': assigning Shift+m (instead of Tab)
Vsync is OFF
WARNING: radv is not a conformant Vulkan implementation, testing use only.
No GPU requested, using first (AMD RADV VANGOGH)
2 vulkan queue families
VK_EXT_provoking_vertex is supported
VK_ARM_rasterization_order_attachment_access is NOT supported
Read 34 entries from '/home/deck/.var/app/net.pcsx2.PCSX2/config/PCSX2/cache/vulkan_shaders.idx'
Vulkan Graphics Driver Info:
	Driver 21.3.8
	Vulkan 1.2.195
	Conformance Version 1.2.3.0
	Mesa 21.3.8 (git-813ee839be)
	radv
	AMD RADV VANGOGH
Using hardware for point expansion and hardware for line expansion.
Vsync is OFF
(Cubeb) Using normal 2 speaker stereo output.
(Cubeb) Minimum latency: 25.00 ms (1200 audio frames)
(Cubeb) Minimum latency is above requested latency: 1200 vs 960, adjusting to compensate.
PAD: controller (Microsoft X-Box 360 pad 0) detected with rumble support, GUID:03000000de280000ff11000001000000
McdSlot 0 [File]: /home/deck/.var/app/net.pcsx2.PCSX2/config/PCSX2/memcards/Mcd001.ps2
McdSlot 1 [File]: /home/deck/.var/app/net.pcsx2.PCSX2/config/PCSX2/memcards/Mcd002.ps2
EE/iR5900-32 Recompiler Reset

**Comment by Godsbane** [comment]
You need to downgrade PCSX2.

You will need to have dev mode on, set a password for the root user, and then issue the flatpak update command to a specific commit.

sudo flatpak update --commit=84bdc9896bb9e5b9c47024d899fdec7bd1243d2724359b119f64970bbf96ee29 net.pcsx2.PCSX2

**Comment by Rup353** [comment]
thanks man

**Comment by filmcriticbeta** [comment]
The error has been already fixed by upstream ( https://github.com/PCSX2/pcsx2/issues/5904 ), however the flathub repo for this emulator ( https://github.com/flathub/net.pcsx2.PCSX2 ) only runs its CI pipeline on a weekly basis.  Assuming flathub keep to their schedule the above workaround should no longer be necessary after 24th April 2022.

**Comment by Astromanaught** [comment]
> You need to downgrade PCSX2.
> 
> You will need to have dev mode on(maybe? Was informed this may not be required. Still haven't tested.), set a password for the deck user, and then issue the flatpak update command to a specific commit.
> 
> Desktop mode:
> 
>     1. open konsole
> 
>     2. Set a password for the deck user (if you haven't already):
> 
> 
>     * type `passwd`
> 
>     * set a password
> 
> 
>     3. `sudo flatpak update --commit=84bdc9896bb9e5b9c47024d899fdec7bd1243d2724359b119f64970bbf96ee29 net.pcsx2.PCSX2 `

Can confirm, this worked. A++ thank you!

**Comment by Pentagrade** [comment]
I had this bug too but ran the newly compiled update this morning and games are running now!

**Comment by dragoonDorise** [comment]
Issue solved by itself then RPCS2 fixed their bug
