### ISSUE TITLE
Bug: PSP save files do not load in game mode on configured games

### ISSUE THREAD

**Issue by DanSM-5** [dragoonDorise/EmuDeck#350]
I found a bug trying to play some PSP games. The titles that were configured to launch from game mode do not load save files. However I can see the saves in PPSSPP and the games launched within PPSSPP load the save files correctly (both game and desktop mode).

## Steps to reproduce
- Go to desktop mode
- Set up PSP titles in Rom Manager and transfer saves to Emulation/saves/ppsspp/saves
- Go to game mode
- Launch a PSP game

## Expected
Game launches and you are able to load from the save files

## Actual
Game launches but save games are not loaded

**Comment by Godsbane** [comment]
Hiya friend, there are two PPSSPP versions available in the parsers list. One is for RetroArch, and one is for PPSSPP standalone. Please make sure you are using PPSSPP standalone if you wish to use that save directory.

**Comment by DanSM-5** [comment]
My bad, I didn't noticed the standalone parser in Rom Manage. Right, it is like you said, using the standalone parser works to get the saves working. Thanks!

**Comment by Godsbane** [comment]
No problem, glad it's sorted!
