### ISSUE TITLE
DLC + Updates Handling

### ISSUE THREAD

**Issue by exp111** [dragoonDorise/EmuDeck#351]
With the addition of ryujinx (which unlike yuzu, doesn't extract updates into the virtual nand, but only takes the nsp files) there should probably be a standard way to handle/store dlc and updates. 

Currently i have a _dlc_ and _updates_ folder inside _roms/switch_ but these gets detected by srm as their own games, so i have to change the parser to ignore subdirs. 

So either ignore those files if they are stored in _roms_ or make a seperate dir that contains the update files. 
This comes down to SRM detecting them as their own games, but I don't think they can do much there either. 

  
Similiar problem with installed updates in RPCS3 where they get detected through the 'installed pkg' parser (which is more difficult to handle cause idk if there is a way to distinguish updates from installed games).

**Comment by Godsbane** [comment]
don't put games and dlc in the roms folders? there's literally no need to do this.

**Comment by Godsbane** [comment]
So you are saying if i now move that update, it will no longer be installed for ryujinx?

**Comment by derrickmehaffy** [comment]
> 

If I might suggest, either there are separate folders for `updates` and `dlc` or we at least name the folder in camelCase? Eg. `updatesAndDLC`

**Comment by Godsbane** [comment]
fixed https://github.com/dragoonDorise/EmuDeck/commit/42da0f5b193c16bf4bbdefff7ef0d362f17736ea
