### ISSUE TITLE
Wrong behaviour of "Update Emudeck"

### ISSUE THREAD

**Issue by glaucon1984** [dragoonDorise/EmuDeck#357]
When running "Update Emudeck", the user might not want to proceed after the changelog and version number are shown (because it's the version currently installed).

After choosing "Custom" installation mode, the user is presented with a list of tasks in the following step, asking what the user wants to do.

Despite the user selecting the "Custom" install in the previous step, if you press "Cancel" at this step (first opportunity provided to "cancel") the install process will go ahead with all options selected.

Suggested changes:
- Offer to abort the install when the version number and changelog are shown
- When prompted for the list of tasks to perform, "Cancel" will stop the installation, or at least prompt the user about it.

**Comment by Godsbane** [comment]
I agree. This behavior is bad. Cancel should probably just exit the script so the user can do it again.

**Comment by Godsbane** [comment]
with the new UI built this should be fixed, as the installation does not kick off until the very end no matter what.
