### ISSUE TITLE
Uninstall doesn't uninstall emulators or SteamRomManager

### ISSUE THREAD

**Issue by Matthew-Burkard** [dragoonDorise/EmuDeck#362]
I ran the uninstall app but it did very little.

I left all of the emulators unchecked which the dialog said to do to uninstall everything but it left everything installed.

The only part that seemed to work is removing emudeck files.
```shell
rm -rf ~/.steam/steam/controller_base/templates/cemu_controller_config.vdf
rm -rf ~/.steam/steam/controller_base/templates/citra_controller_config.vdf
rm -rf ~/.steam/steam/controller_base/templates/pcsx2_controller_config.vdf
rm -rf ~/.steam/steam/controller_base/templates/duckstation_controller_config.vdf
rm -rf ~/emudeck &>> /dev/null	
rm -rf ~/Desktop/EmuDeckCHD.desktop &>> /dev/null
rm -rf ~/Desktop/EmuDeckUninstall.desktop &>> /dev/null
rm -rf ~/Desktop/EmuDeck.desktop &>> /dev/null
rm -rf ~/Desktop/EmuDeckSD.desktop &>> /dev/null
rm -rf ~/Desktop/EmuDeckBinUpdate.desktop &>> /dev/null
```

The expected behavior after uninstall is for the system to be as close as possible a state it was in before the install.

**Comment by perigoso** [comment]
came to open an issue about this, can reproduce

**Comment by KrisCris** [comment]
Can confirm

**Comment by IAmSHOCK** [comment]
Reading the uninstall script does look like you have to select which ones you want to unninstall.

**Comment by Matthew-Burkard** [comment]
I was referring to the following line:
`If you select none of them, everything will be deleted`
from
https://github.com/dragoonDorise/EmuDeck/blob/1fc711821e530876efa0ad46d35cb5e5d0c1a69f/uninstall.sh#L50

**Comment by dragoonDorise** [comment]
This was fixed in the release of EmuDeck 2
