### ISSUE TITLE
Suggestion: Adding GDLauncher

### ISSUE THREAD

**Issue by Gameplayhard** [dragoonDorise/EmuDeck#364]
GDLauncher is a simple, yet powerful Minecraft custom launcher with a strong focus on the user experience.

it also downloads correct Java versions.

**Comment by Titaniumtown** [comment]
what does that have to do with emulation?

**Comment by Gameplayhard** [comment]
> what does that have to do with emulation?

It would be easier if it was just added in so you don’t mass up steam rom Manager, not to mention there are a lot of extra steps for the Minecraft Java version. like the different  Java versions, this is also a mod manager and has it own dedicated controller mod.

 If emulation was easy Emudeck wouldn't exist in the first place.

**Comment by Titaniumtown** [comment]
this seems completely out of scope of the project

**Comment by Godsbane** [comment]
Maybe some sort of addon script, one day? Emudeck extras.
