### ISSUE TITLE
Request - Compress not just ISO/Bin files, but all roms (as 7zip supported format)

### ISSUE THREAD

**Issue by thefunkygibbon** [dragoonDorise/EmuDeck#367]
Maybe i'm missing something but when i run the script it only prompts me to compress my PSX folder.  despite having lots of uncompressed roms in other system folders. 

Given that 7zip files are supported in emulators and emudeck,  it would make sense for it to compress these too, right?

**Comment by Godsbane** [comment]
The script does CHD format and RVZ format for systems which support them.
