### ISSUE TITLE
Please add EmuDeck on Flathub.org

### ISSUE THREAD

**Issue by Chevek** [dragoonDorise/EmuDeck#368]
Hi,

Please package your software using the flatpak format (it seems possible to put an AppImage in a Flatpak) for inclusion into flathub.org

It will provide an easy way to find and install Emudeck on the Steam Deck using the desktop mode + Discover.
And I could include it in my own selection of gaming softwares for Linux : Gaming-Flatpak.

Regards

**Comment by Godsbane** [comment]
No, it won't work because of the way emudeck works. We have to touch and write to many flatpak config locations which are in flatpak sandboxes, and we would not be able to do so if we ran from a flatpak.

**Comment by Godsbane** [comment]
Closing because, although I like the sentiment, just won't work as currently designed.

**Comment by Godsbane** [comment]
It was originally the plan.

**Comment by Godsbane** [comment]
@dragoonDorise can you please update the site?
