### ISSUE TITLE
How can I activate Game Mode with retroarch?

### ISSUE THREAD

**Issue by jazir5** [dragoonDorise/EmuDeck#369]
Could you fix up the game mode driver activation in retroarch? Missing a lot of performance options due to the lack of game mode, and I've been having significant performance issues in bsnes this would likely resolve.

**Comment by Godsbane** [comment]
Don't know what this means. Can you provide more detail? Specific options or screenshots please.

**Comment by jazir5** [comment]
I'm getting a notification when I try to launch any feature that requires the game mode daemon that it isn't active, such as the power management feature. The message is "ensure  GameMode Daemon is installed or running"

**Comment by Godsbane** [comment]
Don't know. I think you should reach out to the developers of RetroArch.

**Comment by Godsbane** [comment]
I'm going to close this as I don't believe there's anything for us to configure here. If you find a specific setting or something you want to adjust let me know.
