### ISSUE TITLE
Add support for BizHawk in place of RetroArch

### ISSUE THREAD

**Issue by BlueMaxima** [dragoonDorise/EmuDeck#370]
Call me whatever you want, but I hate RA for many, many reasons, and I'd love the option to use BizHawk in its place. It supports many of the platforms RA does. There is a native Arch Linux package available.

https://github.com/TASEmulators/BizHawk
https://aur.archlinux.org/packages/bizhawk-monort

**Comment by Godsbane** [comment]
@dragoonDorise this may be a good idea for people who really hate RetroArch. Problem is I don't believe ES-DE supports it. Would need more investigation.

**Comment by leonstyhre** [comment]
Fascinating, I was not aware of this emulator! I'll definitely look into it but I can't say yet whether it makes sense to add it to ES-DE, it depends on its quality and how frontend-friendly it is.

But I have already added support for Mednafen and ares which covers a lot of systems. Mednafen also has the great Mednaffe frontend which you can use to configure the systems and ares has its own GUI. All this will be supported in the future 2.0.0 release.

**Comment by leonstyhre** [comment]
I've investigated BizHawk now and it's a really weird emulator to run on Linux. It's a Windows application using Mono and I couldn't even get it to run on my Ubuntu machine. I may add support for BizHawk on Windows in the future but I prefer not to add too many emulators that are not cross-platform unless there is a very good reason.

With that said there are a few systems which BizHawk would provide standalone emulator support for where it's missing today, for example vectrex, odyssey2, intellivision and sg-1000 but I think it makes more sense to find other emulators for those systems than attempting to get BizHawk to run on Linux.

So for now I'll put this on hold, and again these comments are only for ES-DE and not for EmuDeck.

**Comment by dragoonDorise** [comment]
@rawdatafeel take a look at this :)
