### ISSUE TITLE
Rom Manager never ends downloading all the images... 

### ISSUE THREAD

**Issue by felisucoibi** [dragoonDorise/EmuDeck#371]
Rom Manager never ends downloading all the images... when it starts in PREVIEW there ar 14.000 roms to check, when it reaches 11.000, the grid download stops. Never starts posters downloads.

There is any way to fix this or at least that it tries to download first posters?

**Comment by Godsbane** [comment]
Hi, I think you are reaching a limitation on open handles on the deck.

I would greatly reduce the number of games you are trying to import to steam. Please consider using EmulationStation-DE for your bulk rom sets.

 That said we do not make steam rom manager. You should open an issue on their GitHub for issues with the software

**Comment by Godsbane** [comment]
Closing. I hope you got it sorted. Let me know if you need more help.
