### ISSUE TITLE
[MAME] Default value of bgfx_path in mame.ini cannot reference bgfx folder

### ISSUE THREAD

**Issue by Grimlo9ic** [dragoonDorise/EmuDeck#374]
With its default setting for bgfx_path, the _mame.ini_ under the $HOME/.mame/ folder cannot reference the bgfx folder when the user tries to use shaders with MAME.

The default setting is as follows:

`bgfx_path            bgfx`

The working path is this:

`bgfx_path            /app/share/mame/bgfx`

("Working path" is provided that the MAME flatpak install for future releases will keep the location of the files under `var/lib/flatpak/app/org.mamedev.MAME/current/active/files/share/mame/`)

**Comment by Godsbane** [comment]
fixed by
also added the artpath config
