### ISSUE TITLE
[Feature Request]neogeo and neogeocd support

### ISSUE THREAD

**Issue by ritech** [dragoonDorise/EmuDeck#378]
NEED NEW EMULATORS

**Comment by Godsbane** [comment]
Hiya friend. Both FinalBurnNeo (in Retroarch) and Mame-Standalone should play NeoGeo and NeoGeo cd games.
Both require neogeo.zip (arcade bios files are weird). 

If you have the neogeo.zip in the same folder as your roms, you should be good to go.

**Comment by Godsbane** [comment]
Closing due to no response. Let me know if you continue to have trouble.
