### ISSUE TITLE
Replace appimage files only after new version download is complete

### ISSUE THREAD

**Issue by BLucky-gh** [dragoonDorise/EmuDeck#379]
I just had a short internet outage which stopped my download of srm, after which srm stopped working (internet is back now and I'm downloading it again), so I assume the EmuDeck scripts are replacing the old appimage while downloading. My suggestion is to download into a temporary file and only replace the old file once the new one is successfully downloaded

**Comment by Godsbane** [comment]
Good idea.

**Comment by Godsbane** [comment]
fixed by: bf70adc71ef8e88b76f688ef384e99c10bc1ea23
