### ISSUE TITLE
Whenever duplicate preexisting symlinks occur, symlinking in install.sh creates recursive copies in their target folders

### ISSUE THREAD

**Issue by hifihedgehog** [dragoonDorise/EmuDeck#38]
@dragoonDorise, while working on the Launchbox folders solution, I am noticing a bug with the current symlink creation scheme for EmuDeck. The problem is a symlink will be created recursively inside of the target folder if the symlink already exists. For example, if the megadrive symlink already exists, the command in the install script will create that symlink inside of the megadrive symlinked folder. The fix to this is creating a conditional if statement check to see if the symlink already exists.

That would mean changing this:
`cd $(echo $romsPath | tr -d '\r')
ln -s segacd megacd &>> ~/emudeck/emudeck.log
(...)`
To this:
``cd $(echo $romsPath | tr -d '\r')
if [ ! -d "megacd" ]; then
    ln -s "segacd" megacd
fi
(...)``

This impacts all symlinks in the bash script install.sh in the same way. You need this format of check to test for folder existence first or symlinking will recurse with subsequent runtimes. I have to delete a ton of nested symlinks because of this anomaly whenever rerunning the script.

**Comment by Godsbane** [comment]
this needs to be high priority on fixes. we also need to come up with a solution to clean up bad symlinks from previous runs without clobbering user data.

**Comment by dragoonDorise** [comment]
This has been fixed. it will be published on the next 0.15.5
