### ISSUE TITLE
Failing to install ES-DE

### ISSUE THREAD

**Issue by thesaltineking** [dragoonDorise/EmuDeck#380]
During EmuDeck install/update, Emulation Station fails to install.  No error alert pops up, but the terminal says:
`curl: (3) URL using bad/illegal formato r missing URL
chmod: cannot access '/run/meida/mmcblk0p1/Emulation/tools/EmulationStation-DE-x64_SteamDeck.AppImage': No such file or directory` before moving on with the rest of the installs/updates.

When trying to install via the EmuDeck Tool Updater, an error alert does pop up, stating
"There was a problem updating Emulation Station-DE"

**Comment by LONGACAT** [comment]
GitLab is currently under maintenance. Please monitor https://status.gitlab.com/ to see when it will be up. From ES-DE site:
> GitLab is down for scheduled maintenance on Saturday 2022-09-03 starting at 11:00 UTC to around 14:00 UTC. During this time period it will not be possible to download the ES-DE packages. Please try again after the maintenance work has been completed.

**Comment by thesaltineking** [comment]
Ah, thank you!!!

**Comment by Godsbane** [comment]
This should be all set now, as gitlsb is back up.
