### ISSUE TITLE
Add customization to the Amiga folders in retroarch 

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#381]
https://docs.libretro.com/library/atari800/#bios

**Comment by LONGACAT** [comment]
There are multiple Amiga folders and currently they only serve a visual purpose - the games are still being ran on Amiga 500, even when put in to the Amiga 1200 folder. It would be expected the games run on A1200 when put in the respective folders

**Comment by LONGACAT** [comment]
Oh and it might be good to automatically download the CAPSImg library (If allowed by the license), which is required for PUAE to run `.ipf`  (Interchangeable Preservation Format) images. The difference between ADF and IPF images is covered here: https://openretro.org/adf-and-ipf-variants

**Comment by Godsbane** [comment]
Thanks @LONGACAT

https://github.com/rsn8887/capsimg/releases
I looked the license, seems to allow redistribution. That said... they only have one release, which is a zip and contains the library for every OS, lol. I almost want to pull it out, and then host it it in the EmuDeck repo as a single file instead of downloading at install time (94k uncompressed, vs  1.5MB compressed with lots of other files).

**Comment by Godsbane** [comment]
The customization was done, but the ipf library was not. when that's done i'll mark this one complete.
