### ISSUE TITLE
PSP emulator in steam rom manager

### ISSUE THREAD

**Issue by Chnaps** [dragoonDorise/EmuDeck#385]
Hello,

I deeply apologize if this was already answered but I couldn't find what I was looking for.

I just installed emudeck and it's working great, however it forces me to run PSP game in PPSSPP standalone while I'd rather continue using retroarch. How can I configure this to go back to RA's PPSSPP core ?

Thanks in advance,

Chnaps

**Comment by Chnaps** [comment]
I apologize I just realized it's in the parser... I'm an idiot

**Comment by Godsbane** [comment]
No worries, glad you found it
