### ISSUE TITLE
MAME not found in Emulation Station

### ISSUE THREAD

**Issue by Thraka** [dragoonDorise/EmuDeck#390]
I'm not sure what to do. I've put a romset in the MAME4ALL roms folder, and I've installed Mame. The package manager says the Mame flatkpak is installed and it works, but while Emulation Station shows the games in its UI, when I run them it just goes back to the menu. Looking at the logs it says Mame isn't found. Why isn't it picking up the flatpak?

No idea how to get this fixed. :(

**Comment by Godsbane** [comment]
Arcade folder for Mame

**Comment by Thraka** [comment]
Ack, bad description, I must have been too sleepy 😁 

Emulationstation picks up the games, it shows them in game list and the scraper grabbed art, etc. But when it runs it says Mame emulator not found.

When I go to alternative emulators, arcade isn't listed as an option to select the emulator with either.

**Comment by Godsbane** [comment]
What version of EmulationStation-DE are you using? Support for the Mame flatpak was added with the most recent release.

Check your version. The copy Emudeck downloads and updates is in Emulation/tools.

**Comment by Thraka** [comment]
It says v1.2.6 which according to the https://www.es-de.org/ site, is the latest.

**Comment by Godsbane** [comment]
Hmm. I don't know. That's pretty strange. Can you attach a picture of what you see in the alternate emulators list In EmulationStation-DE?

**Comment by Godsbane** [comment]
You can start ES-DE with the --debug flag and check ~/.emulationstation/es_log.txt for information of what happens during game launch.

**Comment by Thraka** [comment]
OK I'll do that! Sorry for the delay, I was away.

**Comment by Godsbane** [comment]
any update on this? If mame is installed (which it should be if you have updated to the latest Emudeck) then it should work. If it is not installed, because you never updated it then you should do that :)

**Comment by Thraka** [comment]
Here's the log. Hopefully you can spot why it's doing this. Mame is installed through the app manager. I can (in desktop mode) see the icon and run it.

[es_log.txt](https://github.com/dragoonDorise/EmuDeck/files/9739736/es_log.txt)

**Comment by Godsbane** [comment]
what is the Alternate Emulator set to please? It should be set to Mame [Standalone] to use the installed one. The Placeholder message appears to be in place for mame-advmame and mame-mame4all.
```

 <system>
        <name>mame-advmame</name>
        <fullname>AdvanceMAME</fullname>
        <path>%ROMPATH%/mame-advmame</path>
        <extension>.chd .cue .CUE .CHD .cmd .CMD .fba .FBA .iso .ISO .7z .7Z .zip .ZIP</extension>
        <command>PLACEHOLDER %ROM%</command>
        <platform>arcade</platform>
        <theme>mame-advmame</theme>
    </system>
```

**Comment by Thraka** [comment]
I don't have mame listed in alternate emulators at all. it doesn't appear in the UI. Checking `.emulationstation/custom_systems/es_systems.xml` only lists a single entry for wii

**Comment by Godsbane** [comment]
Hi Thraka - i'm afraid i just do not know at this point.  You might be better off joining the EmulationStation-DE discord and speaking with LeonSE  (the dev of the application)

It's normal for this file to only contain Wii U. This is a custom system we added so we can use Wii U on linux.

**Comment by Thraka** [comment]
Thanks, will do, I'll follow up here with closing and a comment when I find more info

**Comment by Thraka** [comment]
They said that the roms can't be in `mame4all` folder, they have to be in the `arcade` folder. after doing that, it works.
