### ISSUE TITLE
Xenia not installed properly 

### ISSUE THREAD

**Issue by whise** [dragoonDorise/EmuDeck#391]
I found that xenia is installed but I can't call it unless I go to the launchers folder. A shortcut would be good. Furthermore, I can't use emulation station with it, it says the emulator is not is not installed.

**Comment by Godsbane** [comment]
xenia is not ready, it's only for testing, and does not actually work yet.

**Comment by whise** [comment]
Really? 

I've seen a lot of YouTubers run RDR on the deck flawlessly using the xenia experimental build.

**Comment by Godsbane** [comment]
Yes, it works on windows.
