### ISSUE TITLE
PCSX2 steam input layout isn't appearing 

### ISSUE THREAD

**Issue by dordododo** [dragoonDorise/EmuDeck#392]
The steam input layout for PCSX2 doesn't appear in the menu to select a layout.

**Comment by Godsbane** [comment]
A steam input layout is no longer required since migration to PCSX2-QT.

**Comment by Godsbane** [comment]
select + r3. This reminds me, we need to update the documentation.

**Comment by dordododo** [comment]
> select + r3. This reminds me, we need to update the documentation.

Thanks for the help.

**Comment by jcotton42** [comment]
Have the docs been updated yet? The README on main, beta, and dev still says you need Steam Input for PCSX2.

**Comment by Godsbane** [comment]
No, it hasn't been done yet. I'll add it to my list of things to do as we finalize beta -->main
