### ISSUE TITLE
How do you add widescreen patches for PCSX2?

### ISSUE THREAD

**Issue by dordododo** [dragoonDorise/EmuDeck#394]

**Comment by Godsbane** [comment]
PCSX2 already has built in widescreen patches. You simply turn on the checkbox. (or use the expert mode option in EmuDeck )

**Comment by dordododo** [comment]
> PCSX2 already has built in widescreen patches. You simply turn on the checkbox. (or use the expert mode option in EmuDeck )

you can't add ones that aren't built in?

**Comment by Godsbane** [comment]
there's a cheats_ws folder in ~/.config/PCSX2/ that you can possibly use. I don't know how it conflicts with the ones which are built into the emulator.

**Comment by dordododo** [comment]
> there's a cheats_ws folder in ~/.config/PCSX2/ that you can possibly use. I don't know how it conflicts with the ones which are built into the emulator.

ok thanks, you've been a huge help, also this is off topic but I'd rather ask here instead of opening up a new thread, do you know the hotkeys for rpsc3?

**Comment by Godsbane** [comment]
There are not any prebuilt rpcs3 hotkeys, as there are not a lot of quick actions one can take with this emulator. What are you looking to do?

**Comment by dordododo** [comment]
> There are not any prebuilt rpcs3 hotkeys, as there are not a lot of quick actions one can take with this emulator. What are you looking to do?

Save states and graphics settings.

**Comment by Godsbane** [comment]
save states don't work that way in rpcs3. it's bound to Ctrl + S by the emulator. Note that if you use this, it will quit the game then and there, and save to a large file on your disc (i've seen the state be nearly 1gb). Then when you launch it from this state (which as far as i know requires you to launch it from the menu in RPCS3 and specifically choose the state file) it gets deleted.
What do you mean by graphics settings? Typically, you can just boot the emulator by itself. You make changes in a per game configuration, then you launch the emulator to test. When happy, your shortcut uses this per game config, and you are good to go.

**Comment by dordododo** [comment]
> save states don't work that way in rpcs3. it's bound to Ctrl + S by the emulator. Note that if you use this, it will quit the game then and there, and save to a large file on your disc (i've seen the state be nearly 1gb). Then when you launch it from this state (which as far as i know requires you to launch it from the menu in RPCS3 and specifically choose the state file) it gets deleted.
> What do you mean by graphics settings? Typically, you can just boot the emulator by itself. You make changes in a per game configuration, then you launch the emulator to test. When happy, your shortcut uses this per game config, and you are good to go.

Ok that makes sense, thanks for all your help.

**Comment by Godsbane** [comment]
No worries, going to close this :)
