### ISSUE TITLE
Ryunjinx path es_find_rules.xml

### ISSUE THREAD

**Issue by saildot4k** [dragoonDorise/EmuDeck#396]
es_find_rules.xml seems to be out of date:
es_find_rules.xml  is not setup properly to find the Ryujinx executable:

```
<rule type="staticpath">
            <entry>/var/lib/flatpak/exports/bin/org.ryujinx.Ryujinx</entry>
            <entry>~/.local/share/flatpak/exports/bin/org.ryujinx.Ryujinx</entry>
        </rule>
```

should be:
```
<rule type="staticpath">
            <entry>/var/lib/flatpak/exports/bin/org.ryujinx.Ryujinx</entry>
            <entry>~/.local/share/flatpak/exports/bin/org.ryujinx.Ryujinx</entry>
            <entry>~/Applications/publish/Ryujinx</entry>
        </rule>
```

Or just update from here:
https://gitlab.com/es-de/emulationstation-de/-/blob/master/resources/systems/unix/es_find_rules.xml

Also, I recommend if as emudeck installs Emulation Station DE then ANY alternative (or not) emulators that are listed should also be installed such as ReDream and Flycast (standalone) otherwise when users try to set things up, they will be confused thinking it is broken (which technically it is) OR if preffered to have emudeck delete these emulator app listings in ESDE

**Comment by Godsbane** [comment]
we don't use RyujinX flatpak, we use the binary (and the find rules in the appimage work fine there). We will not delete the other options, as this is not a closed platform. If someone wants to add something we don't already include, that's ok. We also evolve and add more over time. 

es_find_rules.xml is not something we customize at this time. The file in the repo is unused.

**Comment by saildot4k** [comment]
^Correct I am not using the flatpack. I wiped/removed the individual installs to test out emudeck and the file es_find_rules.xml that is on this repo was the one installed on my deck, hence the problem running ryujinx from ESDE. Re running the emudeck installer nor emudeck updater replaced it with the official ESDE file even when forcing an ESDE update.

**Comment by Godsbane** [comment]
Right we do not customize nor use this file, so if you put it in place, it's untouched by anything we do. We do touch custom systems, but use xmlstarlet to modify it.

**Comment by saildot4k** [comment]
Ok so still a bug that using either script did not re-install the correct es_find_rules.xml from ESDE.

Also as stated, any systems that you keep listed in ESDE Alternative Emulators that your script does not install should be removed from es_find_rules.xml, otherwise users go to try another emulator out and it does not work (and in this case your script installs Ryujinx but it would not launch within ESDE)

**Comment by Godsbane** [comment]
You are misunderstanding how it works, I think. Esde is an AppImage. The find rules are built in. If you put the file in place, then it overrides the one in the AppImage. We would not touch this, as it's not a file we configure. I don't know why you pulled this random file and used it. I will delete it form the repository for the next release.
