### ISSUE TITLE
PCSX2 Config

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#40]
Reports that when selecting internal, it doesn't update the path in the config from the external location. test in dev, see if it fixes it with the other sed fixes.

**Comment by Godsbane** [comment]
https://github.com/dragoonDorise/EmuDeck/blob/dc33a0ce4c37767e2a8401b9057fd5583f6558b9/configs/net.pcsx2.PCSX2/config/PCSX2/inis/PCSX2_ui.ini#L43

I think because there is no trailing slash, the sed command doesn't replace.

**Comment by dragoonDorise** [comment]
Thanks! solved on 0.15.5
