### ISSUE TITLE
Problems with touchpads

### ISSUE THREAD

**Issue by ZzackKbin** [dragoonDorise/EmuDeck#403]
Hello
If I set touchpads "like mouse" in Dosbox Pure and PUAE cursor has invisible walls but when touchpad work like analog cursor moving ok.

**Comment by Godsbane** [comment]
(because this is something that to my knowledge we can't fix, I'm closing this)

**Comment by ZzackKbin** [comment]
thx for answer
I rapport this on steamdeck forum:
https://steamcommunity.com/app/1675200/discussions/1/3370405364916173619/
