### ISSUE TITLE
Dolphin not reading per-game .ini files

### ISSUE THREAD

**Issue by xfechx** [dragoonDorise/EmuDeck#405]
I am modifying a .ini file under:

/home/deck/.var/app/org.DolphinEmu.dolphin-emu/config/dolphin-emu/GameSettings/

Without success..
What is the directory where dolphin in EmuDeck reading the .ini files per game?

**Comment by xfechx** [comment]
The path where you can place game .ini files (with cheats) for dolphin under EmuDeck is:

home/deck/.var/app/org.DolphinEmu.dolphin-emu/data/dolphin-emu/GameSettings/

**Comment by Godsbane** [comment]
Correct! (and - if it's easier, you can do it in Dolphin itself by right clicking a game and going to properties, and modifying it in that little gamesettings window)
