### ISSUE TITLE
Cheats - make it more easy and intutive to use and update them

### ISSUE THREAD

**Issue by Registered55** [dragoonDorise/EmuDeck#406]
I noticed that some of the emulators the cheats are not easy to (turn on or update), for example PPSSPP has cheats off by default...and then where is the location folder where to put them.

the other one is FBNeo, it comes with just the default ini files, but again the folder location cannot be modified (permissions issue).

would be great if the scrips can make the adjustments (turn on cheats if user wishes) and then make the locations easy to find where to put these cheats (files, or database dats) like how the roms folder is so easy for the user to use.

"even now i still haven't figured out where to put the updated retroarch FBNeo cheat files...the location seems really buried in the installation folders"

thanks.

p.s. i'm really new to this stuff, please forgive my ignorance if i'm doing things wrong.

**Comment by ITJamie** [comment]
+1. cheats dont seem to "remember" for any of the retroarch emulators, when i load the game i have to scroll the entire list of cheats to enable the cheats for that specific game (for example gba pokemon yellow).
