### ISSUE TITLE
Unable to update game on cemu

### ISSUE THREAD

**Issue by CodeOneYT** [dragoonDorise/EmuDeck#408]
Trying to install any DLC or Update in Cemu over 1.5GB leads to it telling me that there's only 1558MB available. Any ideas how to fix?

**Comment by Godsbane** [comment]
Use the Emudeck Tool Updater on your desktop to switch to version 1.27 (experimental). You can use the same tool again later to downgrade if you need to use 1.26 (latest stable)

**Comment by Godsbane** [comment]
This is known, so closing it.
