### ISSUE TITLE
Steam Rom Manager - Add "m3u" to the "Sega Saturn - Retroarch - Yabause" and "Sega Dreamcast - Retroarch - Flycast" Parsers

### ISSUE THREAD

**Issue by rawdatafeel** [dragoonDorise/EmuDeck#409]
Could the "m3u" file type be added to the following parsers in Steam Rom Manager?:

1. "Sega Saturn - Retroarch - Yabause"
2. "Sega Dreamcast - Retroarch - Flycast" 

Thank you!

**Comment by WingofaGriffin** [comment]
I made a PR on the Saturn area here: https://github.com/dragoonDorise/EmuDeck/pull/414
it's relatively easy to do the same for Dreamcast, I can add it now.
