### ISSUE TITLE
Retroarch config

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#41]
Reports that retroarch config doesn't get updated during the script when internal is selected. Test in dev!

**Comment by Godsbane** [comment]
https://github.com/dragoonDorise/EmuDeck/blob/dc33a0ce4c37767e2a8401b9057fd5583f6558b9/configs/org.libretro.RetroArch/config/retroarch/retroarch.cfg#L3097

not certain why this one isn't getting updated for userse that pic internal.

**Comment by dragoonDorise** [comment]
Thanks! Fixed on 0.15.5
