### ISSUE TITLE
EmuDeck Tool Updater doesn't propose CEMU 2.0 version

### ISSUE THREAD

**Issue by theonlydude1** [dragoonDorise/EmuDeck#410]
Hello,
I'm not able to select CEMU 2.0 from EmuDeck Tool Updater. The Choose your CEMU version menu only allows me the following:
https://cemu.info/releases/cemu_1.26.2.zip
https://cemu.info/releases/cemu_1.27.1.zip
https://github.com/cemu-project/Cemu/releases

I've tried several time to choose the last link with no effect, when I've a look on the terminal output there is no data transfert and the script is not able to find the cemu.zip file in /run/media/mmcblk0p1/Emulation/roms/wiiu folder
I've tried also several time to update EmuDeck but no change.
Thanks for your help

**Comment by Godsbane** [comment]
This is corrected in beta. It's because the page that lists these was
changed.

**Comment by theonlydude1** [comment]
Thanks for your feedback ! Is there a simple way to install the beta version instead of the standard one ?

**Comment by Godsbane** [comment]
the cemu exe can be swapped out manually until the beta release, which should be soon enough.
