### ISSUE TITLE
Compression tool w/ Gamecube .iso error while loading shared libraries: libavformat.so.59

### ISSUE THREAD

**Issue by spkane** [dragoonDorise/EmuDeck#411]
When using the compression script, and selecting `gamecube` it generates an error about loading a shared library when it hits the `.iso` (non-nkit) files. It might also happen with `.nkit.iso` but I do not have any at the moment.

`dolphin-tool: error while loading shared libraries: libavformat.so.59`

**Comment by Godsbane** [comment]
Yes this is because something in the Dolphin flatpak was updated and it's no longer compatible. It's been corrected in beta to use the one that comes with Primehack, as that one does not have the same problem at this time.
