### ISSUE TITLE
Change Saturn Default Core from Yabuase to Kronos

### ISSUE THREAD

**Issue by WingofaGriffin** [dragoonDorise/EmuDeck#415]
Yabuase is Abandonware: https://github.com/Yabause/yabause https://docs.libretro.com/library/yabause/
Kronos is a an updated fork of Yabuase https://github.com/FCare/Kronos https://docs.libretro.com/library/kronos/
https://emulation.gametechwiki.com/index.php/Sega_Saturn_emulators

Note that it does require some BIOS files in different folder structures than Yabuase due to Retroarch supporting both.

kronos/saturn_bios.bin | Saturn BIOS - Required | af5828fdff51384f99b3c4926be27762
-- | -- | --
kronos/stvbios.zip | ST-V BIOS - Optional |  
mpr-18811-mx.ic1 | The King of Fighters '95 ROM Cartridge - Required for this game | 255113ba943c92a54facd25a10fd780c
mpr-19367-mx.ic1 | Ultraman: Hikari no Kyojin Densetsu ROM Cartridge - Required for this game | 1cd19988d1d72a3e7caa0b73234c96b4

The other option is Beetle Saturn/Mednafen https://docs.libretro.com/library/beetle_saturn/ which also hasn't been updated since 2019 https://github.com/hiddenasbestos/beetle-saturn-libretro

**Comment by Godsbane** [comment]
Interestingly just went through an exercise with the beta testers on discord where they tested beetle / yabause / yabasanshiro.
Did not test kronos, but supposedly performance wise beetle was the clear winner.

Have you tested Kronos's performance vs beetle?

**Comment by WingofaGriffin** [comment]
I have not. Might make more sense to ask the beta testers to try Kronos with the same suite they already tested

**Comment by Godsbane** [comment]
based on testing done, it seems Beetle is the current smoothest experience overall.

**Comment by WingofaGriffin** [comment]
Closing as we migrated to beetle in beta
