### ISSUE TITLE
Change GB/GBC core default from Gambatte to SameBoy

### ISSUE THREAD

**Issue by WingofaGriffin** [dragoonDorise/EmuDeck#416]
While Gambatte works perfectly fine and performance is not an issue on the steamdeck at all, SameBoy has ursurped Gambatte in accuracy with Gambatte not being updated since 2019

https://github.com/LIJI32/SameBoy
https://sourceforge.net/projects/gambatte/
https://emulation.gametechwiki.com/index.php/Game_Boy/Game_Boy_Color_emulators

Gearboy is the other up and coming emulator

**Comment by Godsbane** [comment]
We have Sameboy setup as well (in retroarch) but not a parser for it.

**Comment by WingofaGriffin** [comment]
Nice. This suggestion is to focus on defaults for new users who are less comfortable (or even aware) of swapping cores around. So, this suggestion is to evaluate deprecating the steam rom manager parser for Gambatte in favor of SameBoy, and changing the Emulation Station core default as well.

**Comment by Godsbane** [comment]
I don't think this will be changed to the default. Gambatte seems fine, and sameboy is a valid alternate atm.

going to mark as fixed in dev, and close when next release comes out.

**Comment by dragoonDorise** [comment]
This should be fixed in 2.0.8. Please reopen this if you still find issues!
