### ISSUE TITLE
Installer downloads and installs too much, uninstall leaves stuff

### ISSUE THREAD

**Issue by subworx** [dragoonDorise/EmuDeck#418]
Just did the first set up on a Steam Deck.
Selected to **only** install Yuzu, Ryujinx, Citra, Cemu.
It still downloaded and installed **every** emulator as well as SRM and EmuStation.
What DID work was that no RetroAchievements popup for sign-in information showed.

During uninstallation, I get offered to remove all of that, which it did.
I chose not to keep anything at all, which means removing all applications, their data, saves, everything except ROMs.
Remnants after uninstall: ~/.local/share/yuzu, ~/.config/yuzu, ~/.cache/yuzu.
As I didn't launch any of the emulators, I cannot tell if more directories remain after uninstallation.

**Comment by Godsbane** [comment]
@dragoonDorise Uninstall stuff.

**Comment by subworx** [comment]
Uninstallation is just an afterthought.
The main point is I select four emulators and it installs everything.

**Comment by Godsbane** [comment]
Could you include the Emudeck log?
~/emudeck/emudeck.log

**Comment by subworx** [comment]
OK, just cleaned up everything and then did a fresh install.
- Expert Mode.
- SD Card.
- No Power Tools, Gyro, Steam Rom Manager, Emulation Station, Emu config reset, Bezels, RetroArch Autosave, SNES Aspect Ratio, Widescreen, Retroachievements, EmuStation Theme.
- DO select the emulators to install.
- Deselected all emulators except Cemu and Ryujinx this time.
- Was not asked for a sudo password (so "no power tools" and "no gyro" work fine).
- Close the "Yuzu is not configured" popup that shows on first run.
- Select Exit as I don't care about the SRM.

[emudeck.log](https://github.com/dragoonDorise/EmuDeck/files/9690079/emudeck.log)

**Comment by Godsbane** [comment]
MAME, Cemu, Ryujinx installed in this log. SRM always installs as it's a key part of Emudeck. That's the only stuff i see for installation.

MAME always installing is definitely a bug, but it should be solved for the next release already.
Settings:
```
**doInstallSRM=true**
doInstallESDE=false
doInstallRA=false
doInstallDolphin=false
doInstallPCSX2=false
doInstallRPCS3=false
doInstallYuzu=false
doInstallCitra=false
doInstallDuck=false
**doInstallCemu=true**
doInstallXenia=false
**doInstallRyujinx=true**
doInstallPrimeHacks=false
doInstallPPSSPP=false
doInstallXemu=false
doInstallPCSX2QT=false
doInstallMAME=true
#doInstallMelon=false
doInstallCHD=false
doInstallPowertools=false
doInstallGyro=false
```

this seems to have followed these well.

the next bit is configuration. the choice to customize configuration was not checked, so the defaults were used:
```
doSetupRA=true
doSetupDolphin=true
doSetupPCSX2=true
doSetupRPCS3=true
doSetupYuzu=true
doSetupCitra=true
doSetupDuck=true
doSetupCemu=true
doSetupXenia=false
doSetupRyujinx=true
doSetupMame=true
doSetupPrimeHacks=true
doSetupPPSSPP=true
doSetupXemu=true
doSetupESDE=true
doSetupSRM=false
doSetupPCSX2QT=true
```
So this customization also happened in the execution run, even though the emulators were not chosen for installation. (this is a valid choice combination, as sometimes a user just wants to run the settings portion of expert mode)

You mention having EmulationStation-DE but at no point in this script did it download. Do you simply still have it? It's an appimage in Emulation/tools.

Thanks for testing.

**Comment by dragoonDorise** [comment]
Closing this issue as is related to the old EmuDeck v1
