### ISSUE TITLE
Dolphin Config

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#42]
Paths in the dolphin config are weird.

https://github.com/dragoonDorise/EmuDeck/blob/dc33a0ce4c37767e2a8401b9057fd5583f6558b9/configs/org.DolphinEmu.dolphin-emu/config/dolphin-emu/Dolphin.ini#L35

I tested manually changing the file to the correct paths and it was fine, but if i updated them in the front end they look like that.

**Comment by filmcriticbeta** [comment]
If I’m understanding flatpaks documentation correctly /run/user/$uid is part of their sandboxing mechanism. So I’m guessing the dolphin frontend is erroneously setting the path to flatpaks document export location.  For normal use that’s fine, but it may break things if the config is shared with others.  The $uid should be fine as $uid=1000 maps onto the “deck” account, but the “77fd26b2” identifier may not be idempotent between devices.

**Comment by Godsbane** [comment]
when i use the normal userspace path, the dolphin flatpak can read it fine. I'll probably just do a PR that uses that, and then the user is on their own if they add more or change things.

**Comment by dragoonDorise** [comment]
This wasn't needed but I fixed it anyway, now the roms path for Dolphin are the right ones. 0.15.5
