### ISSUE TITLE
Consider adding Mednaffe as a standalone alternative 

### ISSUE THREAD

**Issue by rawdatafeel** [dragoonDorise/EmuDeck#420]
Mednaffe is a front-end GUI for Mednafen, available on Discover (https://flathub.org/apps/details/com.github.AmatCoder.mednaffe). 

Mednafen's list of supported emulators can be found here: https://mednafen.github.io/. 

I've only personally tested Mednafen's Saturn emulator. We currently have Beetle Saturn, a Retroarch core, which isn't always kept up to date with the latest version of Mednafen. Grandia runs much better on Mednafen than it does on Beetle Saturn. 

The downside to Mednafen is that it does not support chd files. For those who have used EmuDeck's tool compressor and deleted their original bin/cue files, Mednafen may be a headache to use in tandem with EmuDeck's current emulators. 

Another issue to consider is how to best integrate Mednaffe/Mednafen into EmuDeck's current configuration. With the large amount of emulators it supports, is it best and simplest to keep it as an alternative in EmulationStation-DE and not figure out how to best integrate it into Steam Rom Manager? 

One benefit of Mednaffe/Mednafen is that it allows you to do custom controls per system, so one way to handle Steam Rom Manager integration is to add a Mednaffe/Mednafen parser on its own and run all games through that parser instead of dividing it by system. 

Comparison:
Beetle - https://streamable.com/8pbe36
Mednaffe - https://streamable.com/d8mcy0

**Comment by WingofaGriffin** [comment]
Is there a current issue for standalone to support chd files? Adding an emulator that doesn't support the compression tool's format seems like a bad move.
