### ISSUE TITLE
Working with virtual keyboard with SRM even if steam is not running (Desktop mode) 

### ISSUE THREAD

**Issue by urbanracer34** [dragoonDorise/EmuDeck#421]
I have been able to reproduce this every time. 

I go into desktop mode, fire up firefox, keyboard works.

Switch over to SRM and it is nowhere to be found. 

How can we navigate SRM without losing the virtual keyboard?

**Comment by Godsbane** [comment]
Mostly you do not need a keyboard in there. Everything is configured already. However if you want to add a new parser or do an exception, you can reopen steam. Just don't forget to close it before you hit save app list or your category info can't save correctly.
