### ISSUE TITLE
Empty categories in Steam after reboot

### ISSUE THREAD

**Issue by nils23** [dragoonDorise/EmuDeck#427]
See title, this made me mad this weekend. ;-)

I logged out of all other devices (suggestion from a reddit thread), I deactivated the family library in Steam (just in case), I rescanned my 30k+ rom files, all went well initially, but soon after all categories are empty again. 

Also there are e.g. two PSP folders, and when I try to delete one it gets emptied but stays on screen as an empty category that can't be deleted. No deal breaker, but maybe there's a relation?

Thanks for your awesome work!

n.

**Comment by Godsbane** [comment]
30k rom files? I think you have too many and steam is just unable to handle this. Please consider not scanning in bulk sets of roms, and use EmulationStation-DE for these instead.

You may want to try this:

1. Close Steam on desktop mode.
2. Delete your userdata config folder to make sure it's completely fresh: /home/deck/.steam/steam/userdata/NUMERICSTEAMID/config/
3.  Relaunch steam to get the files regenerated.
4.  close steam again and add games to steam one more time. (probably keep them under a few thousand in your library. )
5. If you want to test, keep adding games until it breaks again. Maybe you can find the reason or limit


That all said, we do not make steam rom manager. That is from here: 
https://github.com/SteamGridDB/steam-rom-manager

I'd suggest opening an issue with whatever info you can there on what triggers this. As we can't do anything about it given we do not make the program, I will be closing this eventually. If you want to bounce ideas or questions off me, please feel free to let me know what you try.

**Comment by nils23** [comment]
30k: well, what can I say: I'm a collector! :-)

Thanks for your extensive reply, will try all of that!

Have a good one!
