### ISSUE TITLE
3ds and n3ds folders

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#43]
Symlink one to the other so it works for both retroarch and emulationstation-de.

**Comment by Witherking25** [comment]
It’s supposed to do that but since the folder already exists it puts the symlink inside the folder instead of replacing it :(

**Comment by Witherking25** [comment]
And if we remove the folder it might delete people’s roms.

**Comment by Witherking25** [comment]
We could move the contents to the other folder first?

**Comment by Witherking25** [comment]
This should be fixed now

**Comment by dragoonDorise** [comment]
Fixed on   0.15.5
