### ISSUE TITLE
If we have Primehack... can we get Project Plus? Other forks?

### ISSUE THREAD

**Issue by jacfalcon0** [dragoonDorise/EmuDeck#431]
Since a fork of Dolphin, Primehack, was included, is there any chance that other forks of emulators might be included? Such as [Project Plus](https://projectplusgame.com/) (Super Smash Bros Brawl online)?

**Comment by WingofaGriffin** [comment]
The core installer difference here is installing a forked Ishiiruka Dolphin app image used to improve performance and have consistent netplay versions across users.

That said, there is consideration to take in installing Ishiiruka Dolphin as a performance booster emulator if we have data showing it improve performance for games other than P+/Melee.

The original Ishiiruka is abandoned: https://github.com/Tinob/Ishiiruka
The Ishiiruka fork used by Faster P+: https://github.com/jlambert360/Ishiiruka
The Ishiiruka fork used by Slippi Melee: https://github.com/project-slippi/Ishiiruka

Given that Ishiiruka is supposed to focus on performance over accuracy and stability, it isn't unreasonable to consider Ishiiruka would have benefits on Deck. https://emulation.gametechwiki.com/index.php/Ishiiruka-Dolphin. The question in my eyes is do these forks offer the same improvements to other games, or are they specific to the games they were forked for. @jacfalcon0 are you willing to do some testing and reporting with findings?

**Comment by jacfalcon0** [comment]
> @jacfalcon0 are you willing to do some testing and reporting with findings?

I wish I had the time at the moment, but I might circle back later.

**Comment by Godsbane** [comment]
I'm willing to look at this just as is from a download / setup standpoint, after we get the next release out. It would be a very much optional setup,  and may not be able to be integrated outside of making launcher for steam rom manager to scrape. Will need to research first.

**Comment by tassyguy** [comment]
Hey I was just looking into this feature as well, if it's ok I would like to take a look at implementing this feature as an optional step for EmuDeck? I have an idea of what may need to be done to make it work

**Comment by Godsbane** [comment]
Feel free. Fork the beta repository :)

**Comment by rubengc** [comment]
Would be awesome to have Project Plus and Slippi 😍

As suggestion, Emudeck could have 2 emulators screens, one for official emulators and another one with the custom ones

I installed PrimeHack without meet what is for and when I searched about it just decided to give it try since I love that idea

**Comment by WingofaGriffin** [comment]
This is something that is a bit more finicky than a simple Emulator setup. See the gist I made (also linked in the wiki) for instructions: https://gist.github.com/WingofaGriffin/3202698447ca2452a9431137cfc18d21
