### ISSUE TITLE
L and ZL don't seem to work in Cemu

### ISSUE THREAD

**Issue by undeadindustries** [dragoonDorise/EmuDeck#435]
L and ZL seem to work fine in non-Wii U emulators.
R and ZR work fine.

To test: 
Select Twilight Princess HD.
Switch Controller to the Cemu profile.
Load Twilight Princess HD. Play until you get the fishing pole (takes like 4-5 minutes).
You need to press L as instructed to assign the fishing pole.
Nothing happens.

Steps I've tried:
This same issue happens on Batocera on Steam Deck.

I've assigned the special steam input to the profile intended for Cemu. Tried different controller profiles.

I've remapped controller buttons.

Cemu 1.26 and 1.27 have the same result.

I tried to get to Cemu settings but the top menu bar is missing so I can't change anything.

I've posted this in the discord, but no one responds and it gets buried. Using Github issues is a last resort for this. Sorry :-)

**Comment by Godsbane** [comment]
I believe this is just a tphd issue. Switch to opengl.

You can launch the emulator from desktop mode as documented in the wiki.

**Comment by undeadindustries** [comment]
Thanks so much for the quick response!

I feel like an idiot asking this. Where do I switch to OpenGL?
Thanks!

**Comment by USL5264** [comment]
I'm getting no audio in v2.0.7. One minute it worked and now it's gone. Don't know what's happened.

**Comment by undeadindustries** [comment]
@USL5264 that's a different issue. Please don't hijack issues.

@Godsbane thanks so much for the response. I tested in OpenGL. That didn't solve it. And it was like 5 frames/sec.

**Comment by undeadindustries** [comment]
Quick update: 
I did put this same bug in CEMU to see if they'd look at it.
They said it was EmuDeck's problem. (It happens in Batocera too)
They also eluded to me just pressing the wrong button...
But they also said that the version EmuDeck/Batcera uses is too old for them to support.

_I'm still trying to find literally anyone to just test this on their device._

**Comment by undeadindustries** [comment]
I'm absolutely mortified. There is no bug here at all.
Because it uses gamepad mode, it's a combo of buttons I need to hit. closing this ticket.
