### ISSUE TITLE
Emudeck doesn't load the functions fast enough and freezes on moving to the storage location selection

### ISSUE THREAD

**Issue by Tom-Neverwinter** [dragoonDorise/EmuDeck#437]
first install/update of emudeck 2 run freezes if microsd card does not populate and user selects other install directory.

close and reopens solves [results may vary?]

**Comment by NightHammer1000** [comment]
Also have this.

Happens when SD Card is not detected in /run/media/primary.

Had my HoloISO SD Card in an that was mounted to somewhere else.

**Comment by Godsbane** [comment]
this needs to be addressed. @dragoonDorise

**Comment by Godsbane** [comment]
2.03 looks to have fixed this.
