### ISSUE TITLE
Yuzu migration message pops up behind emudeck and the user has no idea.

### ISSUE THREAD

**Issue by Tom-Neverwinter** [dragoonDorise/EmuDeck#438]
This is the second freeze issue I found when performing an install/update emu deck freezes at adding duck station steam input profile

**Comment by NightHammer1000** [comment]
Also freezes for me without any special settings. Just selecting Easy Install and Internal.
Nothing happens afterwards. Just stuck at the "We are Completing your Installation" screen.

**Comment by Godsbane** [comment]
this is a message popping behind the Emudeck config, waiting for input.
