### ISSUE TITLE
A few issues after updating to Emudeck 2.0

### ISSUE THREAD

**Issue by esotericode** [dragoonDorise/EmuDeck#440]
Attempting to update emulators from the "Tools and Stuff" menu doesn't seem to work. A menu pops up that lets you select the emulators you want updated, but then nothing happens after that. Same result for both "Update Flatpak" and "Update AppImages" buttons. 

Running PCSX2 games results in them running as fast as possible with the toggle for FF doing nothing. 

I updated from a totally vanilla Emudeck install on a totally vanilla Steam Deck. I never messed with any configs or anything myself.

**Comment by Godsbane** [comment]
try disabling vsync, and then trying your games again - then renenabling it.

**Comment by esotericode** [comment]
> try disabling vsync, and then trying your games again - then renenabling it.

It's interesting, when I disabled vsync the games seemed to run at an appropriate speed again. However, then after reenabling it the games ran at max speed again. 

What's also interesting is that running the games by specifically opening pcsx2-qt and then running the game from there seems to work fine. The issue seems to happen when I run games directly from those entries that are created by SRM. 

So perhaps it's caused by the launch options that SRM / Emudeck makes for the PS2 games. I noticed there's a line vblack_mode=0 and I changed the 0 to a 1 and the game ran at normal speed again.

**Comment by Godsbane** [comment]
Yes it's supposed to remove the frame limiter from steam for use with vsync being on.

**Comment by Godsbane** [comment]
I have hotfixed the vblank_mode=0 out

**Comment by esotericode** [comment]
I had previously said that updating from the "Tools and Stuff" menu doesn't work. I was actually wrong about that or it did start to work, however it tried to do it in the background and there's not much of an indication something is happening for the user to see. Since it does work it's not really an issue anymore.

Thank you also for hotfixing the PCSX2 config issue, things work great now.
