### ISSUE TITLE
EmuDeck 2.0 Update/Install Freeze

### ISSUE THREAD

**Issue by masterkrieger** [dragoonDorise/EmuDeck#443]
Ran EmuDeck 2.0 update via "Update Emu Deck" and gets stuck at "Installing ScummVm ..." step. 

Initially thought it froze after going into sleep and not progressing after waking, but its stuck at the same place after I uninstalled Emu Deck and reinstalled

Selected:
- Easy Install
- Internal Storage

**Comment by Godsbane** [comment]
people have been reporting a pop up behind the window, waiting for input. Check please.

**Comment by masterkrieger** [comment]
There was no pop up behind the window for me, but the installer completed after restarting.
