### ISSUE TITLE
[Amiga] PUAE folder is misspelled under home/deck/.var/app/org.libretro.RetroArch/config/retroarch/config/PAUE/

### ISSUE THREAD

**Issue by Grimlo9ic** [dragoonDorise/EmuDeck#447]
Just saw this today as I updated to 2.0 and was trying to play Gods (which is a sweet-ass game, but I digress).

PUAE is misspelled as "PAUE".

**Comment by Godsbane** [comment]
Thank you, I have hotfixed this.
