### ISSUE TITLE
Setup using GNOME?

### ISSUE THREAD

**Issue by CorruptComputer** [dragoonDorise/EmuDeck#453]
How would I set this up using GNOME? GNOME does not have any desktop icons, so even if I put the `EmuDeck.desktop` in my `~/Desktop` folder that doesn't get me any closer to being able to use this. Selecting 'Run as a Program' in the file manager doesn't do anything but open the file in my default text editor.

Is there a proper installer or Flatpak somewhere I can use instead of this default method?

I would like to use this to add ROMs to my Steam library on my desktop as well, and set up the `~/Emulation` folder to automatically sync between my Deck and desktop so saves, ROMs, and whatnot are automatically transferred between the two. The sync part I already have a plan for using pCloud folder syncing, but I just have no idea how I'm supposed to set this up on my desktop PC.

**Comment by Godsbane** [comment]
i use manjaro with gnome for some messing around with this.

I'd say easiest to launch the appimage directly at this time, then you don't have to deal with .desktop files.
https://github.com/EmuDeck/emudeck-electron/releases

**Comment by CorruptComputer** [comment]
Ah, thanks I didn't realize there was an AppImage available for this. I think that should work for me, but it would be nice if that option was given in the installation documentation as well.

I am using Fedora 36.

**Comment by Godsbane** [comment]
That's fair - it is targeted at the deck mostly, so please let me know what works and what doesn't on fedora.

Would like to add support for more than arch based distros via prerequisite scripts depending on which it's distribution being run on.

The script itself assumes that you have all the utilities used in it, as it's targeting a very specific system.

**Comment by CorruptComputer** [comment]
I ran the AppImage, and it seems to work fine. Having the `~/Emulation` folder synced between my Deck and desktop before running the AppImage seemed to be no issue as well. 

The ROMs and BIOS files were fine, however none of the saves seem to have synced. I assume this means that they are not actually being saved in the `~/Emulation/saves` folder there, checked both GameCube and GameBoy for this.

In addition to the saves, it seems that the Emulators do not recognize my Xbox controller so I am not able to play them yet. Will do some troubleshooting with this and let you know if I am able to figure anything out about that.

Also a small thing, but it would be nice if the AppImage added a launcher shortcut to GNOME when running it. Similar to how it adds a desktop entry on the Deck. It added the launcher items for the emulators, just not EmuDeck itself.
![image](https://user-images.githubusercontent.com/5573038/196732479-ad54d204-7a8b-4278-95c0-5901798b155b.png)

**Comment by CorruptComputer** [comment]
Figured out the controller issue, seems you need to uncheck this box in the Steam controller settings for it to be usable by the emulators: 
![image](https://user-images.githubusercontent.com/5573038/196736681-585da24a-effb-4c0f-a34b-95973a02888f.png)

After doing that I was able to use it in GameBoy games, however GameCube games still do not seem to recognize it.

**Comment by CorruptComputer** [comment]
One other small issue noticed, Prime Hack seems to be labeled as 'Dolphin Emulator' in the app launcher so if you search for Dolphin to try to get to the controller settings for GameCube games it can be a bit annoying.
![image](https://user-images.githubusercontent.com/5573038/196760100-789b9e5e-4198-438f-bf73-e0fd3753b448.png)

**Comment by CorruptComputer** [comment]
After setting up the controller configuration manually in Dolphin it seems to work fine, not sure if there would be a way to automatically add a profile for that when setting up EmuDeck. Since as you said, its mainly focused on the Steam Deck so it would likely be unused by many users of the app.

**Comment by Godsbane** [comment]
> 

This same thing happens in gnome for me, but on kde, it has the correct icon at least.
