### ISSUE TITLE
Lynx roms and emudeck 2.0

### ISSUE THREAD

**Issue by ViktorHavok** [dragoonDorise/EmuDeck#455]
Since updating to EmuDeck 2.0 my Atari Lynx roms no longer run. I just get a grey screen when i try to start a game. Im running EmuDeck with Emulation Station on the steamOS. I have followed update instructions step by step. Tried running update both ways, quick update and detailed. I even completely removed the program and did a fresh install, still no luck. After the install I did notice two folders for lynx roms in the roms folder, one is "atarilynx" and the other just "lynx".

**Comment by Godsbane** [comment]
@dragoonDorise can you by chance look at this? I have no lynx games.

**Comment by dragoonDorise** [comment]
Hi @ViktorHavok sorry for the delay, you should use the atarilynx folder, the lynx folder is no longer used and was removed on a previous update :)

I just tested a Lynx game and it launches just fine on ESDE using both the Beetle Lynx and Handy cores.

Did you manage to get your games working?
