### ISSUE TITLE
RetroArch shaders missing

### ISSUE THREAD

**Issue by knaackville** [dragoonDorise/EmuDeck#456]
After updating to EmuDeck 2.0, the shaders for RetroArch seem to be missing.  The CRT filters can be set in Emudeck installer (and will work), but the other ones previously included are not in the shader folder in retroarch. Any way to bring them back?  Thank you!

**Comment by knaackville** [comment]
Never mind…. Was able to download inside RetroArch. Must have forgotten I had done that previously

**Comment by Godsbane** [comment]
This is because the location was changes so you could download updated
shaders. The original location shaders do also work, but can't be updated.
