### ISSUE TITLE
Suggestion: Option for Hotkeys like FF toggle, quick save/load etc to be touchscreen buttons?

### ISSUE THREAD

**Issue by Clydefrosch22** [dragoonDorise/EmuDeck#464]
I dont know how feasible this is on steamdeck and these versions of the emulators,
but it's something I loved on duckstation on android, there's always empty space to the side of the emulated games and while bezels are nice, that space can be so much more functional with some semi-transparent hotkeys for all the quick access functions you need in a modern emulator, mainly open emulation menu, toggle fast forward, slowdown or rewind, an safe and load.

**Comment by Godsbane** [comment]
We have something like this for Duckstation, Citra, and ppsspp with the steam input profiles, using the left trackpad.

I don't think we can do touch screen ones though - just trackpad.

**Comment by Godsbane** [comment]
i am going to close this out - as we can't do touchscreen buttons - but are actively working towards some nice touch / trackpad hotkey layouts. Please look forward to it.
