### ISSUE TITLE
BUG: Custom lets you choose nonvalid locations for install with new UI.

### ISSUE THREAD

**Issue by Ardakilic** [dragoonDorise/EmuDeck#466]
Hello,

I tried to install Emudeck to my SD Card's exfat partition yesterday. It was exfat, because I wanted to access it both from Windows and Linux natively.

However, after setup, I realized that configuration paths are not mapped correctly.

After I check the logs, I realized links were not created properly.

This is because [exfat does not support linking](https://learn.microsoft.com/en-us/windows/win32/fileio/filesystem-functionality-comparison#functionality).

Then I uninstalled EmuDeck, and I re-formatted the partition to ext-4 (I will try UDF in the future on my next format), and reinstalled, then the paths and links worked nicely.

So maybe it'd be a good option to check the custom folder's file structure whether it supports linking, or add a notification somewhere on installation page if the choice is custom, we need to make sure linking is supported on that path.

Apologies if this has been mentioned somewhere already, I could not find it, also a non-programmer gamer friend of mine encountered the same issue on his Steam Deck, so I wanted to raise the issue here.

Thanks in advance!

**Comment by Godsbane** [comment]
This is true - and it's already checked when you choose SDCard. With the new UI this appears to have been missed as a check after the custom selection.

**Comment by Godsbane** [comment]
Fixed in 2.04, but needs final tests

**Comment by Godsbane** [comment]
I'm going to add one more final test in the script itself too. It existed in the old zenity ui for the custom selection, but because we are depending on the appimage to write a settings file, i'd like to add a secondary check to the script execution too, just in case something slips through.

**Comment by Godsbane** [comment]
This was solved a while back.
