### ISSUE TITLE
Could you offer an option to make this work with Retroarch installed via Steam?

### ISSUE THREAD

**Issue by punkonjunk** [dragoonDorise/EmuDeck#467]
Rather than the non-steam install. I'd love to be able to easily sync save data, savestates between steamdeck and my laptop and desktop - this should all be relatively doable, but would be really helpful if emudeck offered this option.

**Comment by Godsbane** [comment]
Duplicate: #31 

please look at the above for the difficulties we had when trying to make this work. It's open for now, but unlikely to be automated ever.
