### ISSUE TITLE
Reports that a and b are swapped for Dolphin GC controllers p2,3,4

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#470]

**Comment by Godsbane** [comment]
This wasn't caught because when you cycle the controller profiles it works fine.
the 4 gamecube controllers are weird, and need to be rebound to one of the profiles via load, and save.

**Comment by dragoonDorise** [comment]
@Godsbane can you check commit [ff88b0d56716653e3e5807f2f3aa0ab20da55560?](https://github.com/dragoonDorise/EmuDeck/commit/ff88b0d56716653e3e5807f2f3aa0ab20da55560) ? I noticed some discrepancies on the 2, 3 and 4 controllers while comparing it to controller #1
