### ISSUE TITLE
Bezels are disabled in Emudeck but NES still has them

### ISSUE THREAD

**Issue by TheMeanCanEHdian** [dragoonDorise/EmuDeck#474]
I have bezels set to off, but NES still displays them. Not seeing bezels on any other console.

**Comment by Godsbane** [comment]
Can you please zip up your config folder and attach it for me to look at?

**Comment by TheMeanCanEHdian** [comment]
Sorry but where is the config folder located?

**Comment by Godsbane** [comment]
`/home/deck/.var/app/org.libretro.RetroArch/config/retroarch/config/Mesen` this whole folder
`/home/deck/.var/app/org.libretro.RetroArch/config/retroarch/retroarch.cfg` this file

If you could zip this all up and send it along with your emudeck log, that would be great.

**Comment by TheMeanCanEHdian** [comment]
Here you are: [configs.zip](https://github.com/dragoonDorise/EmuDeck/files/9852884/configs.zip)

**Comment by Godsbane** [comment]
Thanks. It's definitely on in the nes.cfg. 

Will look into it.

**Comment by Godsbane** [comment]
This should now be fixed. there was an issue where setting a specific aspect ratio would turn the bezel back on.

**Comment by TheMeanCanEHdian** [comment]
I did a custom update, and it does seem to be resolved. Thanks!
