### ISSUE TITLE
Add extract-xiso tool support

### ISSUE THREAD

**Issue by f-andrew-beal** [dragoonDorise/EmuDeck#478]
It would be useful if EmuDeck would provide the option to install the extract-xiso tool for use with the Xemu emulator. 

A windows version is here: https://github.com/XboxDev/extract-xiso
The arch package is here: https://aur.archlinux.org/packages/extract-xiso-git

Not sure which you would use. 

I have been successful with the windows version using a custom launcher script.

**Comment by f-andrew-beal** [comment]
#!/usr/bin/bash
# extract-xiso.sh

# Proton Launcher Script
PROTONLAUNCH="/run/media/mmcblk0p1/Emulation/tools/proton-launch.sh"

# Cemu.exe location
EXISO="/run/media/mmcblk0p1/Emulation/roms/xbox/extract-xiso.exe"

# Call the Proton launcher script and give the arguments
"${PROTONLAUNCH}" -p '7.0' -- "${EXISO}" "${@}"

**Comment by f-andrew-beal** [comment]
Not sure why the editor is ignoring my code indicators. The previous comment is the launcher script I have been using for reference.

**Comment by Godsbane** [comment]
I edited it to include a codeblock to fix the formatting.

It's not a bad idea. I haven't tested the tool.

**Comment by Godsbane** [comment]
Going to close in favor of #485
