### ISSUE TITLE
AT-SPI: Could not obtain desktop path or name

### ISSUE THREAD

**Issue by steve1316** [dragoonDorise/EmuDeck#48]
Currently encountering this issue after deleting the Emulation folder on my BTRFS formatted SD Card and running the .desktop file again to rerun the Emudeck installation script.

After running the .desktop file, it asks if I want to install my roms on either the Internal Storage or SD Card. Selecting SD Card will lead to an error:

```
EmuDeck ERROR

An error has occurred.
```

and the Konsole will close with the log below:

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@.......@@@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@...........@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@..............@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@(..........@@@@@@
@@@@@@@@@@@@@&########@@@@@.........@@@@
@@@@@@@@@@###############@@@@........@@@
@@@@@@@@@##################@@@........@@
@@@@@@@@####################@@@.......@@
@@@@@@@@####################@@@.......@@
@@@@@@@@###################@@@........@@
@@@@@@@@@#################@@@&.......@@@
@@@@@@@@@@@@############@@@@........@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@*.........@@@@@
@@@@@@@@@@@@@@@@@@&..............@@@@@@@
@@@@@@@@@@@@@@@@@@.............@@@@@@@@@
@@@@@@@@@@@@@@@@@@.........@@@@@@@@@@@@@
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
EmuDeck 0.15.4.1


 (zenity:20494): WARNING : 19:09:11.392: AT-SPI: Could not obtain desktop path or name


 (zenity:20494): WARNING : 19:09:11.407: AT-SPI: Could not obtain desktop path or name


 (zenity:20494): WARNING : 19:09:11.407: atk-bridge: get_device_events_reply: unknown signature

 (zenity:20494): WARNING : 19:09:11.407: atk-bridge: get_device_events_reply: unknown signature

 (zenity:20494): WARNING : 19:09:11.407: atk-bridge: GetRegisteredEvents returned message with unknown signature

 (zenity:20494): WARNING : 19:09:11.421: AT-SPI: Could not obtain desktop path or name


 (zenity:20494): WARNING : 19:09:11.422: atk-bridge: get_device_events_reply: unknown signature

 (zenity:20494): WARNING : 19:09:11.422: atk-bridge: get_device_events_reply: unknown signature

 (zenity:20494): WARNING : 19:09:11.422: atk-bridge: GetRegisteredEvents returned message with unknown signature
```

**Comment by steve1316** [comment]
If anyone encounters this issue, just select install to Internal Storage. After installation is complete, copy the Emulation folder from /deck/ to your SD card. If you want the ROM manager to work, you need to manually go into each profile and point the rom location to the SD Card, not the Internal Storage anymore. Luckily I only needed to adjust a few profiles as I do not use the majority of the profiles.

Although installing Emudeck directly to SD Card does not work for me currently, at least the above is a temporary solution.

**Comment by dragoonDorise** [comment]
Hi, the issue is because the SD Card need to be formatted as ext4. Fat32 and EXFAT formats both have issues right now with SteamOS write permissions. Haven't tested BTRFS.. Can you tell me what is in your /run/media folder? please post all the subfolders names in there. Thanks!

**Comment by steve1316** [comment]
Yeah I figured. Emudeck installed onto the BTRFS SD Card the very first time perfectly fine with no errors/issues. ROM manager also worked perfectly as well and was able to match my roms with their appropriate artworks for Steam OS.

Its just that I deleted the Emulation folder from the SD Card and reran the .desktop file thinking it can reinstall back to the SD Card but thats when I encountered the issue above.

SD Card is named "Steam Deck". Path to the SD Card from Desktop Mode is "/run/media/Steam_Deck/"

File structure of the BTRFS SD Card is:
```
/Emulation/
     the regular /bios/, /roms/ and /tools/ from a typical installation.
/steamapps/
     subfolders are the games that Steam OS installs.
```

**Comment by dragoonDorise** [comment]
So you first installed EmuDeck on the BTRFS SDCard and created everything perfectly, but then you deleted the Emulation Folder and then it failed? as of right now EmuDeck is hardcoded to skip installation if the card is not named "mmcblk0p1", that's the name the Deck gives to every SD Card on EXT4, you shouldsee an error telling you to format your SD Card

**Comment by steve1316** [comment]
Ah, I think you might be right. If the EmuDeck is hardcoded to look for "mmcblk0p1", then that might be the reason why the second installation failed as I changed the name of the SD Card to "Steam Deck" after the first installation and before the second installation. I was led to believe that #30 fixes the hardcoded lookup for "mmcblk0p1".

> you shouldsee an error telling you to format your SD Card

I see no error telling me to format my SD Card. It works fine otherwise.

**Comment by Godsbane** [comment]
Not all of the changes in that PR were incorperated. @dragoonDorise only pulled in the sed changes and a couple variable changes. I have opened a new PR to once again allow any name of the sd card. It does however test the sd card is ext4. I have another PR in the works to allow btrfs as well.

**Comment by Godsbane** [comment]
@steve1316 - the name issue is resolved. It will still not let you use BTRFS at this point, just wanted to give you an update.

**Comment by steve1316** [comment]
Since the original issue has been resolved, I will close this issue.
