### ISSUE TITLE
Add Big Picture argument to Duckstation and PCSX2 sh scripts

### ISSUE THREAD

**Issue by rawdatafeel** [dragoonDorise/EmuDeck#486]
I brought this up in Discord, but figured a Github issue might be easier to track. 

`-bigpicture` mode allows users to use Duckstation and PCSX2 in game mode with a controller, and allows for easier configuration.

Duckstation and PCSX2 can also be used as front-ends for their respective libraries with this option, providing users with additional ways to manage their games in game mode. 

Photos:

![image](https://user-images.githubusercontent.com/108900299/198331866-fd3e8025-e7a6-4cfb-8cf9-dc7bfbcf183c.png)

![image](https://user-images.githubusercontent.com/108900299/198331906-7ab09464-838d-4ced-97ea-2963ab1c7f36.png)

![image](https://user-images.githubusercontent.com/108900299/198331925-487544a5-17d9-4765-a74a-5a8f9a74d884.png)

**Comment by dragoonDorise** [comment]
This should be fixed in 2.0.8. Please reopen this if you still find issues!
