### ISSUE TITLE
[BUG] Cloud save service are no longer backing up new saves

### ISSUE THREAD

**Issue by ghost** [dragoonDorise/EmuDeck#488]
It seems I've found yet another issue with Cloud Saves despite the great progress we made in #475 

**Issue:** The automatic cloud save backup service is no longer backing up save files, states or test files. The lack successful sync I had was three days ago and I can see that any files after this are just not being reflected in my OneDrive. I have tried ```systemctl --user list-timers``` in Konsole to see if the service was running and it confirmed that the service IS in fact running every 15 minutes. Yet, for some strange reason, saves aren't being updated or reflected in my cloud provider.

Not sure what could be causing this as it was working fine until a few days ago. I've not made any changes in Emudeck, my OneDrive or anything related.

**Comment by Godsbane** [comment]
anything in the rclone log in Emulation/tools/rclone

**Comment by Godsbane** [comment]
the log is empty?!

**Comment by Godsbane** [comment]
what happens if you run the job script in that same folder?

**Comment by Godsbane** [comment]
i think i've tracked this down -  rclone is not requesting a refresh token with the Files.ReadWrite scope. This LOOKS like an rclone bug, but i can't rule out a config issue quite yet.

**Comment by Godsbane** [comment]
Nope - it's a me bug.

Reopen Emudeck  - -> Reinstall savebackup --> login --> check the terminal in the background

When you look at the log in the background you should see offline_access listed in the scopes and `"refresh_token":"LOTS OF STUFF` in the token

**Comment by Godsbane** [comment]
Yep thanks for helping solidify this :)
