### ISSUE TITLE
[Suggestion] Bios scanning

### ISSUE THREAD

**Issue by wolfgangvc** [dragoonDorise/EmuDeck#49]
Whilst including bios files for various systems may not be possible. And automatically downloading them from an external source, will be unreliable and also questionable.

EmuDeck could scan for files in a user provided directory (maybe default to the user directory) and automatically copy them to the needed directory and rename them as needed.

This would make things easier for less technically savvy users. (A similar feature using rom fingerprinting systems may also be possible)

Scanning should use known hashes to match correct bioses.

Suggested implementation would go something like.

 - **Prompt:** `Do you already have any system bioses you wish to use? (y/N) ...`
 - If yes. **Prompt:** `Where are they located? (~) ...`
 - Scan the directory hashing files to find bioses.
 - Copy/rename bioses that match appropriate hashes to their appropriate folder wherever user specified (sdcard or not)

Known hashes can be found on various wiki's like https://emulation.gametechwiki.com/index.php/File_Hashes (some like for yuzu or so may need sourcing elsewhere)

**Comment by dragoonDorise** [comment]
Hi!

We're already asking the user to copy their bios on Emulation/bios, no need to copy the bios on another folder to then copy then to the right folder.

The hash check if a really great idea. I've already implemented it for PS1 and PS2 bios on the next 0.15.5 update!

Thank you for the suggestion!!
