### ISSUE TITLE
gamecube/wii game file formate is not changed

### ISSUE THREAD

**Issue by array-in-a-matrix** [dragoonDorise/EmuDeck#492]
Gamecube/wii games in `.nkit.iso` get compressed but their format is not changed. The EmuDeck compression tool page says all files will be convert. Anyone who didn't read the output of `chddeck.sh` might not realize the files have been compressed as they still have the same file format.

**Comment by Godsbane** [comment]
We don't advertise conversion of nkit. You need to convert those back to iso on your own, or just don't use (nkit) files to begin with. once converted, it should compress fine by my understanding.

**Comment by array-in-a-matrix** [comment]
Sounds good, thank you.
