### ISSUE TITLE
[Discussion/Suggestion] Recommended emulators, without the need for Retroarch/Libretro.

### ISSUE THREAD

**Issue by John-Enigma** [dragoonDorise/EmuDeck#501]
I've searched for emulators that don't have to rely at all on Retroarch/Libretro (don't ask why, please), at least for the most popular ones, which are Nintendo, Sega, PlayStation, and Xbox consoles. 

Let me know what you guys think. If it's a bad idea, then you can close it.

I Nintendo

	A. Consoles
	
		1. NES 
		
			a. Mesen-X 
		
				Ubuntu PPA: https://github.com/NovaSquirrel/Mesen-X/releases
			
				Arch AUR available: https://aur.archlinux.org/packages/mesen-x-git
	
		2. Super NES (SNES) 
		
			a. Bsnes-HD 
			
				Binary: https://github.com/DerKoun/bsnes-hd/releases
			
			b. Ares 
			
				Flatpak: https://flathub.org/apps/details/dev.ares.ares
				
				Arch AUR: https://aur.archlinux.org/packages/ares-emu
			
			c. Snes9X 
			
				Flatpak: https://flathub.org/apps/details/com.snes9x.Snes9x
				
				Arch AUR: https://aur.archlinux.org/packages/snes9x-git
				
				GTK and X11 binaries: https://github.com/snes9xgit/snes9x#nightly-builds
	
		3. Nintendo 64 
		
			a. RMG 
			
				Flatpak: https://flathub.org/apps/details/com.github.Rosalie241.RMG
				
				Portable binaries available: https://github.com/Rosalie241/RMG/releases
			
			b. simple64 (WIP) 
			
				Flatpak: https://flathub.org/apps/details/io.github.simple64.simple64
				
				Arch AUR: https://aur.archlinux.org/packages/simple64-git
			
			c. Ares (WIP) 
			
				Flatpak: https://flathub.org/apps/details/dev.ares.ares
				
				Arch AUR: https://aur.archlinux.org/packages/ares-emu
	
		4. Nintendo GameCube 
		
			a. Dolphin (Packages available here: https://pkgs.org/download/dolphin-emu)
		
		5. Nintendo Wii 
		
			a. Dolphin (Packages available here: https://pkgs.org/download/dolphin-emu)
		
		6. Nintendo Wii U 
		
			a. CEMU (WIP) 
			
				Ubuntu PPA: https://github.com/cemu-project/Cemu/releases/tag/v2.0
		
		7. Nintendo Switch 
		
			a. Yuzu 
			
				Flatpak: https://flathub.org/apps/details/org.yuzu_emu.yuzu
				
				AppImage: https://yuzu-emu.org/downloads/
			
			b. Ryujinx 
			
				Flatpak: https://flathub.org/apps/details/org.ryujinx.Ryujinx
				
				Arch AUR: https://aur.archlinux.org/packages/ryujinx-git
				
				Binary: https://ryujinx.org/download
		
	B. Handhelds
	
		1. GameBoy(Color) 
		
			a. SameBoy 
			
				Flatpak: https://flathub.org/apps/details/io.github.sameboy.SameBoy
				
				Snap: https://snapcraft.io/sameboy
			
			c. BGB (Run via Wine)
		
		2. Game Boy Advance 
		
			a. mGBA 
			
				Flathub: https://flathub.org/apps/details/io.mgba.mGBA
				
				Arch AUR: https://aur.archlinux.org/packages/mgba-qt-git
			
			b. NanoBoyAdvance 
			
				Arch AUR: https://aur.archlinux.org/packages/nanoboyadvance-git
				
				Ubuntu PPA/Debian binary: https://github.com/nba-emu/NanoBoyAdvance/releases
			
			c. SkyEmu
			
				Binary: https://skyemu.app/
		
		3. Nintendo DS(i) 
		
			a. melonDS 
			
				Flathub: https://flathub.org/apps/details/net.kuribo64.melonDS
				
				Binary: https://melonds.kuribo64.net/downloads.php
		
		4. Nintendo 3DS
		
			a. Citra 
			
				Binary: https://citra-emu.org/download/#
		
II Sega

	A. Consoles
	
		1. SG-1000 
		
			a. MasterGear
			
				Ubuntu PPA: https://fms.komkon.org/MG/#Downloads
			
			b. Ares 
			
				Flatpak: https://flathub.org/apps/details/dev.ares.ares
				
				Arch AUR: https://aur.archlinux.org/packages/ares-emu
		
		2. Sega Master System 
		
			a. MasterGear 
			
				Ubuntu PPA: https://fms.komkon.org/MG/#Downloads
			
			b. Ares 
			
				Flatpak: https://flathub.org/apps/details/dev.ares.ares
				
				Arch AUR: https://aur.archlinux.org/packages/ares-emu
		
		3. Sega Genesis/Mega Drive 
		
			a. BlastEm (no CD, 32X, or Pico support though) 
			
				Arch AUR: https://aur.archlinux.org/packages?O=0&SeB=nd&K=blastem&outdated=&SB=p&SO=d&PP=50&submit=Go
				
				Ubuntu PPA: https://launchpad.net/~hda-me/+archive/ubuntu/blastem
				
				Normal binaries: https://www.retrodev.com/blastem/
			
			b. Ares 
			
				Flatpak: https://flathub.org/apps/details/dev.ares.ares
				
				Arch AUR: https://aur.archlinux.org/packages/ares-emu
		
		4. Sega Saturn 
		
			a. Yaba Sanshiro 2 
			
				Snap: https://snapcraft.io/yabasanshiro
			
			b. Kronos 
			
				Arch AUR: https://aur.archlinux.org/packages/kronos
				
				Ubuntu PPA: https://github.com/FCare/Kronos/releases
		
		5. Sega Dreamcast 
		
			a. Flycast 
			
				Flatpak: https://flathub.org/apps/details/org.flycast.Flycast
			
			b. Flycast Dojo (for netplay purposes) 
			
				Binary: https://github.com/blueminder/flycast-dojo/releases
		
	B. Handhelds
	
		1. Game Gear 
		
			a. MasterGear 
			
				Ubuntu PPA: https://fms.komkon.org/MG/#Downloads
			
			b. Ares 
			
				Flatpak: https://flathub.org/apps/details/dev.ares.ares
				
				Arch AUR: https://aur.archlinux.org/packages/ares-emu
		
III Sony

	A. Consoles
	
		1. PlayStation 
		
			a. DuckStation 
			
				Flathub: https://flathub.org/apps/details/org.duckstation.DuckStation
				
				AppImage: https://www.appimagehub.com/p/1460142
				
				Arch AUR: https://aur.archlinux.org/packages/duckstation-git
		
		2. PlayStation 2 
		
			a. PCSX2 
			
				Flatpak: https://flathub.org/apps/details/net.pcsx2.PCSX2
				
				Ubuntu PPA: https://launchpad.net/~pcsx2-team/+archive/ubuntu/pcsx2-daily
				
				Arch AUR: https://aur.archlinux.org/packages/pcsx2-git
				
				Binaries: https://pcsx2.net/downloads/
		
		3. PlayStation 3 
		
			a. RPCS3 
			
				Flatpak: https://flathub.org/apps/details/net.rpcs3.RPCS3 
		
	B. Handhelds
	
		1. PlayStation Portable 
		
			a. PPSSPP 
			
				Flatpak: https://flathub.org/apps/details/org.ppsspp.PPSSPP
		
		2. PlayStation Vita 
		
			a. Vita3k (WIP) 
			
				Arch AUR: https://aur.archlinux.org/packages/vita3k-git
				
				Ubuntu PPA: https://github.com/Vita3K/Vita3K/releases
		
IV Microsoft

	A. Consoles
	
		1. Xbox (Original) 
		
			a. Xemu 
			
				Flatpak: https://flathub.org/apps/details/app.xemu.xemu
				
				Arch AUR: https://aur.archlinux.org/packages/xemu
		
		2. Xbox 360 - 
		
			a. Xenia (Via Wine/Proton GE/Lutris, at least until they start implementing a Vulkan-based GPU emulation implementation (https://github.com/xenia-project/xenia/issues/2028), with some parity with DX12)

**Comment by Godsbane** [comment]
We already include a huge majority of these. Why don't you pare down the list to ones which are 

a) official release (as in by the emu team themselves), or available on flathub at minimum.
b) not already included
C) appimage, Flatpak, binary. ( No builds from other distros)

**Comment by John-Enigma** [comment]
I'll try.

**Comment by John-Enigma** [comment]
@Godsbane Yeah, I can't think of anything else. 

I only made this list based on popular emulators, and the fact that most of them weren't exclusively Retroarch-only. 

Like you said, there's probably a list of better emulators out there, like Ares or Mednafen (with Mednaffe). 

That being said, as unfortunate as it may sound, not all of these emulators have their own respective Flatpak (or Appimage, or Snap). And even if they did, they would be third-party, and not officially by the authors.

I'm gonna close this now.

**Comment by Godsbane** [comment]
I think ares and mednaffe have merit to add
