### ISSUE TITLE
EmuDeck Cemu super smash Bros not working

### ISSUE THREAD

**Issue by MarkerJames** [dragoonDorise/EmuDeck#502]
Cemu super smash Bros crashing when I click start in the start menu? Is there any solution? SOMEONE PLEASE HELP 😔

**Comment by Godsbane** [comment]
Sorry I don't think this is an emudeck issue. More likely a cemu in proton general or a game file issue.

I am going to close this.

**Comment by Godsbane** [comment]
one thing to try, as a follow up, use the Emudeck tool updater and update to the 2.0 experimental release of cemu. You can swap back and forth with that as needed. See if the more recent releases of cemu help.
