### ISSUE TITLE
(Appimage, Ubuntu) Custom directory chooser does not work

### ISSUE THREAD

**Issue by shoesio** [dragoonDorise/EmuDeck#504]
When pressing the choose custom directory icon at the start of the install, I just get a dialog saying "Non writable directory selected, please choose another".
I'm running the appimage installer under Ubuntu

**Comment by Godsbane** [comment]
Do you have findmnt?

**Comment by shoesio** [comment]
Sure do

**Comment by Godsbane** [comment]
Sounds strange. i used it on manjaro with issues.

Any way you can record a quick clip of exactly what happens?

Perhaps no zenity?

**Comment by shoesio** [comment]
Sure will get something over to you tonight

It’s the latest Ubuntu with Xorg btw.

**Comment by shoesio** [comment]
Computer: Apple Inc. iMac19,1 (2020 iMac 24")
24gb ram
Processor: Intel® Core™ i5-8500 × 6
GPU: AMD Radeon™ RX 470 Graphics
System: Ubuntu 22.10
Windowing: x11

**Comment by shoesio** [comment]
Here's the screencast: https://youtu.be/hXU2mx_HxNg

**Comment by Godsbane** [comment]
so - looking into this - the /bin/sh that ships with ubuntu doesn't seem to interpret `source` as a command. Which is how we load our functions.

**Comment by shoesio** [comment]
Cool hope the feedback helped :)

**Comment by elfosardo** [comment]
If I can help here and give an explanation, since I use extensively both Fedora and Ubuntu for work, historically `/bin/sh` is not a binary, but a link to the default linux shell.
While in Fedora (and Manjaro BTW) the /bin/sh binary is a link to bash, in ubuntu (especially the latest versions) it's a link to dash, that does not support the `source` command as it's not bash compatible.
My suggestion is to directly call `/bin/bash` (or equivalent) instead.

**Comment by elfosardo** [comment]
this https://github.com/dragoonDorise/EmuDeck/pull/512 can probably help

**Comment by Godsbane** [comment]
Thanks @elfosardo - this is really great info. Appreciate it.
We'll need to look at doing this in the AppImage as well when it calls /bin/sh. change to /bin/bash @dragoonDorise

**Comment by Godsbane** [comment]
@dragoonDorise mentioned he isn't calling /bin/sh, but instead is using a native feature in electron to run commands. Perhaps that needs to call bash explicitly to solve this.

**Comment by dragoonDorise** [comment]
@elfosardo fixed in our dev environment, it will be ready for our next beta release :)

**Comment by dragoonDorise** [comment]
@shoesio can you try this beta and report if your issue is fixed? Thanks!

https://github.com/EmuDeck/emudeck-electron-beta/releases/download/v2.0.28/EmuDeck-2.0.28.AppImage
