### ISSUE TITLE
Replace touch menu icons for emulators with custom icons

### ISSUE THREAD

**Issue by Moskeeto93** [dragoonDorise/EmuDeck#507]
I made several icons specifically for emulation. I wasn't happy with the default icons provided by Steam. These icons must be placed in .steam/steam/tenfoot/resource/images/library/controller/binding_icons

I have uploaded the icons here: https://drive.google.com/drive/u/1/folders/1ES1cwVIREYEG1pp2X8n7fhetHGxLF7jX

**Comment by Godsbane** [comment]
Can we put them in a subfolder there to keep them organized together?

**Comment by Moskeeto93** [comment]
> Can we put them in a subfolder there to keep them organized together?

I haven't tried so I'm not sure. However, once they are added there they can be found under the "user" category in Steam Input when selecting an icon for a virtual menu. Currently, this feature is only in beta but I'm sure it'll be coming to stable soon.

**Comment by Godsbane** [comment]
I was just thinking for ease of update or removal.

**Comment by Moskeeto93** [comment]
I just tested it and putting the icons in a subfolder makes them unusable, sadly.

**Comment by Godsbane** [comment]
that's ok - we can do something like emudeck_icon_ffwd.png or something like that and then key off that.

**Comment by Moskeeto93** [comment]
I did make sure to name them all EmuDeck_xyz so they all do show up grouped together in the Steam Input UI.

**Comment by Moskeeto93** [comment]
I have updated the icons in the google drive link since I made more

**Comment by Godsbane** [comment]
this is completed
