### ISSUE TITLE
Dolphin and Cemu second controller not automatically recognized

### ISSUE THREAD

**Issue by Tormentor667** [dragoonDorise/EmuDeck#509]
Dear EmuDeck developers,

first of all thank you for your amazing work. EmuDeck is the reason why I bought a Steamdeck actually :) everything works well except one thing that I stumbled upon:

I am using two 8BitDo controllers connected via Bluetooth. The first player works perfect on all instances and I can control everything as it is supposed to be.

The second player controller though only works on Retroarch games (SNES, NES, Genesis, etc) but does not work with Cemu or Dolphin out of the box. It simply doesn’t do anything.

Can you be so kind and fix that? 

Kind regards,

**Comment by Godsbane** [comment]
No, you have to enable these manually. They are mapped already, though. Unfortunately having them on out of the box causes problems with single player.

**Comment by Tormentor667** [comment]
But how and where can I enable them? I can't find information about that in the wiki or on the page unfortunately.

**Comment by Godsbane** [comment]
In the input settings in cemu. You can load deck2 for player 2, for example.

**Comment by Tormentor667** [comment]
Does this work for Dolphin as well? And do I have to do that in Desktop mode or in Gaming mode?

**Comment by Godsbane** [comment]
For GameCube you just turn them on. For Wii, the wiimote attach hotkey should work. Check the hotkeys for that l.

**Comment by Tormentor667** [comment]
Okay, I have it a try but ran into various problems, here is an explanation:

**Dolphin | Gamecube**

- If I connect two bluetooth controllers to the Steam Deck and launch Dolphin via Emulation Station (Gaming mode, tried with Mario Kart Double Dash), Steam Deck's own controls move both player 1 and player 2, the first external controller moves player 3 and the second external controller doesn't move anything
- Same procedure in Gaming mode by launching Dolphin as an emulator app directly results in Steam Deck's own controls moving both player 1 and 2, the external controllers do not do anything (they are connected via bluetooth though and can both control the Steam Deck menu)
- Same procedure in Desktop by launching Dolphin as an emulator app directly results in Steam Deck's own controls moving only player 1, the external controllers do not do anything (they are connected via bluetooth though and can both control the Steam Deck menu)

_I will investigate further with Cemu and Wii_

**Comment by Tormentor667** [comment]
**Cemu | Wii U**

- Connected two bluetooth controllers, _Controller 1_ is set up as "Deck-Gamepad-Gyro", "Wii U Gamepad" and "Controller 1 [DSU Controller]", _Controller 2_ is "Deck2", "Wii U Pro Controller", "Controller 2 XInput", and _Controller 3" is "Deck3", "Wii U Pro Controller", "Controller 1 XInput" (no idea why these are swapped thought). SteamDeck and Controller 1 works, Controller 2 does not.

**Comment by Tormentor667** [comment]
**Dolphin | Wii**

- Connected two bluetooth controllers, _launched EmulationStation_ as App. SteamDeck controls work fine, Controller 1 and Controller 2 do nothing but are connected, work well in SteamDeck OS and I can use the Hotkey "Select + Left Stick Down" to make the emulator say "Wii Remote 2/3 connected" so it actually should work.
- Connected two bluetooth controllers, _launched Dolphin_ as App. SteamDeck controls work fine, Controller 1 does nothing but is connected, works well in SteamDeck OS and I can use the Hotkey "Select + Left Stick Down" to make the emulator say "Wii Remote 2 connected". Controller 2 does nothing except controlling the WiiMote mouse pointer of player 1 with the left analog stick but that's all.

**Comment by Godsbane** [comment]
Just for clarification other than changing a setting you should not be in Desktop mode for this. 

I've double checked and everything works correctly in game mode.

**Comment by Tormentor667** [comment]
Okay, maybe I have messed up my Dolphin configuration then before. How can I reset that single configuration to the original EmuDeck setup?

**Comment by Godsbane** [comment]
Emudeck --> tools --> emulator guides --> dolphin

**Comment by Tormentor667** [comment]
You crazy people thought of everything, didn't you? ;) Thanks, I will just try that!

**Comment by Godsbane** [comment]
Lol we try. 

Let me know how it goes.

**Comment by Tormentor667** [comment]
Okay then. This is what I can report:

- From Emulation Station launching GameCube and Wii titles, the first player control works perfect. The second does nothing. Even using the hockeys that make „Wii Controller 2 connected“ do not change anything about it.
- Same issue when launching Dolphin directly from SteamDeck, except that Controller 2 doesn’t even recognize tue hotkey for pluggin in.

**Comment by Tormentor667** [comment]
Any suggestions on that? Still don't get it working...
