### ISSUE TITLE
Unique IDs in Emulator configs (Dolphin)

### ISSUE THREAD

**Issue by Leseratte10** [dragoonDorise/EmuDeck#51]
Looking at the config for the Dolphin emulator an an example (Dolphin.ini), there's a hardcoded Analytics ID and a hard-coded WirelessMAC in the config file. I don't think that's a good idea, because it will make every SteamDeck install of Dolphin look identical. 

Best would be to remove both of them from the config file in this repository (so Dolphin will auto-generate them once upon first boot), and while installing just check if they are already present in an existing config file and then keep the values as they are, so they don't change with each EmuDeck update. 

Or, for the MAC address, have the script figure out the Steam Deck's actual MAC address and add that to the config.

 (Also, is there a reason why in the logger config all the ultra-verbose logs are enabled and always written to the file system?

**Comment by dragoonDorise** [comment]
Fixed on 0.15.5
