### ISSUE TITLE
[SRM] Change default controller mappings

### ISSUE THREAD

**Issue by erdemoney** [dragoonDorise/EmuDeck#511]
Hi,
I'm using EmuDeck on HoloISO with a Switch Pro controller. The default controller configurations that are imported with games via SRM swap A with B and X with Y. The switch pro controller does not need these swaps so they instead mess up the controller configuration for all my games. The only way I can figure out to fix the layouts is in the per game controller configs. What files do I need to edit so when games are imported via SRM they have the right layout by default?

![Screenshot_20221114_160642](https://user-images.githubusercontent.com/21229271/201794751-6330554a-af96-4d30-b2ec-0f03bc327bf6.png)

**Comment by Godsbane** [comment]
SRM does not control this. This is steam.

SRM cannot apply any input settings at this time. There's an open request on their github page for this feature though.
