### ISSUE TITLE
Unable to use local images

### ISSUE THREAD

**Issue by rodcs** [dragoonDorise/EmuDeck#516]
I'm unable to use local images scrapped externally.

I tried copying the snes downloaded_images folder inside the roms folder to the Emulation/tools/downloaded_media/snes/miximages folder, but it still doesn't recognize the images at all, only the ones scrapped from emulationstation itself.

Any way to use local images?

**Comment by Godsbane** [comment]
Hello. This is a question for the developers of ES-DE regarding acceptable formats.

https://gitlab.com/es-de/emulationstation-de/-/blob/master/USERGUIDE.md#manually-copying-game-media-files

I would reach out to the dev of this application if you cannot get it to work :)
