### ISSUE TITLE
Enable Auto Change Discs in Dolphin

### ISSUE THREAD

**Issue by Tormentor667** [dragoonDorise/EmuDeck#517]
I noticed that when playing the Resident Evil remake, I have no hotkeys to change the discs. I made an .m3u including both discs and it runs the game well through EmulationStation but I can not switch the discs ingame.

**Comment by Godsbane** [comment]
Will address this by setting the automatic change disc setting on as default.

**Comment by Tormentor667** [comment]
Thanks kindly!

**Comment by Godsbane** [comment]
- [ ] Change Auto Change Discs setting
- [ ] Add m3u to Dolphin parser in SRM

**Comment by dragoonDorise** [comment]
This should be fixed in 2.0.8. Please reopen this if you still find issues!
