### ISSUE TITLE
Make it possible to differentiate yuzu/ryujinx games more easily

### ISSUE THREAD

**Issue by exp111** [dragoonDorise/EmuDeck#520]
Currently when browsing the through installed games it's difficult to see which game belongs to which emulator without looking into the categories:
![grafik](https://user-images.githubusercontent.com/17885980/203107783-559dc04e-908a-4cc9-941f-d7ecc3106317.png)
Currently the easiest way is to check by pressing start and looking into the categories:
![grafik](https://user-images.githubusercontent.com/17885980/203109791-2148e5ed-8afd-435b-8935-cd33c72117f4.png)

SRM allows to set Title modifiers which would make it possible to do set titles to something like "Animal Crossing (Yuzu)", which would be more visible, but may also make finding custom controller layouts harder (as those are matched by name on non steam games afaik).

Something like a logo overlay would be nice, but I don't think SRM offers something like that. Any other ideas on that front?

**Comment by dragoonDorise** [comment]
This should be fixed in 2.0.8. Please reopen this if you still find issues!
