### ISSUE TITLE
Configure Dolphin Wii Layout for multiple controllers

### ISSUE THREAD

**Issue by ModProg** [dragoonDorise/EmuDeck#521]
I'd imagine, that adding a second/third xbox like controller would be a pretty comon usecase, and it'd be great if emudeck could set them up with the same keybindings/layout switch abilities.

It is currently possible to reuse the layout created by emudeck for additional controllers, but setting it up still can be quite cumbersome. And when I did so, the layout switch seemed to break it.

**Comment by Godsbane** [comment]
Dolphin is already configured to use 4 controllers.

Can you explain what you mean, if not this?

**Comment by ModProg** [comment]
Oh ok, then maybe I did something wrong.

Could the problem be that dolphin was already installed prior to installing emudeck?


Because for me there was only one controller set up.

And even after setting up a second one by loading one of the layouts created by emudeck, when I used the keybind to switch layout, it made the steam deck control both characters.

**Comment by Godsbane** [comment]
you shouldn't load the layout for a second one - they were already setup. Only needed to be enabled. 
Loading a layout will change the device, which you do not want. (as you can see now you have 1 controller controlling two players)

  here are the configs from the base config:
  player 1:
  ```
  [Wiimote2]
  Device = evdev/0/Microsoft X-Box 360 pad 0
  ```
  
  player 2:
  ```
  [Wiimote2]
  Device = evdev/0/Microsoft X-Box 360 pad 1
  ```

and so forth. By loading a profile for player 2 - it actually changes to pad 0 in the config. By it changing to pad 0, now player 1 in Steam Input will control player 1 and 2.

**Comment by ModProg** [comment]
Makes sense, I deleted the dolphin config and ran emudeck again, to regenerate the configuration.

Afterwards, I was able to use the controllers after enabling them in the Dolphin settings but not changing their configuration.

Would it be possible to configure dolphin to automatically enable these when additional controllers are connected/document this somewhere (maybe it already is, but I didn't find it)?

**Comment by Godsbane** [comment]
there's no way other than manually. They are off by default because of stuff like player 2's wiimote pointer being stuck in the middle of your screen all the time.

**Comment by ModProg** [comment]
Yeah makes sense. I thought, maybe Dolphin could detect the number of connected controllers. But maybe that is something that would need to be raised with them.

**Comment by Godsbane** [comment]
Yes I think so.

When using real wiimotes, it seems to work as expected. I am not really sure beyond this and if you ever find out something that makes this work without manual intervention let me know.
