### ISSUE TITLE
"sneshd" folder missing from install

### ISSUE THREAD

**Issue by DaniPhoFani** [dragoonDorise/EmuDeck#522]
I'm trying to get EmuDeck to setup Widescreen versions of Super Mario World and Super Metroid. I'm fairly confident I patched and named the roms and .bso files correctly following the instructions from their respective sources. I searched the EmuDeck discord and found threads stating you're supposed to put widescreen snes roms in the "sneshd" folder so that EmuDeck knows to use bsnes hd Retroarch cores but it's absent from my install. In the "roms" folder I see subfolders for "snes" "snesna" and "sfc" but not "sneshd".

**Comment by Godsbane** [comment]
You can just make it. This is a bug. Will readd the folder for new installs.

**Comment by dragoonDorise** [comment]
This should be fixed in 2.0.8. Please reopen this if you still find issues!
