### ISSUE TITLE
Please support updating emulators without re-writing settings

### ISSUE THREAD

**Issue by maddox** [dragoonDorise/EmuDeck#524]
I use EmuDeck, but I also do a lot of customizations for my personal preferences of emulation. The problem is, the only way to update some emulators, like Yuzu, is by using EmuDeck's installer/updater.

EmuDeck's function of installing/updating emulators is not divorced from setting those emulators up. This means any time you need to update Yuzu or another emulator, it resets all of the settings. 

This might be great for some people, but those that add customizations on top, like changing SDMC or NAND paths, have to then do it all over again. 

It would be nice if there was a way to update an emulator without worrying about settings changing ever.

**Comment by Godsbane** [comment]
There is an updater specifically for these in tools

**Comment by Godsbane** [comment]
@maddox did you find the update option so i can close this?

https://github.com/dragoonDorise/EmuDeck/wiki/Updating

This should do exactly what you want. There's no need to run the emudeck update / install script for just updating emulators. Next time you'll want to run the main install would be if we added an emulator you want, i suppose. (but even then - you should be able to run the individual update / install from the Emulator guides section after an AppImage update including the new item)

**Comment by maddox** [comment]
Yes I did. Thank you for making this more clear!

**Comment by CodeTappert** [comment]
But this does not seem to work with yuzuEA. It only updates the normal yuzu
