### ISSUE TITLE
Please don't update EmulationStation on every run

### ISSUE THREAD

**Issue by maddox** [dragoonDorise/EmuDeck#525]
Whenever you run EmuDeck, to update an emulator, or other things, it then updates EmulationStation at the end of the script.

This is not great because any customizations done to EmulationStation, like skins or path changes, are reset. It's especially frustrating when you run EmuDeck to update an emulator, and then it does something to EmulationStation, when you were just trying to update a single emulator.

All of the emulators have a way to disable them during the EmuDeck run, so that you can update just specified software. How come EmulationStation isn't one of these?

Please consider making the updating of EmulationStation optional and not something that happens every time EmuDeck is run.

**Comment by dragoonDorise** [comment]
This should be fixed in 2.0.8. Please reopen this if you still find issues!

**Comment by maddox** [comment]
❤️
