### ISSUE TITLE
Discord issue

### ISSUE THREAD

**Issue by USL5264** [dragoonDorise/EmuDeck#526]
To whom it may concern,

I am unable to access the Emudeck discord server.
My account got hacked and I think I have been banned. I have now changed my password and added 2FA.

My discord username is nscxp2005#3061

Please could I be reinstated?
This would be much appreciated.

Thank you for your time.

**Comment by Godsbane** [comment]
Yes your account was spamming all the channels.

DM me - Livedeht#9111

**Comment by USL5264** [comment]
I've tried but it says 

![2DFF991B-58E8-47CC-942B-BDAA380205FC](https://user-images.githubusercontent.com/91735282/204308854-29f74d19-643d-4e75-a6ec-60f20704c7af.jpeg)

What shall I do
