### ISSUE TITLE
Steam ROM Manager - Single arcade collection

### ISSUE THREAD

**Issue by svera** [dragoonDorise/EmuDeck#527]
Currently, arcade collections created in Steam by Steam ROM Manager are separated by emulator. So, we end up with Arcade - Mame current, Arcade - FBNeo, and so forth. For simplicity and consistency with the way other collections are created, just put all arcade games into a single Arcade collection.

**Comment by Godsbane** [comment]
no because there are multiple parsers pointed to the same folders in some cases (such as Retroarch - Mame-Current and Mame standalone)

it can't all go to the same one. You can however, adjust the category on yours without issue if you know specifically what you want to use.

**Comment by svera** [comment]
@Godsbane but I'm not talking about folders here, but of arcade collections in steam which, as you say, can be modified from Steam ROM Manager itself. So what I propose is just to modify the default value of "Steam Category" to just "Arcade" in Steam ROM Manager for arcade parsers.

**Comment by Godsbane** [comment]
i understand. There are multiple different parsers (in at least once case) pointed to a single actual folder.

This means you have two games with two different emulators in the same collection. There'd be no way of knowing which is which without separate collections.

**Comment by svera** [comment]
> This means you have two games with two different emulators in the same collection. There'd be no way of knowing which is which without separate collections.

But you could know by looking at which folder each ROM is located, right? Sorry @Godsbane because surely I'm missing something here, but I don't understand what's the relationship between Steam collections and system folders. Aren't collections just a Steam-exclusive abstraction?

**Comment by Godsbane** [comment]
If you change both mame-current and mame-standalone to make a collection called arcade, and you put centipede in the actual arcade folder. Running Steam rom manager will make two entries in Steam for Centipede. Both will be in the Arcade collection, each running a different emulator. You will have no way of knowing which version you are running at a given time without checking the properties before launching.

It's the same reason we don't do, for example, both `yuzu` and `ryujinx` as just `Switch`. You'd have duplicates in the category without knowing which is which.

**Comment by svera** [comment]
Thank you for the explanation @Godsbane, I'll close the suggestion.
