### ISSUE TITLE
Undo what's done by the script

### ISSUE THREAD

**Issue by MiraiSubject** [dragoonDorise/EmuDeck#53]
I wasn't satisfied with EmuDeck and I couldn't find any way to complete undo what was done by the script. This goes in particular for the controller templates that get added by it. 

For now I just deleted the folder, but I still need to find out how to delete the templates. Anyhow it would be greatly appreciated to add instructions (or a script) on how to get rid EmuDeck if you don't want it anymore.

**Comment by Witherking25** [comment]
- open Discover and uninstall all the emulators.
- delete all the folders for the emulators in ~/.var/app
- delete ~/.emulationstation
- delete the Emulation folder

**Comment by C0Nd3Mnd** [comment]
How do you remove the added controller templates?

**Comment by Witherking25** [comment]
What controller templates?

**Comment by Witherking25** [comment]
Oh the steam input thing?

**Comment by Witherking25** [comment]
Go to `~/.steam/steam/controller_base/templates and delete whatever templates you want

**Comment by pencilcheck** [comment]
the uninstaller didn't install the folders mentioned in the post above though

**Comment by MediaMaquina** [comment]
how to access the uninstaller?

**Comment by azeveco** [comment]
Even with the uninstaller I had to:

- Delete folders from `~/.var/app`
- Delete `~/.emulationstation`

**Comment by jason-shen** [comment]
where is the uninstaller lol

**Comment by aaronkjones** [comment]
> where is the uninstaller lol

In the root of this repository.

1. Open Konsole
2. `wget https://raw.githubusercontent.com/dragoonDorise/EmuDeck/refs/heads/main/uninstall.sh`
3. Review the script if you'd like: `less uninstall.sh`
4. Make it executable: `chmod +x uninstall.sh`
5. Run it: `./uninstall.sh`

**Comment by dragoonDorise** [comment]
Or in the app, in the left sidebar, one of the last options. It literally says "Uninstall" 💃
