### ISSUE TITLE
[Feature Request] Add Sharp X68000 Community Parser

### ISSUE THREAD

**Issue by jet082** [dragoonDorise/EmuDeck#537]
I created a community parser here: https://github.com/SteamGridDB/steam-rom-manager/issues/98#issuecomment-1340384323

I'm unsure what the process is to add it to the community parsers on Emudeck, but I'd like to do so. I dislike having to remake this after each update lol.

**Comment by dragoonDorise** [comment]
This should be fixed in 2.0.8. Please reopen this if you still find issues!
