### ISSUE TITLE
Still can't select CEMU 2.0

### ISSUE THREAD

**Issue by lingenfr** [dragoonDorise/EmuDeck#538]
When will the beta or next version be available?

https://github.com/dragoonDorise/EmuDeck/issues/410

**Comment by ViViDboarder** [comment]
For folks tracking this, it looks like there's a PR #505.

**Comment by Godsbane** [comment]
2.0 has been selectable for months in the appimage updater. That pr is for cemu native.

I thought I replied to this, but I guess I only closed it. Sorry.
