### ISSUE TITLE
Support Distinct Names for Randomizers

### ISSUE THREAD

**Issue by jet082** [dragoonDorise/EmuDeck#539]
I know this would be a difficult thing to implement/design and that it is a big ask. I also recognize it may not happen at all, or may take awhile to implement. Still - I'd like to make a request anyway.

It is nice to load up a number of randomizers onto the Deck before going on a long flight. Flying to India from Montana is much easier when you have 10-20 Final Fantasy 4 Randomizers to play on the flight. However, currently, each of these will have the same name and the same icon in Steam. This creates visual clutter and confusion, particularly if you're looking for the exact seed you're trying to resume (this is especially important as some randomizers do commonly take multiple sessions to clear).

It would be nice to be able to add some more features to the game parsing. For instance, one could conceivably add something along the lines of a standardized naming scheme for randomized games.

``Game Name (Randomizer, Seed#).extension``

Such that an example might be: ``Final Fantasy IV - Free Enterprise (Randomizer, UVUGA13960).sfc``

If the parser detects "Randomizer" it would then ensure that the seed is appended to the beginning in the resulting Steam name. For example, it might show the FF4 cover art (since a specific one for Free Enterprise doesn't exist on steamgriddb), but the resulting display name in the steam library would be ``UVUGA13960 (Final Fantasy IV)``. Similar formats could be used for any other randomizer - Zelda 1, Wind Waker, etc.

Or something like that. The goal would be to ensure that one can differentiate seeds from one another and store many separate randomized versions of the game in the same library for better play on long trips. Even better would be to layer the seed number over the art (and maybe overlay a random tint on the art on a per-seed basis) with Pillow or something as well so seeds could be even better visually distinguished ("I'm currently playing the yellow tinted FF4 seed" etc), but that'd be more the icing on the cake.

**Comment by dragoonDorise** [comment]
Hi @jet082 this is something outside our control, I've seen you've already make the request on the SRM GitHub, they are the ones that can make this happen ;)

I'm closing the issue since we need them to add this to SRM.
