### ISSUE TITLE
Invalid parsers

### ISSUE THREAD

**Issue by TheCatDrowned** [dragoonDorise/EmuDeck#540]
I downloaded Emudeck and stuff a while back and when I tried to get the rom manager going, it told me my parsers were invalid. I put the games in the right folders (they’re Wii and GameCube roms) and put the GameCube bios into the bios folder. I got on steam rom manager and went to community parsers and added Wii-Dolphin and Gamecube-Dolphin. Then I went to preview and pressed “generate app list”. What I was told was that “2 parsers was/were skipped (invalid)”. Did I do something wrong?

**Comment by TheCatDrowned** [comment]
Sorry if I put this in the wrong place, as it seems like it’s tagged to some other guys account, which was not intentional

**Comment by Godsbane** [comment]
Parsers are not invalid as configured by us. Community parsers are not ours.

**Comment by Godsbane** [comment]
And one more thing - because it sounds like you need support. Please join the discord for help. There's a link to it on the main emudeck page.

**Comment by TheCatDrowned** [comment]
Yeah I found out why it was doing that. I went through the emudeck easy update mode thing and immediately went to steam rom manager and it worked. The games didn’t show up, but I’ll just ask the emudeck discord.
