### ISSUE TITLE
[Feature Request] Add rewind activation globally 

### ISSUE THREAD

**Issue by Tormentor667** [dragoonDorise/EmuDeck#542]
Would be cool if rewind could be activated globally somewhere instead of doing it each time you play a game

**Comment by Godsbane** [comment]
We had it on for 2.0, but it caused a bunch of problems and was reverted.

**Comment by Tormentor667** [comment]
What about a toggable option then for the customer?

**Comment by Tormentor667** [comment]
Awesome, thank you!
