### ISSUE TITLE
[Feature Request] Backup saves to personal nas server

### ISSUE THREAD

**Issue by DuckersMcQuack** [dragoonDorise/EmuDeck#547]
I want to request a option for the backup tool to backup to a local network location for nas/servers

**Comment by Godsbane** [comment]
https://rclone.org/smb/

Like this? There are many ways to do this, so be a smidgen more specific with how :)

**Comment by DuckersMcQuack** [comment]
> https://rclone.org/smb/
> 
> Like this? There are many ways to do this, so be a smidgen more specific with how :)

Pretty much, so that you can simply add a SMB path to the program and it either compresses it to a zip, and an option to store raw files on that SMB share that emudeck can read from :)

**Comment by Godsbane** [comment]
Sounds good, we can look at adding SMB support to the list.

**Comment by DuckersMcQuack** [comment]
> Sounds good, we can look at adding SMB support to the list.

Sweet :) Also a restore button hehe. Is switch games something that could be compressed like ps2 games by the way?

**Comment by Godsbane** [comment]
restore button exists

no compression for switch games, outside nsz, but it doesn't work for yuzu

**Comment by DuckersMcQuack** [comment]
Alrighty. Does emudeck have a way to backup to a folder on the deck's internal? Or only to designated current cloud storages?

**Comment by Godsbane** [comment]
it's only cloud at the moment.

**Comment by seniorm0ment** [comment]
How about NFS instead of SMB?
Anyways I would be interested.

**Comment by dragoonDorise** [comment]
this was added recently
