### ISSUE TITLE
Mismatch Exception not working

### ISSUE THREAD

**Issue by Pentazer** [dragoonDorise/EmuDeck#548]
![image](https://user-images.githubusercontent.com/54109677/208281967-a78fa4fb-4da8-488c-8c78-4554c0e4fca2.png)
![image](https://user-images.githubusercontent.com/54109677/208281999-8148503f-f7ec-41e4-ab30-a7ef881be34c.png)
Please see above. No matter what I do, this exception is not working. Penta Dragon comes in as the wrong game, I renamed it to PDragon and that also comes in at the wrong game (Epic Dragon) so I tries to use exceptions, but it's not doing anything.

**Comment by Godsbane** [comment]
That's not setup correctly. The field you have shown is the Display Title, and you have put that in the Extracted Title field.

The extracted title is what it gets from the filename (select the parser and hit test parser, or mouse over the wrong entry and you'll see it pop up the extracted title):
![image](https://user-images.githubusercontent.com/1683513/208317228-b47bc415-008c-4c74-9d4d-5c6335398b5a.png)
![image](https://user-images.githubusercontent.com/1683513/208317256-a5644d83-b5ca-4662-ac80-66671b778cf3.png)

if you want it to work though - it has to exist on steamgriddb - which it does not appear to (so you'll have to get it added there too):
https://www.steamgriddb.com/search/grids?term=penta+dragon

[here's our guide](https://github.com/dragoonDorise/EmuDeck/wiki/steam-rom-manager#how-to-fix-a-mismatched-entry)
Closing this as it's not an Emudeck issue, but feel free to let me know if you have more questions.
