### ISSUE TITLE
Support New RPCS3 SDL2 Gyro Controls

### ISSUE THREAD

**Issue by jet082** [dragoonDorise/EmuDeck#549]
See https://github.com/RPCS3/rpcs3/issues/8600 and https://github.com/RPCS3/rpcs3/pull/12502. It seems like we may now be able to do sixaxis control via the Steam Deck gyro. This would allow play of games like Folklore, which have unavoidable motion controls.

**Comment by Godsbane** [comment]
fantastic news - will investigate

**Comment by Godsbane** [comment]
This doesn't work on SteamOS, because valve doesn't surface the gyro to SDL.

i will be closing this, but if anything changes reopen please.
