### ISSUE TITLE
RetroAchievements doesn't sign in to DuckStation or PCSX2

### ISSUE THREAD

**Issue by joeShuff** [dragoonDorise/EmuDeck#550]
Every time I run the install script I have to manually go into Duckstation and PCSX2 to sign in to retroachievements as the script doesn't sign in for me like it does in retroarch.

**Comment by Godsbane** [comment]
it can't, unfortunately. PR's accepted if you want to reverse how duck / pcsx2 do it. Some kind of token response / api call.

**Comment by Godsbane** [comment]
looks like angel decided to take this on #554 and figured out how it's done. Track that issue for the future.

**Comment by joeShuff** [comment]
Thanks for updating!
