### ISSUE TITLE
on the Desmume emulator, when I tap my finger on the screen, it thinks I am touching another area on the screen.

### ISSUE THREAD

**Issue by SkyrimFan64** [dragoonDorise/EmuDeck#553]
Hi. Not sure if this is a Retroarch thing or a Desmume thing but from the Retroarch app on my Steamdeck I have it run DS games from the Retroarch app and selected Desmume as the emulator, but when I tap the screen it thinks I am tapping another area on the screen. Like I could tap the bottom right of the screen and it would think I am tapping a inch or so away. In this case, It is Harry Potter and the Order of the Phoenix.

https://user-images.githubusercontent.com/42390465/208315514-144b072e-0568-40b0-9562-5cccf5af23d3.mp4

**Comment by Godsbane** [comment]
Sorry - we don't setup desmume - so this is going to be a vanilla Retroarch / non emudeck question.

(we do setup melonDS core as well, and that seems to work fine)
