### ISSUE TITLE
Feature Request - Use cheevos token instead of password

### ISSUE THREAD

**Issue by AngelofWoe** [dragoonDorise/EmuDeck#554]
We can send the login to RetroAchievements to test whether the user/pass is good (might even help us with confirmation emails).

```sh
curl --location --request POST 'https://retroachievements.org/dorequest.php?r=login&u=username&p=password'
```

Returns JSON response with either success or failure:

```json
{
  "Success": true,
  "User": "username",
  "Token": "token",
  "Score": 14,
  "SoftcoreScore": 868,
  "Messages": 0,
  "Permissions": 1,
  "AccountType": "Registered"
}
```

```json
{
  "Success": false,
  "Error": "Invalid User/Password combination. Please try again"
}
```

This allows us to make sure the login is good, and use the returned `Token` in `cheevos_token` instead of `cheevos_password` for the user.

**Comment by dragoonDorise** [comment]
@Godsbane I'll do this on the AppImage

**Comment by dragoonDorise** [comment]
@Godsbane can we use this token to setup RetroAchievements on PCSX2 and Duckstation?

**Comment by AngelofWoe** [comment]
> @Godsbane can we use this token to setup RetroAchievements on PCSX2 and Duckstation?

PCSX2-Qt

inis > PCSX2.ini
```ini
[Achievements]
Token = TokenHere
```

DuckStation

settings.ini

```ini
[Cheevos]
Token = TokenHere
```
