### ISSUE TITLE
Yuzu Config Breaks Steam Input "Use Nintendo Button Layout" setting

### ISSUE THREAD

**Issue by andrew-kennedy** [dragoonDorise/EmuDeck#562]
Because emudeck manually sets up the Yuzu input config to use the "nintendo" layout (maps steam deck "b" to nintendo "a"), it means that using the official setting to turn on nintendo layout globally on the steam deck actually turns it off for yuzu. It seems best to handle any and all remappings at the Steam Input layer, otherwise this also breaks toggles and handling for various types of controllers, including the Switch Pro Controller and the PS5 Controller.

This can be corrected by mapping a back to button 0, b to 1, x to 2 and y to 3.

context is here:
https://github.com/dragoonDorise/EmuDeck/blob/1353de6585db5a2dfb87df3f1accc91611afb511/configs/org.yuzu_emu.yuzu/config/yuzu/qt-config.ini#L88
should read:
`player_0_button_a="button:0,guid:03000000de280000ff11000001000000,port:0,engine:sdl"`

https://github.com/dragoonDorise/EmuDeck/blob/1353de6585db5a2dfb87df3f1accc91611afb511/configs/org.yuzu_emu.yuzu/config/yuzu/qt-config.ini#L90
should read:
`player_0_button_b="button:1,guid:03000000de280000ff11000001000000,port:0,engine:sdl"`

https://github.com/dragoonDorise/EmuDeck/blob/1353de6585db5a2dfb87df3f1accc91611afb511/configs/org.yuzu_emu.yuzu/config/yuzu/qt-config.ini#L124
should read:
`player_0_button_x="button:2,guid:03000000de280000ff11000001000000,port:0,engine:sdl"`

https://github.com/dragoonDorise/EmuDeck/blob/1353de6585db5a2dfb87df3f1accc91611afb511/configs/org.yuzu_emu.yuzu/config/yuzu/qt-config.ini#L126
should read:
`player_0_button_y="button:3,guid:03000000de280000ff11000001000000,port:0,engine:sdl"`

**Comment by Godsbane** [comment]
No we do our best to avoid needing steam input changes. All items are location mapped.

I don't see how this would **break** anything?

**Comment by andrew-kennedy** [comment]
Essentially, because emudeck tries to anticipate users wanting to use the nintendo button layout, it sets up the nintendo layout within the yuzu config files. this means when users have their controller preferences set up within the steam deck input settings to "use nintendo layout", a and b and x and y are reversed. you have to "toggle on" nintendo layout in steam in order to turn off nintendo layout in yuzu.

**Comment by Godsbane** [comment]
yeah i don't see this is as a problem. It would be a bigger problem to switch this. Everything is again mapped positional and that's not changing.

The buttons are mapped so the location matches. This works for all controllers; psx, nintendo, and xbox.

sorry but i am closing this. If you want to work on a PR to setup an option to swap these in quick settings please feel free.
