### ISSUE TITLE
[Feedback] Alternative WiiMote Input

### ISSUE THREAD

**Issue by WingofaGriffin** [dragoonDorise/EmuDeck#563]
Trying to get feedback on proposing a new WiiMote Input Map with the following image as reference

![](https://jilaxzone.com/wp-content/uploads/2019/11/Nintendo-Wii-Wiimote-and-Nunchuck-layout-jilaxzone.com_.jpg)

![](https://user-images.githubusercontent.com/108900299/208781446-a65f52f0-2071-4d61-9830-9e56de92b5fb.png)

![](https://user-images.githubusercontent.com/108900299/208781519-b3e91fc3-1a71-4aa4-90f2-a49afa727280.png)

| Wii            | Steam Deck     |
|----------------|----------------|
| A              | A              |
| B              | R2             |
| C              | L1             |
| Z              | L2             |
| +              | Start          |
| -              | Select         |
| 1              | X              |
| 2              | Y              |
| Nuncheck Stick | Left Stick     |
| IR Pointer     | Right Stick    |
| Nunchuck Move  | Left Trackpad  |
| WiiMote Move   | Right Trackpad |
| Home           | B              |
| DPad           | DPad           |

This better emulates the physical feeling for a righthanded nunchuck and wiimote user from my experience. Otherwise most games will accept Gamecube/Classic Controller input.

**Comment by Godsbane** [comment]
this is close to what we had originally.
