### ISSUE TITLE
Error GetVSyncParamatersIfAvailable() failed

### ISSUE THREAD

**Issue by Dervilacus** [dragoonDorise/EmuDeck#564]
So im trying to install emudeck onto my steamdeck and i got this error -   ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParamatersIfAvailable() failed   - 3 times in aq row and now it doesnt seem like it's doing anything at all, Also (in case it matters) the error is showing up on the ~:sh-Konsole page(/tab?) and the last thing on the ~:tail-Konsole one is -   Updating: /home/deck/.var/app/org.libretro.RetroArch/config/retroarch/config/YabaSanshiro/saturn.cfg - input_overlay_scale_landscape = to input_overlay_scale_landscape = "1.070000"

**Comment by Dervilacus** [comment]
... just had to exit out of it and try again, i'm going to assume it might have been caused by the steamdeck going into sleep mode?? not sure

**Comment by Godsbane** [comment]
where did you see that error? in the actual Emudeck log?
