### ISSUE TITLE
vita3k.sh bash script maybe bugged

### ISSUE THREAD

**Issue by 0lm** [dragoonDorise/EmuDeck#566]
Hello.

First of all, I am not 100% sure if this is an issue with the bash script, the Steamdeck OS Updates itself or missing dependencies of vita3k (probably because of SteamOS not being up to date enough). So, I apologize if I am completely wrong here, but:

Let me show what happens when I try to start Vita3k in Desktop Mode in Steam deck:

```
terminate called after throwing an instance of 'std::runtime_error'
what():  locale::facet::_S_create_c_locale name not valid
/run/media/mmcblk0p1/Emulation/tools/launchers/vita3k.sh: line 23:  4450 Aborted
(core dumped) /home/deck/Applications/Vita3K/Vita3K
```

this is what I get from terminal, when trying to start vita3k in Desktop Mode. Awkwardly, when starting it via Steam library (after adding vita3k to Steam with SteamManager that comes with Emudeck) it works and starts properly. My SteamOS is v.3.4.2 stable.

**Comment by elfosardo** [comment]
the script forces to use the en_US.UTF-8 locale and that is indeed an issue related to a missing locale
I wonder if that's not generated for some reason in your case

@0lm can you please show the output of /etc/locale.gen ?
open a terminal from desktop mode and run `cat /etc/locale.gen` to get that

**Comment by Godsbane** [comment]
Hardcoding the locale worked prior to 3.4 for users with non en-US locales set.

If it works from steam but not from the script outside steam, it sounds like there's more env variables we need to override now.

**Comment by Godsbane** [comment]
@dragoonDorise can you replicate this since you have spanish locale?

**Comment by Godsbane** [comment]
With the help of someone discord, we came up with a new script that seems to fix this. Pushed to beta.
