### ISSUE TITLE
[BUG] Cloud Saves no longer working after update 2.0.8

### ISSUE THREAD

**Issue by watchinglearninglistening** [dragoonDorise/EmuDeck#570]
After updating Emudeck to V2.0.8, I have noticed my cloud saves are no longer being reflected/updated in my OneDrive. I have attempted to remedy this with the following steps, but to no avail:

- ) Uninstalling and reinstalling cloud save backups via Konsole (Along with deleting the Emudeck folder in my OneDrive).
- ) Re-logging into my cloud service provider via Konsole.

I have also attempted to create a backup with the 'run backup once' option, which produces the following response:

```Failed to create file system for "Emudeck-OneDrive:Emudeck/saves": unable to get drive_id and drive_type - if you are upgrading from older versions of rclone, please run 'rclone config' and re-configure this backend.```

Upon checking the rclone_job.log file, I see repeated attempts at transferring of data, but with 0B/0B(s) transferred. 

Additionally, I can see by running 'systemctl --user list-timers' in Konsole that the auto-backup timer is running as intended, every 15 minutes.

Finally, I went into the rclone.conf file and verified that I have a valid token for OneDrive, along with files.readwrite, offline_access all present. I'm not sure where else to go from here.

**Comment by Godsbane** [comment]
Sounds like an rclone version thing.

Did you try the `rclone configure` command specified in the error?

**Comment by Godsbane** [comment]
You have to do it from the folder with rclone.

`./rclone config` let me know

**Comment by Godsbane** [comment]
Give me a day to see if I can reproduce

**Comment by Godsbane** [comment]
sorry i have not had time to mess with this.

I haven't heard any other reports of it either though, so it's sort of weird.  I will do my best to test tomorrow during the day!

**Comment by Godsbane** [comment]
I attempted to reproduce this, but it just happily synced everything to one drive for me.

perhaps start it fresh? use the reinstall button, login to provider, create backup, run backup once. then post a fresh log?

**Comment by Godsbane** [comment]
strange - the reinstall button recreates the whole config file. I've just tested to be sure and deleted the one drive entry as you did. then i ran this button: 
![image](https://user-images.githubusercontent.com/1683513/210281207-cdf731ef-ce34-43c7-8de4-c715f852defc.png)


and it recreated this below:

you could manually readd this to your `rclone.conf`

```
[Emudeck-OneDrive]
type = onedrive
token =
access_scopes = Files.ReadWrite, offline_access
drive_id =
drive_type = personal
```

**Comment by Godsbane** [comment]
`Script terminating. Exit code 0` just means the script completed- i want the job log please.

**Comment by Godsbane** [comment]
This indicates it's working

**Comment by watchinglearninglistening** [comment]
Going to close this as I've resigned myself to never have cloud saves again for Emudeck. Apologies to have wasted your time, Godsbane.

**Comment by Godsbane** [comment]
:(
