### ISSUE TITLE
Use a better GBC core

### ISSUE THREAD

**Issue by Jaizu** [dragoonDorise/EmuDeck#571]
The current core doesn't support the MBC30 mapper.

**Comment by Godsbane** [comment]
we include both gambatte and sameboy. (and technically also mGBA)

Neither support this?

**Comment by Jaizu** [comment]
Unless I misschecked, steam rom list or whatever that thing is called only supported one

**Comment by Godsbane** [comment]
You aren't wrong. Somehow it got dropped.

https://github.com/dragoonDorise/EmuDeck/pull/429

We def built it. Will readd. Doesn't change the fact that I am not sure about the feature you mention. I was under the impression gambatte was the best.

**Comment by Jaizu** [comment]
Asked some gbcx devs, they recommend bgb or sameboy, not sure if they are available as cores on retroarch tho

**Comment by Godsbane** [comment]
sameboy is included - that's the bit we added above. we def configure the emu and it's installed. Just missing the parser which will get readded. In the meantime you can test it with EmulationStation if you want.

**Comment by Jaizu** [comment]
I will be fine with sameboy, feel free to close the issue once it's re-added to the parser.

**Comment by WingofaGriffin** [comment]
SameBoy has began to supersede Gambatte, though ensuring save compatibility wont be broken if we change the default is the main concern. Existing Gambatte users who are unsure of the change we don't want facing "broken" saves/states.

**Comment by dragoonDorise** [comment]
Parser Added in current beta

**Comment by tylernguyen** [comment]
Hello,

The current parser only supports the Sameboy core for GameBoy games. Please add parser support for GameBoy Color games as well.
