### ISSUE TITLE
[Wiki] Add guides for dumping & installing extra system data on the Citra page

### ISSUE THREAD

**Issue by eeveeishpowered** [dragoonDorise/EmuDeck#573]
Some games need extra system data (3DS common fonts, mii data, etc) from a 3DS to work/work properly. I've looked at the Citra page in this repository's wiki but couldn't find any mention on how to dump the extra data in it.

An example of a game that needs extra data is Tomodachi Life, which needs Mii data from a 3DS to be able to display Miis correctly. Otherwise, all Miis will look like this:
![citra-qt_BWyWSL37GE](https://user-images.githubusercontent.com/82042525/209718906-436f59e2-1814-45e9-9a13-05239f9bd24a.png)
The game also needs AES keys to be able to scan QR codes, but this is already mentioned in the wiki. It can also use the 3DS common fonts, but these aren't required for the game to run.

A guide for dumping this data should be added so that it will be easier & more straightforward for users who want to play the games that need it.

**Comment by Godsbane** [comment]
If you know this information please add it to the wiki. It's allowed. No need to open an issue on it.

We do not compile citra or anything, just install it, so our wikis aren't as comprehensive as the actual emulator documentation.
