### ISSUE TITLE
Default rclone Google Drive client ID rate limited

### ISSUE THREAD

**Issue by burdenc** [dragoonDorise/EmuDeck#574]
Using the save backup feature I was unable to authenticate with Google Drive because rclone's default client ID is being rate limited: https://forum.rclone.org/t/google-cloud-sign-in-limit-rate/34772

This seems like it's hard to avoid once a project gets too big, but it'd help if EmuDeck generated their own cloud project and client ID for the save backups with rclone.

**Comment by Godsbane** [comment]
You can generate and provide your own.

I don't think generating one and distributing it is wise. The one in rclone is not public, but was discovered somehow.
