### ISSUE TITLE
[Enhancement] Add the language besides the English

### ISSUE THREAD

**Issue by Bob0111** [dragoonDorise/EmuDeck#579]
Currently the deck is shipping to Asia. And in the selling countries or regions, the default language is not English. So I think it is a good idea to use a website like crowdin to translate the English to other languages with the help of volunteers. I can't code the EmuDeck, but I'm glad to help translate English to Chinese.

**Comment by Godsbane** [comment]
This is something we want to do too, but are not quite ready.

Soon!
