### ISSUE TITLE
Mismatch between systeminfo.txt and rom-manager configuration regarding .zip files

### ISSUE THREAD

**Issue by Landcross** [dragoonDorise/EmuDeck#582]
So, I just copied some PSP games onto my Steam deck and before copying I quickly checked the systeminfo.txt and it said the supported file extensions included .zip. So, I copied over my zip files and went into steam rom manager, but my games did not show up. After a quick look, it seems that the included PSP configuration for Steam Rom Manager does not actually include .zip.

PSP systeminfo.txt (with .zip):

- https://github.com/dragoonDorise/EmuDeck/blob/main/roms/psp/systeminfo.txt

PSP glob configuration (without .zip): 

- https://github.com/dragoonDorise/EmuDeck/blob/main/configs/steam-rom-manager/userData/userConfigurations.json#L3250
- https://github.com/dragoonDorise/EmuDeck/blob/main/configs/steam-rom-manager/userData/userConfigurations.json#L3188

**Comment by Godsbane** [comment]
it's not mismatched. That's for ES-DE.
