### ISSUE TITLE
Subfolders on systems GB/GBA/GBC/ are ignored.

### ISSUE THREAD

**Issue by Conan179** [dragoonDorise/EmuDeck#583]
Good day. Yesterday I did my Emudeck installation again, when I wanted to add my roms back with the srm, I noticed that my GB/GBA/GBC/ roms are being ignored. The system necessary folders are /run/media/card/Emulation/roms/gb(x)/, one subfolder for each initial letter (i.e. "/run/media/card/Emulation/roms/gb(x)/A " "/run/media/card/Emulation/roms/gb(x)/B" and so on).
I looked at the other parsers and noticed that in the systems that are no longer displayed for me, the line "User's glob" is missing "../" at the beginning.
Why removed this?

**Comment by Godsbane** [comment]
i explained on the discord, this was changed by @dragoonDorise for the addition of the homebrew folders. He didn't want the homebrew to get picked up by the parser.

technically you should use the root folder, or none of the content directory overrides that are setup work anyways.

regardless, i'm already fixing the parsers to ignore the homebrew folder specifically, yet enable recursion. So i am closing this.
