### ISSUE TITLE
chddeck.sh no longer works for GameCube 

### ISSUE THREAD

**Issue by nathanaelries** [dragoonDorise/EmuDeck#585]
The last working copy of chddeck.sh when it comes to the dolphin-tool is the commit on September 27 2022. 

Ever since the change was made November 1st 2022 to switch dolphin-tool to alias, GameCube compression has been broken.

Please revert back to using the prime hack dolphin tool binary.

**Comment by Godsbane** [comment]
it's fixed in beta
