### ISSUE TITLE
[Enhancement] Ability to move some emulators/roms to different drive

### ISSUE THREAD

**Issue by Aljutor** [dragoonDorise/EmuDeck#586]
It can be quite beneficial to store some emulators/roms on fast internal m.2 drive, and use slower sd card for others where it not so beneficial.

**Comment by Godsbane** [comment]
1) The emulator install location won't change, regardless of choice. Flatpaks install to their /var partition. Appimages and binaries go in ~/Applications
2) you can already do what you want with symlinks, with regards to rom location.
3) almost nothing has load time issues with either m.2 or SD card. There are users who even put their roms on network locations without problems.

We won't fracture the setup, as it's just a script which installs stuff for you. After install, you can do whatever you want, but updates won't work as expected if you move things around.
