### ISSUE TITLE
Steam Rom Manager not working on latest beta

### ISSUE THREAD

**Issue by realJustinLee** [dragoonDorise/EmuDeck#587]
OS build: 20230109.1003
Kernel version: 5.13.0-valve37-1-neptune

Steam Version: 1672959434

**Comment by Godsbane** [comment]
Will need you to be way more specific, which piece?

**Comment by Godsbane** [comment]
I am going to close this without more info. Logs, or anything else so it can be looked at.

(Also we do not make Steam Rom Manager, https://github.com/SteamGridDB/steam-rom-manager/issues )

**Comment by Godsbane** [comment]
i have tested on main and beta and had no issues. I am going to close this.

**Comment by realJustinLee** [comment]
@Godsbane I finally figured out what happened. Steam OS update 3.4 has changed SD card mount path. And my EmuDeck installation was conducted on some earlier Steam OS. Thus there’s a path not found error that caused all of these problems. And a reinstallation would fix this mess.

See reference [here](https://gamerant.com/steam-deck-update-34-break-sd-card-path/)

**Comment by Godsbane** [comment]
Yes we all went through this panic last month. That said they rolled this change back in 3.4.1

It has been reapplied in 3.5 ( main steamos branch)

In stable and beta, it should still be the original location.

On main, the location has changed. Reinstall does fix, but it's annoying.

Right now it looks like a symlink of the old path to the new paths works :)
