### ISSUE TITLE
EmuDeck Compression tool not detecting any wii games installed

### ISSUE THREAD

**Issue by qfoxb** [dragoonDorise/EmuDeck#588]
I have multiple wii games installed under the wii roms folder that i ripped and put in wbfs format, and emudeck compression tool doesn't recognize any games inside of the wii folder. I tried using the uncompresed ISO files as well and it doesn't seem to see them either. It only sees the PS2 games i ripped in iso, which it converted to CHD just fine

**Comment by Godsbane** [comment]
This is fixed in beta - however wbfs is not touched ever. iso can be.

**Comment by objecttothis** [comment]
Thank you for fixing this.  Is there an ETA on when Dev will be released?

**Comment by objecttothis** [comment]
Also, @Godsbane does this fix add the primehacks folder to the list to check in addition to the wii folder?

**Comment by Godsbane** [comment]
No eta.

Yes it checks all three folders.
