### ISSUE TITLE
chd conversion script says (only some) files are missing that are present

### ISSUE THREAD

**Issue by therealjkvalentine** [dragoonDorise/EmuDeck#591]
Tool ran successfully on all files in the below directory, but repeatedly displays error that Gradius and Tekken Tag are missing .cue files. Names seem to match, permissions seem right, no special characters.

![image](https://user-images.githubusercontent.com/26639321/212443245-0b2093ea-8657-43fe-a090-606041798b53.png)

(deck@steamdeck ps2)$ ls -l
total 34880732
-rw-r--r-- 1 deck deck        232 Oct 18 07:45 'Archive 0-J.URL'
-rw-r--r-- 1 deck deck        246 Oct 18 07:45 'Archive K-R.URL'
-rw-r--r-- 1 deck deck        255 Oct 18 07:46 'Archive S-Z.URL'
-rw-r--r-- 1 deck deck 2758469242 Jan 13 15:57 'Castlevania - Curse of Darkness.chd'
-rw-r--r-- 1 deck deck 2428838285 Jan 13 17:21 'Castlevania - Lament of Innocence.chd'
-rw-r--r-- 1 deck deck 1227418687 Jan 13 16:09 'God Hand .chd'
-rw-r--r-- 1 deck deck  465832416 Apr  1  2016 'Gradius V.bin'
-rw-r--r-- 1 deck deck         81 Mar 28  2016 'Gradius V.cue'
-rw-r--r-- 1 deck deck 2867979304 Jan 13 17:01 'Jak II.chd'
-rw-r--r-- 1 deck deck  979388508 Jan 13 16:13 'Jaws Unleashed.chd'
-rw-r--r-- 1 deck deck 1322113652 Jan 13 16:49 'Katamari Damacy.chd'
-rw-r--r-- 1 deck deck  893767346 Jan 13 17:05 'Mega Man X8 .chd'
-rw-r--r-- 1 deck deck 3304907118 Oct 18 12:30 'Metal Gear Solid 3 - Snake Eater .chd'
-rw-r--r-- 1 deck deck 2757648876 Jan 13 16:43 'Onimusha - Warlords.chd'
-rw-r--r-- 1 deck deck 1110012495 Oct 18 12:16 'Shadow of the Colossus.chd'
-rw-r--r-- 1 deck deck 2394035570 Jan 13 17:13 'Sly Cooper and the Thievius Raccoonus.chd'
-rw-r--r-- 1 deck deck 2477760194 Oct 18 12:08 'SSX Tricky.chd'
-rw-r--r-- 1 deck deck 1752973491 Jan 13 16:05 'Steambot Chronicles.chd'
-rw-r--r-- 1 deck deck        474 Oct 18 06:53  systeminfo.txt
-rw-r--r-- 1 deck deck  728143920 Apr  9  2016 'Tekken Tag Tournament.bin'
-rw-r--r-- 1 deck deck        101 Mar 28  2016 'Tekken Tag Tournament.cue'
-rw-r--r-- 1 deck deck 2887343282 Jan 13 15:46 "Tony Hawk's Pro Skater 3.chd"
-rw-r--r-- 1 deck deck 3746592813 Jan 13 16:26 'Valkyrie Profile 2 - Silmeria.chd'
-rw-r--r-- 1 deck deck 1614504034 Jan 13 16:32 'Zone of the Enders.chd'
(deck@steamdeck ps2)$ pwd
/run/media/mmcblk0p1/Emulation/roms/ps2
(deck@steamdeck ps2)$

**Comment by Godsbane** [comment]
What's the contents of one of the cue files it didn't like?

**Comment by Godsbane** [comment]
No response, so closing. Please be sure to check the contents of your cue match your bin file exactly, including casing.

**Comment by therealjkvalentine** [comment]
You are absolutely correct, I'm so sorry to have missed this and to have added to your ticket queue by filing a bug for a silly user error like this. Kudos to you and the team for keeping it so classy despite my mistake. Have an awesome day.
