### ISSUE TITLE
Dolphin retroarch core

### ISSUE THREAD

**Issue by musyne** [dragoonDorise/EmuDeck#595]
Question: I see Dolphin has a core for retroarch. Why not use this instead of installing it as a standalone?

I guess the same question could apply to the Playstation emulators, the 3DS, ...

**Comment by Godsbane** [comment]
Because they are not well done and lack features, performance, or accuracy compared to the standalone equivalent.

In fact we should definitely skip installing them all. They are mostly only including for completeness for es-de, and should be avoided.

#561 is where we can track the removal.
