### ISSUE TITLE
yuzu is not installed

### ISSUE THREAD

**Issue by dreamerblue** [dragoonDorise/EmuDeck#596]
I have used EmuDeck latest version (SRM ver 2.3.40, linux 5.13) with options "Quick Update" and “Install Homebrew Games: yes” to install (I have not installed any other emulators from Discover before).
But after installation completed and opened Steam Rom Manager (yuzu is enabled), I found I cannot open `yuzu EmuDeck` from application list.

I execuated some commands from `/home/deck/Emulation/tools/launchers/yuzu.sh` to test:
```sh
emuName="yuzu"
emufolder="$HOME/Applications"
find $emufolder -iname "${emuName}*.AppImage" | sort -n | cut -d' ' -f 2- | tail -n 1 2>/dev/null
flatpak list --app --columns=application | grep $emuName
```
The line#3 outputs none. The line#4 outputs none and exited with 1.

So I guess it may caused by yuzu is not installed by EmuDeck. How to fix this? I have reinstalled once but the issue still exitsts.

**Comment by Godsbane** [comment]
Please upload your emudeck log
~/emudeck/emudeck.log

**Comment by dreamerblue** [comment]
[emudeck.log](https://github.com/dragoonDorise/EmuDeck/files/10431972/emudeck.log)

**Comment by Godsbane** [comment]
every time you try to connect to github to download anything - you get a 403 forbidden in your log.

curl: (22) The requested URL returned error: 403

Github doesn't like you.

**Comment by dreamerblue** [comment]
Oh yep, in China, it's not easy to access GitHub without proxy 😂.

It may related to my proxy issue like too many requests sent by other users. I will use another proxy and retry, thanks!

**Comment by Godsbane** [comment]
Sounds good, good luck!

Btw, the parts that did not download can be grabbed with the appimage updater in Emudeck--> tools --> updater.

Faster than going through the whole install.

**Comment by dreamerblue** [comment]
Aha, thanks! I have successfully installed
