### ISSUE TITLE
List of built-in templates keeps growing

### ISSUE THREAD

**Issue by KaiClavier** [dragoonDorise/EmuDeck#599]
I can only assume this is an emudeck issue, since it creates templates for Cemu, PCSX2, and Citra... A lot of the default valve-created templates (suck as "Keyboard (WASD) and Mouse")are now in the list multiple times for me. It might be possible that every time I update emudeck it doesn't properly rebuild this list...? I'm not totally sure. Please disregard if this is a known issue with valve instead of emudeck.

**Comment by Godsbane** [comment]
It's a valve issue.

It also went away for me when I switched to branches to beta and back.
