### ISSUE TITLE
Move emulationstation config directory to SD card

### ISSUE THREAD

**Issue by dunestorm333** [dragoonDorise/EmuDeck#60]
When configuring EmuDeck for the SD card, it should also point EmulationStation's config directory to the SD card. This is because if you decide to scrape game media using ES, your home directory can get quite large, filling your internal storage rather quickly. My workaround for this was to move `~/.emulationstation` to `/run/media/mmcblk0p1/Emulation/es_config` and then create a symbolic link between the two locations. This allows me to download as much metadata as I'd like on my 64GB SteamDeck 🙂

**Comment by dragoonDorise** [comment]
Hi, already done on dev branch, will be on the next 0.16.3 version :)
