### ISSUE TITLE
Ryujinx black screen issue - temp fix below

### ISSUE THREAD

**Issue by urbanracer34** [dragoonDorise/EmuDeck#601]
I was having a problem with Ryujinx. No matter what game I would pull up, it would sit at a black screen. 

Someone on the EmuDeck discord posted a solution in a gist which worked for me and others.

Could we please get this implimented?

https://gist.github.com/rawdatafeel/5a64d84b3d112b126649a2416f4e4c1c

**Comment by Godsbane** [comment]
Probably not.

When the ava branch is merged it's going to disappear, which would suddenly break stuff. 

Unfortunately, there's not a great solution here. You can use the script emotion gisted for now.

I will leave this open so people can find it easily.

**Comment by Godsbane** [comment]
i think we can close this. Up to date steamos has solved this and workarounds are no longer needed.
