### ISSUE TITLE
req: Emumovies support

### ISSUE THREAD

**Issue by Hakker** [dragoonDorise/EmuDeck#602]
Besides screenscraper have emumovies support for those who already have such an account.
As I use Launchbox as well the scraping seems to be a lot better for me on emumovies compared to screenscraper.

that or you can fine tune it better with  having box art specifically and such. Now you end up having different styles of images.

**Comment by Godsbane** [comment]
You need to request this from EmulationStation-DE, not us, as we do not make that software.
