### ISSUE TITLE
Stuck on checking for updates

### ISSUE THREAD

**Issue by thestuartcarson** [dragoonDorise/EmuDeck#604]
Just what the title says. Starting emudeck on desktop mode. Stuck on checking for updates screen, nothing happens. Any way to get around this without reinstalling? 
![3B804543-9144-4F92-90FA-FAB02974739A](https://user-images.githubusercontent.com/86478803/215225736-a95f5d6d-c226-4580-b507-aa88c52743e2.jpeg)

**Comment by liuk** [comment]
I can confirm I have exactly the same problem on a brand-new steam deck.

**Comment by Dasonk** [comment]
Same here but this is a fresh install on a steam deck.

This is the output I have on my konsole:

`
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   738  100   738    0     0    816      0 --:--:-- --:--:-- --:--:--   816
Session {
  resolveProxy: [Function: resolveProxy],
  getCacheSize: [Function: getCacheSize],
  clearCache: [Function: clearCache],
  clearStorageData: [Function: clearStorageData],
  flushStorageData: [Function: flushStorageData],
  setProxy: [Function: setProxy],
  forceReloadProxyConfig: [Function: forceReloadProxyConfig],
  setDownloadPath: [Function: setDownloadPath],
  enableNetworkEmulation: [Function: enableNetworkEmulation],
  disableNetworkEmulation: [Function: disableNetworkEmulation],
  setCertificateVerifyProc: [Function: setCertificateVerifyProc],
  setPermissionRequestHandler: [Function: setPermissionRequestHandler],
  setPermissionCheckHandler: [Function: setPermissionCheckHandler],
  setDevicePermissionHandler: [Function: setDevicePermissionHandler],
  clearHostResolverCache: [Function: clearHostResolverCache],
  clearAuthCache: [Function: clearAuthCache],
  allowNTLMCredentialsForDomains: [Function: allowNTLMCredentialsForDomains],
  isPersistent: [Function: isPersistent],
  setUserAgent: [Function: setUserAgent],
  getUserAgent: [Function: getUserAgent],
  setSSLConfig: [Function: setSSLConfig],
  getBlobData: [Function: getBlobData],
  downloadURL: [Function: downloadURL],
  createInterruptedDownload: [Function: createInterruptedDownload],
  setPreloads: [Function: setPreloads],
  getPreloads: [Function: getPreloads],
  loadExtension: [Function: loadExtension],
  removeExtension: [Function: removeExtension],
  getExtension: [Function: getExtension],
  getAllExtensions: [Function: getAllExtensions],
  getSpellCheckerLanguages: [Function: getSpellCheckerLanguages],
  setSpellCheckerLanguages: [Function: setSpellCheckerLanguages],
  availableSpellCheckerLanguages: [Getter],
  setSpellCheckerDictionaryDownloadURL: [Function: setSpellCheckerDictionaryDownloadURL],
  listWordsInSpellCheckerDictionary: [Function: listWordsInSpellCheckerDictionary],
  addWordToSpellCheckerDictionary: [Function: addWordToSpellCheckerDictionary],
  removeWordFromSpellCheckerDictionary: [Function: removeWordFromSpellCheckerDictionary],
  setSpellCheckerEnabled: [Function: setSpellCheckerEnabled],
  isSpellCheckerEnabled: [Function: isSpellCheckerEnabled],
  spellCheckerEnabled: [Getter/Setter],
  preconnect: [Function: preconnect],
  closeAllConnections: [Function: closeAllConnections],
  getStoragePath: [Function: getStoragePath],
  setCodeCachePath: [Function: setCodeCachePath],
  clearCodeCaches: [Function: clearCodeCaches],
  cookies: [Getter],
  netLog: [Getter],
  protocol: [Getter],
  serviceWorkers: [Getter],
  webRequest: [Getter],
  storagePath: [Getter]
}
[8275:0127/174539.122677:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
17:45:39.930 › Checking for update
17:45:39.966 › Generated new staging user ID: df394635-bda3-5453-ba23-699da7d673df
Session {
  resolveProxy: [Function: resolveProxy],
  getCacheSize: [Function: getCacheSize],
  clearCache: [Function: clearCache],
  clearStorageData: [Function: clearStorageData],
  flushStorageData: [Function: flushStorageData],
  setProxy: [Function: setProxy],
  forceReloadProxyConfig: [Function: forceReloadProxyConfig],
  setDownloadPath: [Function: setDownloadPath],
  enableNetworkEmulation: [Function: enableNetworkEmulation],
  disableNetworkEmulation: [Function: disableNetworkEmulation],
  setCertificateVerifyProc: [Function: setCertificateVerifyProc],
  setPermissionRequestHandler: [Function: setPermissionRequestHandler],
  setPermissionCheckHandler: [Function: setPermissionCheckHandler],
  setDevicePermissionHandler: [Function: setDevicePermissionHandler],
  clearHostResolverCache: [Function: clearHostResolverCache],
  clearAuthCache: [Function: clearAuthCache],
  allowNTLMCredentialsForDomains: [Function: allowNTLMCredentialsForDomains],
  isPersistent: [Function: isPersistent],
  setUserAgent: [Function: setUserAgent],
  getUserAgent: [Function: getUserAgent],
  setSSLConfig: [Function: setSSLConfig],
  getBlobData: [Function: getBlobData],
  downloadURL: [Function: downloadURL],
  createInterruptedDownload: [Function: createInterruptedDownload],
  setPreloads: [Function: setPreloads],
  getPreloads: [Function: getPreloads],
  loadExtension: [Function: loadExtension],
  removeExtension: [Function: removeExtension],
  getExtension: [Function: getExtension],
  getAllExtensions: [Function: getAllExtensions],
  getSpellCheckerLanguages: [Function: getSpellCheckerLanguages],
  setSpellCheckerLanguages: [Function: setSpellCheckerLanguages],
  availableSpellCheckerLanguages: [Getter],
  setSpellCheckerDictionaryDownloadURL: [Function: setSpellCheckerDictionaryDownloadURL],
  listWordsInSpellCheckerDictionary: [Function: listWordsInSpellCheckerDictionary],
  addWordToSpellCheckerDictionary: [Function: addWordToSpellCheckerDictionary],
  removeWordFromSpellCheckerDictionary: [Function: removeWordFromSpellCheckerDictionary],
  setSpellCheckerEnabled: [Function: setSpellCheckerEnabled],
  isSpellCheckerEnabled: [Function: isSpellCheckerEnabled],
  spellCheckerEnabled: [Getter/Setter],
  preconnect: [Function: preconnect],
  closeAllConnections: [Function: closeAllConnections],
  getStoragePath: [Function: getStoragePath],
  setCodeCachePath: [Function: setCodeCachePath],
  clearCodeCaches: [Function: clearCodeCaches],
  cookies: [Getter],
  netLog: [Getter],
  protocol: [Getter],
  serviceWorkers: [Getter],
  webRequest: [Getter],
  storagePath: [Getter]
}
Display with current scale factor: 1
17:45:41.272 › Error: Error: Cannot parse releases feed: Error: Unable to find latest version on GitHub (https://github.com/EmuDeck/emudeck-electron/releases/latest), please ensure a production release exists: SyntaxError: Unexpected token < in JSON at position 7
    at JSON.parse (<anonymous>)
    at t.GitHubProvider.getLatestTagName (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:135514)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at t.GitHubProvider.getLatestVersion (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:133895)
    at d.getUpdateInfoAndProvider (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:91044)
    at doCheckForUpdates (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:91330)
    at Object.t.newError (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:16445)
    at t.GitHubProvider.getLatestTagName (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:135549)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at t.GitHubProvider.getLatestVersion (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:133895)
    at d.getUpdateInfoAndProvider (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:91044)
    at doCheckForUpdates (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:91330),
XML:
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/" xml:lang="en-US">
  <id>tag:github.com,2008:https://github.com/EmuDeck/emudeck-electron/releases</id>
  <link type="text/html" rel="alternate" href="https://github.com/EmuDeck/emudeck-electron/releases"/>
  <link type="application/atom+xml" rel="self" href="https://github.com/EmuDeck/emudeck-electron/releases.atom"/>
  <title>Release notes from emudeck-electron</title>
  <updated>2023-01-15T20:52:15Z</updated>
  <entry>
    <id>tag:github.com,2008:Repository/507401294/v2.0.9</id>
    <updated>2023-01-20T22:27:53Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/EmuDeck/emudeck-electron/releases/tag/v2.0.9"/>
    <title>2.0.9</title>
    <content type="html">&lt;p&gt;FIX: GyroDSU Installation&lt;br&gt;
FIX: SDCard path detection, if the path changes between launches&lt;/p&gt;</content>
    <author>
      <name>github-actions[bot]</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/in/15368?s=60&amp;v=4"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/507401294/v2.0.8</id>
    <updated>2022-12-18T21:28:59Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/EmuDeck/emudeck-electron/releases/tag/v2.0.8"/>
    <title>2.0.8</title>
    <content type="html">&lt;ul&gt;
&lt;li&gt;HomeBrew Games - A collection of free non commercial games.&lt;/li&gt;
&lt;li&gt;AutoSave &amp;amp; Autoload for RA Games&lt;/li&gt;
&lt;li&gt;DeckyControl - See our hotkeys in gaming mode&lt;/li&gt;
&lt;li&gt;New Parsers&lt;/li&gt;
&lt;li&gt;Several bug fixes:&lt;/li&gt;
&lt;li&gt;Solved an issue that prevented RetroAchievements to work when the username / password contained special characters.&lt;/li&gt;
&lt;li&gt;Solved an issue with sudo passwords contaning special characters.&lt;/li&gt;
&lt;li&gt;Solved some fixes when launching Proton emulators.&lt;/li&gt;
&lt;li&gt;Added Progress Bar to Appimage &amp;amp; Binary updater.&lt;/li&gt;
&lt;li&gt;Fixed an issue that overwrote RetroArch configurations even when asking not to.&lt;/li&gt;
&lt;li&gt;Optimization of all images used on the AppImage so they take less space.&lt;/li&gt;
&lt;li&gt;New SRM page on Emulators Guides.&lt;/li&gt;
&lt;li&gt;SNES 8:7 Bezels fix&lt;/li&gt;
&lt;li&gt;DOSBox-pure legacy .conf support&lt;/li&gt;
&lt;li&gt;Option to prevent ESDE config overwrite&lt;/li&gt;
&lt;li&gt;Option to prevent ESDE installation&lt;/li&gt;
&lt;li&gt;Emulators overwrite/disable selection is now persistent between installations&lt;/li&gt;
&lt;li&gt;Added Big Picture argument to Duckstation and PCSX2&lt;/li&gt;
&lt;/ul&gt;</content>
    <author>
      <name>github-actions[bot]</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/in/15368?s=60&amp;v=4"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/507401294/v2.0.7</id>
    <updated>2022-12-10T00:52:07Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/EmuDeck/emudeck-electron/releases/tag/v2.0.7"/>
    <title>v2.0.7</title>
    <content type="html">&lt;p&gt;Merge branch &#39;dev&#39; into beta&lt;/p&gt;</content>
    <author>
      <name>dragoonDorise</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/u/6368050?s=60&amp;v=4"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/507401294/v2.0.6</id>
    <updated>2022-11-20T02:35:43Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/EmuDeck/emudeck-electron/releases/tag/v2.0.6"/>
    <title>v2.0.6</title>
    <content type="html">&lt;p&gt;fix branch&lt;/p&gt;</content>
    <author>
      <name>dragoonDorise</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/u/6368050?s=60&amp;v=4"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/507401294/v2.0.5</id>
    <updated>2022-10-31T23:15:38Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/EmuDeck/emudeck-electron/releases/tag/v2.0.5"/>
    <title>v2.0.5</title>
    <content type="html">&lt;p&gt;Fix branch.json path&lt;/p&gt;</content>
    <author>
      <name>dragoonDorise</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/u/6368050?s=60&amp;v=4"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/507401294/v2.0.4</id>
    <updated>2022-10-21T07:22:57Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/EmuDeck/emudeck-electron/releases/tag/v2.0.4"/>
    <title>2.0.4</title>
    <content type="html">&lt;p&gt;FIX: Custom location selector, now it tests if the path is writable and allows symlinks.&lt;br&gt;
NEW: Appimage &amp;amp; installation live log.&lt;br&gt;
FIX: Compressor Tool.&lt;/p&gt;</content>
    <author>
      <name>github-actions[bot]</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/in/15368?s=60&amp;v=4"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/507401294/v2.0.3</id>
    <updated>2022-10-20T09:45:51Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/EmuDeck/emudeck-electron/releases/tag/v2.0.3"/>
    <title>2.0.3</title>
    <content type="html">&lt;p&gt;FIX: Removed LOG for RAchievement Users and password&lt;br&gt;
FIX: Changed the way settings.sh is created.&lt;br&gt;
FIX: English Grammar&lt;br&gt;
FIX: CHD tool log&lt;br&gt;
FIX: Removed Update Log on Welcome Screen&lt;br&gt;
IMPROVEMENT: Better SD Card detection&lt;/p&gt;</content>
    <author>
      <name>github-actions[bot]</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/in/15368?s=60&amp;v=4"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/507401294/v2.0.2</id>
    <updated>2022-10-18T20:48:15Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/EmuDeck/emudeck-electron/releases/tag/v2.0.2"/>
    <title>2.0.2</title>
    <content type="html">&lt;ul&gt;
&lt;li&gt;FIX: Improved SD Card detection&lt;/li&gt;
&lt;li&gt;FIX: Improved Backend detection&lt;/li&gt;
&lt;li&gt;FIX: SteamDeckGyroDSU Installation&lt;/li&gt;
&lt;li&gt;FIX: Checking for updates screen freeze&lt;/li&gt;
&lt;li&gt;NEW: Appimage logs&lt;/li&gt;
&lt;/ul&gt;</content>
    <author>
      <name>github-actions[bot]</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/in/15368?s=60&amp;v=4"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/507401294/v2.0.1</id>
    <updated>2022-10-17T19:56:51Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/EmuDeck/emudeck-electron/releases/tag/v2.0.1"/>
    <title>2.0.1</title>
    <content type="html">&lt;p&gt;FIX: Reset Config for PrimeHack and PCSX2&lt;br&gt;
FIX: Distorted images in certain resolutions&lt;br&gt;
FIX: Messages on PowerTools&lt;br&gt;
FIX: Improved SD Card detection&lt;br&gt;
FIX: Improved Backend detection&lt;br&gt;
FIX: RetroAchievments&lt;br&gt;
NEW: Appimage file log&lt;br&gt;
KNOWN BUG: GyroDSU installation&lt;/p&gt;</content>
    <author>
      <name>github-actions[bot]</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/in/15368?s=60&amp;v=4"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/507401294/v2.0.0</id>
    <updated>2022-10-16T15:00:33Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/EmuDeck/emudeck-electron/releases/tag/v2.0.0"/>
    <title>2.0.0</title>
    <content type="html">&lt;p&gt;EmuDeck 2 is here and this is our biggest update ever!&lt;br&gt;
Brand new format, now EmuDeck has a GUI to make it even easier to use.&lt;br&gt;
Quick settings, no need to reinstall to apply customizations.&lt;br&gt;
Backup your saves to the cloud.&lt;br&gt;
New Emulators: Vita3K, ScummVM and DooM.&lt;br&gt;
Performance improvements for all emulators.&lt;br&gt;
Completely revamped Controllers and Hotkeys.&lt;br&gt;
A lot of bug fixes and under the hood improvements.&lt;/p&gt;</content>
    <author>
      <name>github-actions[bot]</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/in/15368?s=60&amp;v=4"/>
  </entry>
</feed>

    at Object.t.newError (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:16445)
    at t.GitHubProvider.getLatestVersion (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:134048)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at d.getUpdateInfoAndProvider (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:91044)
    at doCheckForUpdates (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:91330)
(node:8242) UnhandledPromiseRejectionWarning: Error: Cannot parse releases feed: Error: Unable to find latest version on GitHub (https://github.com/EmuDeck/emudeck-electron/releases/latest), please ensure a production release exists: SyntaxError: Unexpected token < in JSON at position 7
    at JSON.parse (<anonymous>)
    at t.GitHubProvider.getLatestTagName (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:135514)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at t.GitHubProvider.getLatestVersion (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:133895)
    at d.getUpdateInfoAndProvider (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:91044)
    at doCheckForUpdates (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:91330)
    at Object.t.newError (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:16445)
    at t.GitHubProvider.getLatestTagName (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:135549)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at t.GitHubProvider.getLatestVersion (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:133895)
    at d.getUpdateInfoAndProvider (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:91044)
    at doCheckForUpdates (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:91330),
XML:
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom" xmlns:media="http://search.yahoo.com/mrss/" xml:lang="en-US">
  <id>tag:github.com,2008:https://github.com/EmuDeck/emudeck-electron/releases</id>
  <link type="text/html" rel="alternate" href="https://github.com/EmuDeck/emudeck-electron/releases"/>
  <link type="application/atom+xml" rel="self" href="https://github.com/EmuDeck/emudeck-electron/releases.atom"/>
  <title>Release notes from emudeck-electron</title>
  <updated>2023-01-15T20:52:15Z</updated>
  <entry>
    <id>tag:github.com,2008:Repository/507401294/v2.0.9</id>
    <updated>2023-01-20T22:27:53Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/EmuDeck/emudeck-electron/releases/tag/v2.0.9"/>
    <title>2.0.9</title>
    <content type="html">&lt;p&gt;FIX: GyroDSU Installation&lt;br&gt;
FIX: SDCard path detection, if the path changes between launches&lt;/p&gt;</content>
    <author>
      <name>github-actions[bot]</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/in/15368?s=60&amp;v=4"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/507401294/v2.0.8</id>
    <updated>2022-12-18T21:28:59Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/EmuDeck/emudeck-electron/releases/tag/v2.0.8"/>
    <title>2.0.8</title>
    <content type="html">&lt;ul&gt;
&lt;li&gt;HomeBrew Games - A collection of free non commercial games.&lt;/li&gt;
&lt;li&gt;AutoSave &amp;amp; Autoload for RA Games&lt;/li&gt;
&lt;li&gt;DeckyControl - See our hotkeys in gaming mode&lt;/li&gt;
&lt;li&gt;New Parsers&lt;/li&gt;
&lt;li&gt;Several bug fixes:&lt;/li&gt;
&lt;li&gt;Solved an issue that prevented RetroAchievements to work when the username / password contained special characters.&lt;/li&gt;
&lt;li&gt;Solved an issue with sudo passwords contaning special characters.&lt;/li&gt;
&lt;li&gt;Solved some fixes when launching Proton emulators.&lt;/li&gt;
&lt;li&gt;Added Progress Bar to Appimage &amp;amp; Binary updater.&lt;/li&gt;
&lt;li&gt;Fixed an issue that overwrote RetroArch configurations even when asking not to.&lt;/li&gt;
&lt;li&gt;Optimization of all images used on the AppImage so they take less space.&lt;/li&gt;
&lt;li&gt;New SRM page on Emulators Guides.&lt;/li&gt;
&lt;li&gt;SNES 8:7 Bezels fix&lt;/li&gt;
&lt;li&gt;DOSBox-pure legacy .conf support&lt;/li&gt;
&lt;li&gt;Option to prevent ESDE config overwrite&lt;/li&gt;
&lt;li&gt;Option to prevent ESDE installation&lt;/li&gt;
&lt;li&gt;Emulators overwrite/disable selection is now persistent between installations&lt;/li&gt;
&lt;li&gt;Added Big Picture argument to Duckstation and PCSX2&lt;/li&gt;
&lt;/ul&gt;</content>
    <author>
      <name>github-actions[bot]</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/in/15368?s=60&amp;v=4"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/507401294/v2.0.7</id>
    <updated>2022-12-10T00:52:07Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/EmuDeck/emudeck-electron/releases/tag/v2.0.7"/>
    <title>v2.0.7</title>
    <content type="html">&lt;p&gt;Merge branch &#39;dev&#39; into beta&lt;/p&gt;</content>
    <author>
      <name>dragoonDorise</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/u/6368050?s=60&amp;v=4"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/507401294/v2.0.6</id>
    <updated>2022-11-20T02:35:43Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/EmuDeck/emudeck-electron/releases/tag/v2.0.6"/>
    <title>v2.0.6</title>
    <content type="html">&lt;p&gt;fix branch&lt;/p&gt;</content>
    <author>
      <name>dragoonDorise</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/u/6368050?s=60&amp;v=4"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/507401294/v2.0.5</id>
    <updated>2022-10-31T23:15:38Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/EmuDeck/emudeck-electron/releases/tag/v2.0.5"/>
    <title>v2.0.5</title>
    <content type="html">&lt;p&gt;Fix branch.json path&lt;/p&gt;</content>
    <author>
      <name>dragoonDorise</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/u/6368050?s=60&amp;v=4"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/507401294/v2.0.4</id>
    <updated>2022-10-21T07:22:57Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/EmuDeck/emudeck-electron/releases/tag/v2.0.4"/>
    <title>2.0.4</title>
    <content type="html">&lt;p&gt;FIX: Custom location selector, now it tests if the path is writable and allows symlinks.&lt;br&gt;
NEW: Appimage &amp;amp; installation live log.&lt;br&gt;
FIX: Compressor Tool.&lt;/p&gt;</content>
    <author>
      <name>github-actions[bot]</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/in/15368?s=60&amp;v=4"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/507401294/v2.0.3</id>
    <updated>2022-10-20T09:45:51Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/EmuDeck/emudeck-electron/releases/tag/v2.0.3"/>
    <title>2.0.3</title>
    <content type="html">&lt;p&gt;FIX: Removed LOG for RAchievement Users and password&lt;br&gt;
FIX: Changed the way settings.sh is created.&lt;br&gt;
FIX: English Grammar&lt;br&gt;
FIX: CHD tool log&lt;br&gt;
FIX: Removed Update Log on Welcome Screen&lt;br&gt;
IMPROVEMENT: Better SD Card detection&lt;/p&gt;</content>
    <author>
      <name>github-actions[bot]</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/in/15368?s=60&amp;v=4"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/507401294/v2.0.2</id>
    <updated>2022-10-18T20:48:15Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/EmuDeck/emudeck-electron/releases/tag/v2.0.2"/>
    <title>2.0.2</title>
    <content type="html">&lt;ul&gt;
&lt;li&gt;FIX: Improved SD Card detection&lt;/li&gt;
&lt;li&gt;FIX: Improved Backend detection&lt;/li&gt;
&lt;li&gt;FIX: SteamDeckGyroDSU Installation&lt;/li&gt;
&lt;li&gt;FIX: Checking for updates screen freeze&lt;/li&gt;
&lt;li&gt;NEW: Appimage logs&lt;/li&gt;
&lt;/ul&gt;</content>
    <author>
      <name>github-actions[bot]</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/in/15368?s=60&amp;v=4"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/507401294/v2.0.1</id>
    <updated>2022-10-17T19:56:51Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/EmuDeck/emudeck-electron/releases/tag/v2.0.1"/>
    <title>2.0.1</title>
    <content type="html">&lt;p&gt;FIX: Reset Config for PrimeHack and PCSX2&lt;br&gt;
FIX: Distorted images in certain resolutions&lt;br&gt;
FIX: Messages on PowerTools&lt;br&gt;
FIX: Improved SD Card detection&lt;br&gt;
FIX: Improved Backend detection&lt;br&gt;
FIX: RetroAchievments&lt;br&gt;
NEW: Appimage file log&lt;br&gt;
KNOWN BUG: GyroDSU installation&lt;/p&gt;</content>
    <author>
      <name>github-actions[bot]</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/in/15368?s=60&amp;v=4"/>
  </entry>
  <entry>
    <id>tag:github.com,2008:Repository/507401294/v2.0.0</id>
    <updated>2022-10-16T15:00:33Z</updated>
    <link rel="alternate" type="text/html" href="https://github.com/EmuDeck/emudeck-electron/releases/tag/v2.0.0"/>
    <title>2.0.0</title>
    <content type="html">&lt;p&gt;EmuDeck 2 is here and this is our biggest update ever!&lt;br&gt;
Brand new format, now EmuDeck has a GUI to make it even easier to use.&lt;br&gt;
Quick settings, no need to reinstall to apply customizations.&lt;br&gt;
Backup your saves to the cloud.&lt;br&gt;
New Emulators: Vita3K, ScummVM and DooM.&lt;br&gt;
Performance improvements for all emulators.&lt;br&gt;
Completely revamped Controllers and Hotkeys.&lt;br&gt;
A lot of bug fixes and under the hood improvements.&lt;/p&gt;</content>
    <author>
      <name>github-actions[bot]</name>
    </author>
    <media:thumbnail height="30" width="30" url="https://avatars.githubusercontent.com/in/15368?s=60&amp;v=4"/>
  </entry>
</feed>

    at Object.t.newError (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:16445)
    at t.GitHubProvider.getLatestVersion (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:134048)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at d.getUpdateInfoAndProvider (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:91044)
    at doCheckForUpdates (/tmp/.mount_EmuDecu3duFZ/resources/app.asar/dist/main/main.js:2:91330)
(Use `emudeck --trace-warnings ...` to show where the warning was created)
(node:8242) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

`

**Comment by thestuartcarson** [comment]
> I can confirm I have exactly the same problem on a brand-new steam deck.

When did this issue start for you? Mine was working fine a day or two ago

**Comment by thestuartcarson** [comment]
When did you fresh install this? Within the last day or two?

**Comment by liuk** [comment]
> > I can confirm I have exactly the same problem on a brand-new steam deck.
> 
> When did this issue start for you? Mine was working fine a day or two ago

I was doing a brand new install. I did install emudeck on another machine this Monday and everything worked fine.

**Comment by Dasonk** [comment]
I had emudeck working fine but did a factory reset of my deck this morning
and tried installing emudeck not even an hour ago.

**Comment by thestuartcarson** [comment]
Looks like it’s a few of us then. Probably more to come. Hopefully gets patched asap.

**Comment by oliverhermanni** [comment]
Another one bites the dust. :(

**Comment by thestuartcarson** [comment]
> Another one bites the dust. :(

I’m certain this issue will be fixed. I wouldn’t be concerned.

**Comment by Godsbane** [comment]
the issue is here: https://github.com/orgs/community/discussions/45590
We use electron-builder
Electron-builder calls for the updates in a way that github has broken as of this past hour.

**Comment by thestuartcarson** [comment]
> the issue is here: https://github.com/orgs/community/discussions/45590
> We use electron-builder
> Electron-builder calls for the updates with electron-updater in a way that github has broken as of this past hour.

Interesting. I’m not hugely familiar with how all of this works, but is electron-builder popular enough that it’s likely to get fixed?

**Comment by dragoonDorise** [comment]
We are going to deploy a fix in a few. We've fixed the screen being stuck but we need to test some other stuff before deploying it

**Comment by thestuartcarson** [comment]
> We are going to deploy a fix in a few. We've fixed the screen being stuck but we need to test some other stuff before deploying it

Thank you so much!

**Comment by dragoonDorise** [comment]
Hi @thestuartcarson , the fix is deployed! Since the updater is broken on github you'll need to download emudeck from our website again.

**Comment by twidgit** [comment]
> Hi @thestuartcarson , the fix is deployed! Since the updater is broken on github you'll need to download emudeck from our website again.

I redownloaded the updater but it's making me reinstall it? Is this going to overwrite my roms/games/saves? Kinda disappointing if so

**Comment by dragoonDorise** [comment]
@twidgit nope, that's just normal behavior, when you reopen EmuDeck it just gives you the option to reinstall in case you want to. As soon as you have the new app you can carry on and just update when the next proper version comes along

**Comment by SuperSentai03** [comment]
Yeah same here idek what's going on

**Comment by thestuartcarson** [comment]
Well I started it up today and it worked without having to update or anything :) It just worked! Thanks for your help, and unless anyone else is having issues this issue can be closed?
