### ISSUE TITLE
Add Support For Mesen 2

### ISSUE THREAD

**Issue by John-Enigma** [dragoonDorise/EmuDeck#605]
As you may know, SourMesen closed his [Mesen](https://github.com/SourMesen/Mesen) and [Mesen S](https://github.com/SourMesen/Mesen-S) repos in 2020. While these emulators can still be downloaded, they're no longer active. Even just recently, NovaSquirrel's community forks, [Mesen-X](https://github.com/NovaSquirrel/Mesen-X) and [Mesen-SX](https://github.com/NovaSquirrel/Mesen-SX) have been officially deprecated, despite her repos still being active. 

SourMesen just recently decided to come back, and reboot his emulators into one, [Mesen 2](https://github.com/SourMesen/Mesen2/), where he also added GB and PC-Engine support. 

This emulator has Linux support, so is it possible to add this to EmuDeck?

**Comment by WingofaGriffin** [comment]
In full honesty, despite this emulator being linux compatible, the fact its based in .NET makes it a larger task than expected for integration into the more closed ecosystem the deck provides for typical users. This, along with the fact that alternatives for both of these emulators exist both in RA and standalone (work is being done on ares, Snes9x, and Nestopia), makes it not a high priority right now.

This could change if we see a RA core or a Flatpak/AppImage of the emulator.

**Comment by John-Enigma** [comment]
Got it.

**Comment by Godsbane** [comment]
I will be closing this request for now, however, if official builds come along with the requirements packaged we can take a look at it again.

**Comment by pizzadude** [comment]
@Godsbane Currently there are prebuilt AppImages linked from the Mesen 2 readme.

**Comment by d0k3** [comment]
I was just about to write a new emulator request myself when I found this one.

I'm seconding the request, specifically because the Mesen LibRetro emulator does not support (or not support properly) several Mesen HD packs, among those gems like [this one](https://www.romhacking.net/forum/index.php?topic=26811.0).

I guess I'll try to get it running on my Deck and will come back with more remarks.
