### ISSUE TITLE
Add support for "snesna" and "32xna" configs (tg16 too?)

### ISSUE THREAD

**Issue by CorneliousJD** [dragoonDorise/EmuDeck#606]
Both the SNES and 32X in their North American (NA) variants do not get matching retroarch config files created -- I noticed when launching games from "snes" that the proper pixel scaling/interger scaling was correct, but INCORRECT when launching from "snesna" folder. (This is easily visible in MegaMan X on the health bar).

Note that the reason I want my ROMS in "snesna" is because in Emulation Station the themes for "SNES" show the european version of the SNES and not the NA version, so I use "snesna" folder. This is where the issues start to show. 

![image](https://user-images.githubusercontent.com/724777/215300580-3907901d-eaa9-4a23-874e-1d9b9baaaaca.png)
![image](https://user-images.githubusercontent.com/724777/215300578-41d81654-cb82-4a8b-8d40-ab2ed90acde5.png)

To correct this I posted in Discord and livedeht was very helpful in pointing me to 
/home/deck/.var/app/org.libretro.RetroArch/config/retroarch/config
And then in the Snes9x folder and PicoDrive folders, there's configs for "snes" and "32x" but not any for "snesna" or "32xna" at all.
To fix this for now I symlinked the non-na counterparts so they match the others.

I feel as though this should be included out of the box with EmuDeck (or just have matching config files, not necessarily symlinks) -- as many users who run it will likely want to see the NA version of the SNES and 32x, and this is already being done for MegaDrive and Genesis out of the box.

It looks like this may also need to be done between "pcengine" and "tg16" as well - possibly PCE CD and TG16CD? 
There may be other regional variations of consoles that I'm forgetting and just haven't setup yet, but I would assume you want users to be able to put their ROMS into any folder that's generated, be it snes vs snesna, pcengine vs tg16, etc -- it will depend on the console name they're familiar with and artwork they're looking for in Emulation Station 

My setup now is below - please let me know if this ends up being pushed in an update and I will remove my symlinks in preparation for the actual config files.

![2023-01-28 21_08_20-Snes9x — Dolphin  Streaming](https://user-images.githubusercontent.com/724777/215300664-ad6afd54-9f93-4a9d-867d-09dcf12a065b.png)

![2023-01-28 21_08_05-PicoDrive — Dolphin  Streaming](https://user-images.githubusercontent.com/724777/215300663-8028c949-e0f3-4dbb-8ae1-d3a1471bdfcc.png)

![image](https://user-images.githubusercontent.com/724777/215300890-beec94cd-0635-4a40-b981-0f8ed505081b.png)

**Comment by CorneliousJD** [comment]
Noticed the same thing for pcengine vs tg16 as well - updated original post.

**Comment by dragoonDorise** [comment]
@CorneliousJD Fixed on current beta

**Comment by Godsbane** [comment]
One more task will be adding all these folders to srm

**Comment by CorneliousJD** [comment]
I am sorry for reopening this but I just tested and I noticed snesna.cfg and .glsp and .slangp all got created ,but only tg16.fcfg and 32xna.cfg got created (missing the glslp and slangp files) -- not sure if this is intentional or an oversight.
