### ISSUE TITLE
Unable to use ' in password for installing tools

### ISSUE THREAD

**Issue by Interestle** [dragoonDorise/EmuDeck#607]
When trying to install a tool like Power Tools or Decky Controls that require a password in the gui, if the password has a `'` character in it, the following error occurs:
`/bin/sh: -c: line 1: unexpected EOF while looking for matching '"\n/bin/sh: -c: line 2: syntax error: unexpected end of file\n`

Here is a screenshot of this happening when using a single ':
![Screenshot_20230129_201621](https://user-images.githubusercontent.com/42608349/215381073-582467e5-b13d-4fdb-b8f8-d8aa3f29094c.png)

**Comment by Godsbane** [comment]
investigating

**Comment by Godsbane** [comment]
can you test this with the EmuDeck beta appimage and confirm it's all set?

**Comment by Interestle** [comment]
Just tested against 2.0.33. I can't find any character that results in a similar error. Thanks for looking into it!

**Comment by Godsbane** [comment]
Thanks for reporting and testing!
