### ISSUE TITLE
The installer doesn't mention the need to add a BIOS for Xbox emulation

### ISSUE THREAD

**Issue by UwUnyaa** [dragoonDorise/EmuDeck#610]
After installing emudeck, the tip card about BIOSes doesn't mention Xbox as a system that requires one, despite the list stating that it's exhaustive. This is a big letdown considering I was hoping it would be a way for me to get a working Xbox emulator.

**Comment by Godsbane** [comment]
Sorry for the letdown. The wiki is the more complete list.
