### ISSUE TITLE
PCSX2 Slow Motion/Lagging With Many Games

### ISSUE THREAD

**Issue by seniorm0ment** [dragoonDorise/EmuDeck#621]
So I just setup Emudeck the other night, and have been having issues with almost every game I've tried on PCSX2. They all seem to have issues with lag. It's almost like the game is running in slow motion, and it shows fps drops from 17. The main menus seem fine but then go into gameplay and it drops. Or sometimes on certain stages like with SSX Tricky first few stages seemed fine then suddenly the issue occured. It's unplayable.

I tried disabling SMT with Powertools, and messing with some of the PCSX2 settings. Haven't figured it out. Also no power restrictions are on, and I've tried capping FPS on deck to 60, and also setting it to unrestricted FPS. Did not fix either.

Everything is up to date, and the ROMS are running on built in SSD.
Not sure what to try, it is likely a setting with PCSX2 that I'm missing.

**Comment by Godsbane** [comment]
It's game dependent. the game you mentioned, ssx tricky is notoriously hard to play well, even on much more capable hardware.

Anyways, use the discord for support. This is for issues with emudeck.

**Comment by seniorm0ment** [comment]
Ok.
Also as far as Discord it would be nice to see a bridge to a more privacy/libre friendly platform at least. Discord is a very invasive platform, so I won't be joining it.
Thanks.
