### ISSUE TITLE
Gamelists should be placed in the micro SD

### ISSUE THREAD

**Issue by genna87** [dragoonDorise/EmuDeck#624]
During installation, if you choose to put ROMs in the micro SD, EmuDeck generates a downloaded_media folder in the SD that will be populated with scraped media files.

But scraping also populates metadata in the gamelists files that are still placed in the home folder ( /home/deck/.emulationstation/ ).

Putting both gamelists and downloaded_media in the SD would make easier to backup all the scraped data in a single place.

**Comment by Godsbane** [comment]
I do not believe that the gamelist location can be changed in EmulationStation-DE. if you can find / point me to a setting that allows this, we can look at it, otherwise we can do something like link the gamelists folder to Emulation/saves/es-de/gamelists for easy sync / access.

**Comment by genna87** [comment]
You're probably right:
https://github.com/Aloshi/EmulationStation/blob/master/GAMELISTS.md#gamelists

All I can think of is using symlinks, but don't know if there's any drawback

**Comment by Godsbane** [comment]
I've added a symlink in the saves folder for beta.
