### ISSUE TITLE
Website Typo

### ISSUE THREAD

**Issue by Fmstrat** [dragoonDorise/EmuDeck#625]
Couldn't really figure out anywhere else to put this, but thought you might want to be aware. On https://www.emudeck.com/#how_to_install

> When **The** installation finish you'll need to copy **yor** games and run an app called Steam Rom Manager.

Should be:

> When **the** installation finish**es** you'll need to copy **your** games and run an app called Steam Rom Manager.

**Comment by Godsbane** [comment]
https://github.com/EmuDeck/EmuDeckWebsite

please open website issues on the website github. thanks!
