### ISSUE TITLE
.m3u missing from the list of supported formats for Sega CD (Genesis Plus GX) [confirmed]

### ISSUE THREAD

**Issue by notimp** [dragoonDorise/EmuDeck#629]
Just had a user in the discord complain, that .m3u is not a supported format for Sega CD games, and did the research and then confirmed, that it is indeed supported by the core and works in retroarch (loaded a game, switched discs, loaded it again, tried to start a new game, got a "please switch discs" message).

It does work. It is needed for Sega CD games (Genesis Plus GX tested) - so it should be added to the list of supported formats.

(Steam Rom Manager,
Emulation Station (unsure, I'm not using it please doublecheck)
and as an entry in the readmes and wikis, for Sega CD)

Thank you for considering,

notimp

**Comment by Godsbane** [comment]
Thanks notimp, we'll get it added.
