### ISSUE TITLE
Compression Tool only works on external storage

### ISSUE THREAD

**Issue by gclawes** [dragoonDorise/EmuDeck#631]
`chddeck.sh` appears to be hard-coded to use external storage under `/run/media/`, which prevents it's use in compressing roms on internal storage (`$HOME/Emulation/...`).  It would be very useful to be able to use this for roms on internal storage, or at least clarify that it only works for external storage.

https://github.com/dragoonDorise/EmuDeck/blob/28ff221930f7de566b79c8f5f3a278f073ea4ddd/tools/chdconv/chddeck.sh#L16

**Comment by Godsbane** [comment]
no, this is sed'd during update / installation
