### ISSUE TITLE
Waydroid as Emulator for "Google Android"

### ISSUE THREAD

**Issue by JavaCoder5542884** [dragoonDorise/EmuDeck#635]
Can I use WayDroid/Anbox/or something different as emulator for the "Google Android"

**Comment by Godsbane** [comment]
if you can install it, perhaps.
ES-DE might work, but again - you'd need to figure out a way to install a proper android emulator that it supports.

I'm going to close this for now, if you want to chat about it use the Discord please, and maybe someone has tried it already.
