### ISSUE TITLE
LCD shader not aligned in GB

### ISSUE THREAD

**Issue by MisterAnderson91** [dragoonDorise/EmuDeck#636]
The default shader set for gb does not align properly with the pixels on screen. The issue seems to be because integer scaling is off by default. However, turning it on then makes the Gameboy screen border the wrong size.

I think if shaders are an option in the setup, it would be logical to turn on integer scaling and use correct sized borders rather than the poor experience of misaligned shaders that is currently the default setting (when enabled). The screen resolution is already known as all steam decks are currently the same, so it should be easy enough to adjust for.

Integer scaling could also be a separate option in the setup anyway as it's very commonly preferred.

EDIT: On further inspection, GBA has the same issue which is already integer scaled by virtue of having an exact multiple in the 800 vertical res. However its default shader is also quite awful, with the lcd grid lines almost off by exactly half (splitting pixels in half instead of going between them). It seems that maybe the issue is maybe with the choice of lcd3x.slangp as the default.

**Comment by Godsbane** [comment]
Could you post pictures illustrating the issue (if possible)

**Comment by MisterAnderson91** [comment]
You can see in the screenshot that scanlines run within the scaled up pixels instead of between them.

![20230224220641_1](https://user-images.githubusercontent.com/50129983/221319788-9dd86dee-f48c-4af9-b057-4c57590f56bc.jpg)
![20230224220641_1 copy](https://user-images.githubusercontent.com/50129983/221319801-128b6c32-c306-4e41-aaef-379069bd8094.jpg)
![20230224220641_1 copy copy](https://user-images.githubusercontent.com/50129983/221319804-0ca71b9e-70ee-4b0d-9b64-4f9f2ca85f81.jpg)

**Comment by Godsbane** [comment]
@dragoonDorise what do you think? I tend to agree that the other shader looks better.

**Comment by dragoonDorise** [comment]
@Godsbane @MisterAnderson91 , yep it looks a lot better. I've changed it on beta
