### ISSUE TITLE
Add support for CHD compression for Phillips CD-i, and bios folder structure for Same_CDi

### ISSUE THREAD

**Issue by KBouder** [dragoonDorise/EmuDeck#640]
The Same_CDi core for Retroarch supports CHDs, this request is to add Phillips CD-i roms to the list of systems able to be compressed. The folder for CDi roms is cdimono1.

Same_CDi can load CHD, ISO, and BIN/CUE (even though the documentation does not mention the last one)

3 bios files (cdibios.zip, cdimono1.zip, cdimono2.zip) are needed to run Same_CDi which needs to be placed in /Emulation/bios/same_cdi/bios/. A pre-made folder structure for this would be helpful for setting this up. This should also be added to the BIOS checker. 

- [ ] add cdimono1 to chd compression whitelist
- [ ] add/update same_cdi parser
- [ ] create bios folder automatically (prob won't do)

Reference:
https://docs.libretro.com/library/same_cdi/

**Comment by WingofaGriffin** [comment]
Initial config made and ready for testing once approved and merged to beta

**Comment by WingofaGriffin** [comment]
looks like it was merged to beta branch. @Godsbane can confirm

**Comment by Godsbane** [comment]
Yep

**Comment by KBouder** [comment]
I tested this out, and it appears to not work. chdman seems to return "Unsupported Format" when converting bin/cue to chd. I did a little bit of digging and it seems that others have had similar issues with converting CDi bin/cue.

**Comment by WingofaGriffin** [comment]
Can you link those? If CHDman doesn't support it, that bug needs to be fixed by MAME devs.

**Comment by KBouder** [comment]
> Can you link those? If CHDman doesn't support it, that bug needs to be fixed by MAME devs.

https://github.com/mamedev/mame/issues/2784
https://github.com/libretro/same_cdi/pull/6

I re-read the post and I was wrong about the dump, it is good.

**Comment by Godsbane** [comment]
Based on this info I'd say we should disable it.

Once chdman gets updated to support the format we can update the binary and try again.

**Comment by Godsbane** [comment]
If and when chdman is updated to support this format, please reopen this issue and we can take a look at adding this support.
