### ISSUE TITLE
[Enhancement] Common language configuration

### ISSUE THREAD

**Issue by rubengc** [dragoonDorise/EmuDeck#641]
Hi there!

Some emulators like Dolphin, Citra, Cemu, etc have a system language option

Would be awesome to select a language (or detect the OS one) to apply this language to all emulators where possible

Thanks in advance for the amazing job! Emudeck is simply great!

**Comment by Godsbane** [comment]
https://github.com/dragoonDorise/EmuDeck/pull/545

This is being worked on by @exp111 already.

**Comment by SiTWulf** [comment]
Any new about this feature?
I like to change my emulators language from English to Spanish.

**Comment by dragoonDorise** [comment]
@SiTWulf EmuDeck 2.3 does this automatically
