### ISSUE TITLE
[Suggestion] Assign the same hotkeys for the same actions

### ISSUE THREAD

**Issue by rubengc** [dragoonDorise/EmuDeck#642]
Hi there!

In Cemu, you can toggle screens using L3 and L4 while on Citra is through R3 and R4, would be awesome and easier to remember if double screen consoles switching is made through the same hotkeys

The same happens when saving/loading states, so the proposal would be to try to keep, where possible, the same hotkeys

Thanks in advance!

**Comment by Godsbane** [comment]
Citra doesn't accept combo hotkeys, which is why we made the trackpad menu for states and other stuff for it.

Cemu could be swapped to the other side, but it's perhaps too late.
