### ISSUE TITLE
Unable to save Retroarch main config

### ISSUE THREAD

**Issue by danielbyon** [dragoonDorise/EmuDeck#644]
I'm unable to save the Retro arch main config file when a game is running.

Repro steps:

1. Start ES-DE
2. Launch a rom (I did a GBA one)
3. Click L3+R3
4. Navigate to `Main Menu -> Configuration File`
5. Attempt to "Save Current Configuration"

I get a `"Failed saving config to <path>"` error

If I do `Quick Menu -> Close Content` and then try to save the main config it works (says `"Saved new config to <path>"`). Then if I exit Retroarch back to ES-DE and repeat the repro steps I still get the error

**Comment by Godsbane** [comment]
you cannot save config when content is loaded with an override.

**Comment by Godsbane** [comment]
All content is loaded with overrides. That's how they are preconfigured for you with bezels and shaders.

If you want to make changes, use the quick settings or save the appropriate override.
