### ISSUE TITLE
GyroDSU for Dolphin Emulator is not set up correctly in Controller Configuration [Motion Input]

### ISSUE THREAD

**Issue by KBouder** [dragoonDorise/EmuDeck#647]
Controller mappings for motion controls within Dolphin should be typed out as:
'DSUClient/0/steamdeckgyro:[Input Type]'

The current option on stock config is:
[Input Type]

Which does nothing.
https://wiki.dolphin-emu.org/index.php?title=DSU_Client

This guide has been useful to me in getting this set up properly on my Deck.

**Comment by Godsbane** [comment]
We do not have motion controls mapped, and it's not planned for dolphin ( at this time )

We used to, but removed it, as it was generally not universal.

Take a look at the community contributions wiki for some more ideas. One of the members took our old profile and expanded upon it.

I am going to close this, as it is not an issue that I think is solvable in a general way.

If you disagree, I am open to dialogue :)
