### ISSUE TITLE
[Enhancement] Add support for .cue files in the Genesis folder. And consequently add MD+ Sega Genesis support

### ISSUE THREAD

**Issue by ThomasEricB** [dragoonDorise/EmuDeck#649]
I am placing the Patched MD+ Sega Genesis roms with all the files inside the folder but Retroarch refuses to read them correctly. The Genesis GX core supports the MD+ patches. Pretty sure what causes it is that retroarch is getting the .md rom instead of the .cue sheet file. 

More information here: https://www.zeldix.net/t2175-md-emulators-genesis-plus-gx-mame

**Comment by WingofaGriffin** [comment]
I'm not sure I follow, this seems like a Retroarch bug, not an Emudeck bug. If you open the cue file directly within Retroarch, it doesn't load?

**Comment by Godsbane** [comment]
We can enable cue in the Genesis parser, but it will pick up both the game and the cue file as separate entities.

Will need to test.

**Comment by ThomasEricB** [comment]
Thank you @Godsbane !
