### ISSUE TITLE
Yuzu directory config errors after recent SteamOS Update. 

### ISSUE THREAD

**Issue by opmuh** [dragoonDorise/EmuDeck#65]
My deck was caught in a bootloop from trying to update via the Desktop, after re-imaging was performed I reinstalled Emudeck using the new Easy mode. Upon opening Yuzu I found that it was pointing to the wrong game directory folder and the one configured didn't exist, as well as the Keys folder link not having been created in the deck/emulation/Bios/Yuzu directory.

**Comment by dragoonDorise** [comment]
hi @opmuh  @Godsbane , just tested installing both on SD card and Internal and the links to Yuzus folder were done without issue. I think the game directory is randomly created for each user so can't be automated, it's something every user has to configure if they want to run games using Yuzus instead of using Steam Rom Manager for instance.

**Comment by dragoonDorise** [comment]
@Godsbane who sent you that? the firmware folder is not a dot folder :/

**Comment by Godsbane** [comment]
I don't recall, it was in a log file in one of the issues we had open for something else.

**Comment by opmuh** [comment]
@dragoonDorise Interesting, so this is Yuzu issue not a Emudeck thing? I assumed Emudeck was configuring Yuzu to point it to the correct directories.

Steam Rom Manager wouldnt pull the games from the switch rom folder (I suppose because they are multiple files and in a subdirectory), which is why i went through Yuzu. EmulationStation sees them just fine and launches with no problems, but I can't get them to populate on the Rom Manager even after changing Parser settings.

**Comment by Godsbane** [comment]
Steam Rom manager definitely needs to the files in the base directory with the way it is configured.

**Comment by opmuh** [comment]
@Godsbane  understood, I'll figure out how to merge the dlc/update files into the NSP then.

**Comment by Godsbane** [comment]
hey @opmuh 

The piece i was addressing was :
> Steam Rom Manager wouldnt pull the games from the switch rom folder (I suppose because they are multiple files and in a subdirectory)
SRM looks in the rom folder for the various individual file types, and those files have to be in the root of the roms/switch directory. they can't be in subfolders.

I am not the most familiar with Yuzu, but mine are setup with the base game being in the roms directory, but the dlc / updates are installed in Yuzu.

Then the files updates and dlcs don't live with the rom itself, and the parser works as designed.

hope that helps.

**Comment by opmuh** [comment]
Thanks for the clarification. That makes sense, would be easier to reorganise the folder/files to the way you described.
________________________________

**Comment by Godsbane** [comment]
original issue fixed by @dragoonDorise here:

https://github.com/dragoonDorise/EmuDeck/blob/0636b0eea249177eb863489e38b10e880f55c87c/install.sh#L1045-L1046
