### ISSUE TITLE
Rewind option not activated in Retroarch

### ISSUE THREAD

**Issue by aldos973** [dragoonDorise/EmuDeck#651]
The Rewind option is not activated by default in Retroarch, whereas the Steam Deck can easily handle it for most systems. I find myself re-activating it manually but I think it should be on by default;

**Comment by Godsbane** [comment]
We enabled it, and lots of systems ran terribly, and ended up hotfixing it off - you can enable it for yourself as you mentioned.

it's possible we could enable it for some systems with overrides though. (or you can do this for the systems you want it on for)
