### ISSUE TITLE
Cloud saves should enforce maximum file size

### ISSUE THREAD

**Issue by Pobega** [dragoonDorise/EmuDeck#656]
It would be nice if cloud saves enforced maximum file sizes by default. It took me a while to realize my PCSX2 HDD (which is a sparse file and only uses 2GB on my filesystem) was being uploaded as a 40GB file in the background.

Ideally there would be some sane by default file size limit that could be disabled in case anyone actually wants to sync larger files.

Also note that it would need to be sparse file aware (`du --apparent-size`) since a file could be 100mb on Deck but 40+GB in GDrive (due to lack of support for sparse files)

**Comment by Godsbane** [comment]
I had no idea that people put the hdd in the saves location. 

Nonetheless it would be an rclone issue, I think.

Please look at the documentation there and if it can handle your restriction, we can look at adding it in general if it makes sense.

**Comment by Pobega** [comment]
Yeah, I've since moved my HDD out of the save location to stop it from syncing but it was an unfortunate surprise to find my Google Drive full, thankfully I wasn't on mobile data at the time (was traveling shortly after setting up my PS2 emulator.)

Browsing through the `rclone` docs it looks like [there is a --max-size filter option available](https://rclone.org/filtering/#max-size-don-t-transfer-any-file-larger-than-this)
