### ISSUE TITLE
Add GyroDSU as a Controller config to Dolphin

### ISSUE THREAD

**Issue by harkamalsr** [dragoonDorise/EmuDeck#659]
Currently I have to go into the settings and add every motion control manually for the Wii remote. It would be nice if there was a preset config for GyroDSU with everything already set up like in Cemu or Yuzu.

https://www.reddit.com/r/SteamDeck/comments/11dko6e/help_configuring_tilt_controls_for_dolphin_wii/
https://www.reddit.com/r/SteamDeck/comments/1155ics/motion_controls_on_dolphin_emulator/

For reference this has been mentioned on the Steam deck subreddit multiple times. A small quality of life fix like this could make life a lot easier

**Comment by Godsbane** [comment]
No, we removed them because it wasn't a great experience. We also have some profiles on the wiki for people who want stuff pre built.

**Comment by harkamalsr** [comment]
Ah, alright my bad, I didn't see that while looking around on the subreddit. Found it in the wiki like you said; thank you for sending me in the right direction

https://github.com/dragoonDorise/EmuDeck/wiki/community-creations#community-dolphin-profiles

Here's the link for anyone who's interested in Dolphin's gyro controls.

**Comment by Godsbane** [comment]
https://github.com/dragoonDorise/EmuDeck/wiki/community-creations#wiimote-motion-controls-with-nunchuck
I was just grabbing the link and you beat me to it.
