### ISSUE TITLE
EmuDeck Update Process Defaults to Installing CEMU Version 1.27.1 (pre-2.0 experimental version)

### ISSUE THREAD

**Issue by mannkeithc** [dragoonDorise/EmuDeck#660]
I have the latest version of EmuDeck installed on my Steam Deck running the latest version of Steam OS and Steam Client from the stable release channel.

Regardless of what version on CEMU I've installed via the "Update Your Emulator & Tools" function, viz 1.26.2f (stable), 1.27.1 (pre-2.0 experimental version) or 2.0-29 (current latest experiment version), when I subsequently re-run the original installer and select the "Quick" option to update the EmuDeck package to its latest iteration, CEMU version 1.27.1 is always installed. Why doesn't the Quick original installer process prompt you to select what version of CEMU you would like to install, as it does witj the "Update Your Emulator & Tools" function or the old EmuDeck update tool? Failing this, I would expect the EmuDeck installer / re-installer's default to be the CEMU stable release?

**Comment by Godsbane** [comment]
You can choose to not install / change things with custom.  That's it's function. Quick will always do the defaults.

The github Cemu 2.0 builds have taken a long time to be as stable as they are, and the current stable release of EmuDeck is from October. Forgive us for not updating it fast enough.

1.26.2 has enough linux issues that 1.27.1 is the better choice (like installation not working for larger dlcs / updates, wua support etc).

With the next release the the 2.0 builds will be the default. You'll also have an option to install the AppImage 

I'll be closing this as it's not actual issue, and your desires will be releazed with the next release. Hopefully this satisfies :)
