### ISSUE TITLE
EmulationStatoin on Install Guide

### ISSUE THREAD

**Issue by ehawman** [dragoonDorise/EmuDeck#661]
On the [website install guide](https://www.emudeck.com/#how_to_install), bullet #4 reads:

>Click on Preview, then Generate App list, wait for all the images to download and then click Save App list. The first time it could take some minutes. This will add all your games, emulators an EmulationStatoin DE to your Steam Library.

EmulationStatoin >> EmulationStation

**Comment by Godsbane** [comment]
@dragoonDorise website issue!

**Comment by dragoonDorise** [comment]
Fixed
