### ISSUE TITLE
Game and Watch fails with Error Code 2 after updating to EmulationStation-DE 2.0

### ISSUE THREAD

**Issue by iHazCode** [dragoonDorise/EmuDeck#662]
When launching any previously working Game and Watch titles from t he ROMs/game and watch directory now fail with Error Code 2 since updating to EmulationStation-DE 2.0 via the EmuDeck update tool. These same titles worked in previous versions of EmuDeck/EmulationStation.
Is this a known issue or is there a work around?

**Comment by Godsbane** [comment]
do you mean EmulationStation-DE 2.0?

**Comment by iHazCode** [comment]
Updated the question and title for posterity

**Comment by Godsbane** [comment]
I spoke with Leon - the dev of ES-DE. He actually changed the default from the gameandwatch RA core to Mame Standalone.

More information can be found here: https://gitlab.com/es-de/emulationstation-de/-/blob/master/USERGUIDE.md#lcd-handheld-games

You would need to change it back to the old core to continue as it was, or setup gameandwatch from the MAME set instead to use it for proper emulation. (read that link above where it's explained)

Let me know if you have trouble, but I'll be closing this :)

**Comment by iHazCode** [comment]
Thanks for the intel, I am trying to get this old behavior back with es_systems.cfg extension but not having a ton of luck. Do you happen to have a sample of the old config handy that would work with EmuDeck?

I am checking on the ES-DE GitHub but don’t see a relevant sample though I thought I had seen one there in the past? I may ping them to ask if they can help me figure out where that went.

Again thanks again for the information and all you do!

**Comment by Godsbane** [comment]
You simply change the setting in the UI :)

**Comment by iHazCode** [comment]
Oh geeze, I did take a peek but didn’t see it under the “Alternate Emulators” screens in EmulationStation. 

Guessing it’s a retro arch setting somewhere. I’ll take a look again and update this post (if I find the config you refer to) in hopes that it helps some other poor soul in the future.

You’re the best!

**Comment by iHazCode** [comment]
Disregard, it is in fact under the alternate emulators section in ES just like you said. I was apparently just too blind to see it. Thanks again for all of your help!

**Comment by iHazCode** [comment]
@Godsbane I know this is another topic, but I don’t know where best to ask would be so will start here.

The reason I updated EmuDeck to the ES-DE 2.0 was because I noticed the controls were not working for my Game & Watch titles. Unfortunately it seems ES-DE 2.0 did not solve t his problem either. Do you know if the steam deck inputs should work OOTB for the G&W titles via EmuDeck -> ES-DE?

I’m trying to determine if there is some configuration I need to supply manually or if something else went wrong that is unique to my setup.

**Comment by Godsbane** [comment]
I am not sure. I have never used game and watch. That said it's RetroArch, and everything RetroArch should work, since we provide it with a controller map.
