### ISSUE TITLE
suggestion: add the option between Ryujinx and Ryujinx LDN

### ISSUE THREAD

**Issue by chowder3907** [dragoonDorise/EmuDeck#664]
as it stands now, you have to separately download the LDN version of Ryujinx. It would be great to have it included either as an option in the installer or as a separate emulator to be installed alongside the stock version of Ryujinx

**Comment by Godsbane** [comment]
I am not sure how to do this, as the ldn version comes from Patreon right? Are there static links or an update feed?

**Comment by chowder3907** [comment]
the link is a direct download from patreon but they keep the link updated in their [LDN Local Wireless Guide](https://github.com/Ryujinx/Ryujinx/wiki/Multiplayer-(LDN-Local-Wireless)-Guide)

**Comment by chowder3907** [comment]
> I am not sure how to do this, as the ldn version comes from Patreon right? Are there static links or an update feed?

the link is a direct download from patreon but they keep the link updated in their [LDN Local Wireless Guide](https://github.com/Ryujinx/Ryujinx/wiki/Multiplayer-(LDN-Local-Wireless)-Guide)

**Comment by Godsbane** [comment]
Thanks, will use this info.
