### ISSUE TITLE
Steam Deck controls don't work in emulated games in desktop mode

### ISSUE THREAD

**Issue by mockdeep** [dragoonDorise/EmuDeck#672]
When I switch my Steam Deck to desktop mode the controls on the deck no longer work in emulated games. They still seem to work as expected in Steam games, though. I would normally prefer to play in gaming mode, but as far as I've found so far desktop mode is the only way I can script (and in particular, enforce a shutdown time).

**Comment by Godsbane** [comment]
That's because your deck uses desktop binds in desktop mode.

Hold start for 3 seconds to swap modes.
