### ISSUE TITLE
EmuDeck Hotkeys plugin is not working.

### ISSUE THREAD

**Issue by Kanadeforever** [dragoonDorise/EmuDeck#676]
After updating to Steam OS 3.4.6, plugins are not available and reloading or reinstalling does not work, as shown in the following picture:
![7_screenshots_20230406004215_1](https://user-images.githubusercontent.com/20147029/230148670-04929b6d-2f14-4ccf-bd09-cd772c9d99f4.jpg)

**Comment by Godsbane** [comment]
make sure to update decky to prerelease, then reboot. if that doesn't work let us know.

**Comment by Kanadeforever** [comment]
I updated to 2.6.5-pre2, but there is still no change.

**Comment by dragoonDorise** [comment]
@Kanadeforever are you on both SteamOS and Steam Client Main branch? I jus tested it on my deck and works fine

**Comment by Kanadeforever** [comment]
is the main branch

I later chose to reset the system and reinstalled it again to restore the usable state, very strange

**Comment by Kanadeforever** [comment]
> @Kanadeforever so now it works?

Yes, it works properly

**Comment by dragoonDorise** [comment]
Great!
