### ISSUE TITLE
DeckyControls unable to install

### ISSUE THREAD

**Issue by ElDingo424** [dragoonDorise/EmuDeck#677]
When inputting Sudo Password then clicking Install DeckyControls, I get a long error at the top with it giving a "cannot touch" and "Permission Denied Error"

end line reads:
\ntouch:cannot touch '/home/deck/.steam/steam/.cef-enable-remote-debugging':Permission Denied\n

Other plugin installs such as powertools work fine through the emudeck interface.

**Comment by Godsbane** [comment]
`sudo chown $USER:$USER ~/.steam/steam/.cef-enable-remote-debugging`

to fix your issue with permissions.

@dragoonDorise can you take a look at this for your plugin?

**Comment by dragoonDorise** [comment]
@Godsbane applied your fix both in beta and in main
