### ISSUE TITLE
Rom manager treating each bin file as separate game (PSX)

### ISSUE THREAD

**Issue by technic88** [dragoonDorise/EmuDeck#68]
PSX games with multi track bins are showing in the rom manager as duplicates of the same game. Also happens if the psx image is a single bin and cue showing as two games on the list.

**Comment by Godsbane** [comment]
Not sure how you would want multi disc games to be handled. I'd suggest using PBP for this type of game.

Bin / cue is similar. Unfortunately some people don't have the cue to match the bin, however the emulators can load the bin on their own. I will look into what logic can be used to make this nicer, though.

**Comment by dragoonDorise** [comment]
@technic88 I really recommend using chaman to convert your PS1 games to .CHD, it's a so much better format:
https://archive.org/details/chdman

Regarding .bin .cue, what is the best practice? To only scan the .bin or the .cue? are there any issues if you don't use both? @Godsbane what do you think?

**Comment by technic88** [comment]
Many redump projects for dreamcast, psx, etc use multitrack bin's for whatever reason. I'll look into converting to CHD instead, thanks @dragoonDorise!

**Comment by Godsbane** [comment]
I am not certain what is best. We could certainly just delete the bin scan, and require the user have a cue. You can remake the cue pretty easily, so i don't think it's a big ask.

I hadn't heard of the chd format before, but it seems better than pbp so i'll recommend that in the future.

**Comment by Godsbane** [comment]
As I dig more, chd still require an m3u for multiple discs. That won't solve something like a final fantasy showing up a bunch of times in SRM.

**Comment by dragoonDorise** [comment]
Fixed on V0.17.1!

**Comment by technic88** [comment]
Confirmed working with multi-track bin's  and standard bin/cue on my end. Thanks!
