### ISSUE TITLE
Cheatengine not working with cemu.

### ISSUE THREAD

**Issue by Conan179** [dragoonDorise/EmuDeck#681]
Good evening. I wanted to use a CT file in a Wiiu game, I start the cheat engine via steamlinkerlaunch, my problem is that Cemu doesn't appear in the ce process list, does anyone have a tip for me on how to do it, so that I can use the ct file can use?

**Comment by Godsbane** [comment]
Have never used those things. This doesn't seem like an EmuDeck issue, so I'll be closing it. Maybe come to the discord and we can poke around.
