### ISSUE TITLE
Proper Pro Controller config in Yuzu

### ISSUE THREAD

**Issue by d0k3** [dragoonDorise/EmuDeck#685]
The Steam Deck allows to connect Switch Pro Gamepads. If we turn off Steam Gamepad Support in Steam and change the Yuzu config to directly use the Pro Gamepad, motion control via Gamepad becomes available.

Now, what's the issue here? I'd rather not have to change my config every time I switch between TV and handheld play. By default the gamepad config is set to "any", which defaults to the first gamepad it finds, which is still a "Steam Gamepad" (note: even with Steam Gamepad support turned off).

A rather minor issue, because there's a workaround, and it may also not be an issue of Emu Deck, but rather Yuzu or Steam. Still, there may be something that could be done about it, like a gamepad priority list somewhere in config or a magic command line parameter that I'm not aware of.

**Comment by Godsbane** [comment]
If there is an automated way to do this I am not aware of it. We use the Steam Virtual Gamepads for everything, as that's what the deck abstracts controllers to.

The only "workaround" i can think of is two config files, or sed to update the identifier. Build in a config file swap before the execution?

I dunno, it's hacky, but may work.

**Comment by Godsbane** [comment]
I have some ideas on this front involving zenity and some config file edits in the script. I'm not sure yet how i'd tackle this fully, but i'll think about it some more.

**Comment by d0k3** [comment]
Thanks a lot for checking this! I'd be willing to test if you have something.
