### ISSUE TITLE
[FEATURE REQUEST] clearer progress bars during updates and installs

### ISSUE THREAD

**Issue by bpalmz** [dragoonDorise/EmuDeck#686]
Hi. I want to say thanks for developing this project and making emulation more accessible on the deck.

One thing I want to request if possible would be adding more robust progress bars, especially when updating appimages/binaries. Currently when updating multiple appimages the process just sort of starts in a separate program. There are minimal progress bars that happen for the individual updates, but they sort of "hang up" and don't give a good indication of where you are in the overall process.

Having a "parent" progress bar in EmuDeck indicating that the process has started, which binary is being updated, how many still need to be updated, etc. would be helpful. I know it's largely user error, but I think I semi-borked my installations by ending the update process prematurely.

**Comment by Godsbane** [comment]
assuming you mean the AppImage updater / flatpak updater, this is already done in beta.

**Comment by Godsbane** [comment]
beta released to main so this is all set!
