### ISSUE TITLE
Feature Request - Android games via Genymotion

### ISSUE THREAD

**Issue by upintheairsheep** [dragoonDorise/EmuDeck#687]
Android games can be emulated on Steam Deck via the Genymotion emulator. Genymotion is the most easiest and most popular way to emulate Android on the Steam Deck.

**Comment by upintheairsheep** [comment]
![D376D9D5-AC68-4ACD-A43C-A6A719FE2990](https://user-images.githubusercontent.com/43690204/232335635-90613b7a-f4e3-4bfc-883b-cc5dd3ca7604.png)
The title cover legitimately has Android on it

**Comment by WingofaGriffin** [comment]
Genymotion as of right now I believe requires disabling read only mode on SteamOS, which is beyond the scope of EmuDeck.

If this changes in the future, we are very open to adding this.
