### ISSUE TITLE
Feature Request: RokuOS Games via BrightScript Emulator

### ISSUE THREAD

**Issue by upintheairsheep** [dragoonDorise/EmuDeck#688]
https://github.com/lvcabral/brs-emu
https://github.com/lvcabral/brs-emu-app
https://lvcabral.com/brs/
https://www.reddit.com/r/SteamDeck/comments/znuk9l/roku_brightscript_emulator_pwa_prototype_on/ (Don’t make it like this)

**Comment by Godsbane** [comment]
I don't see there being much demand for this. I doubt I'd add this personally, but if someone does the work and submits a pull request, we can review it.

**Comment by upintheairsheep** [comment]
The man behind the emulator himself will be the one who will add this most likely, as he uses a steam deck and tested the two together out.

**Comment by Godsbane** [comment]
That sounds great.
