### ISSUE TITLE
Add Option to not overwrite / reset steam rom manager configuration

### ISSUE THREAD

**Issue by joyrider3774** [dragoonDorise/EmuDeck#69]
Hi,

I've made many changes to the steam rom manager config file (using SRM itselve). But there does not seem to be an option to keep my config changes, even when choosing no at installing SRM (as i had it downloaded manually) it will still try to configure the Steam rom manager overwriting / resetting any changes i / we did. Maybe also ask a question if we want steam rom manager config reconfigured / rewritten so we can keep our customn configs but still update all other parts using emudeck script

**Comment by dragoonDorise** [comment]
Can you tell me what did you customize? Maybe we can add that to our current configuration :)

**Comment by joyrider3774** [comment]
what i mainly added was defining local folders based on rom filename for Logo, Tall Images and Images (grid). I also removed the online image query value in certain parsers (so it only uses local media) i also added a system identifier flag to the image pool settings (so it does not show multiple (local) images if same game name is detected across systems) and lastly i only enabled parsers i use. first option could be handy if you mimic rom folders on either SD or internal (depending on what users chooses) and for each local media setting reference those folders with ${fileName} (not finaltitle) that way people can add their own local media comming from scrapers in those folders and steam rom manager will use them. I think if you don't clear online image query it will give preference to local media if found and otherwise search online (did not verify / test this i use local media only). removing the image query option is definatly not an option for you guys but it is for me (i don't want to loose time for it searching for online images or even mix them in with my local images hence i remove online image query value so it never searches online on steamgriddb).

Thanks for adding the option

**Comment by dragoonDorise** [comment]
I remember, I think we talk on either reddit or discord. We'll just wait for the next revision to get this new feature :) Closing this now!
