### ISSUE TITLE
enable GitHub Sponsors

### ISSUE THREAD

**Issue by electrovir** [dragoonDorise/EmuDeck#691]
I'd love to support this project through Github Sponsors. I'm sure there are other users who would be happy to use GitHub Sponsors to provide donations as well.

(I know there's a Patreon link on https://www.emudeck.com, but I don't use Patreon.)

**Comment by Godsbane** [comment]
Looks like dragoon enabled this. Guess I can close it

**Comment by electrovir** [comment]
The `Sponsor` button on this repo is just a link to Patreon 😕 but it looks like @dragoonDorise themself has sponsorship setup, so that works 🥳

**Comment by Godsbane** [comment]
Ahh my apologies, I was misled by the sponsor button.
