### ISSUE TITLE
Using real third-party Wiimotes in Dolphin doesn't work

### ISSUE THREAD

**Issue by roydbt** [dragoonDorise/EmuDeck#692]
I'm trying to connect 2 third-party Wiimotes to my Steam Deck, but so far without success
I have tried to:
1. Connect using the "Emulate the Wii's..." option, but the controllers don't want to connect
2. Connect using the "Passthrough a Bluetooth adapter" (while following [this official guide](https://web.archive.org/web/20230323071627/https://wiki.dolphin-emu.org/index.php?title=Bluetooth_Passthrough)). While the controllers seem to stop trying to sync, they get stuck lighting all 4 light-indicator-thingy (sometimes non of them stay up) until the batteries are removed.

**Comment by Godsbane** [comment]
https://github.com/dragoonDorise/EmuDeck/wiki/Dolphin#how-to-configure

keep in mind that we do not develop or package dolphin. the version in use comes from Flathub. If the above wiki doesn't work for you, that's about the end of what w can do.

for what it's worth i've tested using a real first party wii mote and it worked fine. The key is that you cannot pair it to steam.

Best of luck with it.
