### ISSUE TITLE
Nextcloud backups not currently working (new config)

### ISSUE THREAD

**Issue by CorneliousJD** [dragoonDorise/EmuDeck#693]
I setup the save data backup option and logged into NextCloud but I gives me an error of 
**Failed to create file system for "Emudeck-NextCloud:Emudeck/saves": read metadata failed: 405 Method Not Allowed**
**Script Terminating. Exit Code 1**

I've re-set this up multiple times but still no luck.

**Comment by Godsbane** [comment]
Show me your rclone.conf

Take out any secrets first.

https://data.example.com/remote.php/webdav/ is the format it expects

**Comment by CorneliousJD** [comment]
> Show me your rclone.conf
> 
> Take out any secrets first.
> 
> https://data.example.com/remote.php/webdav/ is the format it expects

Where does that file live? In my emudeck settings.sh the final line says 
rclone_provider=Emudeck-NextCloud 
but I don't know where the rclone.conf is on the filesystem.

**Comment by CorneliousJD** [comment]
> Show me your rclone.conf
> 
> Take out any secrets first.
> 
> https://data.example.com/remote.php/webdav/ is the format it expects

Found where it is.

[Emudeck-Nextcloud}
type = webdav
url = https://cloud.mydomain.com
user = MyUsername
pass = TOKEN
vendor = nextcloud

**Comment by CorneliousJD** [comment]
Changing URL to https://cloud.mydomain.com/remote.php/webdav/ gets further, but then errors with **red metadata failed: OAC\DAV\Connector\Sabre\Exception\PasswordLoginForbidden: 401 Unauthorized**

I do have 2FA enabled on my NextCloud instance, but I generated an apppassword to use for this script.

**Comment by CorneliousJD** [comment]
Ok the last error was due to me fat-fingering my app password when entering it. All is working now.

It may make sense to add the instructions when adding the nextcloud URL to include /remote.php/webdav/ to the end, that was the root cause of my issue. 

I'm now wondering if there's any way to customize the folder in my NextCloud that it gets saved to? I'd like to have it go to a custom folder (if possible). 

This can probably be closed now since this isn't actually an issue, if you have a chance to answer the above question that would be great.

**Comment by Godsbane** [comment]
That would be defined in the run job script in the rclone folder

**Comment by CorneliousJD** [comment]
> That would be defined in the run job script in the rclone folder

wonderful, thank you for the help and extra information. 

confirming the 15-min auto-backup is working  now too. thanks again!
