### ISSUE TITLE
Consider using rclone "bisync" function instead of copy [Feature Request]

### ISSUE THREAD

**Issue by Crono141** [dragoonDorise/EmuDeck#694]
Maybe I'm misunderstanding the purpose or the script used for the save backup rclone (rclone copy). But it seems that if I set this up on 2 different machines (Steam Deck and PC using emudeck), then whichever machine is set up last will have its files copy/overwrite what is already on the cloud.

The copy of rclone shipped with EmuDeck supports "bisync", which allows for 2 way sync with a cloud storage provider. To make this most like steam's cloud saves, it would make sense to use bisync instead of copy, as all machines set up with the save backup utility would share the same set of save files after a sync.

I suppose there is a risk that if 2 people are playing the same game on each machine, that there might be a save conflict, and one of the players will have their data replaced by the other's save, but I think this is a relatively unlikely scenario. Steam gets around this by locking play to a single machine at a time, but we don't have that ability with EmuDeck. Still, I think its worth the risk as this would be an edge case rarely encountered, in my opinion.

Thanks for your time.

**Comment by Godsbane** [comment]
Well, you can edit the scripts in any way you see fit.

We are open source and accept pull requests.

**Comment by dragoonDorise** [comment]
@Crono141 we are overhauling this for a future release, we will take it into consideration since we want to enable a proper sync between machines
