### ISSUE TITLE
several issues with emudeck

### ISSUE THREAD

**Issue by justalex95** [dragoonDorise/EmuDeck#695]
Tried emudeck and god damn does it break alot of emulators...

- emudecks vita3k just didnt function at all (vulkan backend=vita3k not starting up, games randomly freezing, failed installs for games very regularly, couldnt measure game performance because it couldnt load washing into a washing machine), downloaded the standalone vita3k, magically worked perfectly
- ryujinx had 10-15fps drops in mariokart, standalone worked immaculately running at 60 fps constant
- pcsx2 emulation frametimes were diabolically bad, and again were remedied by not using emudeck

and then after uninstalling, had to uninstall most of the folders myself by travelling to 12 different directories, steam rom manager did nothing when it was supposed to remove all the entries.

personal opinion but its never a good idea to mash this much code together while running emulators through nested apps, the very fact that emustation has a setting for how much memory it uses is a clue to why it shouldnt be running while your cpu is being choked by switch or vita emulation

and it seems like the steam rom manager isnt working properly either and may be a cause of the problems but who knows, is it emustation, steam rom manager, emudeck, the version that emudeck downloads, how emudeck updates emu's, the updates themselves... who knows, the performance dips are obviously running apps at the same time as hardcore emulation, call me old fashioned but, shouldnt you have less running when you hammer the hardware? revolutionary but it mjust might work.

anyway, thought I'd report on the many issues of emudeck to see if they can be fixed but currently I would only recommend emudeck to someone who knows their way around the linux ecosystem because troubleshooting becomes impossible because of how many moving parts there are and in the case of vita3k, it becomes a collection of code stubs through emudeck which for the emulators creator is a pretty big disservice to their hard work

**Comment by Godsbane** [comment]
It is standalone vita3k, literally downloaded from their GitHub.

Same with ryju and pcsx2.

I am not sure where your issues lie, but i am not sure why you would have such issues.

Steam rom manager does not run at the same time. It simply makes shortcuts. Es-de does, but suspends itself during Emulation.

I am going to close this.

Use the discord for support.
