### ISSUE TITLE
Add option to uninstall Homebrew Games

### ISSUE THREAD

**Issue by WedgeSparda** [dragoonDorise/EmuDeck#700]
Hi, I installed the Homebrew games provided some months ago but now I wanted to uninstall them and there is no option to do that. Running the Emudeck script again and selecting 'No' in the Homebrew Games step didn't work.

Is this intended? Is deleting the folder containing those roms the only way to remove them?

Thanks

**Comment by Godsbane** [comment]
there's an option to do this in the new release under quick settings.
