### ISSUE TITLE
Javascript EPIPE error

### ISSUE THREAD

**Issue by starkirby1** [dragoonDorise/EmuDeck#701]
I'm getting this error when I update EmuDeck. I tried uninstalling EmuDeck and reinstalling it but the error keeps coming back.

![Screenshot_20230425_144456](https://user-images.githubusercontent.com/131814380/234386851-6cf4a743-4c71-4795-9a76-21f0b6418808.jpg)

**Comment by Godsbane** [comment]
Yes, it's nothing. Just click ok.

It will go away with the next update of emudeck.

**Comment by starkirby1** [comment]
Thank you! Just wanted to make sure it.
