### ISSUE TITLE
Request Syncthing guide correction for YUZU 

### ISSUE THREAD

**Issue by Xarishark** [dragoonDorise/EmuDeck#705]
Was not sure where to post a request for a guide change. The recommended path for yuzu is a bad idea according to the devs when I talked with them on discord a while ago. 

They recommend to NOT sync the entire NAND folder and instead sync the profiles (su/avators) and saves folder (nand/user/saves) this way you can sync your info to your desktop too and it will fully work. If you sync the whole Nand folder there are many things that will sync to your desktop installation that should not!

I had a myriad of problems on my windows client when I synced the whole Nand folder that got fixed after I only synced the profiles and saves folder.

If your point is ONLY to backup to the cloud syncing the whole Nand is fine but people (like me) use syncthing to sync saves to their desktop for when they are home. 

![image](https://user-images.githubusercontent.com/21146743/234541668-b0cef7a9-47dd-401e-9a9b-c8194b66d6eb.png)

**Comment by Godsbane** [comment]
Hello!
If you refer to the guide on wiki, that is open to all to make changes. Please feel free to make the edits. It is community driven.

You will note our own backup script does not sync the whole nand, but only syncs the saves folders. I will add the other folder you mention as well.

**Comment by Xarishark** [comment]
Im sorry but what backup script are you referring to? Yeah I mean the wiki at the community creations tab.
as you can see here the script it has backups the whole nand ( if you are referring to that script)
![image](https://user-images.githubusercontent.com/21146743/234634357-bd74c92c-e37e-4410-8011-8c9cdef88a0e.png)

**Comment by saildot4k** [comment]
I wrote the sybcthing wiki. I tried only syncing saves, but was running into problems such as 2 different account id's, one on desktop 1 on deck. This way it is the same on both IF you setup one then sync the new Yuzu/Rujinx install. Also less hassle having to install DLC or updates. You do you, but I set it up so that it works as close to a cloud sync as possible between installed locations.

**Comment by saildot4k** [comment]
Also op you state `nand/user/saves` but the correction would be `nand/user/save`

You can do you way but I recommend an ignore pattern with the same nand path I documented:

//Ignore all
*
//Do not ignore
!/system/save/*/su/avators
!/user/save

**Comment by Godsbane** [comment]
I am going to close this as it's not really related actual EmuDeck (the script). Thank you for the information, however. And appreciate all the work on the wiki.
