### ISSUE TITLE
CEMU Not adding additional controllers for multiplayer

### ISSUE THREAD

**Issue by chowder3907** [dragoonDorise/EmuDeck#709]
When using the cemu appimage, I can open the emulator in steam and verify that both controllers are working, I can even play splitscreen. However when I open the rom directly through steam, only one player is detected. Switching controller order allows me to switch which controller is controlling the game, however I cannot do splitscreen.

**Comment by Godsbane** [comment]
Please validate the properties of the shortcut you are using and share here. My first guess is you are using the proton version in steam, not the appimage. (the default parser will setup proton shortcuts, not native, but there are two for Native as well)

**Comment by chowder3907** [comment]
Here's a picture of the shortcut properties, I did enable the parsers in emudeck and am running the game out of the cemu collection and not the cemu (proton) collection
![PXL_20230427_054713324](https://user-images.githubusercontent.com/63274355/234770848-b4ae520f-c582-4380-927a-6489f4cc921b.jpg)

**Comment by Godsbane** [comment]
yep -w tells us it's windows. Please use the other parser and try again.

**Comment by chowder3907** [comment]
Here's a video- It should be the right parser. You can see that the CEMU that opens first is the appimage due to the UI, it doesn't have the UI that CEMU has when being ran through proton. Multiplayer works there. When opening the game through the CEMU collection, I mash start on my controller and you can see it doesn't work and only one controller is recognized in the top left when the game starts. I removed all steam entries before running the new parsers so it's not anything residual from my old emudeck setup.

https://user-images.githubusercontent.com/63274355/234772796-75da7543-46e9-4473-b892-3ccb5df78318.mp4

**Comment by Godsbane** [comment]
As i mentioned -w makes it run with proton; please use the second set of parsers and try one more time.

**Comment by chowder3907** [comment]
I deleted all the entries and re-ran the parsers. The problem persists: Here you can see that I have removed all entries again. There are no more minecraft entries at least, which can be seen here. 
Here, you can see that both parsers are enabled. 
![PXL_20230427_060852700](https://user-images.githubusercontent.com/63274355/234775962-2d28fcdd-96d1-43c5-982f-ff906896ee64.jpg)

![PXL_20230427_060816358](https://user-images.githubusercontent.com/63274355/234775823-67d2599d-dc68-4444-bf53-ba1a616c8760.jpg)
Here, you can see that the parsers are listed correctly within steam rom manager
![PXL_20230427_061257745](https://user-images.githubusercontent.com/63274355/234775896-1e3ac86d-750e-41f5-b25f-200a8d81d843.jpg)
![PXL_20230427_061252709](https://user-images.githubusercontent.com/63274355/234775898-85b3429c-0572-4117-adcf-163451ddfacc.jpg)
And finally, you can see that the wrong shortcut is generated inside of steam. This is again within the CEMU folder and not the CEMU proton folder
![PXL_20230427_061424984](https://user-images.githubusercontent.com/63274355/234776081-ca282836-f529-42ea-9e90-7eb736dd727d.jpg)


Do I need to re-run without having both native and proton parsers? Do I just need to change the shortcut to be correct?

**Comment by Godsbane** [comment]
yes please run without the Proton ones enabled. I think we uncovered an issue with AppId's being the same.

**Comment by chowder3907** [comment]
Rerunning with just the native parser and changing the shortcut manually both worked. Thanks :) glad I could help uncover something

**Comment by chowder3907** [comment]
> and i just hotfixed it too - If you go to manage emulators --> Steam rom manager --> reset config you should be able to parse both at the same time.
> 
> please validate and i'll close this issue.

It is now working and parsing correctly, validated
