### ISSUE TITLE
Revamp controls

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#71]
I would like to create more / revamp the controller templates.

Moskeeto, in our discord, has come up with a really nice left touchpad quick menu setup. I'd like to propose we build this for each emulator for emulation hotkeys.

I'd also like to standarize the right touchpad as mouse instead of joystick.

**Comment by dragoonDorise** [comment]
We need to use Steam Input for that, right?

**Comment by Godsbane** [comment]
yes, it would be a combo of emulator binds, and steam input templates.

**Comment by dragoonDorise** [comment]
We could do that for the current ESDE template, sure.

**Comment by dragoonDorise** [comment]
Already done for EmuDeck 2
