### ISSUE TITLE
SRM won't open from the updated emudeck installation 

### ISSUE THREAD

**Issue by Vervaticus** [dragoonDorise/EmuDeck#711]
![cf14880b-2959-4583-8d0e-e62ba2c70024.jpg](https://user-images.githubusercontent.com/120331409/234774865-b475070b-2a31-46c2-a935-a2887c1ff0c7.jpg)

![904c2764-8b71-4cbf-b72a-4d01472a7521.jpg](https://user-images.githubusercontent.com/120331409/234774893-05022616-9885-4422-85a8-f8d27234e07b.jpg)

![406f55d3-0ffe-4318-a5af-71001096e9ee.jpg](https://user-images.githubusercontent.com/120331409/234774915-462cdfd9-31eb-4c8b-af46-8236baaab292.jpg)

**Comment by Godsbane** [comment]
@dragoonDorise we need to troubleshoot this. i have no idea of what the issue could be at this point. user validated the appimage is in the correct spot.

**Comment by justauselessaccounes** [comment]
Had this happen to both my friends and my deck.  Can't get SRM open anymore to change some settings on xenia.  Stuck until it's fixed.

**Comment by Godsbane** [comment]
you can't open it normally? (app list / appimage?)

**Comment by dragoonDorise** [comment]
@justauselessaccounes  do you mean that you can't edit the parsers? Change the theme in settings to Deck or Classic
