### ISSUE TITLE
Parsec Gaming Mode shortcut not launching with new EmuDeck Update

### ISSUE THREAD

**Issue by MXNPD** [dragoonDorise/EmuDeck#713]
After the newest EmuDeck update which added the ability for us to add Parsec, Moonlight, Discord, amount other apps along with emulators, it seems trying to open parsec, just doesn't work. I click play yet nothing appears to happen at all, just brings me back to the launch screen.

**Comment by Godsbane** [comment]
![image](https://user-images.githubusercontent.com/1683513/234785498-fd1af7e0-063f-4080-879c-af984706ac6e.png)
Mine's working fine.

can you validate parsec works in desktop mode?

**Comment by MXNPD** [comment]
> 

Launching the app itself in desktop mode works fine, launching it from steam via desktop mode or via gaming mode doesn't appear to do anything. Seems like it attempts to launch it, but fails.

**Comment by Godsbane** [comment]
can you share the properties of the shortcut in steam please?

**Comment by MXNPD** [comment]
> can you share the properties of the shortcut in steam please?

Sure thing, the "parsec.sh" file that steam seems to be referencing has this code content 

`#!/bin/bash
cd ~/.local/share/flatpak/app/com.parsecgaming.parsec/current/active/files/bin
/usr/bin/flatpak run --branch=stable --arch=x86_64 --file-forwarding com.parsecgaming.parsec @@u @@`

The "Target" field in the properties of the steam shortcut has the following 
`"/run/media/mmcblk0p1/Emulation/roms/remoteplay/Parsec.sh"`

And the "Start In" field has the following 
`/run/media/mmcblk0p1/Emulation/roms/remoteplay`

**Comment by Godsbane** [comment]
Can you run the parsec script and let me know if it works from there? This all looks fine.

@KingIzzymon any ideas

**Comment by KingIzzymon** [comment]
I'll take a peak at this over the weekend. Been a while since I touched this project, but I remember Parsec being funky. I'll respond again once I have a look :)

**Comment by MXNPD** [comment]
> Can you run the parsec script and let me know if it works from there? This all looks fine.
> 
> @KingIzzymon any ideas

Attempting to directly launch the parsec.sh file within the Dolphin file browser appears to do nothing as well, nothing opens

**Comment by KingIzzymon** [comment]
@MXNPD On your deck, go to desktop mode and open a terminal, then run that script from inside the terminal so we can see the script execution line-by-line. That will give me more details as to what's crashing. Please post the results here.

**Comment by MXNPD** [comment]
> @MXNPD On your deck, go to desktop mode and open a terminal, then run that script from inside the terminal so we can see the script execution line-by-line. That will give me more details as to what's crashing. Please post the results here.

Executing the script via the terminal indicates that when trying to navigate to /home/deck/.local/share/flatpack/app/com.parsecgaming.parsec/current/active/files/bin no such file or directory exists. Manually navigating through that directory tree it seems that there is no /app directory within the /flatpack directory. Showing only /db /overrides /repo and a hidden file of .changed. I went to go and find where my version of parsec is installed in the system, I had installed it via flatpack originally. Seems like its directory is /var/lib/flatpack/app/com.parsecgaming.parsec/current/active/export/share/applications

I then changed the directory the script navigates to and now it says that /usr/binc/flatpack does not exist either. I then went to go and find that, and it does not exist, so I changed binc to just bin as in that directory there is a flatpack file. Once I changed that the script now appears to work in desktop mode. Launching through Steam now properly works as well. In gaming mode it seems to work now as well now.

**Comment by Godsbane** [comment]
I know what's happening here. Since the user already had the system flatpak, when the user flatpak was requested to be installed it was skipped, so this path was not correct. It's all aliasing of the same things, so we can refine this a bit.

@KingIzzymon we'll prob need to account for the possibility of either one, or force the user one to install, and the system one uninstalled. This is because Discover does install things as system by default.

**Comment by KingIzzymon** [comment]
That makes sense. I'll have to make that change applied to chiaki and moonlight too then. It's honestly surprising that Steam still hasn't changed Discover to only be at the user level... I'll have a PR submitted before the end of the weekend.

**Comment by Godsbane** [comment]
We may need to do some testing, but sounds good to me.

**Comment by KingIzzymon** [comment]
Excellent troubleshooting work @MXNPD ! I appreciate your efforts and sounds like you reverse engineered it to get it to work from the system level directory. I just submitted a fix for testing and, if its applied to the main branch, it will overwrite your altered script. Id recommend making a copy of your "Parsec.sh" and saving it just in case.
