### ISSUE TITLE
Cemu Appimage not having correct root folder set

### ISSUE THREAD

**Issue by chowder3907** [dragoonDorise/EmuDeck#714]
When done through WINE, Cemu correctly identifies /run/media/mmcblk0p1/Emulation/roms/wiiu/ as the Cemu root folder. This can be easily be verified by opening WINE Cemu and going to file -> Open Cemu folder. When opening the appimage, I noticed my online functionality was not working. The appimage identifies $HOME/.local/share/Cemu as the root folder, and I needed to copy the online files there. This can again be verified with file -> Open Cemu folder.

**Comment by Godsbane** [comment]
that is the correct root folder for the appimage.

**Comment by chowder3907** [comment]
> that is the correct root folder for the appimage.

Ah okay, I just would've expected it to stay on the SD card like most things. Though now that I dig deeper, I don't see a place where that location can be configured

**Comment by Godsbane** [comment]
yeah, no way that i know of : /

**Comment by chowder3907** [comment]
Would it be worth adding a pop-up asking the user if they want to copy the files from the SD card over to the correct root folder when they press the "install appimage" button? The only super important thing (for my case at least) were the online otp.bin and seeprom.bin files, running a copy operation for those two files wouldn't be hard. Something like "Do you want to copy your online files from the SD card?" would at least put in the user's head that if they say no, they'll have to put the online files in manually.

**Comment by Godsbane** [comment]
not a bad idea - can you open this as a feature request?

**Comment by chowder3907** [comment]
> not a bad idea - can you open this as a feature request?

Absolutely
