### ISSUE TITLE
Directory for the Xbox 360 roms in EmulationStation is one directory above

### ISSUE THREAD

**Issue by tegaidogun** [dragoonDorise/EmuDeck#715]
I was wondering if there was a way I could modify the directory in EmulationSTation for Xbox 360 ROMS, it redirects to the roms folder but not to where the ISO files are stored.

to `...\roms\xbox360` instead of `...\roms\xbox360\roms`

**Comment by Godsbane** [comment]
Not sure I understand. Put the iso files in the roms folder? That's what it's for.

**Comment by Godsbane** [comment]
We figured this out. Once you put a game in the folder it will be correct. If you don't want to put a game in the folder, and want to hide xbox360 in ES-DE add noload.txt to the folder.

**Comment by tegaidogun** [comment]
I already had 3 games in the folder and it is still doing that.

**Comment by Godsbane** [comment]
I'm not sure, rereading your original post it still sounds like you are using the wrong folder.

Isos go in the roms folder inside xbox360, not xbox360 directly.

**Comment by tegaidogun** [comment]
These are images from my Steam Deck at the current moment:

![20230505_151156](https://user-images.githubusercontent.com/63559796/236554770-70aeb4d5-e0c1-47ca-bc2f-1ddbd712e741.jpg)
![20230505_151133](https://user-images.githubusercontent.com/63559796/236554789-b4cc8e22-378f-4bbb-834e-4d937cafd882.jpg)

**Comment by Godsbane** [comment]
No that's it. Try deleting the license file.

**Comment by tegaidogun** [comment]
I have tried what you said, but I'm still getting the same issues. Is there anything I can do?

![20230506_005028](https://user-images.githubusercontent.com/63559796/236600770-d72cea5f-a298-48d9-85c1-cd17e664d9b8.jpg)
![20230506_005302](https://user-images.githubusercontent.com/63559796/236600775-4ae19f57-c997-4f26-b314-70ebc0839a30.jpg)
![20230506_005252](https://user-images.githubusercontent.com/63559796/236600768-7308c5e0-91a8-4e3f-8a38-d035f3df98d9.jpg)

**Comment by Godsbane** [comment]
This should just work.

Can you upload the file: `/home/deck/.emulationstation/custom_systems/es_systems.xml` Let's make sure it's correct.

**Comment by tegaidogun** [comment]
Sorry for the late reply :+1: 
```
?xml version="1.0"?>
<systemList>
  <system>
    <name>wiiu</name>
    <fullname>Nintendo Wii U</fullname>
    <path>%ROMPATH%/wiiu/roms</path>
    <extension>.rpx .RPX .wud .WUD .wux .WUX .elf .ELF .iso .ISO .wad .WAD .wua .WUA</extension>
    <command label="Cemu (Proton)">/usr/bin/bash /run/media/mmcblk0p1/Emulation/tools/launchers/cemu.sh -f -g z:%ROM%</command>
    <platform>wiiu</platform>
    <theme>wiiu</theme>
  </system>
</systemList>
```

**Comment by Godsbane** [comment]
Well, this is missing xenia AND the new cemu system as well, which indicates you haven't updated.

You need to update emudeck.

Either use a custom reset ( this is the old custom update button)

Or go to manage Emulators, then pick emulation station and hit reinstall/update.

Go to Xenia and hit reinstall / update

**Comment by tegaidogun** [comment]
Thank you!

**Comment by tegaidogun** [comment]
Upon resetting installations again, it finally worked! Thank you!
