### ISSUE TITLE
Automatic copying of important files to the root directory of the Cemu appimage [Feature Request]

### ISSUE THREAD

**Issue by chowder3907** [dragoonDorise/EmuDeck#716]
Currently upon installation of the Cemu appimage, the user must copy online files from their SD card do $HOME/.local/share/Cemu, the root directory for the appimage, manually. When the user goes out of their way to install the appimage, the option to copy important files to the right directory should be given. The files that come to mind are the online files, otp.bin and seeprom.bin . A small popup asking if the user wants to copy their online files to the right location would at least serve to tell the user that it's something they would have to do, and that information being readily available would allow for easier support when people inevitably ask about it. A small "copy online files" button within the emulator config could work too. As it is, they work on the root of the SD card like one would expect when running through wine, but not with the appimage. This would make the experience more seamless.

**Comment by WingofaGriffin** [comment]
This is the mlc01 folder right? We already provide a link to that folder in the Emulation/storage folder: https://github.com/dragoonDorise/EmuDeck/blob/main/functions/EmuScripts/emuDeckCemuNative.sh#L178

We even check if the Windows one already exists for migrating: https://github.com/dragoonDorise/EmuDeck/blob/main/functions/EmuScripts/emuDeckCemuNative.sh#L37

It's possible there's a bug here, @Godsbane I see you wrote this function.

**Comment by Godsbane** [comment]
the mlc01 is shared yes - however there are additional files which go with the cemu executable on windows (otp, seeprom, keys.txt at least)
we should (or at least _could_) symlink them? this way these three important files only have to be put in one location.

the other option is migration / duplication during installation. They are very small.

**Comment by DBSimoes** [comment]
Mods and shaders seem to be separate at the moment too. Not sure if this is by design

**Comment by Godsbane** [comment]
Yes they are completely separate, and will likely stay that way. We hope to eventually get away from the proton version altogether.
