### ISSUE TITLE
New SRM Excluded Apps

### ISSUE THREAD

**Issue by T-bone25** [dragoonDorise/EmuDeck#718]
Anyone know how to find excluded apps in the new steam rom manager? I accidentally excluded some apps I didn’t want to and would like to un-exclude them but I can’t find them anywhere in SRM now. I tried resetting the configuration and uninstalling and reinstalling SRM too and they’re still completely gone.

**Comment by Godsbane** [comment]
You need to change to the deck theme to access the exception manager.

We've discussed this with the developer, and will be including the exception manager in the emudeck theme with the next srm update.

**Comment by T-bone25** [comment]
Thanks so much! You all are awesome!!

**Comment by dragoonDorise** [comment]
SRM already deployed this
