### ISSUE TITLE
Flatpak Permissions Automation

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#72]
We should automate the setting for rpcs3.

Especially for SD card installs, we should add the sd card path to the flatpak permissions.

https://docs.flatpak.org/en/latest/sandbox-permissions.html

I haven't actually read through how to do this yet, still in idea phase.

I'd want to prompt the user with a question about it, rather than adusting their permissions without them knowing.

**Comment by dragoonDorise** [comment]
I've tried, you need to use sudo to change that, I have no idea how flatseal does it with no sudo

**Comment by Godsbane** [comment]
`flatpak override org.citra_emu.citra --filesystem=host --user`

looks like the --user flag makes it work without sudo, as it only overrides for deck, instead of the system. but that's good enough i think.

**Comment by popsUlfr** [comment]
Yeah I'm also using flatpak user override for bottles for cxbx-reloaded. It's just like flatseal does it anyway.

**Comment by dragoonDorise** [comment]
All done on v17
