### ISSUE TITLE
Add PC-FX Parser

### ISSUE THREAD

**Issue by KusanagiShiro** [dragoonDorise/EmuDeck#721]
User's Glob: @(pcfx)/**/${title}@(.7z|.7Z|.bin|.BIN|.cue|.CUE|.ccd|.CCD|.toc|.TOC|.chd|.CHD|.zip|.ZIP)
Command Line: run org.libretro.RetroArch -L ${os:win|cores|${os:mac|${racores}|${os:linux|${racores}}}}${/}mednafen_pcfx_libretro.${os:win|dll|${os:mac|dylib|${os:linux|so}}} "${filePath}"

**Comment by WingofaGriffin** [comment]
This is definitely doable, and frankly if you want, you can try your hand at making a PR yourself in https://github.com/dragoonDorise/EmuDeck/blob/main/configs/steam-rom-manager/userData/userConfigurations.json

Remember to base it to beta, and to use a unique parserId if you do decide to.
