### ISSUE TITLE
Add Nintendo Virtual Boy parser

### ISSUE THREAD

**Issue by KusanagiShiro** [dragoonDorise/EmuDeck#722]
Userglob: @(virtualboy)/**/${title}@(7z|.7Z|.bin|.BIN|.vb|.VB|.vboy|.VBOY|.zip|.ZIP)
Command Line: run org.libretro.RetroArch -L ${os:win|cores|${os:mac|${racores}|${os:linux|${racores}}}}${/}mednafen_vb_libretro.so.${os:win|dll|${os:mac|dylib|${os:linux|so}}} "${filePath}"

**Comment by WingofaGriffin** [comment]
This is definitely doable, and frankly if you want, you can try your hand at making a PR yourself in https://github.com/dragoonDorise/EmuDeck/blob/main/configs/steam-rom-manager/userData/userConfigurations.json

Remember to base it to beta, and to use a unique parserId if you do decide to.
