### ISSUE TITLE
2.1.0 Some Systems Now Save and Load from Content Directory

### ISSUE THREAD

**Issue by brandflake11** [dragoonDorise/EmuDeck#725]
Hello all,
As of the latest EmuDeck 2.1.0 update on the Steam Deck, some retroarch systems are now saving and loading (including saveram and savestates) to the content directory. I have noticed this using "Retroarch - Snes9x" and "Retroarch - Mupen64", but strangely enough, it's not happening with "Retroarch - Flycast." 

When loading the game, it will appear as if your save file and or savestate, if you have savestate autoloading, doesn't load. This is because retroarch is looking at the directory of where your rom is located for the loading and saving of the game. You can confirm this by navigating to the roms directory and seeing that a .srm and .state file is created.

I have checked the configuration file for the retroarch flatpak and the option savefiles_in_content_dir is equal to "false." When loading Flycast and Snes9x, retroarch reports that the config file is the same. 

How can this be? Anyways, I thought I would report this as maybe others are having this problem. I have not found a fix for this. Is there anything I can do to fix this? Thank you for your help!

**Comment by Godsbane** [comment]
certainly we have never enabled this setting - so it doesn't make sense to me either.

please upload your retroarch config file and then

Zip up this folder ~/.var/app/org.libretro.RetroArch/config/retroarch/config and upload it as well.

**Comment by brandflake11** [comment]
I apologize for opening this issue, it seems that retroarch fixed itself after a steam deck reboot. I hadn't rebooted after updating emudeck when filing this issue.

I can still upload these files if you are interested, just let me know. I will close this issue since a reboot was the fix.

**Comment by Godsbane** [comment]
If you are reasonably sure it's not a config issue, I would not worry about it.

If you ever replicate it feel free to reopen and upload.
