### ISSUE TITLE
RPCS3 shortcuts Steam Rom Manager stuck loading with Steam Logo

### ISSUE THREAD

**Issue by jesusitoshiny** [dragoonDorise/EmuDeck#730]
I bought a new deck and installed emudeck 2.1, the rpcs3 games work perfectly from the emulator but from the shortcuts created with the new steam rom manager I can't load them. Can someone help me with this? Im probably not the only one whit this problem…

Video: https://www.reddit.com/r/SteamDeck/comments/133w1kf/rpcs3_shortcuts_steam_rom_manager_stuck_loading/

**Comment by Godsbane** [comment]
`flatpak update --commit=5e4c8f25c5c274f071ff35ee417961253b2f8105cfafa89c9ef10247a8248579 net.rpcs3.RPCS3`

this is a small rollback of the application. Should solve it until an update fixes it.

**Comment by jesusitoshiny** [comment]
Its WOKS! Youre the best! OMG After 2 days of going crazy, thanks to you I have been able to fix the bug, I hope they fix it natively in emudeck.

**Comment by Godsbane** [comment]
it's not an EmuDeck issue, we can do nothing about it.
