### ISSUE TITLE
Add Chiaki4deck

### ISSUE THREAD

**Issue by ThaMighty90** [dragoonDorise/EmuDeck#734]
Hello EmuDeck Team,

i really like the new inclusion of RemotePlay Clients but i would love to see chiaki4deck as well as an option because it is just more optimisied to run on the Deck than chiaki. For example chiaki4deck has stretch/zoom options and a key combo to cleanly disconnect and shut down the app. Is there any possible way you can add it as well?

**Comment by extremesecrecy** [comment]
+ The Chiaki project is in maintenance mode and has not updated in a little while.

**Comment by ThaMighty90** [comment]
another huge bonus is that it has script support to make a shortcut that automatically connects to your PS4/PS5. So emudeck could assist in adding said shortcut as a steam game. Also chiaki4deck is still maintained and adds some nice features like gyro and rumble support. it even supports adaptive triggers when you connect a ps5 controller.
