### ISSUE TITLE
Feature Request: Implementation of Switch Army Knife (SAK) and  Wii U USB Helpe

### ISSUE THREAD

**Issue by mateowoetam** [dragoonDorise/EmuDeck#740]
I recently tried to mingle with merging and updating Yuzu and Cemu save files. I was introduced to [Switch Army Knife](https://github.com/dezem/SAK) as well as [Wii U USB Helper](https://github.com/FailedShack/USBHelperInstaller), which only work on Windows; I know they could technically work with Wine, but I couldn't get them to work, I hope they could be added in the new update of EmuDeck to make updating games easier.

**Comment by Godsbane** [comment]
absolutely not these are piracy tools. I will delete this post.
