### ISSUE TITLE
Allow selective compression of roms

### ISSUE THREAD

**Issue by rybandrei2014** [dragoonDorise/EmuDeck#743]
Is it possible to implement user selection of roms that will be converted by compression tool? Because sometimes you want to skip compression for some roms that may have compatibility issues due to compression.

**Comment by Godsbane** [comment]
We introduced the ability to choose a specific file for compression with the latest release.

What doesn't work, btw?

**Comment by dragoon000320** [comment]
@Godsbane yeah I know, command line interface allows you to choose one at the time file in file manager. It is not very comfortable and fast. It would be nice, if Emudeck offered some UI that will traverse rom directories to present list of possible compression targets with possibility to select several files at once. Toggleable option to keep the initial file/s after compression would be handy as well.

**Comment by Godsbane** [comment]
I meant compatibility wise. you mention sometimes wanting to skip? what would you want to skip?

**Comment by dragoonDorise** [comment]
Hi @dragoon000320 , can we close this issue?

**Comment by dragoon000320** [comment]
Hi @Godsbane, @dragoonDorise sorry for keeping you waiting... Sometimes I just want to skip some roms during compression to not possibly mess things up, and that's why I posted this feature request. Of course you are free to close it, if there are no plans to add such functionality.
