### ISSUE TITLE
Setting to swap controller layout for Nintendo emus to match the button instead of the orientation

### ISSUE THREAD

**Issue by PascalLeroi** [dragoonDorise/EmuDeck#746]
I've noticed that I prefer to have to click on the right button instead of the right original controller button.
So for most Nintendo emulators this means that the settings now have you click on B to Accept as A=B and X=Y
I started changing this setting for myself, especially for Cemu. As with the standard settings, I would have to press B to click A while using a real Wii U Pro controller. Which does not make all that much sense to me :P 
Then I noticed that some users on discord asking for some kind of setting. And I though why not have more options as it seems that there are two camps here :) 

I don't know how to program such button or even all the settings for the emulators for that matter. 
But I managed to have a few ready and thought it could be shared. 
[ButtonMatchButton.zip](https://github.com/dragoonDorise/EmuDeck/files/11423805/ButtonMatchButton.zip)

I added configs for Dolphin(GameCube), Citra and Cemu (proton, as I don't know where to find the controller profile xmls for the AppImage)

Would this option "Use Nintendo Orientation or use Button Matches Button" be something that could be implemented?

**Comment by dragoonDorise** [comment]
Hi @PascalLeroi we have this planned, to add a xBox or Nintendo Layout for all the emus, so it will come

**Comment by PascalLeroi** [comment]
Awesome! Thanks

**Comment by dragoonDorise** [comment]
This was added in the last update :)
