### ISSUE TITLE
[Feature Request] Integer scaling

### ISSUE THREAD

**Issue by puddydoo** [dragoonDorise/EmuDeck#747]
I dislike the fact that integer scaling is turned off by default and has to be enabled in the individual emulators, it should be something that can be automatically enabled in emudeck settings like with the crt filter.

**Comment by dragoonDorise** [comment]
Hi @puddydoo we use the normal4X filter to emulate Integer Scaling so you get the max height of the screen used but you still see "perfect" pixels. Have you see an issue with this on some particular game?

**Comment by puddydoo** [comment]
It's pretty good, but it's not quite as perfect as when integer scaling is turned on. NDS games look particularly bad (particularly their text) in views that show multiple screens at once.

Although on DS retroarch, integer scaling is just broken when I turn it on.
