### ISSUE TITLE
Bilinear Filtering + Normal4x not in all RA cores? Also, an alternative?

### ISSUE THREAD

**Issue by MushGuyDS** [dragoonDorise/EmuDeck#748]
Hello, I just noticed that the Final Burn Neo core does not use the Bilinear Filtering + Normal4x filter setting as the other cores use, though MAME curiously does. Is this an oversight? If so, can it be fixed in a future update? Also, would it be possible that instead of Normal4x, Retroarch could use the sharp-bilinear-simple shader for screen interpolation (Bilinear Filtering not needed)? The results will be identical, but with the difference that [the integer pre-scale is done automatically](https://gamingprojects.wordpress.com/2017/12/03/reducing-pixel-blur-and-distortion/) (2x, 3x, 4x, etc.) instead of locked at 4x, which is great if you hook it up to a monitor with different resolutions, and it can be used as a global setting to be used on all cores.

**Comment by dragoonDorise** [comment]
@MushGuyDS We do use normal4x for FBNEO, but only as long as you don't enable the CRT Shaders on EmuDeck, that will disable the Normal4x filter. We will test sharp-bilinear-simple and see how it goes!
