### ISSUE TITLE
installs with sudo password fail when having special character at beginning

### ISSUE THREAD

**Issue by ThaMighty90** [dragoonDorise/EmuDeck#749]
Hello EmuDeck-Team,

i noticed something strange while trying to install EmuControls.
My sudo password starts with a $ and when I enter it and hit install, the Konsole shows that I didn't provide a sudo password. I was curious so i changed it to something else and it instantly worked.

**Comment by Godsbane** [comment]
I hate passwords.

@dragoonDorise

**Comment by WingofaGriffin** [comment]
We probably just need to sanitize the inputs better lol. Shell is treating it as an environment variable.

**Comment by Godsbane** [comment]
Yes, of course. I'm just annoyed. Went through a lot of this already.

Will need testing to see if it can be relocated and fixed of course.

**Comment by dragoonDorise** [comment]
@Godsbane not this again lol

**Comment by FearNaBoinne** [comment]
Not just at the beginning... Any passwords with special characters ($,!) break... I am hesitant to change my password in case I forget I changed it, and what I changed it into...

Try `steampa$$!` (I tested the scripts with that, and it broke just as bad as with my real password, stating no password was provided for sudo!)
