### ISSUE TITLE
Steam ROM Manager only showing EmulationStation

### ISSUE THREAD

**Issue by mmclellan93** [dragoonDorise/EmuDeck#750]
When I run the Steam ROM Manager, if I have everything selected, then press Preview, only the EmulationStation shows up. 

It used to be that all the consoles and games I had selected would show up. Now, none of them do, and only EmulationStation shows up.

If I unselect EmulationStationDE then press Preview, nothing happens, and I get a message that says "Please shutdown Steam if it is running".

**Comment by Godsbane** [comment]
Please come to the discord for support.

**Comment by mmclellan93** [comment]
I joined the discord and whenever I try to post a message on any channel I
get the following message:

 “Your message could not be delivered. This is usually because you don't
share a server with the recipient or the recipient is only accepting direct
messages from friends.”

Do you know what I can do to be able to ask my question on the discord?

**Comment by Godsbane** [comment]
I've never heard of such a thing. DM me.  livedeht#9111
