### ISSUE TITLE
Add Emulator Version to Desktop Mode Config/Platform Page

### ISSUE THREAD

**Issue by apiweb** [dragoonDorise/EmuDeck#752]
**Description:** It would be helpful to display the Emulator version on the Manager or Platform page in EmuDeck. It is difficult to identify what version of the Emulator we are using. Adding the version number to these pages would make it easier for users to track which version they are using.

**Suggested Solution:** Display the Emulator version number on the Manager or Platform page, either in a prominent location. This would make it easy to quickly identify which version of the Emulator is currently in use.

**Expected Behavior:** Users should be able to see the Emulator version number on the Desktop Mode or each Platform page without digging through settings or configuration files.

Thank you for considering this feature request. Let me know if you need any additional information or clarification.

**Comment by dragoonDorise** [comment]
@Godsbane can we do a JSON with the current emu version installed and use that to show updates for the emulators like we do with the configs?
