### ISSUE TITLE
USB Transfer Wizard – Remove hidden dot-files created by macOS

### ISSUE THREAD

**Issue by nilsbyte** [dragoonDorise/EmuDeck#754]
When copying over ROMs to a USB drive with macOS to the folder structure that EmuDeck created before, macOS also copies the typical macOS resource files / meta data files (hidden, same name as actual file, prepended with a dot).

This leads to problems with parsing in Steam Rom Manager and EmulationStation as the hidden dot files are handled like regular files.

It would be really helpful if the ROM copying wizard did account for this:

- check for existence of such files
- ignore these files 
- import the folder structure without these files

**Comment by WingofaGriffin** [comment]
This is something OnionOS does via this function: https://github.com/OnionUI/Onion/blob/4c7e2dbcc5c585eeeb110ee4ddc43f7285ab671b/static/build/.tmp_update/script/dot-clean.sh#L6

I think we could add a cleanup tool similar to this.

**Comment by Godsbane** [comment]
Definitely should happen.

I think the transfer wizard experience needs to be updated in general.

**Comment by dragoonDorise** [comment]
Fixed on DEV

**Comment by nilsbyte** [comment]
very good. i will check it out! thanks!
