### ISSUE TITLE
RetroArch overlay for NES incorrect

### ISSUE THREAD

**Issue by nilsbyte** [dragoonDorise/EmuDeck#755]
The overlay for NES does currently show a Famicom console (Japanese version). Can you replace this overlay with the overlay for the NES version for the rest of the world? I suggest adding the current "Famicom" overlay as a separate one, so that the user can change it if desired.

**Comment by Godsbane** [comment]
Sure thing - provide an image and do a PR, we'll consider it!

**Comment by dragoonDorise** [comment]
@nilsbyte fixed in dev

**Comment by nilsbyte** [comment]
@dragoonDorise you may want to correct the name. Currently it's `famicon` (wrong). The correct name is `famicom` (for Family Computer). Thanks!
