### ISSUE TITLE
Enhancement (with method): Cloud saves on start/stop of game/emulator

### ISSUE THREAD

**Issue by Fmstrat** [dragoonDorise/EmuDeck#758]
Hi,

I created a script that uses `rclone` and `konsole` to launch a window that synchronizes saved games when you start/close a game, vs every 15 minutes. This was before I realized EmuDeck used `rclone` as well. You can see it here: https://github.com/Fmstrat/emudeck-sync

Is there a reason the same method can't be used for official EmuDeck to avoid the un-needed 15 minute sync? You can see the function here: https://github.com/Fmstrat/emudeck-sync/blob/38ba94533dd367407d38c1af923d637aa40380b8/emudeck-sync.sh#L113

It basically just adds the following line to the beginning and end of `yuzu.sh`:
```
konsole --hide-menubar --hide-tabbar --fullscreen --notransparency --workdir ${HOME} -e ${SCRIPT_DIR}/emudeck-sync.sh
```
which works by then executing:
```
${ESPATH}/rclone bisync -v ${SERVER_TYPE}:${SERVER_PATH} ${ESPATH}/${SERVER_TYPE}
```
to bisync files.

Thanks.

**Comment by Godsbane** [comment]
This is already how the upcoming save sync essentially works. It is not bisync, it is download at the start, and then upload at the end of play.

**Comment by Fmstrat** [comment]
@Godsbane Any chance you could point me to the branch? I considered that method but ended up having to do tons of validation since I couldn't assume a successful upload after the last session (offline, internet issues, etc could overwrite newer local saves or the reverse), so I'd love to see how you pulled it off.

**Comment by Godsbane** [comment]
It is in the early branch.

I did not work on it, but dragoon dorise has been working on it for a while.

**Comment by Fmstrat** [comment]
@Godsbane Took a quick skim, just as a reference point, the existing code looks like it may be susceptible to the same problem once it's in use: https://github.com/dragoonDorise/EmuDeck/blob/448c467db370f22cdd3d90030b937b97b764b3fc/functions/ToolScripts/emuDeckrclone.sh#L360

@dragoonDorise The problem I had was this:
- Launch game
- Saves download before start
- Play game then quit
- Saves fail to upload due to a connectivity issue (or just offline)
- Launch game
- Saves download (overwriting newer saves) before start

I believe there is a `-u` option to skip files that are newer on the destination, but some form of `sync` (such as `bisync`, since `sync` could also delete local files) may be a better option. If not, manual comparisons need to take place to ensure there is no loss of save files (unless I'm missing something which is of course 100% possible).

**Comment by Godsbane** [comment]
i believe i led you astray.

https://github.com/dragoonDorise/EmuDeck/tree/feature/cloudsavesync

**Comment by Fmstrat** [comment]
@Godsbane Ahh yes, that is way more involved, and I can't think of any use cases of the top of my head that would be issues.

I would recommend looking at `bisync` though, as it may handle more future issues that could arise, since it does the same time checks as the code above, but on a per file basis (https://github.com/rclone/rclone/blob/51a468b2bae4ca8e21760435211623a8199a9167/cmd/bisync/deltas.go#L131) plus many other deltas. 

Some advantages:
- Local cache keeps delta processing fast
- The exit codes can be used to determine if there is a failure
- The output can be parsed to specify exactly why the user needs to select cloud or local saves
- `--resync` can be used after the user selects, which basically enforces what you're doing in the code above
- It will likely be the standard for full sync going forward

Admitted disadvantage:
- The Rclone team considers it non-production. That being said it's been around for over a year, and works great for me.

Either way, very excited to see this hit the official release. Thanks for all the work!

**Comment by dragoonDorise** [comment]
Hi @Fmstrat i was really really tempted to use bysinc, but I did't want to use anything that deleted stuff, so I went wit the safe way of just copy and add several checks along the way so It's more hard to screw saved games. We have been using this with early access users for several weeks and so far so good :)
