### ISSUE TITLE
EmuDeck Creates Roms folder & Etc for systems a user explicitly says now to download & setup for.

### ISSUE THREAD

**Issue by dawnbomb** [dragoonDorise/EmuDeck#759]
This needlessly and unintuitively creates confusion with things the user explicitly did not want. 

Please remove this.

**Comment by dragoonDorise** [comment]
Hi, @dawnbomb currently we use the ESDE convention and we just install their folders. There are no plans to change that at the momento, but we will keep in mind your idea as it would simplify the experience for more novice users.
