### ISSUE TITLE
Now fails on BTRFS (non-ext4) formatted cards

### ISSUE THREAD

**Issue by AngelofWoe** [dragoonDorise/EmuDeck#76]
Complains a BTRFS formatted SD card isn't ext4 even though BTRFS works just fine and refuses to continue.

**Comment by popsUlfr** [comment]
I think the check should simply be if a symlink can be created instead of looking at the filesystem.

**Comment by AngelofWoe** [comment]
I was bypassing it by just adding an || to btrfs or an elif for btrfs with a confirmation window.

`#check dev to see if sd card is inserted and has a partition	
	if [ -b "/dev/mmcblk0p1" ]; then	
		#test if card is ext4 or btrfs
		sdFormat=$(findmnt -n --raw --evaluate --output=fstype -S /dev/mmcblk0p1)
		if [  "${sdFormat}" = "ext4" ]; then
			# use findmnt to explicitly find the path where the first partition on the SD card is mounted.
			sdCardFull=$(findmnt -n --raw --evaluate --output=target -S /dev/mmcblk0p1)
			echo "SD Card found; installing to $sdCardFull"> ~/emudeck/emudeck.log
		elif [ "${sdFormat}" = "btrfs" ]; then
			text="`printf "<b>You are using BTRFS formatting.</b>\nDo you want to continue?\n\nYou continue <b>At Your Own Risk.</b>"`"
			zenity --question \
					 --title="EmuDeck" \
					 --width=250 \
					 --ok-label="Continue" \
					 --cancel-label="Cancel" \
					 --text="${text}" &>> /dev/null
			ans=$?
			if [ $ans = 0 ]; then
				# use findmnt to explicitly find the path where the first partition on the SD card is mounted.
				sdCardFull=$(findmnt -n --raw --evaluate --output=target -S /dev/mmcblk0p1)
				echo "SD Card found; installing to $sdCardFull"> ~/emudeck/emudeck.log
			else
				exit
			fi
		else`
		
or

`#check dev to see if sd card is inserted and has a partition	
	if [ -b "/dev/mmcblk0p1" ]; then	
		#test if card is ext4 or btrfs
		sdFormat=$(findmnt -n --raw --evaluate --output=fstype -S /dev/mmcblk0p1)
		if [  "${sdFormat}" = "ext4" ||  "${sdFormat}" = "btrfs" ]; then
			# use findmnt to explicitly find the path where the first partition on the SD card is mounted.
			sdCardFull=$(findmnt -n --raw --evaluate --output=target -S /dev/mmcblk0p1)
			echo "SD Card found; installing to $sdCardFull"> ~/emudeck/emudeck.log
		else`
		
But yeah, something that isn't reliant on the exact format would probably be better.

**Comment by popsUlfr** [comment]
Maybe it should be something like:

```sh
sdCardFull="$(findmnt -n --raw --evaluate --output=target -S /dev/mmcblk0p1)"
if ! tmp_file="$(mktemp -p "${sdCardFull}")"; then
    # error
fi
if ! ln -s "$tmp_file" "$tmpfile.link"; then
    # error
fi
rm -f "$tmp_file" "$tmpfile.link"
```

And continue as normal.

**Comment by Godsbane** [comment]
I already made a filesystem whitelist pr instead of it requiring what the deck does, but there was something else going on when it was being tested.

I will re make that and pr to dev.

**Comment by Godsbane** [comment]
> Maybe it should be something like:
> 
> ```shell
> sdCardFull="$(findmnt -n --raw --evaluate --output=target -S /dev/mmcblk0p1)"
> if ! tmp_file="$(mktemp -p "${sdCardFull}")"; then
>     # error
> fi
> if ! ln -s "$tmp_file" "$tmpfile.link"; then
>     # error
> fi
> rm -f "$tmp_file" "$tmpfile.link"
> ```
> 
> And continue as normal.

I sort of like this approach though. A simple test of symlinks. if they work, who cares what the fs type is.

**Comment by AngelofWoe** [comment]
If you just need to know if the directory is writable:

```bash
 sdCardFull="$(findmnt -n --raw --evaluate --output=target -S /dev/mmcblk0p1)"
if [ -w "${sdCardFull}" ]; then 
    # continue
else
    # error
fi
```

**Comment by Godsbane** [comment]
Not just writable, it's the ability to use symlinks is what we really need to be sure of.

**Comment by AngelofWoe** [comment]
I wasn't sure. But yeah, the only way I know of to do that is to do what you're suggesting.

**Comment by Godsbane** [comment]
#82

**Comment by dragoonDorise** [comment]
@popsUlfr this has been merged on the beta branch, can you please test it?

Beta installer: https://discord.com/channels/934078500552462346/969754179797139496/969754780501168208

**Comment by dragoonDorise** [comment]
Fixed on V0.17.1! Thanks to @popsUlfr

**Comment by popsUlfr** [comment]
I feel incredibly humbled by all the mentions of me xD . It also made me giggle quite a lot as it felt like I hold some sort of patent on symlink checking or something haha. There was really no need to go that far but really appreciate the thought, thanks guys. :smile: (all credit to @Godsbane for doing the real work hehe)

**Comment by Godsbane** [comment]
It will forever be known as the @popsUlfr method.  =P

You know when you are approaching a problem from a way that seems completely logical to you, and someone else comes by with something simpler that solves the actual problem.... yeah that's why I made sure to call you out. The method was just better.

**Comment by AngelofWoe** [comment]
😂🤣
And so it is written.
