### ISSUE TITLE
Emudeck Does not actually have a option to go to roms location at launch

### ISSUE THREAD

**Issue by dawnbomb** [dragoonDorise/EmuDeck#760]
Despite being what should be an obvious all in one solution, emudeck doesn't actually offer anyway to to setup roms for emudeck, or if it does it's not intuitive at all.  Incase it does exist, before someone tells me it's in some menu and i need to learn more about Emu Deck, it should simply be more intuitive and not ask users to learn so much. The only options are steam rom manager, and USB transfer Wizard, neither of which actually manage roms locally like most users would want.  The lack of these kind of extremely basic options most people expect is what drives people away from "tools" like this.

Change USB Transfer Wizard to something like "ROM Manager" and inside it have some options. Suggestions include...

Open roms folder  (Clicking this can prompt an ask for what emulator's ROM folder you want to open)
ROM USB transfer
Steam ROM Manager  (Yes, put that inside here)

**Comment by dragoonDorise** [comment]
HI @dawnbomb , we did try putting SRM inside a subsection but people complained that it was hidden away, so we kept it at top level. When you install EmuDeck, right after it's done it loads the USB Transfer Wizard, so the first thing the user see is how to get their roms on their device. The idea for opening the rom folder is a nice one, we'll look into that.
