### ISSUE TITLE
I would like to see the entire card format of EmuDeck's main settings menu swapped for Citra style.

### ISSUE THREAD

**Issue by dawnbomb** [dragoonDorise/EmuDeck#763]
Aside from my other topic on screen efficiency, it would be a lot better to have a menu like Citra's configure menu, where all the main options are on a list on the left, and the right side shows everything related to the current option.

This would be much more intuitive then the current format. The left list tabs can even be a little chunky for touch controls and they should still all fit without needing a scroll bar.  The current method is simply extremely confusing, and many options could be merged into one, such as Cloud Backup and Cloud Manager. Why does a menu called something like "Cloud Manager" not manage everything involving the cloud anyway? 

I can give more detailed explanations if necessary, but it should be pretty obvious what i mean.

**Comment by Godsbane** [comment]
I don't think a redesign is in the works atm, and this is not the right repository anyways. The electron repo is separate.

Pull requests are welcome, but i am going to go ahead and close this.
