### ISSUE TITLE
EmuDeck's Steam ROM Manager option lies, claiming controls will "Temporarily revert", except they never come back.

### ISSUE THREAD

**Issue by dawnbomb** [dragoonDorise/EmuDeck#764]
Aside from this menu being extemely confusing and full of esoteric language even veteran emulators users would absolutely have no idea what the hell anything means because the developers don't want anyone to understand anything and intensionally use the most confusing language possible, the option to even open the steam rom manage claims it "temporarily reverts" the controls, but when closing the menu they do not come back. The reverts are not at all temporary.

**Comment by dragoonDorise** [comment]
We'll add a "temporary until Steam is opened again"
