### ISSUE TITLE
Scraping problem

### ISSUE THREAD

**Issue by CroHammeR** [dragoonDorise/EmuDeck#767]
My games are listed as a TOP 10 or TOP 100 and have the position number e.g.

01. Super Mario Bros. 3 (USA)
02. The Legend of Zelda (USA) (Collector's Edition)
03. Super Mario Bros. + 77. Duck Hunt (USA)
...

is there a way to Scrapen one anyway? For "young" ones who don't know retro games, this is a good and interesting list.

**Comment by Godsbane** [comment]
Most scrapers are filename based. This will interfere, unfortunately. You can manually scrape every file if you want in es-de. You do that by hitting select and going to metadata editor. Set the name, then scrape.

If you use steam rom manager, you can use exceptions to refine each search.
