### ISSUE TITLE
Cloud Saves - Nextcloud and Self-Signed Cert

### ISSUE THREAD

**Issue by maxxxxpower** [dragoonDorise/EmuDeck#768]
Getting an error trying to use my internal nextcloud instance for cloud saves. It states the SSL is not valid (it isn't; self signed). I can't seem to find a way to allow/override it.

I have accepted the cert and logged in via Firefox, the default browser, but still it does not work when using the EmuDeck Cloud Save login. Am I missing an easy step? Wiki for the Cloud Save config is empty.

Thanks.

**Comment by Godsbane** [comment]
I did some research on this, it seems you can skip the cert check.

**Comment by Godsbane** [comment]
https://rclone.org/flags/

**Comment by maxxxxpower** [comment]
Thank you. I see the no check cert option. I'll give it a try in the morning and report back.

**Comment by maxxxxpower** [comment]
So tested putting in the rclone.conf following this thread (https://github.com/rclone/rclone/issues/468), as well as putting it in the command line of the Save script itself, both to no avail.

I ensure I followed the formatting (no-check-cert for backend and --no-check-cert in the command line).

I'm new to rclone, so hoping I am just missing an easy step somewhere.

**Comment by Godsbane** [comment]
Can you share the log output when you use the flag in the job please?

**Comment by maxxxxpower** [comment]
I have also tried adding the --no-check-certificate=true to the desktop shortcut itself. Same console error, still nothing in rclone_job.log

**Comment by Godsbane** [comment]
while i don't think _think_ this is the issue, the format of the URL should be:

`https://host.domain/remote.php/webdav/`

try correcting that first.

**Comment by maxxxxpower** [comment]
Agreed, changed anyway. Same result - invalid cert.

I should note that the webdav url I initially used came straight from the Nextcloud settings page when I logged in to my profile.

**Comment by maxxxxpower** [comment]
Yes that did it. Added near the end of the run_rclone_job.sh:

`"$rclone_provider":Emudeck/saves -P --no-check-certificate > "$toolsPath/rclone/rclone_job.log"`

Confirmed working in the log and checked nextcloud from another device to be sure. Thank you so much for the help here - and forcing me to learn more about rclone.

[rclone_job.log](https://github.com/dragoonDorise/EmuDeck/files/11576095/rclone_job.log)
