### ISSUE TITLE
Steam Rom Manager points to nonexistent directory for WiiU ROMS

### ISSUE THREAD

**Issue by SOberhoff** [dragoonDorise/EmuDeck#77]
By default the Steam Rom Manager points to `Emulation/roms/wiiu/roms` even though the directory structure only contains `Emulation/roms/wiiu`. There's also a readme found at that location which misleadingly states "roms go here".

**Comment by SOberhoff** [comment]
Perhaps I should clarify that this is under the WiiU - Cemu (.rpx) and WiiU Cemu (.wud, .wux, .wua) tabs in their respective ROMs directory configurations.

**Comment by Godsbane** [comment]
Hi. The installer should have made a second roms folder. And your roms should go in there.

The steam rom manager config is what should be on your system.

Could you upload your log of when you ran emudeck? It's ~/emudeck/emudeck.log

**Comment by SOberhoff** [comment]
The logfile just reads:

> Cloning into '/home/deck/dragoonDoriseTools/EmuDeck'...  
fetch-pack: unexpected disconnect while reading sideband packet

**Comment by Godsbane** [comment]
That's not normal at all. That error is a network error from GitHub. I would love if you could rerun emudeck and attach the log. Maybe it was just a brief network issue.

**Comment by dragoonDorise** [comment]
Hi @SOberhoff , we've fixed this on the beta brach, you can fix it manually by just creating that roms folder. Thanks for your feedback!
