### ISSUE TITLE
Issue with all Roms booting and then freezing within 5 seconds

### ISSUE THREAD

**Issue by Rlemon18** [dragoonDorise/EmuDeck#771]
Hi there.

I just got my steam deck about 5 days ago and started to try to get emudeck setup last night. 

I got all of my ROMS and BIOS from my computer (Mostly older NES and GB games) and they are all working just fine on the PC. So I switched them to a USB drive and then dropped them in the appropriate folders on my steam deck.

I got them to appear in steam and everything, but when I go to run any of them on any of the systems they will boot for about 5 seconds and then freeze. Each one. I can push the start button or whatever and it will progress through the screens, but after those 5 seconds they will freeze. 

I've reinstalled Emudeck and updated all of my programs on Discover, and I also tried to "manage emulators" and updated through there but have no success with that. 

Any help is appreciated. Thank you!

EDIT:

My apologies, after tinkering around a bit more at work, when I was in offline mode it started working correctly, however, it seems like the issue is when I connect to "Retro Achievements" is when the freeze happens right after. Any idea why that might be the case?

**Comment by Rlemon18** [comment]
Don't think this was an emudeck issue at all.

**Comment by Godsbane** [comment]
I know that Retroachievements can have issues when loading, if the account is not properly activated.

Otherwise I believe it should work offline normally.

Possibly do some testing.
