### ISSUE TITLE
Feature Request: Steam rom manager custom artwork

### ISSUE THREAD

**Issue by motaku96** [dragoonDorise/EmuDeck#772]
When you have to use a custom image with Steam Rom Manager, it would be nice if the custom image you select gets used in all the areas that need an image on the steam interface. Right now it does the main custom artwork, but it doesn't show when it's the last game you played, or in the background.

**Comment by Godsbane** [comment]
we do not make steam rom manager. 

https://github.com/SteamGridDB/steam-rom-manager/issues

(that said - you can change all the types of art. there are 5 choices. Check the dropdowns at the top during preview)
