### ISSUE TITLE
Remove dependency on Google in Yuzu launcher

### ISSUE THREAD

**Issue by james2432** [dragoonDorise/EmuDeck#776]
Yuzu launcher pings google dns (8.8.8.8) on port 53.

Checking the connection to github/yuzu-emu would be better because it doesn't introduce the dependency on port 53(blocked on more advanced networks to avoid DNS bypass) and less google in our lives :)

See: https://github.com/dragoonDorise/EmuDeck/pull/774

**Comment by james2432** [comment]
Was merged, closing

**Comment by Godsbane** [comment]
Going to keep open until it makes it to production
