### ISSUE TITLE
Crunchyroll "oops! something went wrong. try again"

### ISSUE THREAD

**Issue by Balakay420** [dragoonDorise/EmuDeck#779]
if im not mistaken, this is an issue with the cache needed to be cleared from the instance its using. any idea how to fix? tried reinstalling, issue persists

**Comment by Godsbane** [comment]
You reinstalled what? The browser?

**Comment by Balakay420** [comment]
I deleted crunchyroll and reinstalled it using the cloud services option on emudeck
