### ISSUE TITLE
Allow partitioned SD Cards to show up

### ISSUE THREAD

**Issue by gramueller** [dragoonDorise/EmuDeck#787]
i have a partitioned SD card. One part for Windows and the other for storage on the steam deck. Everything works except Emudeck. From what i gathered Emudeck only supports SD cards where the first partition is mounted for steam with /run/media/mmcblk0 or /run/media/mmcblk0p1. My Windows installation is sadly on mmcblk0p1 and my steam deck space is on mmcblk0p4. 
would be nice if emudeck can detect my SD card there.

**Comment by Godsbane** [comment]
You can use a custom install choice to handle this use case without issue.

Let me know if you have trouble finding it.

**Comment by Godsbane** [comment]
I will record something and upload it after work.

**Comment by Godsbane** [comment]
https://github.com/dragoonDorise/EmuDeck/assets/1683513/ca395867-76fd-42cd-bfc0-c946571173d0

**Comment by gramueller** [comment]
omg of course! i completely overlooked that ... Thank you very much. You can't imagine how long i looked and never realized to click on that option! Sry for making that issue in the first place 😅

**Comment by gramueller** [comment]
> Peek.2023-06-06.17-05.mp4

![DDBF205A-E492-4AE7-BFD9-9DDE71D612D4](https://github.com/dragoonDorise/EmuDeck/assets/34185987/797af6ec-c8fa-4545-beed-04b469bae327)


it still does not work. The drive i selected has 220 GB free and is mounted and works perfectly with steam. I don't know how it would ne if i install it from scratch and not trying to migrate it, but i can't uninstall it right now as i don't want to loose my presets and everything.

**Comment by Godsbane** [comment]
and you are sure there are not spaces in the path?

**Comment by gramueller** [comment]
> This is an issue where @dragoonDorise is sending the wrong value to the migration function.
> 
> He needs to look at this, but it's unrelated to your original case.

ok thanks for the reply. Good it is already known.
