### ISSUE TITLE
Transfering from SDCard to internal storage leads to broken symlinks

### ISSUE THREAD

**Issue by tyalie** [dragoonDorise/EmuDeck#789]
I tried using the EmuDeck utility to migrate from SD-Card to internal storage. For me this only entailed moving Yuzu saves/firmware/... around. During this process the data was correctly copied, but as my symlinks in the Yuzu folder (and from another emulator) were using absolute paths, it broke the Yuzu installation. In my case this meant that saves weren't persistent across emulator restarts (as `yuzu/saves` pointed to the wrong directory) 

I was able to fix it with this horrendous tiny bash script
```bash
# execute in Emulator folder
for i in $(find . -lname "/run/media/*"); do
  oldlink=$(readlink $i);
  # create new link by replacing /run/media/mmcblk0p1 with /home/deck
  newlink=${oldlink/#\/run\/media\/mmcblk0p1/\/home\/deck};
  echo $oldlink "->" $newlink "|" $(basename $oldlink);
  # copy data if things went missing (optional probably)
  #cp -r $oldlink/* $newlink;
  # change symlink
  ln -sfn "$newlink" $i;
  echo "moved symlink";
done
```

**Comment by dragoonDorise** [comment]
this was fixed
