### ISSUE TITLE
User Friendly Method to Set Custom System Configurations

### ISSUE THREAD

**Issue by dionmunk** [dragoonDorise/EmuDeck#790]
CD-based gaming systems can be tricky to get to display correctly inside Emulation Station. You will often have duplicates in the game list because games have multiple files to define multiple discs and Emulation Station recognizes the files as _separate games_.

Users may have a particular naming convention they like to use to organize their library. I prefer the BIN/CUE method for single-disc games and the BIN/CD1,CD2,CD.../M3U method for multi-disc games.

The issue is that there is no easy way to add or remove rom file extensions for the base `es_systems.cfg` without adding a custom entry in the `/home/deck/.emulationstation/custom_systems/es_systems.xml` file. What happens when EmuDeck updates and the custom configuration in this file is now outdated and wrong?

It would be nice if EmuDeck had a way to manage the extensions a system looks for in a more user-friendly manner that would carry across updates rather than manually having to edit the custom config.

**Comment by Godsbane** [comment]
Don't do that, use the methods in the es-de user guide and our wiki to manage your files on a clean way.

You are adding work where it doesn't need to be added.

Also, that file is edited dynamically and not replaced. As long as you don't mess with the entries emudeck added, it should survive updates.
