### ISSUE TITLE
Try to add Orca support

### ISSUE THREAD

**Issue by dragoonDorise** [dragoonDorise/EmuDeck#797]
Accesibility

**Comment by rings2006** [comment]
just a note, you need to add these to your .BashProfile to actually make sure it reads the difrent ui types, these would usually be added to .xinit.rc but well, this is wayland
    export GTK_MODULES=gail:atk-bridge
    export GNOME_ACCESSIBILITY=1
    export QT_ACCESSIBILITY=1
    export QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
