### ISSUE TITLE
Emudeck's Dolphin configuration breaks Console ID from a real NAND dump

### ISSUE THREAD

**Issue by hopelessheron** [dragoonDorise/EmuDeck#798]
I recently installed emudeck on my steam deck, with the intent to use an imported NAND dump to get online with wiimmfi. This was from a previously working installation of Dolphin on macOS (At ~/Library/Application Support/Dolphin), with a valid console ID.  

Upon using that installation in the dolphin environment set up by emudeck (By replacing ~/.var/app/org.DolphinEmu.dolphin-emu with the folder from macOS), trying to connect to wiimmfi results in error 23915: Abuse of a console identifier. This is indicative of trying to connect to wiimmfi with a default dolphin NAND (which is blocked to prevent abuse).  Everything else about the transferred NAND seems to be working correctly, as I am able to see my saves and miis.

Using that same folder in an unconfigured dolphin installation (I just deleted org.DolphinEmu.dolphin-emu and copied data/dolphin-emu back into the recreated folder), dolphin is able to recognize the NAND/Console ID and I am able to connect to wiimmfi without issue.

I don't know enough about dolphin to know what's causing the problem, but there seems to be something that emudeck configures which prevents the emulator from correctly retrieving the console identifier.

**Comment by Godsbane** [comment]
I would need to see your config files. I have never used wiimmfi, but I did have one other report of this happening after a dolphin update recently.

If you want to try to get to the bottom of this please join the discord and message livedeht. We can walk through what's different and perhaps fix this in general.

**Comment by Godsbane** [comment]
i spoke to some of the people on the Dolphin discord and had them look at the config - It appears to be because of the mac address that was in a config file (not on purpose). I removed the line. I would appreciate if you could re-test and let me know if it's solved.
