### ISSUE TITLE
DEV - tool deletion

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#80]
https://github.com/dragoonDorise/EmuDeck/blob/1b6ffa1e50b97cb46c346d50d1383bbe61b377c0/install.sh#L1041

Move this to the end of the script so you don't delete your files too early

**Comment by Godsbane** [comment]
This is not important yet, nothing is used after the deletion. I just suggets it go to the end, always, so you it doesn't cause an issue down the line.

**Comment by dragoonDorise** [comment]
Done!
