### ISSUE TITLE
Enhancement Request:  Support Game and Watch in Mame and add support for separate LCD games folder

### ISSUE THREAD

**Issue by Ardend** [dragoonDorise/EmuDeck#803]
Would it be possible to add an option to play Game and Watch games via Mame?  Looks like emulationstation supports both, and it would be good to support both the "gameandwatch" folder and "lcdgames" folder so that users could play all of the Nintendo GW games in mame, and leave the non Nintendo stuff supported in the gw_libreto core for the lcdgames folder.

**Comment by WingofaGriffin** [comment]
This should already be supported in ES-DE as you have mentioned. Are you saying you would like a SRM parser for it? We do have the option to install standalone MAME. Or am I missing something?

**Comment by Ardend** [comment]
I dropped the mame specific rom set into the gameandwatch folder, structured the way ES-DE says to with the artwork in a subfolder called artwork, and when I try and launch a game it just backs out to the ES-DE menu.  I also tried copying the working simulation set into a lcdsystems folder and it wasn't recognized.  I am going to do some more testing to be sure.

**Comment by WingofaGriffin** [comment]
Is this in ES-DE or in SRM? Also, do you have MAME standalone installed? Try changing the default emulator to MAME standalone as described here: https://github.com/dragoonDorise/EmuDeck/wiki/EmulationStation-DE#how-to-select-a-different-emulator-for-a-system

**Comment by Ardend** [comment]
This is in ES-DE, and in the alternate emulator menu, Game and Watch doesn't show up.  What determines if a platform shows up in that list?

**Comment by WingofaGriffin** [comment]
See the following guide in ES-DE: https://gitlab.com/es-de/emulationstation-de/-/blob/master/USERGUIDE.md#lcd-handheld-games
