### ISSUE TITLE
Emudeck Controls Help

### ISSUE THREAD

**Issue by babayaga511** [dragoonDorise/EmuDeck#812]
I just got a steamdeck a week ago and Emudeck was running awesome! Today i booted up Warioland 4 and no controls were responding. I checked the other emulators and my controls were nonresponsive on those too; both on the decktop mode and handheld one. I've updated the emulators on the Manage Emulators page but still having an issue. Please help!

**Comment by Godsbane** [comment]
Sounds like you need to reboot your deck ( proper shut down and boot up). Please join the discord if you need more help.
