### ISSUE TITLE
Texture replacement not working PCSX2

### ISSUE THREAD

**Issue by NeonNingen** [dragoonDorise/EmuDeck#814]
The emudeck version of PCSX2 doesn't load textures from directory.
Persona 3 FES has a HD overhaul mod that replaces textures, using the latest emudeck nightly build of PCSX2 it does not replace the ingame textures. The PCSX2 appimage from the PCSX2 website using the same nightly build as emudeck does replace the textures. 
I'm not certain why the texture replacement does not work on emudeck?

**Comment by Godsbane** [comment]
Why would the sh matter. It's just launching the appimage.

Will need more info.

**Comment by NeonNingen** [comment]
Running the appimage directly replaces the textures while running the sh files does not. I assume it's either falling back onto the flatpak or the command executed is wrong.
This was the command it executed when running sf file:
/home/deck/Applications/pcsx2-Qt.AppImage -batch -fullscreen -bigpicture "/run/media/mmcblk0p1/Emulation/roms/ps2/P3/Shin Megami Tensei - Persona 3 FES (USA) - Modded.ELF" -bigpicture -fullscreen

**Comment by NeonNingen** [comment]
We found that the emudeck config files sets loadtexturereplacement to false,
![image](https://github.com/dragoonDorise/EmuDeck/assets/48389674/e1f9cf08-5fcb-4218-a9d2-90cbf0f716eb)

On the appimage I have it enabled but the emudeck config seems to overwrite that

**Comment by NeonNingen** [comment]
![image](https://github.com/dragoonDorise/EmuDeck/assets/48389674/ef2eef5a-8fe4-4c7c-89ce-52320308065d)
The config file found in the backend is loaded when it runs the sh file.

This backend config file does not load textures, leading to the issue I posted.
![image](https://github.com/dragoonDorise/EmuDeck/assets/48389674/1ee4bd5a-c4f4-4b16-9d76-f23b775d1b5a)

**Comment by NeonNingen** [comment]
Well tested that, still no dice. Still has the same issue

**Comment by NeonNingen** [comment]
My workaround is just running the appimage of pcsx2 with the game directly from steam but it has to do with the batch file or something else within emudeck

**Comment by NeonNingen** [comment]
I did a custom reset to the emudeck and it fixed the issue.

**Comment by NeonNingen** [comment]
I did a custom reset to the emudeck and it fixed the issue.

**Comment by Godsbane** [comment]
> ![image](https://user-images.githubusercontent.com/48389674/251534205-ef2eef5a-8fe4-4c7c-89ce-52320308065d.png) The config file found in the backend is loaded when it runs the sh file.
> 
> This backend config file does not load textures, leading to the issue I posted. ![image](https://user-images.githubusercontent.com/48389674/251534534-1ee4bd5a-c4f4-4b16-9d76-f23b775d1b5a.png)

This file is not in use during play. It's copied in during install only if the appimage can't generate it's config file on it's own.

I know you closed this already - just wanted to explain.

Emudeck itself does NOTHING during play - only during the installation. Once installed the Application handles everything. (in this case pcsx2)
