### ISSUE TITLE
RPCS3 Needs PS3UPDAT.PUP

### ISSUE THREAD

**Issue by Technologyman00** [dragoonDorise/EmuDeck#819]
RPCS3 requires the PS3UPDAT.PUP from sony's website https://www.playstation.com/en-us/support/hardware/ps3/system-software/. Either it should be added to the bios section in the wiki or be downloaded automatically when RPCS3 is installed

**Comment by Godsbane** [comment]
https://github.com/dragoonDorise/EmuDeck/wiki/RPCS3#getting-started-with-rpcs3

this is covered here.

it's also in the bios section of the wiki:

![image](https://github.com/dragoonDorise/EmuDeck/assets/1683513/7bc7f139-387d-4fe3-abfe-34dbf6914cca)
