### ISSUE TITLE
Manjaro steam folder (tricky)

### ISSUE THREAD

**Issue by mitcoes** [dragoonDorise/EmuDeck#822]
/home/(user)/.steam/steam in Manjaro 
does not work as steam is a link to 
/home/(user)/.local/share/Steam

Just look for properties of the link and copy and paste it, because it can change in the future.

Or you can add to your browser the ability to see links, 
and allow "/home/(user)/.steam/steam" in Manjaro to be set from the interface.

**Comment by Godsbane** [comment]
Hello, what is this in reference to? Steam rom manager?
