### ISSUE TITLE
Steam rom manager not launchable

### ISSUE THREAD

**Issue by deasmi** [dragoonDorise/EmuDeck#823]
A clean install on a clean deck today.

The install finishes without any apparent error, but steam rom manager doesn't work.

You get the pop up warning about closing steam and then nothing.

Fetch log file also seems not to work

How can I troubleshoot this?

**Comment by Godsbane** [comment]
For support please use the Discord. This is for issues with the scripts, etc.

Yours sounds like connection issue. There's some info on the wiki in FAQ on some suggestions for your deck.
