### ISSUE TITLE
Default browser in cloud services has problems with DRM content

### ISSUE THREAD

**Issue by Pender6666** [dragoonDorise/EmuDeck#824]
Google Chrome works with a majority of services but Paramount Plus always returns with an error 3304 when trying to playback videos. 
Others work fine. I suggest changing the default browser to Edge because it runs ok. Didn't try Firefox.

The best part is Edge works with Xbox Cloud Gaming too.

**Comment by qwrwed** [comment]
I've encountered a possibly similar issue with Disney+ (error code 83; someone else has posted about it at https://old.reddit.com/r/SteamDeck/comments/14y1z5q/does_anyone_have_a_solution_for_disney_plus_and/).

**Comment by Godsbane** [comment]
The default is your default based on the settings on your deck. That's why the settings lets you choose something else.

Closing as we are not going to set a default outside of the user's choice.
