### ISSUE TITLE
Ability to change controller port via Sidebar

### ISSUE THREAD

**Issue by lithiumfox** [dragoonDorise/EmuDeck#832]
Is there any chance that using the quick menu on the Steam deck we could be able to change what port our controller is on?

This would be helpful for games like the twin snakes which typically require you to change your controller port if you want to go for a no death run.

I know it'd be a small thing use wise but probably a lot of work, and probably wouldn't matter for a majority of games but it could also be helpful with something like controller tools that allows you to have multiple controllers.

Being able to adjust those things on the fly in full screen games is also helpful and if we could also have it work for switch games to automatically detect what kind of controller is being used that would be even better....  (Eg: pro controller vs Joycons) because having to go into the menu to change that is kind of awful.

**Comment by Godsbane** [comment]
The ... Menu already does change the port, as long as there are more than one controller connected.

The emulators are configured with the steam virtual input where possible, and the ordering should work properly.

As for joycons vs pro controller etc? We don't have a solution for that. I am not really sure of a good way to handle that on the fly.

Yuzu, for example, does let you assign an input profile to game now. Maybe that will sort your use case?
