### ISSUE TITLE
Uninstalling EmuDeck does not uninstall Decky plugins

### ISSUE THREAD

**Issue by karasuhebi** [dragoonDorise/EmuDeck#835]
I'm not sure if this is a bug or intentional but I figured I'd mention it.

**Comment by Godsbane** [comment]
This is intentional, I think. 

@dragoonDorise correct?

**Comment by WingofaGriffin** [comment]
EmuDeck and Decky are seperate projects. We offer a shortcut to install decky within EmuDeck, as some plugins are beneficial for emulation, and some of the EmuDeck devs also develop plugins, but I believe this is 100% intentional, otherwise there is the issue of uninstalling Decky for users who only wanted to uninstall EmuDeck.

**Comment by karasuhebi** [comment]
Sorry you seemed to have misunderstood. I don't want EmuDeck to uninstall Decky Loader. I was wondering about the EmuDeck-specific plugins for Decky Loader.

**Comment by WingofaGriffin** [comment]
My apologies. I think there currently some confusing status of the state of the EmuDeck hotkeys plugin, so @dragoonDorise will need to confirm.

**Comment by karasuhebi** [comment]
No worries. Upon re-reading the title of the Issue and the OP, I can see how I could've been more specific. Sorry about that!

**Comment by dragoonDorise** [comment]
@karasuhebi ummmm probably I just forget to add the plugin to the uninstaller

**Comment by karasuhebi** [comment]
Should I close this Issue since there's a new plugin now?

**Comment by karasuhebi** [comment]
I see that rawdatafeel mentioned that #978 closes this Issue but I just wanted to clarify that it does not. That PR seems to uninstall Decky Loader, while this Issue is about uninstalling the Decky Loader plugin(s) for EmuDeck.
