### ISSUE TITLE
EmuDeck Windows: stuck on the selection your rom directory screen

### ISSUE THREAD

**Issue by etgoa** [dragoonDorise/EmuDeck#836]
Hi, seeking for your help as I'm not able to install emudeck on my Rog Ally. Tried to follow the installation instructions but I'm getting stuck on the selection your rom directory screen, no matter what I do it just restarts the whole process going back to the checking for updates screen.

btw: I'm trying to install on my C: directly...

Any hints, help, guidance?

Thanks.

**Comment by Godsbane** [comment]
This is for steamos.

Please use the discord for help.
