### ISSUE TITLE
Select your drive takes me back to the welcome page

### ISSUE THREAD

**Issue by noahmacf** [dragoonDorise/EmuDeck#838]
This is on my rog ally in version 2.1.18 and downloaded from the exe file on the GitHub for windows. Whenever I select custom or easy mode and then select “select your drive” it sends me straight back to the page where I select custom or easy mode. I can’t move forward with the process at all and am stuck here. I’ve tried deleting and reinstalling as well as restarting the system.

**Comment by Godsbane** [comment]
This is for steamos. Please use the discord for help.
