### ISSUE TITLE
[Feature Request] - Make it more clear which emulators were actually updated

### ISSUE THREAD

**Issue by karasuhebi** [dragoonDorise/EmuDeck#840]
I don't know if this is a zenity limitation or not but it would be great for EmuDeck to make it more clear which AppImage and binary emulators were actually updated when you decide to check for updates. Currently I kind of guess just based on how long the progress bar/text is on the screen for.

Thank you!

**Comment by Godsbane** [comment]
You should get a pop up which tells you which ones were updated at the end.

It also has progress bars for each download, and an overall bar.

Are you not seeing that?

**Comment by karasuhebi** [comment]
I definitely don't get a pop-up at the end telling me which emulators were updated. That'd be really nice. Honestly I'd close this Issue if we had that.

I do get progress bars though, I mentioned that in the OP. But that's not really definitive since it shows progress bars for every single emulator no matter what.
