### ISSUE TITLE
There was an issue trying to install [..]

### ISSUE THREAD

**Issue by MarcoReckless** [dragoonDorise/EmuDeck#842]
I'm on SteamOS 3.5, I installed EmuDeck and I have trouble installing/uninstalling emulators, I always end up getting the "_There was an issue trying to install [..]_" error, I already tried removing it completely and reinstalling but it gives the same error.

It's really odd, it managed to install them on the initial setup but when I try to manage them in the EmuDeck tool it doesn't detect if it's installed or not and it's unable to manage them, so I have to resort to using the discover store.

I uploaded my log so maybe you can figure out what the problem is, just so you know I tried to install RetroArch, so look for that.

[emudeck.log](https://github.com/dragoonDorise/EmuDeck/files/12364440/emudeck.log)

**Comment by Godsbane** [comment]
This is the install log, which looks fine to me. Can you attach the appimage log where you attempted to manage something and got an error?

**Comment by MarcoReckless** [comment]
> This is the install log, which looks fine to me. Can you attach the appimage log where you attempted to manage something and got an error?

Here's the AppImage log, I tried installing RetroArch again.

[Emudeck.AppImage.log](https://github.com/dragoonDorise/EmuDeck/files/12366090/Emudeck.AppImage.log)

**Comment by Godsbane** [comment]
Can you share the output of `flatpak install retroarch` from konsole?

**Comment by MarcoReckless** [comment]
> Can you share the output of `flatpak install retroarch` from konsole?

It managed to install it without any problem from Konsole, yet it still has the same problem installing/uninstall from EmuDeck itself.
Maybe EmuDeck is missing some sort of permission on my system? Because it doesn't have this problem with some emulators.

**Comment by MarcoReckless** [comment]
I installed the SteamOS 3.5 main update that was released some hours ago and I removed all the remains of the apps and the AppImages of bugged emulators that were stuck in the applications folder and now it seems to be able to install/uninstall correctly, I'm not really sure what the problem was tough.

**Comment by Godsbane** [comment]
Well if you have more trouble please let me know.

**Comment by pipoliviero** [comment]
Same issue here. It was fine a couple days ago but now on 3.5.5 it fails to install any emulators.
