### ISSUE TITLE
Can't install Dolphin

### ISSUE THREAD

**Issue by JakobDev** [dragoonDorise/EmuDeck#843]
I installed EmuDeck using the custom installation, because I need only PS2 Emulation, so I installed only PCSX2. Now I want to install Dolphin. But when I go to Manage your Emulators>Dolphin and tap install, nothing happens. No Install, no error message, just nothing.

**Comment by MarcoReckless** [comment]
I am having a similar issue on my topic (#842), it applies to many emulators but not all of them, but in most of them I get an error message.
While it's not a fix, you can install it using the Discover store and then you can apply the recommended settings with EmuDeck and it should apply them.

**Comment by Godsbane** [comment]
> I installed EmuDeck using the custom installation, because I need only PS2 Emulation, so I installed only PCSX2. Now I want to install Dolphin. But when I go to Manage your Emulators>Dolphin and tap install, nothing happens. No Install, no error message, just nothing.

Can you please send the output of `flatpak install flathub org.DolphinEmu.dolphin-emu --user` when run from from konsole?

**Comment by JakobDev** [comment]
I have found out the same thing as MarcoReckless, as I tried to install Dolphin from Flathub.To my surpise it was recognized by EmuDeck (for PCSX2 it uses the AppImage and not the Flatpak, so I didn't think of that).

I had now uninstalled it and installed it again to show the output, but nothing interesting here:
```
(deck@steamdeck ~)$ flatpak install --user org.DolphinEmu.dolphin-emu
Looking for matches…

org.DolphinEmu.dolphin-emu permissions:
    ipc     network     pulseaudio     x11     devices    bluetooth    file access [1]    dbus access [2]

    [1] host:ro, xdg-config/kdeglobals:ro, xdg-run/app/com.discordapp.Discord:create
    [2] com.canonical.AppMenu.Registrar, org.freedesktop.ScreenSaver


        ID                                           Branch           Op           Remote            Download
 1. [✓] org.DolphinEmu.dolphin_emu.Locale            stable           i            flathub            3.6 kB / 1.5 MB
 2. [✓] org.DolphinEmu.dolphin-emu                   stable           i            flathub           27.6 MB / 26.0 MB

Warning: Not exporting file org.DolphinEmu.dolphin-emu.appdata.xml of unsupported type.
Installation complete.
(deck@steamdeck ~)$ 
```

You should really update EmuDeck to show a meaningful error message if something fails, so the User know what happens and can eventually fix it.

**Comment by Godsbane** [comment]
It sounds like there was no meaningful output.

The output of stderr is piped to a notification in emudeck.
