### ISSUE TITLE
Question: Safe to edit SRM settings?

### ISSUE THREAD

**Issue by cdloh** [dragoonDorise/EmuDeck#847]
How safe is it to add parsers and edit parser settings in SRM?

Will EmuDeck updates wipe those or does EmuDeck only modify those settings on first install?

Thanks!

**Comment by dragoonDorise** [comment]
It will wipe them if you do a quick reset or a configuration reset, if you do a custom reset you can tell EmuDeck no not update SRM parsers. We are working on a new way of managing SRM parsers so it will be able to add custom parsers in the future

**Comment by ianharbs** [comment]
> It will wipe them if you do a quick reset or a configuration reset, if you do a custom reset you can tell EmuDeck no not update SRM parsers. We are working on a new way of managing SRM parsers so it will be able to add custom parsers in the future

Is there any way to edit the parser Steam Category?
