### ISSUE TITLE
Bug - Powertools

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#85]
had a report that a user's already installed powertools were deleted when they said no to installing.

**Comment by AngelofWoe** [comment]
I attempted to but am unable to duplicate the issue on 0.17.1, and looking through install.sh, I don't see where the `sudo rm -rf ~/homebrew/plugins/PowerTools` at line 1460 would run unless they selected to install PowerTools.

**Comment by Godsbane** [comment]
I also couldn't reproduce this

**Comment by Godsbane** [comment]
I'm going to close this. Can reopen if we get more reports.
