### ISSUE TITLE
GC Controller on Wii Games 2p Issue

### ISSUE THREAD

**Issue by Emeraldstarmc** [dragoonDorise/EmuDeck#850]
On Mario Kart Wii, the game recognizes the Steamdeck as two separate controllers, making it impossible to play 2P with friends. My temporary solution is to just turn off wii controller entirely in dolphin, and when i want to play any other Wii game i turn Wii controller back on
![20230828220418_1](https://github.com/dragoonDorise/EmuDeck/assets/64788213/24f9b831-93eb-4aae-9194-4eb5b95cbcf8)

**Comment by WingofaGriffin** [comment]
This is how Dolphin works IIRC. You would indeed need to turn off the controller in Dolphin. Not a bug.
