### ISSUE TITLE
Choice between Screen and Trackpad for Touch mode in DS games (in the quick settings menu)

### ISSUE THREAD

**Issue by AdmiralRazorbeard** [dragoonDorise/EmuDeck#860]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

Emulator Configuration Feedback

### Elaborate on the feature you would like to see added to EmuDeck.

By default the DS emulator (melonDs) use the steamdeck screen as the controller.
The steamdeck screen is quite average/unresponsive for this purpose.

Some smart people on reddit found out using the right trackpad as a touchscreen is a WAY smoother experience.
(Plus many people don't like to get fingerprints on their screen)

### Include any websites or links that may support your feature request.

https://www.reddit.com/r/SteamDeck/comments/wew444/how_to_use_trackpad_for_emudeck_nintendo_ds_touch/
https://www.reddit.com/r/SteamDeck/comments/w1maen/finally_figured_out_how_to_get_the_right_trackpad/

### Does this feature work on the Steam Deck?

Yes, and it's quite easy to set up:
On retroarch (L3 + R3): Core Options > Screen > Touch Mode --> change to mouse
On steam controller: right trackpad as mouse, left trackpad (touch) as left click

**Comment by ChildishhAlbino** [comment]
Hey all, just commenting here before I raise an issue for this to make sure it's not an issue with what I'm doing.

Cannot get any game I've loaded with melonDS DS core to register touch inputs on the screen or via the right track pad.

I can make the joystick indicator move but click has no effect on the game.

I tested Desmume core and that had no issues.

If this is worth it's own issue, happy to raise one in the morning.
