### ISSUE TITLE
[Bug Report] retroarch crashes

### ISSUE THREAD

**Issue by JackYansongLi** [dragoonDorise/EmuDeck#861]
### Prerequisite Steps

- [x] I have searched existing issues
- [x] This issue is not a duplicate of an existing one
- [x] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [x] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

I just updated emudeck on my steam deck. The retroarch emulator crashes when I try to start it. I reinstalled emudeck for a few times. Nothing changes. All emulators works fine except for retroarch.

**Comment by JackYansongLi** [comment]
I just updated emudeck on my steam deck. The retroarch emulator crashes when I try to start it. I reinstalled emudeck for a few times. Nothing changes. Every emulators works fine except for retroarch.

**Comment by Godsbane** [comment]
https://emudeck.github.io/common-issues/steamos/#retroarch-does-not-work-anymore-april-30th-2023

Make sure the platform is updated.

**Comment by JackYansongLi** [comment]
> https://emudeck.github.io/common-issues/steamos/#retroarch-does-not-work-anymore-april-30th-2023
> 
> Make sure the platform is updated.

yes, I updated the platform. Problem remains

**Comment by JackYansongLi** [comment]
> https://emudeck.github.io/common-issues/steamos/#retroarch-does-not-work-anymore-april-30th-2023
> 
> Make sure the platform is updated.

This does not work. However, as I manually sudo Pacman -Syu, problem solved
