### ISSUE TITLE
Steam Rom Manager wont read the "File" format my XBLA games are in. [Bug Report] 

### ISSUE THREAD

**Issue by TheCoolRock64** [dragoonDorise/EmuDeck#869]
### Prerequisite Steps

- [ ] I have searched existing issues
- [ ] This issue is not a duplicate of an existing one
- [x] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [ ] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

Trying to play Minecraft XBLA Editon.

**Comment by Godsbane** [comment]
not enough info here.
