### ISSUE TITLE
[Bug Report] xdg-mime seems to be missing in the compression tool

### ISSUE THREAD

**Issue by remyleone** [dragoonDorise/EmuDeck#878]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

I've tried to run the compression tool. It stumbled upon an iso file. Then the script seems to call for xdg-mime which is not installed

### Relevant log output

```shell
sh: line 1: xdg-mime command not found
```

**Comment by WingofaGriffin** [comment]
Can you post a more full log of the compression tool so we can see which system/tool was being used?

**Comment by remyleone** [comment]
That was what was printed inside the terminal :/ Because it didn't worked I didn't kept the iso around. Is xdg-mime installed with emudeck?

**Comment by Godsbane** [comment]
No, nothing is installed for the system by emudeck.

It's also a red herring of a message.

I'm going to close without the log file. If you have another issue please
upload the log itself and reopen.

**Comment by scyto** [comment]
i know this probably doesn't matter but i was using the bul compresson

```
sh: line 1: xdg-mime: command not found
/run/media/deck/e609201c-f7b5-46be-ac6b-3f996b37c02d/Emulation/roms/gc/Super Monkey Ball 2 (USA).iso succesfully converted to /run/media/deck/e609201c-f7b5-46be-ac6b-3f996b37c02d/Emulation/roms/gc/Super Monkey Ball 2 (USA).rvz
Converting: /run/media/deck/e609201c-f7b5-46be-ac6b-3f996b37c02d/Emulation/roms/gc/Viewtiful Joe (USA).iso
sh: line 1: xdg-mime: command not found
/run/media/deck/e609201c-f7b5-46be-ac6b-3f996b37c02d/Emulation/roms/gc/Viewtiful Joe (USA).iso succesfully converted to /run/media/deck/e609201c-f7b5-46be-ac6b-3f996b37c02d/Emulation/roms/gc/Viewtiful Joe (USA).rvz
Converting: /run/media/deck/e609201c-f7b5-46be-ac6b-3f996b37c02d/Emulation/roms/gc/Pikmin 2 (USA).iso
sh: line 1: xdg-mime: command not found
/run/media/deck/e609201c-f7b5-46be-ac6b-3f996b37c02d/Emulation/roms/gc/Pikmin 2 (USA).iso succesfully converted to /run/media/deck/e609201c-f7b5-46be-ac6b-3f996b37c02d/Emulation/roms/gc/Pikmin 2 (USA).rvz
Converting: /run/media/deck/e609201c-f7b5-46be-ac6b-3f996b37c02d/Emulation/roms/gc/Mario Kart - Double Dash!! (USA).iso
sh: line 1: xdg-mime: command not found
/run/media/deck/e609201c-f7b5-46be-ac6b-3f996b37c02d/Emulation/roms/gc/Mario Kart - Double Dash!! (USA).iso succesfully converted to /run/media/deck/e609201c-f7b5-46be-ac6b-3f996b37c02d/Emulation/roms/gc/Mario Kart - Double Dash!! (USA).rvz
Converting: /run/media/deck/e609201c-f7b5-46be-ac6b-3f996b37c02d/Emulation/roms/gc/Paper Mario - The Thousand-Year Door (USA).iso
sh: line 1: xdg-mime: command not found
```

only happend on  the gc folder, not the dc folder
