### ISSUE TITLE
Please add future Pinball in emudeck for steamdeck

### ISSUE THREAD

**Issue by Ferrazzi** [dragoonDorise/EmuDeck#887]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

New Emulator

### Elaborate on the feature you would like to see added to EmuDeck.

Could Citra be added to EmuDeck? It's one of the best 3DS emulators. It has a Flatpak in Discover and runs great on Steam Deck. For the website, see https://citra-emu.org/.

### Include any websites or links that may support your feature request.

https://citra-emu.org/ and https://flathub.org/apps/org.citra_emu.citra

### Does this feature work on the Steam Deck?

Yes, I downloaded Citra from Discover and tested it on my Steam Deck. It works great!

**Comment by WingofaGriffin** [comment]
Citra is in EmuDeck. This seems unrelated to the title.

**Comment by Ferrazzi** [comment]
I was actually wondering if we could add future Pinball not citra.

**Comment by Godsbane** [comment]
@Ferrazzi Please update your issue and put in the correct info, after that's done we'll look at it :)
