### ISSUE TITLE
pcsx2-qt -nogui works if added to .sh but not in emudeck[Bug Report] 

### ISSUE THREAD

**Issue by NasciTollman** [dragoonDorise/EmuDeck#897]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

pcsx2-qt supports -nogui (not --nogui as legacy) and if i create my own .sh to run a game that way it works fine. but I cant pass that parameter anywere to my games using emudeck/es they just all default to some other config that doesnt have that parameter.

**Comment by Godsbane** [comment]
The script is only used when using Steam ROM Manager. ES has it's own config inside of it's AppImage.
