### ISSUE TITLE
[Feature Request] Add the new melonDS libretro core I'm writing

### ISSUE THREAD

**Issue by JesseTG** [dragoonDorise/EmuDeck#899]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

New Emulator

### Elaborate on the feature you would like to see added to EmuDeck.

I'm writing a new [melonDS](https://github.com/melonDS-emu/melonDS) libretro core, titled [melonDS DS](https://github.com/JesseTG/melonds-ds) (for reasons described in the README). It's intended to replace the [legacy melonDS core](https://github.com/libretro/melonDS); virtually all of the legacy core's features and platforms are retained, and quite a few new ones are introduced. There are a few caveats that prevent a fully automated migration, see [this guide](https://github.com/JesseTG/melonds-ds/wiki/Migrating-From-the-Legacy-MelonDS-Core) for details.

For that reason, I don't want to throw out [the existing config](https://github.com/dragoonDorise/EmuDeck/blob/dev/configs/steam-rom-manager/userData/parsers/emudeck/nintendo_ds-ra-melonds.json#L3C1-L3C52); once the core is live, I intend to submit a PR for a new one (and simultaneously mark the legacy one as deprecated).

This core is _almost_ ready to go out; I just need to fix a few final bugs. There will be further support, but my first priority is shipping it.

### Include any websites or links that may support your feature request.

I'm working on setting melonDS DS up to be distributed through [RetroArch's build server](https://buildbot.libretro.com/nightly) and the [Releases section](https://github.com/JesseTG/melonds-ds/releases) of my repository.

### Does this feature work on the Steam Deck?

Yes, multiple people (including me) have tested native builds of the core on the Steam Deck. It works great.

**Comment by WingofaGriffin** [comment]
Once this is on Retroarch's repos this will be much more likely, as it's only a single line change. Until then, this will likely sit on the backburner.
