### ISSUE TITLE
EmulationStation downloaded_media folder should be symlinked to the "Emulation" directory

### ISSUE THREAD

**Issue by C0Nd3Mnd** [dragoonDorise/EmuDeck#90]
I'm suggesting that the `~/.emulationstation/downloaded_media` folder should be stored on the SD card if installation to the SD card was selected. When you use the scraping feature of EmulationStation, this folder can get very big (multiple gigabytes) because preview screenshots and also videos of all roms will be stored there.

**Comment by Godsbane** [comment]
hi,

this should be happening already if you install to an SD card.

https://github.com/dragoonDorise/EmuDeck/blob/0636b0eea249177eb863489e38b10e880f55c87c/install.sh#L654

**Comment by Godsbane** [comment]
I'm going to close, with the comment that you should update  your Emudeck install and it should migrate your data automatically.
If it doesn't happen, reopen with the log file please.

**Comment by C0Nd3Mnd** [comment]
Interesting, running the installer again created the folder and moved existing files just fine. I had 0.17.1 installed already though, so something didn't go quite right the first time I guess.

Anyways, thanks for the hint.

**Comment by Godsbane** [comment]
No problem, hopefully that doesn't happen again to others :) Glad that's all set though.
