### ISSUE TITLE
[Feature Request] EmuDeck Decky plugin for updating everything Auto Flatpaks doesn't cover

### ISSUE THREAD

**Issue by ttang4299** [dragoonDorise/EmuDeck#906]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

EmuDeck Application Feedback

### Elaborate on the feature you would like to see added to EmuDeck.

The current EmuDeck application is dependent on Desktop Mode to update everything Auto Flatpaks cannot. I'd love to be able to update everything, including the EmuDeck application, via a Decky plugin in Gaming Mode.

### Include any websites or links that may support your feature request.

The EmuDeck team is already aware what Decky is.

### Does this feature work on the Steam Deck?

Should be theoretically possible.

**Comment by ttang4299** [comment]
@dragoonDorise I would like to re-propose this idea given the situation that has occurred with both Yuzu and Citra. Now it is very difficult to retrieve the latest versions of both emulators. Having a Decky plugin would reduce the occurance of situations like this, especially since many users do not use Desktop Mode on their Steam Decks

**Comment by dragoonDorise** [comment]
@ttang4299 duplicated here: https://github.com/dragoonDorise/EmuDeck/issues/1000

I want to make the EmuDecky plugin as powerful as posible so there's little need to go to desktop mode
