### ISSUE TITLE
Save importer appends additional "Emudeck/saves" to path.

### ISSUE THREAD

**Issue by HirschBerge** [dragoonDorise/EmuDeck#915]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

Using the Emudeck importer, selecting the directory that contains the "Emudeck" directory, fails with an error "cannot find <path>/Emudeck/saves//Emudeck/saves."
I wget'd the script down, removed all instances of $origin/Emudeck/saves with simply $origin, and it imported everything successfully.

**Comment by p-telling** [comment]
Am able to duplicate this issue.
Can also confrim that the workaround provided also works.

**Comment by Juice805** [comment]
fixed by #914 . can point the .desktop file to that fork in the meantime

**Comment by dragoonDorise** [comment]
@HirschBerge fixed! Thanks for reporting the issue
