### ISSUE TITLE
[Bug Report] DeckyControls v1.0.0 installation script Destination folder is misallaign with released ZIP

### ISSUE THREAD

**Issue by carlosjgp** [dragoonDorise/EmuDeck#925]
### Prerequisite Steps

- [x] I have searched existing issues
- [x] This issue is not a duplicate of an existing one
- [x] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [x] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS 3.5.7

### Which SteamOS Branch are you using?

Beta

### What happened?

Fail to install DeckyControls also because #894 

`emudeck-decky-controls` Github repository releases are using a different folder on v1.0.0.0

- [0.0.7](https://github.com/EmuDeck/emudeck-decky-controls/releases/tag/v.0.0.7) ==> unZIP ==> `emudeck-decky-controls`
- [v1.0.0](https://github.com/EmuDeck/emudeck-decky-controls/releases/tag/v.1.0.0) ==> unZIP ==> `EmuDecky`

The installation script still thinks it's using `emudeck-decky-controls` and the `chown` command fails maybe other bits fail too?
https://github.com/dragoonDorise/EmuDeck/blob/5af92230d3b3f02d1e2cabfd7afb568b11127ee9/functions/ToolScripts/emuDeckPlugins.sh#L22-L31

### Relevant log output

```shell
```

**Comment by misheee** [comment]
Hello. I have same problem. When i try to install deckycontrols plugin, after entering sudo password nothing happens.
Logs is clear

`
[01/13/2024] passwd -S $(whoami) | awk -F " " "{print $2}" & exit
[01/13/2024] stderr: deck P 2024-01-13 0 99999 7 -1`
