### ISSUE TITLE
Cannot install yuzu

### ISSUE THREAD

**Issue by Atlas4218** [dragoonDorise/EmuDeck#926]
### Prerequisite Steps

- [x] I have searched existing issues
- [x] This issue is not a duplicate of an existing one
- [x] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [x] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

Cannot install yuzu, the log show an error bad/illegal format or missing URL

### Relevant log output

```shell
[12/15/2023] Yuzu_install && Yuzu_init
[12/15/2023] stderr: Begin Yuzu Install
yuzu

yuzu

/home/roman/emudeck/yuzu.ver

safeDownload()
- yuzu
- 
- /home/roman/Applications/yuzu.AppImage
- 
- 
curl: (3) URL using bad/illegal format or missing URL
HTTP response code: 000
CURL exit code: 3
yuzu download failed

[12/15/2023] stdout: Error: Command failed: . ~/.config/EmuDeck/backend/functions/all.sh && Yuzu_install && Yuzu_init
/home/roman/.config/EmuDeck/backend/functions/EmuScripts/emuDeckYuzu.sh: ligne 32: jq : commande introuvable
curl: (23) Failure writing output to destination
/home/roman/.config/EmuDeck/backend/functions/helperFunctions.sh: ligne 398: jq : commande introuvable
curl: (23) Failure writing output to destination

[12/15/2023] Yuzu_IsInstalled
[12/15/2023] stderr: false
```

**Comment by Godsbane** [comment]
You are missing jq, please install it.

**Comment by Atlas4218** [comment]
Problem fixed thanks
