### ISSUE TITLE
Request for macOS Version of EmuDeck

### ISSUE THREAD

**Issue by leonekwolfik** [dragoonDorise/EmuDeck#933]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

EmuDeck Feedback

### Elaborate on the feature you would like to see added to EmuDeck.

I am requesting the addition of macOS compatibility for EmuDeck. Currently, EmuDeck is a powerful tool for configuring emulators on various platforms, but it lacks support for macOS. This feature would extend the accessibility of EmuDeck to macOS users, providing them with a seamless experience in configuring emulators on their systems. macOS users are increasingly interested in emulation, and EmuDeck's user-friendly approach aligns well with the preferences of the macOS community.

### Include any websites or links that may support your feature request.

https://citra-emu.org/ and https://flathub.org/apps/org.citra_emu.citra

### Does this feature work on the Steam Deck?

I have not tested this feature on the Steam Deck as the primary focus of this request is to extend compatibility to macOS. However, considering EmuDeck's purpose in autoconfiguring emulators, it would be beneficial for macOS users who might also own a Steam Deck or have similar emulation needs on their Mac systems.

**Comment by dragoonDorise** [comment]
@leonekwolfik it's already on the works, we'll make a twitter announcement when is ready for testing :)

**Comment by dragoonDorise** [comment]
@neofright priorities sifted but I have it planned for the next 3.0 release

**Comment by jtbrough** [comment]
I had to do a triple take today when I noticed some documentation appears to have screenshots of EmuDeck running on macOS.

<img width="2784" height="1582" alt="Image" src="https://github.com/user-attachments/assets/5296f2d0-4937-4b45-853b-fbb656f47dcf" />

i.e. https://manual.emudeck.com/using-app/6_retro-achievements/
