### ISSUE TITLE
Add 3ds batch cia decryptor and SAK (Switch Army Knife), unmerge mame roms with the same files

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [dragoonDorise/EmuDeck#936]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

EmuDeck Feedback

### Elaborate on the feature you would like to see added to EmuDeck.

I would like you to add 3ds cia conversion and the switch army knife to EmuDeck. This will help me play switch games since most games have separate nsp and nsz files. I can merge the nsp files together and convert nsz files to nsp. Mame unmerging may be a bit tougher since the merged sets are a bit different. For example, sf2 and sf2ua have different 11e, 11f, 12e, 12f, 9e, and 9f files. Probably for different programming for how some characters had name changes like balrog, Vega, and m bison.

### Include any websites or links that may support your feature request.

[https://citra-emu.org/ and https://flathub.org/apps/org.citra_emu.citra](https://gbatemp.net/threads/batch-cia-3ds-decryptor-a-simple-batch-file-to-decrypt-cia-3ds.512385/)
https://github.com/dezem/SAK

### Does this feature work on the Steam Deck?

Proton should handle batch cia 3ds decryptor and sak.

**Comment by WingofaGriffin** [comment]
This seems like a potential copyright issue. You should provide your own decrypted files.

**Comment by Iamthebestintheworld222** [comment]
I would do that, but my sd card has to be formatted all over again, and I will lose my data on the sd card in the process.

**Comment by Godsbane** [comment]
Thanks for taking the time to make the suggestion.

Adding cia decryption / sak / other such tools are definitely a no, as they are too adjacent to piracy.
