### ISSUE TITLE
[Bug Report] SRM Dreamcast Parser Not Working

### ISSUE THREAD

**Issue by ianharbs** [dragoonDorise/EmuDeck#938]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

Windows

### Which SteamOS Branch are you using?

Beta

### What happened?

On the emudeck installation it encourages you to use retroarch instead flycast to run dreamcast games, but the SRM parser for the dreamcast games only uses Flycast, this way any dreamcast games that you run over steam won't work if you only installed retroarch.

I just edit the parser and the dreamcast game on steam was good to go.

**Comment by WingofaGriffin** [comment]
There should be two different Flycast parsers, Flycast and Flycast Retroarch. https://github.com/dragoonDorise/EmuDeck/tree/beta/configs/steam-rom-manager/userData/parsers/emudeck

Did you check to see if both were there but only one was enabled?

**Comment by Godsbane** [comment]
Wrong Repository - Please use https://github.com/EmuDeck/emudeck-we/issues
