### ISSUE TITLE
Battle for bikini bottom PS2 not saving [Bug Report] 

### ISSUE THREAD

**Issue by Ruethy** [dragoonDorise/EmuDeck#943]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

You cannot save in the game no matter what you do save states and all are broken for the game. It will act like you save but if you close the emulations completely and then launch it again it detects no saves

**Comment by WingofaGriffin** [comment]
Are you sure this is an EmuDeck bug and not a PCSX2 bug?

**Comment by dragoonDorise** [comment]
PS2 issue, closing
