### ISSUE TITLE
[Bug Report] Curl Illegal Format

### ISSUE THREAD

**Issue by ajb3932** [dragoonDorise/EmuDeck#944]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

Ubuntu 22.04

### Which SteamOS Branch are you using?

Stable

### What happened?

Most emulators do not install due to a curl issue.

### Relevant log output

```shell
Yuzu_install
Begin Yuzu Install
yuzu

yuzu

/home/alex/emudeck/yuzu.ver

safeDownload()
- yuzu
- 
- /home/alex/Applications/yuzu.AppImage
- 
- 
curl: (3) URL using bad/illegal format or missing URL
HTTP response code: 000
CURL exit code: 3
yuzu download failed
Xemu_install
Installing Xemu-Emu
deploying new: /home/alex/.config/EmuDeck/backend/tools/launchers/xemu-emu.sh
'/home/alex/.config/EmuDeck/backend/tools/launchers/xemu-emu.sh' -> '/home/alex/Emulation/tools/launchers/xemu-emu.sh'
Cemu_install
Installing Cemu (proton)
safeDownload()
- cemu
- 
- /home/alex/Emulation/roms/wiiu/cemu.zip
- 
- 
curl: (3) URL using bad/illegal format or missing URL
HTTP response code: 000
CURL exit code: 3
cemu download failed
```

**Comment by Godsbane** [comment]
most likely you are missing jq - install it and try again. There is a prereq script available to you, did you run it? (just cause steamos has different preinstalled things than most distros)

I'll be closing this. Reopen if you still have trouble.
