### ISSUE TITLE
Emudeck stuck at welcome too emudeck screen when trying too install the application 

### ISSUE THREAD

**Issue by Thafunktion** [dragoonDorise/EmuDeck#953]
### Prerequisite Steps

- [ ] I have searched existing issues
- [ ] This issue is not a duplicate of an existing one
- [ ] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [ ] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

A bug happened!

**Comment by WingofaGriffin** [comment]
Please fill out the actual help form. This is not a proper issue report.
