### ISSUE TITLE
[Bug Report] Emudeck and Cloud Backup do not create desktop shortcuts when using folder names in user's home directory from a non-English locale.

### ISSUE THREAD

**Issue by Labaman** [dragoonDorise/EmuDeck#954]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

Endeavouros

### Which SteamOS Branch are you using?

Not Using a Steam Deck

### What happened?

Emudeck and Cloud Backup do not create desktop shortcuts when using folder names in a user's home directory from a non-English locale.
For example, for the Russian locale the folder name "Рабочий стол" is used - Emudeck does not create shortcuts, but if I manually create a folder "Desktop" in the home directory, shortcuts will be created in it.
Thus, it is assumed that in the installation scripts of Emudeck itself, as well as in the installation scripts of Cloud Backup, the desktop folder is hard-coded as "Desktop".
Based on this, a more correct solution would be to take folder names from xdg-user-dir, e.g. for desktop `xdg-user-dir DESKTOP`.

**Comment by dragoonDorise** [comment]
We've changed the way cloudBackup works, no need for desktop icons anymore.

**Comment by Labaman** [comment]
Now CloudBackup works differently and is no longer a problem. But there is still a problem with Emudeck itself - after installation no desktop icon is created if the desktop folder name is set in a locale other than English.
