### ISSUE TITLE
[Bug Report] 

### ISSUE THREAD

**Issue by prey169** [dragoonDorise/EmuDeck#958]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

Windows

### Which SteamOS Branch are you using?

Windows Beta

### What happened?

It looks like when starting an emulator  or Emulation station the fullScreenToast does not  go away and leaves a blackscreen that takes up the whole window

for context: this person opened up a reddit post about it

https://www.reddit.com/r/EmuDeck/comments/18cd29y/emudeck_for_windows_splashscreen/

**Comment by Godsbane** [comment]
https://github.com/EmuDeck/emudeck-we/issues

please use this repo for issues with windows.
