### ISSUE TITLE
[Bug Report] Launchers call generic shell, but incompatible with certain default shells

### ISSUE THREAD

**Issue by jw2249a** [dragoonDorise/EmuDeck#963]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

debian

### Which SteamOS Branch are you using?

Not Using a Steam Deck

### What happened?

Launchers use #!/bin/sh instead of #!/bin/bash or #!/usr/bin/env bash when using incompatible commands with certain shell flavors that don't have source (in my case the default shell in debian and ubuntu is dash). It is also incompatible with other popular default shells ash and pdksh. Using #!/bin/bash should be valid for more dists than #!/bin/sh.

Tested and switching to #!/bin/bash in the launchers fixes the issue.

**Comment by WingofaGriffin** [comment]
@dragoonDorise @Godsbane thoughts? I don't see why this would cause any issues.

**Comment by Godsbane** [comment]
I think #!/bin/bash probably makes the most sense sense.

**Comment by jw2249a** [comment]
One note is that "#!/bin/bash" on a macbook will default to an outdated bash version. I don't think emudeck is offered on macos, but "#!/usr/bin/env bash" would prevent that from breaking if ever ported there.

**Comment by flying-admin** [comment]
@jw2249a a macOS port is indeed in the works, we'll update bash using brew during the dependencies installation proccess.

**Comment by dragoonDorise** [comment]
@jw2249a a MacOS port is in the works indeed ( I develop EmuDeck from a Mac so... ), one of the dependencies we install on macOS is bash trough brew so some bash incompatibilities are fixed that way
