### ISSUE TITLE
Suggestion - switch retroarch renderer

### ISSUE THREAD

**Issue by Godsbane** [dragoonDorise/EmuDeck#97]
Currently retroarch is using the gl renderer. Vulkan is available and should be much faster.

**Comment by AngelofWoe** [comment]
The only downside is that it can crash some cores.

I'll do some testing.

**Comment by AngelofWoe** [comment]
Quick tests just to run around and make sure none of these cores straight up just crash. Swapped rendered in overall settings to Vulkan, the only one that had a non-default setting that I tested was DS, which had glcore in the core overrides.

DS - glcore -> Vulkan - Seems to work fine
GB - Vulkan - Seems to work fine
GBA - Vulkan - Seems to work fine
GBC - Vulkan - Seems to work fine
Genesis/Megadfive - Vulkan - Seems to work fine
NES - Vulkan - Seems to work fine
N64 - Vulkan - Seems to work fine
PSP - Vulkan - Seems to work fine
SNES - Vulkan - Seems to work fine

**Comment by Godsbane** [comment]
while i agree with you regarding RA dolphin, can we just set a core override for that specific core?

**Comment by AngelofWoe** [comment]
Yeah, that's doable

**Comment by AngelofWoe** [comment]
https://github.com/dragoonDorise/EmuDeck/pull/102/commits/7174d5544daac8c51ce90099453a71a87944dc78
