### ISSUE TITLE
[Feature Request] Add Select/Deselect All Buttons to Emulator Selection

### ISSUE THREAD

**Issue by WingofaGriffin** [dragoonDorise/EmuDeck#971]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

EmuDeck Application Feedback

### Elaborate on the feature you would like to see added to EmuDeck.

Instead of manually selecting/deselecting each emulator, having a button to auto select or deselect all would be convenient.

### Include any websites or links that may support your feature request.

n/a

**Comment by WingofaGriffin** [comment]
@dragoonDorise :)

**Comment by dragoonDorise** [comment]
@WingofaGriffin noted!

**Comment by dragoonDorise** [comment]
This will broke the way we check RA vs standalone emulators on the selection screen, so not doing it at the moment.
