### ISSUE TITLE
[Feature Request] RetroArch Save Sorting Option

### ISSUE THREAD

**Issue by PhasecoreX** [dragoonDorise/EmuDeck#976]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)

### Feature Request

Emulator Configuration Feedback

### Elaborate on the feature you would like to see added to EmuDeck.

In RetroArch, when you enable the advanced settings and go to the "Saving" config category, there are 3 settings I would like to have turned on:

- Sort Saves into Folders by Content Directory
- Sort Save States into Folders by Content Directory
- Sort Screenshots into Folders by Content Directory

I can turn these on myself (I have manually edited the retroarch.conf file), but when I reinstall EmuDeck and have it overwrite my config, it will set these back to false. I use this because I like having my saves/states/screenshots all in sub-directories. Since the roms are at `~/Emulation/roms/gba` for example, the saves for it would be in `~/Emulation/saves/retroarch/saves/gba`, instead of `~/Emulation/saves/retroarch/saves`. Same with the save states in the `states` folder. I have tested it, it works correctly.

I also want the screenshots sorted, since I'm Syncthing-ing these 3 folders off to another computer where the same sort settings are being used.

So, if there is a way to turn these on and off, or at least not reset them on future upgrades, that would be appreciated!

### Include any websites or links that may support your feature request.

I don't really have a link for it, but maybe this helps? https://docs.libretro.com/guides/retroarch-cloud-sync/ it at least mentions it, and I'm technically rolling my own cloud sync with Syncthing.

> Be very careful that these directory save settings are also identical on all sync devices:
> - Sort Saves into Folders by Core Name - ON/OFF
> - Sort Save States into Folders by Core Name - ON/OFF
> - Sort Saves into Folders by Content Directory - ON/OFF
> - Sort Save States into Folders by Content Directory - ON/OFF
>
> If these settings are not matching, the sync is likely to fail, as the devices store its data in different directories.

### Does this feature work on the Steam Deck?

Yeah, what I did above does work on the Steam Deck.

**Comment by dragoonDorise** [comment]
Hi, this will open a can of worms related to cloud saving, we tested this in the past but we decided to keep things like they are.
