### ISSUE TITLE
[Bug Report] Importing image choices outputs an error

### ISSUE THREAD

**Issue by Deinorius** [dragoonDorise/EmuDeck#987]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS 3.5 latest stable

### Which SteamOS Branch are you using?

Stable

### What happened?

Saved selected images with the Export option and wanted to do a newer list after reformatting the microSD card with btrfs but trying to import outputs an error.

Json file seems to be fine, here's a sample:
[
  {
    "title": "EmulationStation-DE-x64_SteamDeck",
    "images": {
      "tall": {
        "pool": "EmulationStation-DE-x64_SteamDeck",
        "filename": "17331692086059073536.tall.png"
      },
      "long": {
        "pool": "EmulationStation-DE-x64_SteamDeck",
        "filename": "17331692086059073536.long.png"
      },
      "hero": {
        "pool": "EmulationStation-DE-x64_SteamDeck",
        "filename": "17331692086059073536.hero.png"
      },
      "logo": {
        "pool": "EmulationStation-DE-x64_SteamDeck",
        "filename": "17331692086059073536.logo.png"
      },
      "icon": {
        "pool": "EmulationStation-DE-x64_SteamDeck",
        "filename": "17331692086059073536.icon.ico"
      }
    }
  },
  {
    "title": "scummvm",
    "images": {
      "tall": {
        "pool": "ScummVM",
        "filename": "13426660352557318144.tall.png"
      },
      "long": {
        "pool": "ScummVM",
        "filename": "13426660352557318144.long.png"
      },
      "hero": {
        "pool": "ScummVM",
        "filename": "13426660352557318144.hero.jpg"
      },
      "logo": {
        "pool": "ScummVM",
        "filename": "13426660352557318144.logo.png"
      },
      "icon": {
        "pool": "ScummVM",
        "filename": "13426660352557318144.icon.png"
      }
    }
  },

### Relevant log output

```shell
Applying imported image choices.
Could not import image choices: Cannot read properties of undefined (reading 'content')
```

**Comment by dragoonDorise** [comment]
@Deinorius this is SRM issue, you might need to go their GitHub: https://github.com/SteamGridDB/steam-rom-manager/issues
