### ISSUE TITLE
[Feature request] Amiga support

### ISSUE THREAD

**Issue by slashbeast** [dragoonDorise/EmuDeck#99]
Hey.

Would you consider adding/welcoming Amiga support? I am looking at EmuDeck to replace my rg351mp device but the Amiga emulation is the only thing that is really missing for me to switch.

**Comment by Godsbane** [comment]
Hi Slashbeast - 

Does this retroarch core work for you?
https://docs.libretro.com/library/puae/

**Comment by slashbeast** [comment]
This is the core I use on rg351 that runs RK3326 ARM SoC, so I would only expect it to work on x86_64 as well. I will build retroarch with this core on my desktop in a moment and test it, will let you know.

One thing that is somewhat unique to Amiga is that you need a hotkey for some on-screen keyboard, Sometimes you need to send F1, Enter, Escape or input some code, on RG351 devices (running 351elec/AmberELEC) select hotkey brings it up, not sure if its feature of PUAE or some separated RetroArch feature though.

**Comment by Godsbane** [comment]
because it runs in retroarch already, and the retroarch input setup is done i believe it will just translate over.

**Comment by dragoonDorise** [comment]
Hi @slashbeast , Amiga was already supported when using EmulationStation DE, We've added it to SRM for the next release.
Do you have a Deck to test the hotkey functionality?

**Comment by slashbeast** [comment]
Sorry about not reporting back, got distracted with other things. PUAE works just fine when tested on Gentoo ~amd64 so I think this is the good choice.

I have SteamDeck on me to test. Do you have any test build I can test and report back?
