### ISSUE TITLE
[Bug Report] Installation stuck on SteamOS while linking Cemu saves

### ISSUE THREAD

**Issue by WedgeSparda** [dragoonDorise/EmuDeck#995]
### Prerequisite Steps

- [X] I have searched existing issues
- [x] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Preview

### What happened?

Hi, using Early Access here (not sure if that's Beta or Preview).

Recently I replace my Steam Deck's 64GB disc with a 1TB SSD. I reinstalled SteamOS and now I'm reinstalling EmuDeck, but I found this problem while installing.

After setting all my preferences within the installer, installation starts and everything seems fine: all emulators are downloaded, Decky is installed (it asks for my sudo password twice, which I had to reset following [this guide](https://youtu.be/F96ntnf8qiQ?si=msItEqUVOdrCzeMw)), etc...

But then installation is stuck (right now is still running for about 40 minutes) while trying to configure Cemu. The bottom dialog in the Sonic animation says `Linking Cemu saves to the Emulation/saves folder` and if I open the detailed log, this is what I see:

```
Binary copied.
Update script copied.
Uninstall script copied.
V1-Cleanup script copied.
Log script copied.
Installing service...
Installation done.
Setting up desktop shortcuts...
Update shortcut copied.
Uninstall shortcut copied.
```
No other error at sigh. 

What I am missing?

### Relevant log output

```shell
Binary copied.
Update script copied.
Uninstall script copied.
V1-Cleanup script copied.
Log script copied.
Installing service...
Installation done.
Setting up desktop shortcuts...
Update shortcut copied.
Uninstall shortcut copied.
```

**Comment by WedgeSparda** [comment]
Tried again changing my DNS to 1.1.1.1. Still stuck.

Here's the complete log

[emudeck_install.log.txt](https://github.com/dragoonDorise/EmuDeck/files/14219386/emudeck_install.log.txt)

**Comment by dragoonDorise** [comment]
@WedgeSparda did it got fixed with the latest update?

**Comment by WedgeSparda** [comment]
Yes, sorry. I forgot to close this issue. 

Thanks.

**Comment by dragoonDorise** [comment]
@WedgeSparda no pasa nada! Me alegro que se haya resuelto :)
